module fortran
    !! Function for writing the Fortran code.
    use iso_fortran_env
    use core
    implicit none

    
contains

subroutine write_fortran_module_declaration(fcode, version, name)
    !! Generate the Fortran module declaration.
    implicit none
    ! Arguments
    integer(int32), intent(in) :: fcode
        !! File unit of the Fortran module.
    character(len=*), intent(in) :: version
        !! Version string.
    character(len=*), intent(in) :: name
        !! Name string.

    integer(int32) :: n 
    character(len=32) :: nstr

    n = len(trim(version))
    
    write(nstr, "(I2)") n-2 ! remove quotes for size
    
    write(fcode, "(A)") "module "//trim(name)//"__version"
    write(fcode, "(A)") "!! Version - autogenerated."
    write(fcode, "(A)") "use iso_fortran_env"
    write(fcode, "(A)") "implicit none"
    write(fcode, "(A, /)") "private"
    write(fcode, "(A)", advance="NO") 'character(len='//trim(nstr)//'), parameter, public :: '
    write(fcode, "(A)") trim(name)//'_version_version = '//trim(version)
    write(fcode, "(A)") ""
end subroutine


subroutine write_fortran_module_end(fcode, name)
    !! Generate the end of the Fortran module.
    implicit none
    ! Arguments
    integer(int32), intent(in) :: fcode
        !! File unit of the Fortran module.
    character(len=*), intent(in) :: name
        !! Name string.
    write(fcode, "(A)") "end module "//trim(name)//"__version"
end subroutine


subroutine write_fortran_capi_module_declaration(fcode, version, name)
    !! Generate the Fortran CAPI module declaration.
    implicit none
    ! Arguments
    integer(int32), intent(in) :: fcode
        !! File unit of the Fortran module.
    character(len=*), intent(in) :: version
        !! Version string.
    character(len=*), intent(in) :: name
        !! Name string.
    
    integer(int32) :: n, i
    character(len=32) :: nstr

    n = len(trim(version))
    
    write(nstr, "(I2)") n-2+1 ! remove quotes for size and +1 for c final null char.
    
    write(fcode, "(A)") "module "//trim(name)//"__version_capi"
    write(fcode, "(A)") "!! Version C API - autogenerated."
    write(fcode, "(A)") "use iso_c_binding"
    write(fcode, "(A)") "implicit none"
    write(fcode, "(A, /)") "private"
    
    write(fcode, "(A)", advance="NO") 'character(kind=c_char), protected, public, bind(C) :: '
    write(fcode, "(A)") trim(name)//'_version_capi_version('//trim(nstr)//') = &'
    write(fcode, "(A)", advance="NO") "["
    do i=2, n-1 ! exclude quotes for copying
        write(fcode, "(A)", advance="NO") '"'//version(i:i)//'", '
    end do
    write(fcode, "(A)", advance="NO") 'c_null_char'
    write(fcode, "(A)", advance="YES") "]"

    write(fcode, "(A)") ""
end subroutine


subroutine write_fortran_capi_module_end(fcode, name)
    !! Generate the end of the Fortran CAPI module.
    implicit none
    ! Arguments
    integer(int32), intent(in) :: fcode
        !! File unit of the Fortran module.
    character(len=*), intent(in) :: name
        !! Name string.
    write(fcode, "(A)") "end module "//trim(name)//"__version_capi"
end subroutine



end module