codatacli – codata
codatacli Program
83 statements
Source File
Uses
codata
stdlib_optval
iso_fortran_env
M_CLI2
regex_module
Calls
Variables
Type Attributes Name Initial
type(codata_constant_type), pointer :: cctptr(:)
character(len=:), pointer :: char_fp(:)
character(len=:), allocatable, target :: help_text(:)
integer :: i
character(len=*), parameter :: name = "codata"
character(len=:), allocatable :: patterns(:)
character(len=:), allocatable, target :: version_text(:)
Subroutines
subroutine display(fptr, pattern, value, uncertainty)
Display results
Arguments
Type Intent Optional Attributes Name
type(codata_constant_type), intent(in), pointer :: fptr(:)
character(len=*), intent(in), optional :: pattern
logical, intent(in), optional :: value
logical, intent(in), optional :: uncertainty
Source Code
program codatacli
use, intrinsic :: iso_fortran_env, only: output_unit
use M_CLI2, only: set_args, set_mode, specified, iget, lget, sget, get_args
use M_CLI2, only: args=>unnamed
use regex_module, only: REGEX, parse_pattern, regex_pattern
use stdlib_optval, only: optval
use codata, only :cc, cc_2010,cc_2014, cc_2018, codata_constant_type, version
implicit none(type,external)
character(len=*), parameter :: name="codata"
character(len=:),allocatable, target  :: help_text(:)
character(len=:),allocatable, target  :: version_text(:)
character(len=:), pointer :: char_fp(:)
type(codata_constant_type), pointer :: cctptr(:)
character(len=:), allocatable :: patterns(:)
integer :: i
nullify(char_fp)
nullify(cctptr)
version_text=[character(len=80) :: &
''//name//' '//version()//'                                            ', &
'Copyright (c) 2022 Milan Skocic                                       ', &
'License: MIT                                                          ', &
'' ]
help_text=[character(len=72) :: &
'Usage: codata [OPTION...] [REGEX_PATTERN...]                          ',&
'codata - fundamental physical constants                               ',&
'                                                                      ',&
'  --year, -y YEAR         Codata constants: 2022, 2018, 2014, 2010    ',&
'  --pattern, -p PATTERN   Regex pattern for filtering the constants.  ',&
'  --value, -a             Show only the value.  ',&
'  --error, -e             Show only the uncertainty.      ',&
'  --usage                 Show usage text and exit.     ',&
'  --help                  Show help text and exit.    ',&
'  --verbose               Display additional information.  ',&
'  --version               Show version information and exit.           ',&
'']
call set_mode('strict')
call set_mode('response_file')
call set_args('--year:y 2022 --value:a F --error:e F --pattern:p .', &
              help_text, version_text)
select case(iget("year"))
    case (2022)
        cctptr => cc
    case (2018)
        cctptr => cc_2018
    case (2014)
        cctptr => cc_2014
    case (2010)
        cctptr => cc_2010
    case default
        nullify(cctptr)
        write(output_unit, '(A)') 'Invalid year. See --help.'
        stop
end select
if(ASSOCIATED(cctptr))then
    if(size(args) > 0) then
        do i=1, size(args), 1
             call display(cctptr, trim(args(i)), lget("a"), lget("e"))
        end do
    end if
    if(specified('p'))then
        call get_args('p', patterns, delimiters=',')
        do i=1, size(patterns), 1
            call display(cctptr, trim(patterns(i)), lget("a"), lget("e"))
        end do
    end if
    if(.not.specified('p') .and. size(args) <= 0)then
        call display(cctptr)
    end if
end if
contains
!=======================================================================
! DISPLAY
!=======================================================================
subroutine display(fptr, pattern, value, uncertainty)
!! Display results
type(codata_constant_type), intent(in), pointer :: fptr(:)
character(len=*), intent(in), optional :: pattern
logical, intent(in), optional :: value, uncertainty
integer :: i, n, idx
type(regex_pattern) :: re
logical :: value2, uncertainty2
value2 = optval(value, .false.)
uncertainty2 = optval(uncertainty, .false.)
if(present(pattern))then
    re = parse_pattern(pattern)
    do i=1, size(fptr),1
        idx = REGEX(trim(fptr(i)%name), pattern=re, length=n)
        if(idx /= 0)then
            if(value2)then
                write(output_unit, '(SP,ES24.16)') fptr(i)%value
            elseif(uncertainty2)then
                write(output_unit, '(SP,ES24.16)') fptr(i)%uncertainty
            else
                call fptr(i)%print()
            end if
        end if
    end do
else
    do i=1, size(fptr),1
        call fptr(i)%print()
    end do
end if
end subroutine display
!=======================================================================
end program codatacli
Call graph
codatacli calls args, get_args, iget, lget, display, version, set_args, set_mode, specified
display calls optval, parse_pattern, regex