#!/usr/bin/env bash

. ./common
latest_year=$(gly)

fname="$1"
name=$(basename -s .toml $fname)
year="${name##*_}"

suffix="_$year"
if [[ "$year" == "$latest_year" ]]; then suffix=""; fi

awk -v suffix="$suffix" -v latest_year="$latest_year" '
BEGIN{
    print ""
    print "//------------------------------------------------------------------------"
    if(suffix==""){
        print "// CODATA_CONSTANTS_"latest_year
    }
    else{
        print "// CODATA_CONSTANTS"suffix
    }
    print "//------------------------------------------------------------------------"
    print "//{{{"

    i=0
}
/^\[.*\]/{
    gsub(/\[/,"")
    gsub(/\]/,"")
    var=$0 suffix
    i++
}
NF==0{
    print "ADD_IMPORT extern const struct codata_constant_type "var";"
}
END{
    print "ADD_IMPORT extern const struct codata_constant_type cc"suffix"["i"];"
    print "//}}}"
}
' $1
