#!/usr/bin/env bash

. ./common
latest_year=$(gly)

fname="$1"
name=$(basename -s .toml $fname)
year="${name##*_}"

suffix="_$year"
if [[ "$year" == "$latest_year" ]]; then suffix=""; fi

awk -v suffix="$suffix" -v year="$year" '
NR==FNR{
    if($0 ~ /^#/){next}
    split($0, r, "\t")
    newof[r[1]] = r[2]
    oldof[r[2]] = r[1]
    next
}
function alias_of(k){
    if(k in newof){return newof[k]}
    if(k in oldof){return oldof[k]}
    return ""
}
BEGIN{
    print ".SH CODATA " year
    print ".PP"
    if(suffix==""){
        print "This is the latest adjustment. Its constants are available both"
        print "under the year-suffixed names listed below and, as an alias meaning"
        print "\\(dqcurrent\\(dq, under the same names without the _" year " suffix."
    }
    print "List of available constants:"
    print ".\\\"{{{"
}
/^\[.*\]/{
    gsub(/\[/,"")
    gsub(/\]/,"")
    print ".IP \\(bu "
    print $0 "_" year
    a = alias_of($0)
    if(a != ""){
        print ".IP \\(bu "
        print a "_" year " (alias, renamed by NIST)"
    }
}
END{print ".\\\"}}}"}
' renames.tsv "$1"
