#!/usr/bin/env bash

. ./common
latest_year=$(gly)

fname="$1"
name=$(basename -s .toml $fname)
year="${name##*_}"

suffix="_$year"
if [[ "$year" == "$latest_year" ]]; then suffix=""; fi

awk -v suffix="$suffix" -v latest_year="$latest_year" -v year="$year" '
BEGIN{
    print "/* SPDX-License-Identifier: MIT */"
    print ""
    print "//======================================================================"
    if(suffix==""){
        print "// MODULE: CODATA_CONSTANTS_"year
    }
    else{
        print "// MODULE: CODATA_CONSTANTS"suffix
    }
    print "//======================================================================"
    print "//{{{1"
    print "#include <stdlib.h>"
    print "#include \"codata.h\""
    print ""
    print "//----------------------------------------------------------------------"
    print "// CONSTANTS"
    print "//----------------------------------------------------------------------"
    print "//{{{2"
    i=0
}
/^\[.*\]/{
    gsub(/\[/,"")
    gsub(/\]/,"")
    bare=$0
    var=$0 suffix
    print "const struct codata_constant_type "var" = {"
}
/^name/{
    split($0, x, " = ")
    print x[2]","
    name = x[2]
    gsub(/"/,"",name)
    i++
    vars[i]=var
    bares[i]=bare
    docs[i]=name
    names[i]=x[2]
}
/^value/{
    gsub(/"/, "")
    split($0, x, " = ")
    print x[2]","
    values[i]=x[2]
}
/^uncertainty/{
    gsub(/"/, "")
    split($0, x, " = ")
    print x[2]","
    uncertainties[i]=x[2]
}
/^unit/{
    split($0, x, " = ")
    print x[2]
    print "};/** "name" */"
    units[i]=x[2]
}
NF==0{
    print ""
}
END{
    print "//}}}"
    print ""
    print ""
    print "//----------------------------------------------------------------------"
    print "// ARRAY OF CONSTANTS"
    print "//----------------------------------------------------------------------"
    print "//{{{2"
    print "const struct codata_constant_type *cc"suffix"[] = {" 
    for (j in vars){
        print "&"vars[j]","
    }
    print "NULL,"
    print "};"

    # The latest adjustment is also exposed under its year-suffixed name, so
    # that a caller can pin to it before the next adjustment is released.
    # The unsuffixed names above are kept as aliases meaning "current".
    if(suffix==""){
        print "//}}}"
        print ""
        print ""
        print "//----------------------------------------------------------------------"
        print "// CONSTANTS - YEAR-SUFFIXED NAMES FOR THE LATEST ADJUSTMENT"
        print "//----------------------------------------------------------------------"
        print "//{{{2"
        for (j=1; j<=i; j++){
            print "const struct codata_constant_type "bares[j]"_"year" = {"
            print names[j]","
            print values[j]","
            print uncertainties[j]","
            print units[j]
            print "};/** "docs[j]" */"
            print ""
        }
        print "//}}}"
        print ""
        print ""
        print "//----------------------------------------------------------------------"
        print "// ARRAY OF CONSTANTS - YEAR-SUFFIXED"
        print "//----------------------------------------------------------------------"
        print "//{{{2"
        print "const struct codata_constant_type *cc_"year"[] = {"
        for (j=1; j<=i; j++){
            print "&"bares[j]"_"year","
        }
        print "NULL,"
        print "};"
    }
}
' $1
