#!/usr/bin/env bash


awk '
BEGIN{
    FIELDWIDTHS="50"
}
NR>11{
    printf "%50s%4s", $1, " -> " 
    gsub(/ +$/,"", $1)
    gsub(/ /,"_", $1)
    gsub(/\./,"", $1)
    gsub(/,/,"", $1)
    gsub(/-/,"_",$1)
    gsub(/\(/,"",$1)
    gsub(/\)/,"",$1)
    gsub(/\//,"_",$1)
    printf "%-50s\n", toupper($1)
}
' $1
