.TH "src Directory Reference" 3 "Fri Oct 28 2022" "Version 1.0" "Codata" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcodata\&.c\fP"
.br
.ti -1c
.RI "file \fBcodata\&.f90\fP"
.br
.ti -1c
.RI "file \fBcodata\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.RI "Source code generator for C and Fortran languages\&. "
.in -1c
