.TH "codata.f90" 3 "Fri Oct 28 2022" "Version 1.0" "Codata" \" -*- nroff -*-
.ad l
.nh
.SH NAME
codata.f90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBcodata\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real(c_double), parameter \fBcodata::alpha_particle_electron_mass_ratio\fP = 7294\&.29954142"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_alpha_particle_electron_mass_ratio\fP = 0\&.00000024"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::alpha_particle_mass\fP = 6\&.6446573357d\-27"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_alpha_particle_mass\fP = 0\&.0000000020d\-27"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::alpha_particle_mass_energy_equivalent\fP = 5\&.9719201914d\-10"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_alpha_particle_mass_energy_equivalent\fP = 0\&.0000000018d\-10"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::alpha_particle_mass_energy_equivalent_in_mev\fP = 3727\&.3794066"
.br
.RI "MeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_alpha_particle_mass_energy_equivalent_in_mev\fP = 0\&.0000011"
.br
.RI "MeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::alpha_particle_mass_in_u\fP = 4\&.001506179127"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_alpha_particle_mass_in_u\fP = 0\&.000000000063"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::alpha_particle_molar_mass\fP = 4\&.0015061777d\-3"
.br
.RI "kg mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_alpha_particle_molar_mass\fP = 0\&.0000000012d\-3"
.br
.RI "kg mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::alpha_particle_proton_mass_ratio\fP = 3\&.97259969009"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_alpha_particle_proton_mass_ratio\fP = 0\&.00000000022"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::alpha_particle_relative_atomic_mass\fP = 4\&.001506179127"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_alpha_particle_relative_atomic_mass\fP = 0\&.000000000063"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::angstrom_star\fP = 1\&.00001495d\-10"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_angstrom_star\fP = 0\&.00000090d\-10"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_mass_constant\fP = 1\&.66053906660d\-27"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_mass_constant\fP = 0\&.00000000050d\-27"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_mass_constant_energy_equivalent\fP = 1\&.49241808560d\-10"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_mass_constant_energy_equivalent\fP = 0\&.00000000045d\-10"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_mass_constant_energy_equivalent_in_mev\fP = 931\&.49410242"
.br
.RI "MeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_mass_constant_energy_equivalent_in_mev\fP = 0\&.00000028"
.br
.RI "MeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_mass_unit_electron_volt_relationship\fP = 9\&.3149410242d8"
.br
.RI "eV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_mass_unit_electron_volt_relationship\fP = 0\&.0000000028d8"
.br
.RI "eV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_mass_unit_hartree_relationship\fP = 3\&.4231776874d7"
.br
.RI "E_h 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_mass_unit_hartree_relationship\fP = 0\&.0000000010d7"
.br
.RI "E_h 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_mass_unit_hertz_relationship\fP = 2\&.25234271871d23"
.br
.RI "Hz 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_mass_unit_hertz_relationship\fP = 0\&.00000000068d23"
.br
.RI "Hz 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_mass_unit_inverse_meter_relationship\fP = 7\&.5130066104d14"
.br
.RI "m^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_mass_unit_inverse_meter_relationship\fP = 0\&.0000000023d14"
.br
.RI "m^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_mass_unit_joule_relationship\fP = 1\&.49241808560d\-10"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_mass_unit_joule_relationship\fP = 0\&.00000000045d\-10"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_mass_unit_kelvin_relationship\fP = 1\&.08095401916d13"
.br
.RI "K 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_mass_unit_kelvin_relationship\fP = 0\&.00000000033d13"
.br
.RI "K 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_mass_unit_kilogram_relationship\fP = 1\&.66053906660d\-27"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_mass_unit_kilogram_relationship\fP = 0\&.00000000050d\-27"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_unit_of_1st_hyperpolarizability\fP = 3\&.2063613061d\-53"
.br
.RI "C^3 m^3 J^-2 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_unit_of_1st_hyperpolarizability\fP = 0\&.0000000015d\-53"
.br
.RI "C^3 m^3 J^-2 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_unit_of_2nd_hyperpolarizability\fP = 6\&.2353799905d\-65"
.br
.RI "C^4 m^4 J^-3 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_unit_of_2nd_hyperpolarizability\fP = 0\&.0000000038d\-65"
.br
.RI "C^4 m^4 J^-3 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_unit_of_action\fP = 1\&.054571817d\-34"
.br
.RI "J s 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_unit_of_action\fP = 0\&.0"
.br
.RI "J s 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_unit_of_charge\fP = 1\&.602176634d\-19"
.br
.RI "C 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_unit_of_charge\fP = 0\&.0"
.br
.RI "C 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_unit_of_charge_density\fP = 1\&.08120238457d12"
.br
.RI "C m^-3 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_unit_of_charge_density\fP = 0\&.00000000049d12"
.br
.RI "C m^-3 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_unit_of_current\fP = 6\&.623618237510d\-3"
.br
.RI "A 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_unit_of_current\fP = 0\&.000000000013d\-3"
.br
.RI "A 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_unit_of_electric_dipole_mom\fP = 8\&.4783536255d\-30"
.br
.RI "C m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_unit_of_electric_dipole_mom\fP = 0\&.0000000013d\-30"
.br
.RI "C m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_unit_of_electric_field\fP = 5\&.14220674763d11"
.br
.RI "V m^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_unit_of_electric_field\fP = 0\&.00000000078d11"
.br
.RI "V m^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_unit_of_electric_field_gradient\fP = 9\&.7173624292d21"
.br
.RI "V m^-2 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_unit_of_electric_field_gradient\fP = 0\&.0000000029d21"
.br
.RI "V m^-2 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_unit_of_electric_polarizability\fP = 1\&.64877727436d\-41"
.br
.RI "C^2 m^2 J^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_unit_of_electric_polarizability\fP = 0\&.00000000050d\-41"
.br
.RI "C^2 m^2 J^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_unit_of_electric_potential\fP = 27\&.211386245988"
.br
.RI "V 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_unit_of_electric_potential\fP = 0\&.000000000053"
.br
.RI "V 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_unit_of_electric_quadrupole_mom\fP = 4\&.4865515246d\-40"
.br
.RI "C m^2 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_unit_of_electric_quadrupole_mom\fP = 0\&.0000000014d\-40"
.br
.RI "C m^2 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_unit_of_energy\fP = 4\&.3597447222071d\-18"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_unit_of_energy\fP = 0\&.0000000000085d\-18"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_unit_of_force\fP = 8\&.2387234983d\-8"
.br
.RI "N 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_unit_of_force\fP = 0\&.0000000012d\-8"
.br
.RI "N 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_unit_of_length\fP = 5\&.29177210903d\-11"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_unit_of_length\fP = 0\&.00000000080d\-11"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_unit_of_mag__dipole_mom\fP = 1\&.85480201566d\-23"
.br
.RI "J T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_unit_of_mag__dipole_mom\fP = 0\&.00000000056d\-23"
.br
.RI "J T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_unit_of_mag__flux_density\fP = 2\&.35051756758d5"
.br
.RI "T 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_unit_of_mag__flux_density\fP = 0\&.00000000071d5"
.br
.RI "T 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_unit_of_magnetizability\fP = 7\&.8910366008d\-29"
.br
.RI "J T^-2 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_unit_of_magnetizability\fP = 0\&.0000000048d\-29"
.br
.RI "J T^-2 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_unit_of_mass\fP = 9\&.1093837015d\-31"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_unit_of_mass\fP = 0\&.0000000028d\-31"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_unit_of_momentum\fP = 1\&.99285191410d\-24"
.br
.RI "kg m s^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_unit_of_momentum\fP = 0\&.00000000030d\-24"
.br
.RI "kg m s^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_unit_of_permittivity\fP = 1\&.11265005545d\-10"
.br
.RI "F m^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_unit_of_permittivity\fP = 0\&.00000000017d\-10"
.br
.RI "F m^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_unit_of_time\fP = 2\&.4188843265857d\-17"
.br
.RI "s 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_unit_of_time\fP = 0\&.0000000000047d\-17"
.br
.RI "s 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::atomic_unit_of_velocity\fP = 2\&.18769126364d6"
.br
.RI "m s^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_atomic_unit_of_velocity\fP = 0\&.00000000033d6"
.br
.RI "m s^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::avogadro_constant\fP = 6\&.02214076d23"
.br
.RI "mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_avogadro_constant\fP = 0\&.0"
.br
.RI "mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::bohr_magneton\fP = 9\&.2740100783d\-24"
.br
.RI "J T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_bohr_magneton\fP = 0\&.0000000028d\-24"
.br
.RI "J T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::bohr_magneton_in_ev_t\fP = 5\&.7883818060d\-5"
.br
.RI "eV T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_bohr_magneton_in_ev_t\fP = 0\&.0000000017d\-5"
.br
.RI "eV T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::bohr_magneton_in_hz_t\fP = 1\&.39962449361d10"
.br
.RI "Hz T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_bohr_magneton_in_hz_t\fP = 0\&.00000000042d10"
.br
.RI "Hz T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::bohr_magneton_in_inverse_meter_per_tesla\fP = 46\&.686447783"
.br
.RI "m^-1 T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_bohr_magneton_in_inverse_meter_per_tesla\fP = 0\&.000000014"
.br
.RI "m^-1 T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::bohr_magneton_in_k_t\fP = 0\&.67171381563"
.br
.RI "K T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_bohr_magneton_in_k_t\fP = 0\&.00000000020"
.br
.RI "K T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::bohr_radius\fP = 5\&.29177210903d\-11"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_bohr_radius\fP = 0\&.00000000080d\-11"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::boltzmann_constant\fP = 1\&.380649d\-23"
.br
.RI "J K^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_boltzmann_constant\fP = 0\&.0"
.br
.RI "J K^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::boltzmann_constant_in_ev_k\fP = 8\&.617333262d\-5"
.br
.RI "eV K^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_boltzmann_constant_in_ev_k\fP = 0\&.0"
.br
.RI "eV K^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::boltzmann_constant_in_hz_k\fP = 2\&.083661912d10"
.br
.RI "Hz K^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_boltzmann_constant_in_hz_k\fP = 0\&.0"
.br
.RI "Hz K^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::boltzmann_constant_in_inverse_meter_per_kelvin\fP = 69\&.50348004"
.br
.RI "m^-1 K^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_boltzmann_constant_in_inverse_meter_per_kelvin\fP = 0\&.0"
.br
.RI "m^-1 K^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::characteristic_impedance_of_vacuum\fP = 376\&.730313668"
.br
.RI "ohm 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_characteristic_impedance_of_vacuum\fP = 0\&.000000057"
.br
.RI "ohm 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::classical_electron_radius\fP = 2\&.8179403262d\-15"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_classical_electron_radius\fP = 0\&.0000000013d\-15"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::compton_wavelength\fP = 2\&.42631023867d\-12"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_compton_wavelength\fP = 0\&.00000000073d\-12"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::conductance_quantum\fP = 7\&.748091729d\-5"
.br
.RI "S 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_conductance_quantum\fP = 0\&.0"
.br
.RI "S 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::conventional_value_of_ampere_90\fP = 1\&.00000008887"
.br
.RI "A 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_conventional_value_of_ampere_90\fP = 0\&.0"
.br
.RI "A 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::conventional_value_of_coulomb_90\fP = 1\&.00000008887"
.br
.RI "C 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_conventional_value_of_coulomb_90\fP = 0\&.0"
.br
.RI "C 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::conventional_value_of_farad_90\fP = 0\&.99999998220"
.br
.RI "F 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_conventional_value_of_farad_90\fP = 0\&.0"
.br
.RI "F 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::conventional_value_of_henry_90\fP = 1\&.00000001779"
.br
.RI "H 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_conventional_value_of_henry_90\fP = 0\&.0"
.br
.RI "H 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::conventional_value_of_josephson_constant\fP = 483597\&.9d9"
.br
.RI "Hz V^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_conventional_value_of_josephson_constant\fP = 0\&.0"
.br
.RI "Hz V^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::conventional_value_of_ohm_90\fP = 1\&.00000001779"
.br
.RI "ohm 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_conventional_value_of_ohm_90\fP = 0\&.0"
.br
.RI "ohm 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::conventional_value_of_volt_90\fP = 1\&.00000010666"
.br
.RI "V 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_conventional_value_of_volt_90\fP = 0\&.0"
.br
.RI "V 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::conventional_value_of_von_klitzing_constant\fP = 25812\&.807"
.br
.RI "ohm 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_conventional_value_of_von_klitzing_constant\fP = 0\&.0"
.br
.RI "ohm 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::conventional_value_of_watt_90\fP = 1\&.00000019553"
.br
.RI "W 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_conventional_value_of_watt_90\fP = 0\&.0"
.br
.RI "W 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::copper_x_unit\fP = 1\&.00207697d\-13"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_copper_x_unit\fP = 0\&.00000028d\-13"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::deuteron_electron_mag__mom__ratio\fP = \-4\&.664345551d\-4"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_deuteron_electron_mag__mom__ratio\fP = 0\&.000000012d\-4"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::deuteron_electron_mass_ratio\fP = 3670\&.48296788"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_deuteron_electron_mass_ratio\fP = 0\&.00000013"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::deuteron_g_factor\fP = 0\&.8574382338"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_deuteron_g_factor\fP = 0\&.0000000022"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::deuteron_mag__mom\fP = 4\&.330735094d\-27"
.br
.RI "J T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_deuteron_mag__mom\fP = 0\&.000000011d\-27"
.br
.RI "J T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::deuteron_mag__mom__to_bohr_magneton_ratio\fP = 4\&.669754570d\-4"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_deuteron_mag__mom__to_bohr_magneton_ratio\fP = 0\&.000000012d\-4"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::deuteron_mag__mom__to_nuclear_magneton_ratio\fP = 0\&.8574382338"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_deuteron_mag__mom__to_nuclear_magneton_ratio\fP = 0\&.0000000022"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::deuteron_mass\fP = 3\&.3435837724d\-27"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_deuteron_mass\fP = 0\&.0000000010d\-27"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::deuteron_mass_energy_equivalent\fP = 3\&.00506323102d\-10"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_deuteron_mass_energy_equivalent\fP = 0\&.00000000091d\-10"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::deuteron_mass_energy_equivalent_in_mev\fP = 1875\&.61294257"
.br
.RI "MeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_deuteron_mass_energy_equivalent_in_mev\fP = 0\&.00000057"
.br
.RI "MeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::deuteron_mass_in_u\fP = 2\&.013553212745"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_deuteron_mass_in_u\fP = 0\&.000000000040"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::deuteron_molar_mass\fP = 2\&.01355321205d\-3"
.br
.RI "kg mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_deuteron_molar_mass\fP = 0\&.00000000061d\-3"
.br
.RI "kg mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::deuteron_neutron_mag__mom__ratio\fP = \-0\&.44820653"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_deuteron_neutron_mag__mom__ratio\fP = 0\&.00000011"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::deuteron_proton_mag__mom__ratio\fP = 0\&.30701220939"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_deuteron_proton_mag__mom__ratio\fP = 0\&.00000000079"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::deuteron_proton_mass_ratio\fP = 1\&.99900750139"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_deuteron_proton_mass_ratio\fP = 0\&.00000000011"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::deuteron_relative_atomic_mass\fP = 2\&.013553212745"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_deuteron_relative_atomic_mass\fP = 0\&.000000000040"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::deuteron_rms_charge_radius\fP = 2\&.12799d\-15"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_deuteron_rms_charge_radius\fP = 0\&.00074d\-15"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_charge_to_mass_quotient\fP = \-1\&.75882001076d11"
.br
.RI "C kg^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_charge_to_mass_quotient\fP = 0\&.00000000053d11"
.br
.RI "C kg^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_deuteron_mag__mom__ratio\fP = \-2143\&.9234915"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_deuteron_mag__mom__ratio\fP = 0\&.0000056"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_deuteron_mass_ratio\fP = 2\&.724437107462d\-4"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_deuteron_mass_ratio\fP = 0\&.000000000096d\-4"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_g_factor\fP = \-2\&.00231930436256"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_g_factor\fP = 0\&.00000000000035"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_gyromag__ratio\fP = 1\&.76085963023d11"
.br
.RI "s^-1 T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_gyromag__ratio\fP = 0\&.00000000053d11"
.br
.RI "s^-1 T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_gyromag__ratio_in_mhz_t\fP = 28024\&.9514242"
.br
.RI "MHz T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_gyromag__ratio_in_mhz_t\fP = 0\&.0000085"
.br
.RI "MHz T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_helion_mass_ratio\fP = 1\&.819543074573d\-4"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_helion_mass_ratio\fP = 0\&.000000000079d\-4"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_mag__mom\fP = \-9\&.2847647043d\-24"
.br
.RI "J T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_mag__mom\fP = 0\&.0000000028d\-24"
.br
.RI "J T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_mag__mom__anomaly\fP = 1\&.15965218128d\-3"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_mag__mom__anomaly\fP = 0\&.00000000018d\-3"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_mag__mom__to_bohr_magneton_ratio\fP = \-1\&.00115965218128"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_mag__mom__to_bohr_magneton_ratio\fP = 0\&.00000000000018"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_mag__mom__to_nuclear_magneton_ratio\fP = \-1838\&.28197188"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_mag__mom__to_nuclear_magneton_ratio\fP = 0\&.00000011"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_mass\fP = 9\&.1093837015d\-31"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_mass\fP = 0\&.0000000028d\-31"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_mass_energy_equivalent\fP = 8\&.1871057769d\-14"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_mass_energy_equivalent\fP = 0\&.0000000025d\-14"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_mass_energy_equivalent_in_mev\fP = 0\&.51099895000"
.br
.RI "MeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_mass_energy_equivalent_in_mev\fP = 0\&.00000000015"
.br
.RI "MeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_mass_in_u\fP = 5\&.48579909065d\-4"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_mass_in_u\fP = 0\&.00000000016d\-4"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_molar_mass\fP = 5\&.4857990888d\-7"
.br
.RI "kg mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_molar_mass\fP = 0\&.0000000017d\-7"
.br
.RI "kg mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_muon_mag__mom__ratio\fP = 206\&.7669883"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_muon_mag__mom__ratio\fP = 0\&.0000046"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_muon_mass_ratio\fP = 4\&.83633169d\-3"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_muon_mass_ratio\fP = 0\&.00000011d\-3"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_neutron_mag__mom__ratio\fP = 960\&.92050"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_neutron_mag__mom__ratio\fP = 0\&.00023"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_neutron_mass_ratio\fP = 5\&.4386734424d\-4"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_neutron_mass_ratio\fP = 0\&.0000000026d\-4"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_proton_mag__mom__ratio\fP = \-658\&.21068789"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_proton_mag__mom__ratio\fP = 0\&.00000020"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_proton_mass_ratio\fP = 5\&.44617021487d\-4"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_proton_mass_ratio\fP = 0\&.00000000033d\-4"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_relative_atomic_mass\fP = 5\&.48579909065d\-4"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_relative_atomic_mass\fP = 0\&.00000000016d\-4"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_tau_mass_ratio\fP = 2\&.87585d\-4"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_tau_mass_ratio\fP = 0\&.00019d\-4"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_to_alpha_particle_mass_ratio\fP = 1\&.370933554787d\-4"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_to_alpha_particle_mass_ratio\fP = 0\&.000000000045d\-4"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_to_shielded_helion_mag__mom__ratio\fP = 864\&.058257"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_to_shielded_helion_mag__mom__ratio\fP = 0\&.000010"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_to_shielded_proton_mag__mom__ratio\fP = \-658\&.2275971"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_to_shielded_proton_mag__mom__ratio\fP = 0\&.0000072"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_triton_mass_ratio\fP = 1\&.819200062251d\-4"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_triton_mass_ratio\fP = 0\&.000000000090d\-4"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_volt\fP = 1\&.602176634d\-19"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_volt\fP = 0\&.0"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_volt_atomic_mass_unit_relationship\fP = 1\&.07354410233d\-9"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_volt_atomic_mass_unit_relationship\fP = 0\&.00000000032d\-9"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_volt_hartree_relationship\fP = 3\&.6749322175655d\-2"
.br
.RI "E_h 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_volt_hartree_relationship\fP = 0\&.0000000000071d\-2"
.br
.RI "E_h 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_volt_hertz_relationship\fP = 2\&.417989242d14"
.br
.RI "Hz 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_volt_hertz_relationship\fP = 0\&.0"
.br
.RI "Hz 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_volt_inverse_meter_relationship\fP = 8\&.065543937d5"
.br
.RI "m^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_volt_inverse_meter_relationship\fP = 0\&.0"
.br
.RI "m^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_volt_joule_relationship\fP = 1\&.602176634d\-19"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_volt_joule_relationship\fP = 0\&.0"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_volt_kelvin_relationship\fP = 1\&.160451812d4"
.br
.RI "K 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_volt_kelvin_relationship\fP = 0\&.0"
.br
.RI "K 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::electron_volt_kilogram_relationship\fP = 1\&.782661921d\-36"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_electron_volt_kilogram_relationship\fP = 0\&.0"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::elementary_charge\fP = 1\&.602176634d\-19"
.br
.RI "C 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_elementary_charge\fP = 0\&.0"
.br
.RI "C 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::elementary_charge_over_h_bar\fP = 1\&.519267447d15"
.br
.RI "A J^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_elementary_charge_over_h_bar\fP = 0\&.0"
.br
.RI "A J^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::faraday_constant\fP = 96485\&.33212"
.br
.RI "C mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_faraday_constant\fP = 0\&.0"
.br
.RI "C mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::fermi_coupling_constant\fP = 1\&.1663787d\-5"
.br
.RI "GeV^-2 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_fermi_coupling_constant\fP = 0\&.0000006d\-5"
.br
.RI "GeV^-2 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::fine_structure_constant\fP = 7\&.2973525693d\-3"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_fine_structure_constant\fP = 0\&.0000000011d\-3"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::first_radiation_constant\fP = 3\&.741771852d\-16"
.br
.RI "W m^2 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_first_radiation_constant\fP = 0\&.0"
.br
.RI "W m^2 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::first_radiation_constant_for_spectral_radiance\fP = 1\&.191042972d\-16"
.br
.RI "W m^2 sr^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_first_radiation_constant_for_spectral_radiance\fP = 0\&.0"
.br
.RI "W m^2 sr^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::hartree_atomic_mass_unit_relationship\fP = 2\&.92126232205d\-8"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_hartree_atomic_mass_unit_relationship\fP = 0\&.00000000088d\-8"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::hartree_electron_volt_relationship\fP = 27\&.211386245988"
.br
.RI "eV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_hartree_electron_volt_relationship\fP = 0\&.000000000053"
.br
.RI "eV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::hartree_energy\fP = 4\&.3597447222071d\-18"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_hartree_energy\fP = 0\&.0000000000085d\-18"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::hartree_energy_in_ev\fP = 27\&.211386245988"
.br
.RI "eV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_hartree_energy_in_ev\fP = 0\&.000000000053"
.br
.RI "eV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::hartree_hertz_relationship\fP = 6\&.579683920502d15"
.br
.RI "Hz 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_hartree_hertz_relationship\fP = 0\&.000000000013d15"
.br
.RI "Hz 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::hartree_inverse_meter_relationship\fP = 2\&.1947463136320d7"
.br
.RI "m^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_hartree_inverse_meter_relationship\fP = 0\&.0000000000043d7"
.br
.RI "m^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::hartree_joule_relationship\fP = 4\&.3597447222071d\-18"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_hartree_joule_relationship\fP = 0\&.0000000000085d\-18"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::hartree_kelvin_relationship\fP = 3\&.1577502480407d5"
.br
.RI "K 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_hartree_kelvin_relationship\fP = 0\&.0000000000061d5"
.br
.RI "K 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::hartree_kilogram_relationship\fP = 4\&.8508702095432d\-35"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_hartree_kilogram_relationship\fP = 0\&.0000000000094d\-35"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::helion_electron_mass_ratio\fP = 5495\&.88528007"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_helion_electron_mass_ratio\fP = 0\&.00000024"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::helion_g_factor\fP = \-4\&.255250615"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_helion_g_factor\fP = 0\&.000000050"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::helion_mag__mom\fP = \-1\&.074617532d\-26"
.br
.RI "J T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_helion_mag__mom\fP = 0\&.000000013d\-26"
.br
.RI "J T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::helion_mag__mom__to_bohr_magneton_ratio\fP = \-1\&.158740958d\-3"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_helion_mag__mom__to_bohr_magneton_ratio\fP = 0\&.000000014d\-3"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::helion_mag__mom__to_nuclear_magneton_ratio\fP = \-2\&.127625307"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_helion_mag__mom__to_nuclear_magneton_ratio\fP = 0\&.000000025"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::helion_mass\fP = 5\&.0064127796d\-27"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_helion_mass\fP = 0\&.0000000015d\-27"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::helion_mass_energy_equivalent\fP = 4\&.4995394125d\-10"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_helion_mass_energy_equivalent\fP = 0\&.0000000014d\-10"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::helion_mass_energy_equivalent_in_mev\fP = 2808\&.39160743"
.br
.RI "MeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_helion_mass_energy_equivalent_in_mev\fP = 0\&.00000085"
.br
.RI "MeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::helion_mass_in_u\fP = 3\&.014932247175"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_helion_mass_in_u\fP = 0\&.000000000097"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::helion_molar_mass\fP = 3\&.01493224613d\-3"
.br
.RI "kg mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_helion_molar_mass\fP = 0\&.00000000091d\-3"
.br
.RI "kg mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::helion_proton_mass_ratio\fP = 2\&.99315267167"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_helion_proton_mass_ratio\fP = 0\&.00000000013"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::helion_relative_atomic_mass\fP = 3\&.014932247175"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_helion_relative_atomic_mass\fP = 0\&.000000000097"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::helion_shielding_shift\fP = 5\&.996743d\-5"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_helion_shielding_shift\fP = 0\&.000010d\-5"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::hertz_atomic_mass_unit_relationship\fP = 4\&.4398216652d\-24"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_hertz_atomic_mass_unit_relationship\fP = 0\&.0000000013d\-24"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::hertz_electron_volt_relationship\fP = 4\&.135667696d\-15"
.br
.RI "eV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_hertz_electron_volt_relationship\fP = 0\&.0"
.br
.RI "eV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::hertz_hartree_relationship\fP = 1\&.5198298460570d\-16"
.br
.RI "E_h 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_hertz_hartree_relationship\fP = 0\&.0000000000029d\-16"
.br
.RI "E_h 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::hertz_inverse_meter_relationship\fP = 3\&.335640951d\-9"
.br
.RI "m^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_hertz_inverse_meter_relationship\fP = 0\&.0"
.br
.RI "m^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::hertz_joule_relationship\fP = 6\&.62607015d\-34"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_hertz_joule_relationship\fP = 0\&.0"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::hertz_kelvin_relationship\fP = 4\&.799243073d\-11"
.br
.RI "K 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_hertz_kelvin_relationship\fP = 0\&.0"
.br
.RI "K 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::hertz_kilogram_relationship\fP = 7\&.372497323d\-51"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_hertz_kilogram_relationship\fP = 0\&.0"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::hyperfine_transition_frequency_of_cs_133\fP = 9192631770\&.0"
.br
.RI "Hz 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_hyperfine_transition_frequency_of_cs_133\fP = 0\&.0"
.br
.RI "Hz 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::inverse_fine_structure_constant\fP = 137\&.035999084"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_inverse_fine_structure_constant\fP = 0\&.000000021"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::inverse_meter_atomic_mass_unit_relationship\fP = 1\&.33102505010d\-15"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_inverse_meter_atomic_mass_unit_relationship\fP = 0\&.00000000040d\-15"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::inverse_meter_electron_volt_relationship\fP = 1\&.239841984d\-6"
.br
.RI "eV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_inverse_meter_electron_volt_relationship\fP = 0\&.0"
.br
.RI "eV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::inverse_meter_hartree_relationship\fP = 4\&.5563352529120d\-8"
.br
.RI "E_h 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_inverse_meter_hartree_relationship\fP = 0\&.0000000000088d\-8"
.br
.RI "E_h 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::inverse_meter_hertz_relationship\fP = 299792458\&.0"
.br
.RI "Hz 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_inverse_meter_hertz_relationship\fP = 0\&.0"
.br
.RI "Hz 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::inverse_meter_joule_relationship\fP = 1\&.986445857d\-25"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_inverse_meter_joule_relationship\fP = 0\&.0"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::inverse_meter_kelvin_relationship\fP = 1\&.438776877d\-2"
.br
.RI "K 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_inverse_meter_kelvin_relationship\fP = 0\&.0"
.br
.RI "K 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::inverse_meter_kilogram_relationship\fP = 2\&.210219094d\-42"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_inverse_meter_kilogram_relationship\fP = 0\&.0"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::inverse_of_conductance_quantum\fP = 12906\&.40372"
.br
.RI "ohm 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_inverse_of_conductance_quantum\fP = 0\&.0"
.br
.RI "ohm 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::josephson_constant\fP = 483597\&.8484d9"
.br
.RI "Hz V^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_josephson_constant\fP = 0\&.0"
.br
.RI "Hz V^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::joule_atomic_mass_unit_relationship\fP = 6\&.7005352565d9"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_joule_atomic_mass_unit_relationship\fP = 0\&.0000000020d9"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::joule_electron_volt_relationship\fP = 6\&.241509074d18"
.br
.RI "eV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_joule_electron_volt_relationship\fP = 0\&.0"
.br
.RI "eV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::joule_hartree_relationship\fP = 2\&.2937122783963d17"
.br
.RI "E_h 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_joule_hartree_relationship\fP = 0\&.0000000000045d17"
.br
.RI "E_h 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::joule_hertz_relationship\fP = 1\&.509190179d33"
.br
.RI "Hz 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_joule_hertz_relationship\fP = 0\&.0"
.br
.RI "Hz 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::joule_inverse_meter_relationship\fP = 5\&.034116567d24"
.br
.RI "m^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_joule_inverse_meter_relationship\fP = 0\&.0"
.br
.RI "m^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::joule_kelvin_relationship\fP = 7\&.242970516d22"
.br
.RI "K 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_joule_kelvin_relationship\fP = 0\&.0"
.br
.RI "K 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::joule_kilogram_relationship\fP = 1\&.112650056d\-17"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_joule_kilogram_relationship\fP = 0\&.0"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::kelvin_atomic_mass_unit_relationship\fP = 9\&.2510873014d\-14"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_kelvin_atomic_mass_unit_relationship\fP = 0\&.0000000028d\-14"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::kelvin_electron_volt_relationship\fP = 8\&.617333262d\-5"
.br
.RI "eV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_kelvin_electron_volt_relationship\fP = 0\&.0"
.br
.RI "eV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::kelvin_hartree_relationship\fP = 3\&.1668115634556d\-6"
.br
.RI "E_h 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_kelvin_hartree_relationship\fP = 0\&.0000000000061d\-6"
.br
.RI "E_h 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::kelvin_hertz_relationship\fP = 2\&.083661912d10"
.br
.RI "Hz 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_kelvin_hertz_relationship\fP = 0\&.0"
.br
.RI "Hz 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::kelvin_inverse_meter_relationship\fP = 69\&.50348004"
.br
.RI "m^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_kelvin_inverse_meter_relationship\fP = 0\&.0"
.br
.RI "m^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::kelvin_joule_relationship\fP = 1\&.380649d\-23"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_kelvin_joule_relationship\fP = 0\&.0"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::kelvin_kilogram_relationship\fP = 1\&.536179187d\-40"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_kelvin_kilogram_relationship\fP = 0\&.0"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::kilogram_atomic_mass_unit_relationship\fP = 6\&.0221407621d26"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_kilogram_atomic_mass_unit_relationship\fP = 0\&.0000000018d26"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::kilogram_electron_volt_relationship\fP = 5\&.609588603d35"
.br
.RI "eV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_kilogram_electron_volt_relationship\fP = 0\&.0"
.br
.RI "eV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::kilogram_hartree_relationship\fP = 2\&.0614857887409d34"
.br
.RI "E_h 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_kilogram_hartree_relationship\fP = 0\&.0000000000040d34"
.br
.RI "E_h 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::kilogram_hertz_relationship\fP = 1\&.356392489d50"
.br
.RI "Hz 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_kilogram_hertz_relationship\fP = 0\&.0"
.br
.RI "Hz 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::kilogram_inverse_meter_relationship\fP = 4\&.524438335d41"
.br
.RI "m^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_kilogram_inverse_meter_relationship\fP = 0\&.0"
.br
.RI "m^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::kilogram_joule_relationship\fP = 8\&.987551787d16"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_kilogram_joule_relationship\fP = 0\&.0"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::kilogram_kelvin_relationship\fP = 6\&.509657260d39"
.br
.RI "K 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_kilogram_kelvin_relationship\fP = 0\&.0"
.br
.RI "K 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::lattice_parameter_of_silicon\fP = 5\&.431020511d\-10"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_lattice_parameter_of_silicon\fP = 0\&.000000089d\-10"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::lattice_spacing_of_ideal_si__220\fP = 1\&.920155716d\-10"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_lattice_spacing_of_ideal_si__220\fP = 0\&.000000032d\-10"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::loschmidt_constant__273_15_k__100_kpa\fP = 2\&.651645804d25"
.br
.RI "m^-3 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_loschmidt_constant__273_15_k__100_kpa\fP = 0\&.0"
.br
.RI "m^-3 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::loschmidt_constant__273_15_k__101_325_kpa\fP = 2\&.686780111d25"
.br
.RI "m^-3 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_loschmidt_constant__273_15_k__101_325_kpa\fP = 0\&.0"
.br
.RI "m^-3 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::luminous_efficacy\fP = 683\&.0"
.br
.RI "lm W^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_luminous_efficacy\fP = 0\&.0"
.br
.RI "lm W^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::mag__flux_quantum\fP = 2\&.067833848d\-15"
.br
.RI "Wb 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_mag__flux_quantum\fP = 0\&.0"
.br
.RI "Wb 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::molar_gas_constant\fP = 8\&.314462618"
.br
.RI "J mol^-1 K^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_molar_gas_constant\fP = 0\&.0"
.br
.RI "J mol^-1 K^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::molar_mass_constant\fP = 0\&.99999999965d\-3"
.br
.RI "kg mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_molar_mass_constant\fP = 0\&.00000000030d\-3"
.br
.RI "kg mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::molar_mass_of_carbon_12\fP = 11\&.9999999958d\-3"
.br
.RI "kg mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_molar_mass_of_carbon_12\fP = 0\&.0000000036d\-3"
.br
.RI "kg mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::molar_planck_constant\fP = 3\&.990312712d\-10"
.br
.RI "J Hz^-1 mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_molar_planck_constant\fP = 0\&.0"
.br
.RI "J Hz^-1 mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::molar_volume_of_ideal_gas__273_15_k__100_kpa\fP = 22\&.71095464d\-3"
.br
.RI "m^3 mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_molar_volume_of_ideal_gas__273_15_k__100_kpa\fP = 0\&.0"
.br
.RI "m^3 mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::molar_volume_of_ideal_gas__273_15_k__101_325_kpa\fP = 22\&.41396954d\-3"
.br
.RI "m^3 mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_molar_volume_of_ideal_gas__273_15_k__101_325_kpa\fP = 0\&.0"
.br
.RI "m^3 mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::molar_volume_of_silicon\fP = 1\&.205883199d\-5"
.br
.RI "m^3 mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_molar_volume_of_silicon\fP = 0\&.000000060d\-5"
.br
.RI "m^3 mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::molybdenum_x_unit\fP = 1\&.00209952d\-13"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_molybdenum_x_unit\fP = 0\&.00000053d\-13"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::muon_compton_wavelength\fP = 1\&.173444110d\-14"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_muon_compton_wavelength\fP = 0\&.000000026d\-14"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::muon_electron_mass_ratio\fP = 206\&.7682830"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_muon_electron_mass_ratio\fP = 0\&.0000046"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::muon_g_factor\fP = \-2\&.0023318418"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_muon_g_factor\fP = 0\&.0000000013"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::muon_mag__mom\fP = \-4\&.49044830d\-26"
.br
.RI "J T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_muon_mag__mom\fP = 0\&.00000010d\-26"
.br
.RI "J T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::muon_mag__mom__anomaly\fP = 1\&.16592089d\-3"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_muon_mag__mom__anomaly\fP = 0\&.00000063d\-3"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::muon_mag__mom__to_bohr_magneton_ratio\fP = \-4\&.84197047d\-3"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_muon_mag__mom__to_bohr_magneton_ratio\fP = 0\&.00000011d\-3"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::muon_mag__mom__to_nuclear_magneton_ratio\fP = \-8\&.89059703"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_muon_mag__mom__to_nuclear_magneton_ratio\fP = 0\&.00000020"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::muon_mass\fP = 1\&.883531627d\-28"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_muon_mass\fP = 0\&.000000042d\-28"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::muon_mass_energy_equivalent\fP = 1\&.692833804d\-11"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_muon_mass_energy_equivalent\fP = 0\&.000000038d\-11"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::muon_mass_energy_equivalent_in_mev\fP = 105\&.6583755"
.br
.RI "MeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_muon_mass_energy_equivalent_in_mev\fP = 0\&.0000023"
.br
.RI "MeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::muon_mass_in_u\fP = 0\&.1134289259"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_muon_mass_in_u\fP = 0\&.0000000025"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::muon_molar_mass\fP = 1\&.134289259d\-4"
.br
.RI "kg mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_muon_molar_mass\fP = 0\&.000000025d\-4"
.br
.RI "kg mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::muon_neutron_mass_ratio\fP = 0\&.1124545170"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_muon_neutron_mass_ratio\fP = 0\&.0000000025"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::muon_proton_mag__mom__ratio\fP = \-3\&.183345142"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_muon_proton_mag__mom__ratio\fP = 0\&.000000071"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::muon_proton_mass_ratio\fP = 0\&.1126095264"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_muon_proton_mass_ratio\fP = 0\&.0000000025"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::muon_tau_mass_ratio\fP = 5\&.94635d\-2"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_muon_tau_mass_ratio\fP = 0\&.00040d\-2"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::natural_unit_of_action\fP = 1\&.054571817d\-34"
.br
.RI "J s 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_natural_unit_of_action\fP = 0\&.0"
.br
.RI "J s 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::natural_unit_of_action_in_ev_s\fP = 6\&.582119569d\-16"
.br
.RI "eV s 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_natural_unit_of_action_in_ev_s\fP = 0\&.0"
.br
.RI "eV s 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::natural_unit_of_energy\fP = 8\&.1871057769d\-14"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_natural_unit_of_energy\fP = 0\&.0000000025d\-14"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::natural_unit_of_energy_in_mev\fP = 0\&.51099895000"
.br
.RI "MeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_natural_unit_of_energy_in_mev\fP = 0\&.00000000015"
.br
.RI "MeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::natural_unit_of_length\fP = 3\&.8615926796d\-13"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_natural_unit_of_length\fP = 0\&.0000000012d\-13"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::natural_unit_of_mass\fP = 9\&.1093837015d\-31"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_natural_unit_of_mass\fP = 0\&.0000000028d\-31"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::natural_unit_of_momentum\fP = 2\&.73092453075d\-22"
.br
.RI "kg m s^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_natural_unit_of_momentum\fP = 0\&.00000000082d\-22"
.br
.RI "kg m s^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::natural_unit_of_momentum_in_mev_c\fP = 0\&.51099895000"
.br
.RI "MeV/c 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_natural_unit_of_momentum_in_mev_c\fP = 0\&.00000000015"
.br
.RI "MeV/c 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::natural_unit_of_time\fP = 1\&.28808866819d\-21"
.br
.RI "s 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_natural_unit_of_time\fP = 0\&.00000000039d\-21"
.br
.RI "s 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::natural_unit_of_velocity\fP = 299792458\&.0"
.br
.RI "m s^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_natural_unit_of_velocity\fP = 0\&.0"
.br
.RI "m s^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::neutron_compton_wavelength\fP = 1\&.31959090581d\-15"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_neutron_compton_wavelength\fP = 0\&.00000000075d\-15"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::neutron_electron_mag__mom__ratio\fP = 1\&.04066882d\-3"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_neutron_electron_mag__mom__ratio\fP = 0\&.00000025d\-3"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::neutron_electron_mass_ratio\fP = 1838\&.68366173"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_neutron_electron_mass_ratio\fP = 0\&.00000089"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::neutron_g_factor\fP = \-3\&.82608545"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_neutron_g_factor\fP = 0\&.00000090"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::neutron_gyromag__ratio\fP = 1\&.83247171d8"
.br
.RI "s^-1 T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_neutron_gyromag__ratio\fP = 0\&.00000043d8"
.br
.RI "s^-1 T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::neutron_gyromag__ratio_in_mhz_t\fP = 29\&.1646931"
.br
.RI "MHz T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_neutron_gyromag__ratio_in_mhz_t\fP = 0\&.0000069"
.br
.RI "MHz T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::neutron_mag__mom\fP = \-9\&.6623651d\-27"
.br
.RI "J T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_neutron_mag__mom\fP = 0\&.0000023d\-27"
.br
.RI "J T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::neutron_mag__mom__to_bohr_magneton_ratio\fP = \-1\&.04187563d\-3"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_neutron_mag__mom__to_bohr_magneton_ratio\fP = 0\&.00000025d\-3"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::neutron_mag__mom__to_nuclear_magneton_ratio\fP = \-1\&.91304273"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_neutron_mag__mom__to_nuclear_magneton_ratio\fP = 0\&.00000045"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::neutron_mass\fP = 1\&.67492749804d\-27"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_neutron_mass\fP = 0\&.00000000095d\-27"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::neutron_mass_energy_equivalent\fP = 1\&.50534976287d\-10"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_neutron_mass_energy_equivalent\fP = 0\&.00000000086d\-10"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::neutron_mass_energy_equivalent_in_mev\fP = 939\&.56542052"
.br
.RI "MeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_neutron_mass_energy_equivalent_in_mev\fP = 0\&.00000054"
.br
.RI "MeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::neutron_mass_in_u\fP = 1\&.00866491595"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_neutron_mass_in_u\fP = 0\&.00000000049"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::neutron_molar_mass\fP = 1\&.00866491560d\-3"
.br
.RI "kg mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_neutron_molar_mass\fP = 0\&.00000000057d\-3"
.br
.RI "kg mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::neutron_muon_mass_ratio\fP = 8\&.89248406"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_neutron_muon_mass_ratio\fP = 0\&.00000020"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::neutron_proton_mag__mom__ratio\fP = \-0\&.68497934"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_neutron_proton_mag__mom__ratio\fP = 0\&.00000016"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::neutron_proton_mass_difference\fP = 2\&.30557435d\-30"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_neutron_proton_mass_difference\fP = 0\&.00000082d\-30"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::neutron_proton_mass_difference_energy_equivalent\fP = 2\&.07214689d\-13"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_neutron_proton_mass_difference_energy_equivalent\fP = 0\&.00000074d\-13"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::neutron_proton_mass_difference_energy_equivalent_in_mev\fP = 1\&.29333236"
.br
.RI "MeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_neutron_proton_mass_difference_energy_equivalent_in_mev\fP = 0\&.00000046"
.br
.RI "MeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::neutron_proton_mass_difference_in_u\fP = 1\&.38844933d\-3"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_neutron_proton_mass_difference_in_u\fP = 0\&.00000049d\-3"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::neutron_proton_mass_ratio\fP = 1\&.00137841931"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_neutron_proton_mass_ratio\fP = 0\&.00000000049"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::neutron_relative_atomic_mass\fP = 1\&.00866491595"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_neutron_relative_atomic_mass\fP = 0\&.00000000049"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::neutron_tau_mass_ratio\fP = 0\&.528779"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_neutron_tau_mass_ratio\fP = 0\&.000036"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::neutron_to_shielded_proton_mag__mom__ratio\fP = \-0\&.68499694"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_neutron_to_shielded_proton_mag__mom__ratio\fP = 0\&.00000016"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::newtonian_constant_of_gravitation\fP = 6\&.67430d\-11"
.br
.RI "m^3 kg^-1 s^-2 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_newtonian_constant_of_gravitation\fP = 0\&.00015d\-11"
.br
.RI "m^3 kg^-1 s^-2 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::newtonian_constant_of_gravitation_over_h_bar_c\fP = 6\&.70883d\-39"
.br
.RI "(GeV/c^2)^-2 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_newtonian_constant_of_gravitation_over_h_bar_c\fP = 0\&.00015d\-39"
.br
.RI "(GeV/c^2)^-2 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::nuclear_magneton\fP = 5\&.0507837461d\-27"
.br
.RI "J T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_nuclear_magneton\fP = 0\&.0000000015d\-27"
.br
.RI "J T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::nuclear_magneton_in_ev_t\fP = 3\&.15245125844d\-8"
.br
.RI "eV T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_nuclear_magneton_in_ev_t\fP = 0\&.00000000096d\-8"
.br
.RI "eV T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::nuclear_magneton_in_inverse_meter_per_tesla\fP = 2\&.54262341353d\-2"
.br
.RI "m^-1 T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_nuclear_magneton_in_inverse_meter_per_tesla\fP = 0\&.00000000078d\-2"
.br
.RI "m^-1 T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::nuclear_magneton_in_k_t\fP = 3\&.6582677756d\-4"
.br
.RI "K T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_nuclear_magneton_in_k_t\fP = 0\&.0000000011d\-4"
.br
.RI "K T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::nuclear_magneton_in_mhz_t\fP = 7\&.6225932291"
.br
.RI "MHz T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_nuclear_magneton_in_mhz_t\fP = 0\&.0000000023"
.br
.RI "MHz T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::planck_constant\fP = 6\&.62607015d\-34"
.br
.RI "J Hz^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_planck_constant\fP = 0\&.0"
.br
.RI "J Hz^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::planck_constant_in_ev_hz\fP = 4\&.135667696d\-15"
.br
.RI "eV Hz^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_planck_constant_in_ev_hz\fP = 0\&.0"
.br
.RI "eV Hz^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::planck_length\fP = 1\&.616255d\-35"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_planck_length\fP = 0\&.000018d\-35"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::planck_mass\fP = 2\&.176434d\-8"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_planck_mass\fP = 0\&.000024d\-8"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::planck_mass_energy_equivalent_in_gev\fP = 1\&.220890d19"
.br
.RI "GeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_planck_mass_energy_equivalent_in_gev\fP = 0\&.000014d19"
.br
.RI "GeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::planck_temperature\fP = 1\&.416784d32"
.br
.RI "K 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_planck_temperature\fP = 0\&.000016d32"
.br
.RI "K 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::planck_time\fP = 5\&.391247d\-44"
.br
.RI "s 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_planck_time\fP = 0\&.000060d\-44"
.br
.RI "s 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::proton_charge_to_mass_quotient\fP = 9\&.5788331560d7"
.br
.RI "C kg^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_proton_charge_to_mass_quotient\fP = 0\&.0000000029d7"
.br
.RI "C kg^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::proton_compton_wavelength\fP = 1\&.32140985539d\-15"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_proton_compton_wavelength\fP = 0\&.00000000040d\-15"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::proton_electron_mass_ratio\fP = 1836\&.15267343"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_proton_electron_mass_ratio\fP = 0\&.00000011"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::proton_g_factor\fP = 5\&.5856946893"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_proton_g_factor\fP = 0\&.0000000016"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::proton_gyromag__ratio\fP = 2\&.6752218744d8"
.br
.RI "s^-1 T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_proton_gyromag__ratio\fP = 0\&.0000000011d8"
.br
.RI "s^-1 T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::proton_gyromag__ratio_in_mhz_t\fP = 42\&.577478518"
.br
.RI "MHz T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_proton_gyromag__ratio_in_mhz_t\fP = 0\&.000000018"
.br
.RI "MHz T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::proton_mag__mom\fP = 1\&.41060679736d\-26"
.br
.RI "J T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_proton_mag__mom\fP = 0\&.00000000060d\-26"
.br
.RI "J T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::proton_mag__mom__to_bohr_magneton_ratio\fP = 1\&.52103220230d\-3"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_proton_mag__mom__to_bohr_magneton_ratio\fP = 0\&.00000000046d\-3"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::proton_mag__mom__to_nuclear_magneton_ratio\fP = 2\&.79284734463"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_proton_mag__mom__to_nuclear_magneton_ratio\fP = 0\&.00000000082"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::proton_mag__shielding_correction\fP = 2\&.5689d\-5"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_proton_mag__shielding_correction\fP = 0\&.0011d\-5"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::proton_mass\fP = 1\&.67262192369d\-27"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_proton_mass\fP = 0\&.00000000051d\-27"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::proton_mass_energy_equivalent\fP = 1\&.50327761598d\-10"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_proton_mass_energy_equivalent\fP = 0\&.00000000046d\-10"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::proton_mass_energy_equivalent_in_mev\fP = 938\&.27208816"
.br
.RI "MeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_proton_mass_energy_equivalent_in_mev\fP = 0\&.00000029"
.br
.RI "MeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::proton_mass_in_u\fP = 1\&.007276466621"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_proton_mass_in_u\fP = 0\&.000000000053"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::proton_molar_mass\fP = 1\&.00727646627d\-3"
.br
.RI "kg mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_proton_molar_mass\fP = 0\&.00000000031d\-3"
.br
.RI "kg mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::proton_muon_mass_ratio\fP = 8\&.88024337"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_proton_muon_mass_ratio\fP = 0\&.00000020"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::proton_neutron_mag__mom__ratio\fP = \-1\&.45989805"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_proton_neutron_mag__mom__ratio\fP = 0\&.00000034"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::proton_neutron_mass_ratio\fP = 0\&.99862347812"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_proton_neutron_mass_ratio\fP = 0\&.00000000049"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::proton_relative_atomic_mass\fP = 1\&.007276466621"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_proton_relative_atomic_mass\fP = 0\&.000000000053"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::proton_rms_charge_radius\fP = 8\&.414d\-16"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_proton_rms_charge_radius\fP = 0\&.019d\-16"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::proton_tau_mass_ratio\fP = 0\&.528051"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_proton_tau_mass_ratio\fP = 0\&.000036"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::quantum_of_circulation\fP = 3\&.6369475516d\-4"
.br
.RI "m^2 s^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_quantum_of_circulation\fP = 0\&.0000000011d\-4"
.br
.RI "m^2 s^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::quantum_of_circulation_times_2\fP = 7\&.2738951032d\-4"
.br
.RI "m^2 s^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_quantum_of_circulation_times_2\fP = 0\&.0000000022d\-4"
.br
.RI "m^2 s^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::reduced_compton_wavelength\fP = 3\&.8615926796d\-13"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_reduced_compton_wavelength\fP = 0\&.0000000012d\-13"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::reduced_muon_compton_wavelength\fP = 1\&.867594306d\-15"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_reduced_muon_compton_wavelength\fP = 0\&.000000042d\-15"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::reduced_neutron_compton_wavelength\fP = 2\&.1001941552d\-16"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_reduced_neutron_compton_wavelength\fP = 0\&.0000000012d\-16"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::reduced_planck_constant\fP = 1\&.054571817d\-34"
.br
.RI "J s 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_reduced_planck_constant\fP = 0\&.0"
.br
.RI "J s 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::reduced_planck_constant_in_ev_s\fP = 6\&.582119569d\-16"
.br
.RI "eV s 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_reduced_planck_constant_in_ev_s\fP = 0\&.0"
.br
.RI "eV s 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::reduced_planck_constant_times_c_in_mev_fm\fP = 197\&.3269804"
.br
.RI "MeV fm 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_reduced_planck_constant_times_c_in_mev_fm\fP = 0\&.0"
.br
.RI "MeV fm 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::reduced_proton_compton_wavelength\fP = 2\&.10308910336d\-16"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_reduced_proton_compton_wavelength\fP = 0\&.00000000064d\-16"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::reduced_tau_compton_wavelength\fP = 1\&.110538d\-16"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_reduced_tau_compton_wavelength\fP = 0\&.000075d\-16"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::rydberg_constant\fP = 10973731\&.568160"
.br
.RI "m^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_rydberg_constant\fP = 0\&.000021"
.br
.RI "m^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::rydberg_constant_times_c_in_hz\fP = 3\&.2898419602508d15"
.br
.RI "Hz 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_rydberg_constant_times_c_in_hz\fP = 0\&.0000000000064d15"
.br
.RI "Hz 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::rydberg_constant_times_hc_in_ev\fP = 13\&.605693122994"
.br
.RI "eV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_rydberg_constant_times_hc_in_ev\fP = 0\&.000000000026"
.br
.RI "eV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::rydberg_constant_times_hc_in_j\fP = 2\&.1798723611035d\-18"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_rydberg_constant_times_hc_in_j\fP = 0\&.0000000000042d\-18"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::sackur_tetrode_constant__1_k__100_kpa\fP = \-1\&.15170753706"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_sackur_tetrode_constant__1_k__100_kpa\fP = 0\&.00000000045"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::sackur_tetrode_constant__1_k__101_325_kpa\fP = \-1\&.16487052358"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_sackur_tetrode_constant__1_k__101_325_kpa\fP = 0\&.00000000045"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::second_radiation_constant\fP = 1\&.438776877d\-2"
.br
.RI "m K 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_second_radiation_constant\fP = 0\&.0"
.br
.RI "m K 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::shielded_helion_gyromag__ratio\fP = 2\&.037894569d8"
.br
.RI "s^-1 T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_shielded_helion_gyromag__ratio\fP = 0\&.000000024d8"
.br
.RI "s^-1 T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::shielded_helion_gyromag__ratio_in_mhz_t\fP = 32\&.43409942"
.br
.RI "MHz T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_shielded_helion_gyromag__ratio_in_mhz_t\fP = 0\&.00000038"
.br
.RI "MHz T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::shielded_helion_mag__mom\fP = \-1\&.074553090d\-26"
.br
.RI "J T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_shielded_helion_mag__mom\fP = 0\&.000000013d\-26"
.br
.RI "J T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::shielded_helion_mag__mom__to_bohr_magneton_ratio\fP = \-1\&.158671471d\-3"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_shielded_helion_mag__mom__to_bohr_magneton_ratio\fP = 0\&.000000014d\-3"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::shielded_helion_mag__mom__to_nuclear_magneton_ratio\fP = \-2\&.127497719"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_shielded_helion_mag__mom__to_nuclear_magneton_ratio\fP = 0\&.000000025"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::shielded_helion_to_proton_mag__mom__ratio\fP = \-0\&.7617665618"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_shielded_helion_to_proton_mag__mom__ratio\fP = 0\&.0000000089"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::shielded_helion_to_shielded_proton_mag__mom__ratio\fP = \-0\&.7617861313"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_shielded_helion_to_shielded_proton_mag__mom__ratio\fP = 0\&.0000000033"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::shielded_proton_gyromag__ratio\fP = 2\&.675153151d8"
.br
.RI "s^-1 T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_shielded_proton_gyromag__ratio\fP = 0\&.000000029d8"
.br
.RI "s^-1 T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::shielded_proton_gyromag__ratio_in_mhz_t\fP = 42\&.57638474"
.br
.RI "MHz T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_shielded_proton_gyromag__ratio_in_mhz_t\fP = 0\&.00000046"
.br
.RI "MHz T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::shielded_proton_mag__mom\fP = 1\&.410570560d\-26"
.br
.RI "J T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_shielded_proton_mag__mom\fP = 0\&.000000015d\-26"
.br
.RI "J T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::shielded_proton_mag__mom__to_bohr_magneton_ratio\fP = 1\&.520993128d\-3"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_shielded_proton_mag__mom__to_bohr_magneton_ratio\fP = 0\&.000000017d\-3"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::shielded_proton_mag__mom__to_nuclear_magneton_ratio\fP = 2\&.792775599"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_shielded_proton_mag__mom__to_nuclear_magneton_ratio\fP = 0\&.000000030"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::shielding_difference_of_d_and_p_in_hd\fP = 2\&.0200d\-8"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_shielding_difference_of_d_and_p_in_hd\fP = 0\&.0020d\-8"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::shielding_difference_of_t_and_p_in_ht\fP = 2\&.4140d\-8"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_shielding_difference_of_t_and_p_in_ht\fP = 0\&.0020d\-8"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::speed_of_light_in_vacuum\fP = 299792458\&.0"
.br
.RI "m s^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_speed_of_light_in_vacuum\fP = 0\&.0"
.br
.RI "m s^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::standard_acceleration_of_gravity\fP = 9\&.80665"
.br
.RI "m s^-2 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_standard_acceleration_of_gravity\fP = 0\&.0"
.br
.RI "m s^-2 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::standard_atmosphere\fP = 101325\&.0"
.br
.RI "Pa 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_standard_atmosphere\fP = 0\&.0"
.br
.RI "Pa 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::standard_state_pressure\fP = 100000\&.0"
.br
.RI "Pa 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_standard_state_pressure\fP = 0\&.0"
.br
.RI "Pa 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::stefan_boltzmann_constant\fP = 5\&.670374419d\-8"
.br
.RI "W m^-2 K^-4 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_stefan_boltzmann_constant\fP = 0\&.0"
.br
.RI "W m^-2 K^-4 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::tau_compton_wavelength\fP = 6\&.97771d\-16"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_tau_compton_wavelength\fP = 0\&.00047d\-16"
.br
.RI "m 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::tau_electron_mass_ratio\fP = 3477\&.23"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_tau_electron_mass_ratio\fP = 0\&.23"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::tau_energy_equivalent\fP = 1776\&.86"
.br
.RI "MeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_tau_energy_equivalent\fP = 0\&.12"
.br
.RI "MeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::tau_mass\fP = 3\&.16754d\-27"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_tau_mass\fP = 0\&.00021d\-27"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::tau_mass_energy_equivalent\fP = 2\&.84684d\-10"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_tau_mass_energy_equivalent\fP = 0\&.00019d\-10"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::tau_mass_in_u\fP = 1\&.90754"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_tau_mass_in_u\fP = 0\&.00013"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::tau_molar_mass\fP = 1\&.90754d\-3"
.br
.RI "kg mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_tau_molar_mass\fP = 0\&.00013d\-3"
.br
.RI "kg mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::tau_muon_mass_ratio\fP = 16\&.8170"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_tau_muon_mass_ratio\fP = 0\&.0011"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::tau_neutron_mass_ratio\fP = 1\&.89115"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_tau_neutron_mass_ratio\fP = 0\&.00013"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::tau_proton_mass_ratio\fP = 1\&.89376"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_tau_proton_mass_ratio\fP = 0\&.00013"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::thomson_cross_section\fP = 6\&.6524587321d\-29"
.br
.RI "m^2 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_thomson_cross_section\fP = 0\&.0000000060d\-29"
.br
.RI "m^2 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::triton_electron_mass_ratio\fP = 5496\&.92153573"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_triton_electron_mass_ratio\fP = 0\&.00000027"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::triton_g_factor\fP = 5\&.957924931"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_triton_g_factor\fP = 0\&.000000012"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::triton_mag__mom\fP = 1\&.5046095202d\-26"
.br
.RI "J T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_triton_mag__mom\fP = 0\&.0000000030d\-26"
.br
.RI "J T^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::triton_mag__mom__to_bohr_magneton_ratio\fP = 1\&.6223936651d\-3"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_triton_mag__mom__to_bohr_magneton_ratio\fP = 0\&.0000000032d\-3"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::triton_mag__mom__to_nuclear_magneton_ratio\fP = 2\&.9789624656"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_triton_mag__mom__to_nuclear_magneton_ratio\fP = 0\&.0000000059"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::triton_mass\fP = 5\&.0073567446d\-27"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_triton_mass\fP = 0\&.0000000015d\-27"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::triton_mass_energy_equivalent\fP = 4\&.5003878060d\-10"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_triton_mass_energy_equivalent\fP = 0\&.0000000014d\-10"
.br
.RI "J 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::triton_mass_energy_equivalent_in_mev\fP = 2808\&.92113298"
.br
.RI "MeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_triton_mass_energy_equivalent_in_mev\fP = 0\&.00000085"
.br
.RI "MeV 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::triton_mass_in_u\fP = 3\&.01550071621"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_triton_mass_in_u\fP = 0\&.00000000012"
.br
.RI "u 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::triton_molar_mass\fP = 3\&.01550071517d\-3"
.br
.RI "kg mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_triton_molar_mass\fP = 0\&.00000000092d\-3"
.br
.RI "kg mol^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::triton_proton_mass_ratio\fP = 2\&.99371703414"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_triton_proton_mass_ratio\fP = 0\&.00000000015"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::triton_relative_atomic_mass\fP = 3\&.01550071621"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_triton_relative_atomic_mass\fP = 0\&.00000000012"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::triton_to_proton_mag__mom__ratio\fP = 1\&.0666399191"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_triton_to_proton_mag__mom__ratio\fP = 0\&.0000000021"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::unified_atomic_mass_unit\fP = 1\&.66053906660d\-27"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_unified_atomic_mass_unit\fP = 0\&.00000000050d\-27"
.br
.RI "kg 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::vacuum_electric_permittivity\fP = 8\&.8541878128d\-12"
.br
.RI "F m^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_vacuum_electric_permittivity\fP = 0\&.0000000013d\-12"
.br
.RI "F m^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::vacuum_mag__permeability\fP = 1\&.25663706212d\-6"
.br
.RI "N A^-2 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_vacuum_mag__permeability\fP = 0\&.00000000019d\-6"
.br
.RI "N A^-2 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::von_klitzing_constant\fP = 25812\&.80745"
.br
.RI "ohm 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_von_klitzing_constant\fP = 0\&.0"
.br
.RI "ohm 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::weak_mixing_angle\fP = 0\&.22290"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_weak_mixing_angle\fP = 0\&.00030"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::wien_frequency_displacement_law_constant\fP = 5\&.878925757d10"
.br
.RI "Hz K^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_wien_frequency_displacement_law_constant\fP = 0\&.0"
.br
.RI "Hz K^-1 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::wien_wavelength_displacement_law_constant\fP = 2\&.897771955d\-3"
.br
.RI "m K 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_wien_wavelength_displacement_law_constant\fP = 0\&.0"
.br
.RI "m K 
.br
 "
.ti -1c
.RI "real(c_double), parameter \fBcodata::w_to_z_mass_ratio\fP = 0\&.88153"
.br
.ti -1c
.RI "real(c_double), parameter \fBcodata::d_w_to_z_mass_ratio\fP = 0\&.00017"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Codata from the source code\&.
