.TH "example_in_fortran.f90" 3 "Fri Oct 28 2022" "Version 1.0" "Codata" \" -*- nroff -*-
.ad l
.nh
.SH NAME
example_in_fortran.f90
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBexample_in_fortran\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "program example_in_fortran"

.SH "Author"
.PP 
Generated automatically by Doxygen for Codata from the source code\&.
