.TH "example_in_c.c" 3 "Fri Oct 28 2022" "Version 1.0" "Codata" \" -*- nroff -*-
.ad l
.nh
.SH NAME
example_in_c.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'codata\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Codata from the source code\&.
