@node Man Pages
@chapter Man Pages

@ifinfo
Man pages are available.
@end ifinfo


@node ecx.3
@section ecx.3
@ifhtml
@url{./ecx.3.html}
@end ifhtml
@iftex
@verbatiminclude build/txt/ecx.3.txt
@end iftex


@node ecx__api.3
@section ecx__api.3
@ifhtml
@url{./ecx__api.3.html}
@end ifhtml
@iftex
@verbatiminclude build/txt/ecx__api.3.txt
@end iftex



@node ecx__capi.3
@section ecx__capi.3
@ifhtml
@url{./ecx__capi.3.html}
@end ifhtml
@iftex
@verbatiminclude build/txt/ecx__capi.3.txt
@end iftex

