display – codata
display Subroutine
29 statements
Source File
subroutine display(fptr, pattern, value, uncertainty)
Display results
Arguments
Type Intent Optional Attributes Name
type(codata_constant_type), intent(in), pointer :: fptr(:)
character(len=*), intent(in), optional :: pattern
logical, intent(in), optional :: value
logical, intent(in), optional :: uncertainty
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, public :: i
integer, public :: idx
integer, public :: n
type(regex_pattern), public :: re
logical, public :: uncertainty2
logical, public :: value2
Source Code
subroutine display(fptr, pattern, value, uncertainty)
!! Display results
type(codata_constant_type), intent(in), pointer :: fptr(:)
character(len=*), intent(in), optional :: pattern
logical, intent(in), optional :: value, uncertainty
integer :: i, n, idx
type(regex_pattern) :: re
logical :: value2, uncertainty2
value2 = optval(value, .false.)
uncertainty2 = optval(uncertainty, .false.)
if(present(pattern))then
    re = parse_pattern(pattern)
    do i=1, size(fptr),1
        idx = REGEX(trim(fptr(i)%name), pattern=re, length=n)
        if(idx /= 0)then
            if(value2)then
                write(output_unit, '(SP,ES24.16)') fptr(i)%value
            elseif(uncertainty2)then
                write(output_unit, '(SP,ES24.16)') fptr(i)%uncertainty
            else
                call fptr(i)%print()
            end if
        end if
    end do
else
    do i=1, size(fptr),1
        call fptr(i)%print()
    end do
end if
end subroutine display
Call graph
display calls optval, parse_pattern, regex
codatacli calls display