/**
* @file
* @brief CAPI - Constants 2018 - autogenerated.
*/

#ifndef codata_CONSTANTS_H__2018
#define codata_CONSTANTS_H__2018
#if _MSC_VER
#define ADD_IMPORT __declspec(dllimport)
#else
#define ADD_IMPORT
#endif
ADD_IMPORT extern const int YEAR_2018;/**< Year of codata constants*/

ADD_IMPORT extern const double ALPHA_PARTICLE_ELECTRON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_ALPHA_PARTICLE_ELECTRON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double ALPHA_PARTICLE_MASS_2018;/**< kg */
ADD_IMPORT extern const double U_ALPHA_PARTICLE_MASS_2018;/**< kg */

ADD_IMPORT extern const double ALPHA_PARTICLE_MASS_ENERGY_EQUIVALENT_2018;/**< J */
ADD_IMPORT extern const double U_ALPHA_PARTICLE_MASS_ENERGY_EQUIVALENT_2018;/**< J */

ADD_IMPORT extern const double ALPHA_PARTICLE_MASS_ENERGY_EQUIVALENT_IN_MEV_2018;/**< MeV */
ADD_IMPORT extern const double U_ALPHA_PARTICLE_MASS_ENERGY_EQUIVALENT_IN_MEV_2018;/**< MeV */

ADD_IMPORT extern const double ALPHA_PARTICLE_MASS_IN_U_2018;/**< u */
ADD_IMPORT extern const double U_ALPHA_PARTICLE_MASS_IN_U_2018;/**< u */

ADD_IMPORT extern const double ALPHA_PARTICLE_MOLAR_MASS_2018;/**< kg mol^-1 */
ADD_IMPORT extern const double U_ALPHA_PARTICLE_MOLAR_MASS_2018;/**< kg mol^-1 */

ADD_IMPORT extern const double ALPHA_PARTICLE_PROTON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_ALPHA_PARTICLE_PROTON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double ALPHA_PARTICLE_RELATIVE_ATOMIC_MASS_2018;/**< dimensionless */
ADD_IMPORT extern const double U_ALPHA_PARTICLE_RELATIVE_ATOMIC_MASS_2018;/**< dimensionless */

ADD_IMPORT extern const double ANGSTROM_STAR_2018;/**< m */
ADD_IMPORT extern const double U_ANGSTROM_STAR_2018;/**< m */

ADD_IMPORT extern const double ATOMIC_MASS_CONSTANT_2018;/**< kg */
ADD_IMPORT extern const double U_ATOMIC_MASS_CONSTANT_2018;/**< kg */

ADD_IMPORT extern const double ATOMIC_MASS_CONSTANT_ENERGY_EQUIVALENT_2018;/**< J */
ADD_IMPORT extern const double U_ATOMIC_MASS_CONSTANT_ENERGY_EQUIVALENT_2018;/**< J */

ADD_IMPORT extern const double ATOMIC_MASS_CONSTANT_ENERGY_EQUIVALENT_IN_MEV_2018;/**< MeV */
ADD_IMPORT extern const double U_ATOMIC_MASS_CONSTANT_ENERGY_EQUIVALENT_IN_MEV_2018;/**< MeV */

ADD_IMPORT extern const double ATOMIC_MASS_UNIT_ELECTRON_VOLT_RELATIONSHIP_2018;/**< eV */
ADD_IMPORT extern const double U_ATOMIC_MASS_UNIT_ELECTRON_VOLT_RELATIONSHIP_2018;/**< eV */

ADD_IMPORT extern const double ATOMIC_MASS_UNIT_HARTREE_RELATIONSHIP_2018;/**< E_h */
ADD_IMPORT extern const double U_ATOMIC_MASS_UNIT_HARTREE_RELATIONSHIP_2018;/**< E_h */

ADD_IMPORT extern const double ATOMIC_MASS_UNIT_HERTZ_RELATIONSHIP_2018;/**< Hz */
ADD_IMPORT extern const double U_ATOMIC_MASS_UNIT_HERTZ_RELATIONSHIP_2018;/**< Hz */

ADD_IMPORT extern const double ATOMIC_MASS_UNIT_INVERSE_METER_RELATIONSHIP_2018;/**< m^-1 */
ADD_IMPORT extern const double U_ATOMIC_MASS_UNIT_INVERSE_METER_RELATIONSHIP_2018;/**< m^-1 */

ADD_IMPORT extern const double ATOMIC_MASS_UNIT_JOULE_RELATIONSHIP_2018;/**< J */
ADD_IMPORT extern const double U_ATOMIC_MASS_UNIT_JOULE_RELATIONSHIP_2018;/**< J */

ADD_IMPORT extern const double ATOMIC_MASS_UNIT_KELVIN_RELATIONSHIP_2018;/**< K */
ADD_IMPORT extern const double U_ATOMIC_MASS_UNIT_KELVIN_RELATIONSHIP_2018;/**< K */

ADD_IMPORT extern const double ATOMIC_MASS_UNIT_KILOGRAM_RELATIONSHIP_2018;/**< kg */
ADD_IMPORT extern const double U_ATOMIC_MASS_UNIT_KILOGRAM_RELATIONSHIP_2018;/**< kg */

ADD_IMPORT extern const double ATOMIC_UNIT_OF_1ST_HYPERPOLARIZABILITY_2018;/**< C^3 m^3 J^-2 */
ADD_IMPORT extern const double U_ATOMIC_UNIT_OF_1ST_HYPERPOLARIZABILITY_2018;/**< C^3 m^3 J^-2 */

ADD_IMPORT extern const double ATOMIC_UNIT_OF_2ND_HYPERPOLARIZABILITY_2018;/**< C^4 m^4 J^-3 */
ADD_IMPORT extern const double U_ATOMIC_UNIT_OF_2ND_HYPERPOLARIZABILITY_2018;/**< C^4 m^4 J^-3 */

ADD_IMPORT extern const double ATOMIC_UNIT_OF_ACTION_2018;/**< J s */
ADD_IMPORT extern const double U_ATOMIC_UNIT_OF_ACTION_2018;/**< J s */

ADD_IMPORT extern const double ATOMIC_UNIT_OF_CHARGE_2018;/**< C */
ADD_IMPORT extern const double U_ATOMIC_UNIT_OF_CHARGE_2018;/**< C */

ADD_IMPORT extern const double ATOMIC_UNIT_OF_CHARGE_DENSITY_2018;/**< C m^-3 */
ADD_IMPORT extern const double U_ATOMIC_UNIT_OF_CHARGE_DENSITY_2018;/**< C m^-3 */

ADD_IMPORT extern const double ATOMIC_UNIT_OF_CURRENT_2018;/**< A */
ADD_IMPORT extern const double U_ATOMIC_UNIT_OF_CURRENT_2018;/**< A */

ADD_IMPORT extern const double ATOMIC_UNIT_OF_ELECTRIC_DIPOLE_MOM_2018;/**< C m */
ADD_IMPORT extern const double U_ATOMIC_UNIT_OF_ELECTRIC_DIPOLE_MOM_2018;/**< C m */

ADD_IMPORT extern const double ATOMIC_UNIT_OF_ELECTRIC_FIELD_2018;/**< V m^-1 */
ADD_IMPORT extern const double U_ATOMIC_UNIT_OF_ELECTRIC_FIELD_2018;/**< V m^-1 */

ADD_IMPORT extern const double ATOMIC_UNIT_OF_ELECTRIC_FIELD_GRADIENT_2018;/**< V m^-2 */
ADD_IMPORT extern const double U_ATOMIC_UNIT_OF_ELECTRIC_FIELD_GRADIENT_2018;/**< V m^-2 */

ADD_IMPORT extern const double ATOMIC_UNIT_OF_ELECTRIC_POLARIZABILITY_2018;/**< C^2 m^2 J^-1 */
ADD_IMPORT extern const double U_ATOMIC_UNIT_OF_ELECTRIC_POLARIZABILITY_2018;/**< C^2 m^2 J^-1 */

ADD_IMPORT extern const double ATOMIC_UNIT_OF_ELECTRIC_POTENTIAL_2018;/**< V */
ADD_IMPORT extern const double U_ATOMIC_UNIT_OF_ELECTRIC_POTENTIAL_2018;/**< V */

ADD_IMPORT extern const double ATOMIC_UNIT_OF_ELECTRIC_QUADRUPOLE_MOM_2018;/**< C m^2 */
ADD_IMPORT extern const double U_ATOMIC_UNIT_OF_ELECTRIC_QUADRUPOLE_MOM_2018;/**< C m^2 */

ADD_IMPORT extern const double ATOMIC_UNIT_OF_ENERGY_2018;/**< J */
ADD_IMPORT extern const double U_ATOMIC_UNIT_OF_ENERGY_2018;/**< J */

ADD_IMPORT extern const double ATOMIC_UNIT_OF_FORCE_2018;/**< N */
ADD_IMPORT extern const double U_ATOMIC_UNIT_OF_FORCE_2018;/**< N */

ADD_IMPORT extern const double ATOMIC_UNIT_OF_LENGTH_2018;/**< m */
ADD_IMPORT extern const double U_ATOMIC_UNIT_OF_LENGTH_2018;/**< m */

ADD_IMPORT extern const double ATOMIC_UNIT_OF_MAG__DIPOLE_MOM_2018;/**< J T^-1 */
ADD_IMPORT extern const double U_ATOMIC_UNIT_OF_MAG__DIPOLE_MOM_2018;/**< J T^-1 */

ADD_IMPORT extern const double ATOMIC_UNIT_OF_MAG__FLUX_DENSITY_2018;/**< T */
ADD_IMPORT extern const double U_ATOMIC_UNIT_OF_MAG__FLUX_DENSITY_2018;/**< T */

ADD_IMPORT extern const double ATOMIC_UNIT_OF_MAGNETIZABILITY_2018;/**< J T^-2 */
ADD_IMPORT extern const double U_ATOMIC_UNIT_OF_MAGNETIZABILITY_2018;/**< J T^-2 */

ADD_IMPORT extern const double ATOMIC_UNIT_OF_MASS_2018;/**< kg */
ADD_IMPORT extern const double U_ATOMIC_UNIT_OF_MASS_2018;/**< kg */

ADD_IMPORT extern const double ATOMIC_UNIT_OF_MOMENTUM_2018;/**< kg m s^-1 */
ADD_IMPORT extern const double U_ATOMIC_UNIT_OF_MOMENTUM_2018;/**< kg m s^-1 */

ADD_IMPORT extern const double ATOMIC_UNIT_OF_PERMITTIVITY_2018;/**< F m^-1 */
ADD_IMPORT extern const double U_ATOMIC_UNIT_OF_PERMITTIVITY_2018;/**< F m^-1 */

ADD_IMPORT extern const double ATOMIC_UNIT_OF_TIME_2018;/**< s */
ADD_IMPORT extern const double U_ATOMIC_UNIT_OF_TIME_2018;/**< s */

ADD_IMPORT extern const double ATOMIC_UNIT_OF_VELOCITY_2018;/**< m s^-1 */
ADD_IMPORT extern const double U_ATOMIC_UNIT_OF_VELOCITY_2018;/**< m s^-1 */

ADD_IMPORT extern const double AVOGADRO_CONSTANT_2018;/**< mol^-1 */
ADD_IMPORT extern const double U_AVOGADRO_CONSTANT_2018;/**< mol^-1 */

ADD_IMPORT extern const double BOHR_MAGNETON_2018;/**< J T^-1 */
ADD_IMPORT extern const double U_BOHR_MAGNETON_2018;/**< J T^-1 */

ADD_IMPORT extern const double BOHR_MAGNETON_IN_EV_T_2018;/**< eV T^-1 */
ADD_IMPORT extern const double U_BOHR_MAGNETON_IN_EV_T_2018;/**< eV T^-1 */

ADD_IMPORT extern const double BOHR_MAGNETON_IN_HZ_T_2018;/**< Hz T^-1 */
ADD_IMPORT extern const double U_BOHR_MAGNETON_IN_HZ_T_2018;/**< Hz T^-1 */

ADD_IMPORT extern const double BOHR_MAGNETON_IN_INVERSE_METER_PER_TESLA_2018;/**< m^-1 T^-1 */
ADD_IMPORT extern const double U_BOHR_MAGNETON_IN_INVERSE_METER_PER_TESLA_2018;/**< m^-1 T^-1 */

ADD_IMPORT extern const double BOHR_MAGNETON_IN_K_T_2018;/**< K T^-1 */
ADD_IMPORT extern const double U_BOHR_MAGNETON_IN_K_T_2018;/**< K T^-1 */

ADD_IMPORT extern const double BOHR_RADIUS_2018;/**< m */
ADD_IMPORT extern const double U_BOHR_RADIUS_2018;/**< m */

ADD_IMPORT extern const double BOLTZMANN_CONSTANT_2018;/**< J K^-1 */
ADD_IMPORT extern const double U_BOLTZMANN_CONSTANT_2018;/**< J K^-1 */

ADD_IMPORT extern const double BOLTZMANN_CONSTANT_IN_EV_K_2018;/**< eV K^-1 */
ADD_IMPORT extern const double U_BOLTZMANN_CONSTANT_IN_EV_K_2018;/**< eV K^-1 */

ADD_IMPORT extern const double BOLTZMANN_CONSTANT_IN_HZ_K_2018;/**< Hz K^-1 */
ADD_IMPORT extern const double U_BOLTZMANN_CONSTANT_IN_HZ_K_2018;/**< Hz K^-1 */

ADD_IMPORT extern const double BOLTZMANN_CONSTANT_IN_INVERSE_METER_PER_KELVIN_2018;/**< m^-1 K^-1 */
ADD_IMPORT extern const double U_BOLTZMANN_CONSTANT_IN_INVERSE_METER_PER_KELVIN_2018;/**< m^-1 K^-1 */

ADD_IMPORT extern const double CHARACTERISTIC_IMPEDANCE_OF_VACUUM_2018;/**< ohm */
ADD_IMPORT extern const double U_CHARACTERISTIC_IMPEDANCE_OF_VACUUM_2018;/**< ohm */

ADD_IMPORT extern const double CLASSICAL_ELECTRON_RADIUS_2018;/**< m */
ADD_IMPORT extern const double U_CLASSICAL_ELECTRON_RADIUS_2018;/**< m */

ADD_IMPORT extern const double COMPTON_WAVELENGTH_2018;/**< m */
ADD_IMPORT extern const double U_COMPTON_WAVELENGTH_2018;/**< m */

ADD_IMPORT extern const double CONDUCTANCE_QUANTUM_2018;/**< S */
ADD_IMPORT extern const double U_CONDUCTANCE_QUANTUM_2018;/**< S */

ADD_IMPORT extern const double CONVENTIONAL_VALUE_OF_AMPERE_90_2018;/**< A */
ADD_IMPORT extern const double U_CONVENTIONAL_VALUE_OF_AMPERE_90_2018;/**< A */

ADD_IMPORT extern const double CONVENTIONAL_VALUE_OF_COULOMB_90_2018;/**< C */
ADD_IMPORT extern const double U_CONVENTIONAL_VALUE_OF_COULOMB_90_2018;/**< C */

ADD_IMPORT extern const double CONVENTIONAL_VALUE_OF_FARAD_90_2018;/**< F */
ADD_IMPORT extern const double U_CONVENTIONAL_VALUE_OF_FARAD_90_2018;/**< F */

ADD_IMPORT extern const double CONVENTIONAL_VALUE_OF_HENRY_90_2018;/**< H */
ADD_IMPORT extern const double U_CONVENTIONAL_VALUE_OF_HENRY_90_2018;/**< H */

ADD_IMPORT extern const double CONVENTIONAL_VALUE_OF_JOSEPHSON_CONSTANT_2018;/**< Hz V^-1 */
ADD_IMPORT extern const double U_CONVENTIONAL_VALUE_OF_JOSEPHSON_CONSTANT_2018;/**< Hz V^-1 */

ADD_IMPORT extern const double CONVENTIONAL_VALUE_OF_OHM_90_2018;/**< ohm */
ADD_IMPORT extern const double U_CONVENTIONAL_VALUE_OF_OHM_90_2018;/**< ohm */

ADD_IMPORT extern const double CONVENTIONAL_VALUE_OF_VOLT_90_2018;/**< V */
ADD_IMPORT extern const double U_CONVENTIONAL_VALUE_OF_VOLT_90_2018;/**< V */

ADD_IMPORT extern const double CONVENTIONAL_VALUE_OF_VON_KLITZING_CONSTANT_2018;/**< ohm */
ADD_IMPORT extern const double U_CONVENTIONAL_VALUE_OF_VON_KLITZING_CONSTANT_2018;/**< ohm */

ADD_IMPORT extern const double CONVENTIONAL_VALUE_OF_WATT_90_2018;/**< W */
ADD_IMPORT extern const double U_CONVENTIONAL_VALUE_OF_WATT_90_2018;/**< W */

ADD_IMPORT extern const double COPPER_X_UNIT_2018;/**< m */
ADD_IMPORT extern const double U_COPPER_X_UNIT_2018;/**< m */

ADD_IMPORT extern const double DEUTERON_ELECTRON_MAG__MOM__RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_DEUTERON_ELECTRON_MAG__MOM__RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double DEUTERON_ELECTRON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_DEUTERON_ELECTRON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double DEUTERON_G_FACTOR_2018;/**< dimensionless */
ADD_IMPORT extern const double U_DEUTERON_G_FACTOR_2018;/**< dimensionless */

ADD_IMPORT extern const double DEUTERON_MAG__MOM_2018;/**< J T^-1 */
ADD_IMPORT extern const double U_DEUTERON_MAG__MOM_2018;/**< J T^-1 */

ADD_IMPORT extern const double DEUTERON_MAG__MOM__TO_BOHR_MAGNETON_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_DEUTERON_MAG__MOM__TO_BOHR_MAGNETON_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double DEUTERON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_DEUTERON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double DEUTERON_MASS_2018;/**< kg */
ADD_IMPORT extern const double U_DEUTERON_MASS_2018;/**< kg */

ADD_IMPORT extern const double DEUTERON_MASS_ENERGY_EQUIVALENT_2018;/**< J */
ADD_IMPORT extern const double U_DEUTERON_MASS_ENERGY_EQUIVALENT_2018;/**< J */

ADD_IMPORT extern const double DEUTERON_MASS_ENERGY_EQUIVALENT_IN_MEV_2018;/**< MeV */
ADD_IMPORT extern const double U_DEUTERON_MASS_ENERGY_EQUIVALENT_IN_MEV_2018;/**< MeV */

ADD_IMPORT extern const double DEUTERON_MASS_IN_U_2018;/**< u */
ADD_IMPORT extern const double U_DEUTERON_MASS_IN_U_2018;/**< u */

ADD_IMPORT extern const double DEUTERON_MOLAR_MASS_2018;/**< kg mol^-1 */
ADD_IMPORT extern const double U_DEUTERON_MOLAR_MASS_2018;/**< kg mol^-1 */

ADD_IMPORT extern const double DEUTERON_NEUTRON_MAG__MOM__RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_DEUTERON_NEUTRON_MAG__MOM__RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double DEUTERON_PROTON_MAG__MOM__RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_DEUTERON_PROTON_MAG__MOM__RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double DEUTERON_PROTON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_DEUTERON_PROTON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double DEUTERON_RELATIVE_ATOMIC_MASS_2018;/**< dimensionless */
ADD_IMPORT extern const double U_DEUTERON_RELATIVE_ATOMIC_MASS_2018;/**< dimensionless */

ADD_IMPORT extern const double DEUTERON_RMS_CHARGE_RADIUS_2018;/**< m */
ADD_IMPORT extern const double U_DEUTERON_RMS_CHARGE_RADIUS_2018;/**< m */

ADD_IMPORT extern const double ELECTRON_CHARGE_TO_MASS_QUOTIENT_2018;/**< C kg^-1 */
ADD_IMPORT extern const double U_ELECTRON_CHARGE_TO_MASS_QUOTIENT_2018;/**< C kg^-1 */

ADD_IMPORT extern const double ELECTRON_DEUTERON_MAG__MOM__RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_ELECTRON_DEUTERON_MAG__MOM__RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double ELECTRON_DEUTERON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_ELECTRON_DEUTERON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double ELECTRON_G_FACTOR_2018;/**< dimensionless */
ADD_IMPORT extern const double U_ELECTRON_G_FACTOR_2018;/**< dimensionless */

ADD_IMPORT extern const double ELECTRON_GYROMAG__RATIO_2018;/**< s^-1 T^-1 */
ADD_IMPORT extern const double U_ELECTRON_GYROMAG__RATIO_2018;/**< s^-1 T^-1 */

ADD_IMPORT extern const double ELECTRON_GYROMAG__RATIO_IN_MHZ_T_2018;/**< MHz T^-1 */
ADD_IMPORT extern const double U_ELECTRON_GYROMAG__RATIO_IN_MHZ_T_2018;/**< MHz T^-1 */

ADD_IMPORT extern const double ELECTRON_HELION_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_ELECTRON_HELION_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double ELECTRON_MAG__MOM_2018;/**< J T^-1 */
ADD_IMPORT extern const double U_ELECTRON_MAG__MOM_2018;/**< J T^-1 */

ADD_IMPORT extern const double ELECTRON_MAG__MOM__ANOMALY_2018;/**< dimensionless */
ADD_IMPORT extern const double U_ELECTRON_MAG__MOM__ANOMALY_2018;/**< dimensionless */

ADD_IMPORT extern const double ELECTRON_MAG__MOM__TO_BOHR_MAGNETON_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_ELECTRON_MAG__MOM__TO_BOHR_MAGNETON_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double ELECTRON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_ELECTRON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double ELECTRON_MASS_2018;/**< kg */
ADD_IMPORT extern const double U_ELECTRON_MASS_2018;/**< kg */

ADD_IMPORT extern const double ELECTRON_MASS_ENERGY_EQUIVALENT_2018;/**< J */
ADD_IMPORT extern const double U_ELECTRON_MASS_ENERGY_EQUIVALENT_2018;/**< J */

ADD_IMPORT extern const double ELECTRON_MASS_ENERGY_EQUIVALENT_IN_MEV_2018;/**< MeV */
ADD_IMPORT extern const double U_ELECTRON_MASS_ENERGY_EQUIVALENT_IN_MEV_2018;/**< MeV */

ADD_IMPORT extern const double ELECTRON_MASS_IN_U_2018;/**< u */
ADD_IMPORT extern const double U_ELECTRON_MASS_IN_U_2018;/**< u */

ADD_IMPORT extern const double ELECTRON_MOLAR_MASS_2018;/**< kg mol^-1 */
ADD_IMPORT extern const double U_ELECTRON_MOLAR_MASS_2018;/**< kg mol^-1 */

ADD_IMPORT extern const double ELECTRON_MUON_MAG__MOM__RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_ELECTRON_MUON_MAG__MOM__RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double ELECTRON_MUON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_ELECTRON_MUON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double ELECTRON_NEUTRON_MAG__MOM__RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_ELECTRON_NEUTRON_MAG__MOM__RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double ELECTRON_NEUTRON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_ELECTRON_NEUTRON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double ELECTRON_PROTON_MAG__MOM__RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_ELECTRON_PROTON_MAG__MOM__RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double ELECTRON_PROTON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_ELECTRON_PROTON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double ELECTRON_RELATIVE_ATOMIC_MASS_2018;/**< dimensionless */
ADD_IMPORT extern const double U_ELECTRON_RELATIVE_ATOMIC_MASS_2018;/**< dimensionless */

ADD_IMPORT extern const double ELECTRON_TAU_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_ELECTRON_TAU_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double ELECTRON_TO_ALPHA_PARTICLE_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_ELECTRON_TO_ALPHA_PARTICLE_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double ELECTRON_TO_SHIELDED_HELION_MAG__MOM__RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_ELECTRON_TO_SHIELDED_HELION_MAG__MOM__RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double ELECTRON_TO_SHIELDED_PROTON_MAG__MOM__RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_ELECTRON_TO_SHIELDED_PROTON_MAG__MOM__RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double ELECTRON_TRITON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_ELECTRON_TRITON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double ELECTRON_VOLT_2018;/**< J */
ADD_IMPORT extern const double U_ELECTRON_VOLT_2018;/**< J */

ADD_IMPORT extern const double ELECTRON_VOLT_ATOMIC_MASS_UNIT_RELATIONSHIP_2018;/**< u */
ADD_IMPORT extern const double U_ELECTRON_VOLT_ATOMIC_MASS_UNIT_RELATIONSHIP_2018;/**< u */

ADD_IMPORT extern const double ELECTRON_VOLT_HARTREE_RELATIONSHIP_2018;/**< E_h */
ADD_IMPORT extern const double U_ELECTRON_VOLT_HARTREE_RELATIONSHIP_2018;/**< E_h */

ADD_IMPORT extern const double ELECTRON_VOLT_HERTZ_RELATIONSHIP_2018;/**< Hz */
ADD_IMPORT extern const double U_ELECTRON_VOLT_HERTZ_RELATIONSHIP_2018;/**< Hz */

ADD_IMPORT extern const double ELECTRON_VOLT_INVERSE_METER_RELATIONSHIP_2018;/**< m^-1 */
ADD_IMPORT extern const double U_ELECTRON_VOLT_INVERSE_METER_RELATIONSHIP_2018;/**< m^-1 */

ADD_IMPORT extern const double ELECTRON_VOLT_JOULE_RELATIONSHIP_2018;/**< J */
ADD_IMPORT extern const double U_ELECTRON_VOLT_JOULE_RELATIONSHIP_2018;/**< J */

ADD_IMPORT extern const double ELECTRON_VOLT_KELVIN_RELATIONSHIP_2018;/**< K */
ADD_IMPORT extern const double U_ELECTRON_VOLT_KELVIN_RELATIONSHIP_2018;/**< K */

ADD_IMPORT extern const double ELECTRON_VOLT_KILOGRAM_RELATIONSHIP_2018;/**< kg */
ADD_IMPORT extern const double U_ELECTRON_VOLT_KILOGRAM_RELATIONSHIP_2018;/**< kg */

ADD_IMPORT extern const double ELEMENTARY_CHARGE_2018;/**< C */
ADD_IMPORT extern const double U_ELEMENTARY_CHARGE_2018;/**< C */

ADD_IMPORT extern const double ELEMENTARY_CHARGE_OVER_H_BAR_2018;/**< A J^-1 */
ADD_IMPORT extern const double U_ELEMENTARY_CHARGE_OVER_H_BAR_2018;/**< A J^-1 */

ADD_IMPORT extern const double FARADAY_CONSTANT_2018;/**< C mol^-1 */
ADD_IMPORT extern const double U_FARADAY_CONSTANT_2018;/**< C mol^-1 */

ADD_IMPORT extern const double FERMI_COUPLING_CONSTANT_2018;/**< GeV^-2 */
ADD_IMPORT extern const double U_FERMI_COUPLING_CONSTANT_2018;/**< GeV^-2 */

ADD_IMPORT extern const double FINE_STRUCTURE_CONSTANT_2018;/**< dimensionless */
ADD_IMPORT extern const double U_FINE_STRUCTURE_CONSTANT_2018;/**< dimensionless */

ADD_IMPORT extern const double FIRST_RADIATION_CONSTANT_2018;/**< W m^2 */
ADD_IMPORT extern const double U_FIRST_RADIATION_CONSTANT_2018;/**< W m^2 */

ADD_IMPORT extern const double FIRST_RADIATION_CONSTANT_FOR_SPECTRAL_RADIANCE_2018;/**< W m^2 sr^-1 */
ADD_IMPORT extern const double U_FIRST_RADIATION_CONSTANT_FOR_SPECTRAL_RADIANCE_2018;/**< W m^2 sr^-1 */

ADD_IMPORT extern const double HARTREE_ATOMIC_MASS_UNIT_RELATIONSHIP_2018;/**< u */
ADD_IMPORT extern const double U_HARTREE_ATOMIC_MASS_UNIT_RELATIONSHIP_2018;/**< u */

ADD_IMPORT extern const double HARTREE_ELECTRON_VOLT_RELATIONSHIP_2018;/**< eV */
ADD_IMPORT extern const double U_HARTREE_ELECTRON_VOLT_RELATIONSHIP_2018;/**< eV */

ADD_IMPORT extern const double HARTREE_ENERGY_2018;/**< J */
ADD_IMPORT extern const double U_HARTREE_ENERGY_2018;/**< J */

ADD_IMPORT extern const double HARTREE_ENERGY_IN_EV_2018;/**< eV */
ADD_IMPORT extern const double U_HARTREE_ENERGY_IN_EV_2018;/**< eV */

ADD_IMPORT extern const double HARTREE_HERTZ_RELATIONSHIP_2018;/**< Hz */
ADD_IMPORT extern const double U_HARTREE_HERTZ_RELATIONSHIP_2018;/**< Hz */

ADD_IMPORT extern const double HARTREE_INVERSE_METER_RELATIONSHIP_2018;/**< m^-1 */
ADD_IMPORT extern const double U_HARTREE_INVERSE_METER_RELATIONSHIP_2018;/**< m^-1 */

ADD_IMPORT extern const double HARTREE_JOULE_RELATIONSHIP_2018;/**< J */
ADD_IMPORT extern const double U_HARTREE_JOULE_RELATIONSHIP_2018;/**< J */

ADD_IMPORT extern const double HARTREE_KELVIN_RELATIONSHIP_2018;/**< K */
ADD_IMPORT extern const double U_HARTREE_KELVIN_RELATIONSHIP_2018;/**< K */

ADD_IMPORT extern const double HARTREE_KILOGRAM_RELATIONSHIP_2018;/**< kg */
ADD_IMPORT extern const double U_HARTREE_KILOGRAM_RELATIONSHIP_2018;/**< kg */

ADD_IMPORT extern const double HELION_ELECTRON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_HELION_ELECTRON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double HELION_G_FACTOR_2018;/**< dimensionless */
ADD_IMPORT extern const double U_HELION_G_FACTOR_2018;/**< dimensionless */

ADD_IMPORT extern const double HELION_MAG__MOM_2018;/**< J T^-1 */
ADD_IMPORT extern const double U_HELION_MAG__MOM_2018;/**< J T^-1 */

ADD_IMPORT extern const double HELION_MAG__MOM__TO_BOHR_MAGNETON_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_HELION_MAG__MOM__TO_BOHR_MAGNETON_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double HELION_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_HELION_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double HELION_MASS_2018;/**< kg */
ADD_IMPORT extern const double U_HELION_MASS_2018;/**< kg */

ADD_IMPORT extern const double HELION_MASS_ENERGY_EQUIVALENT_2018;/**< J */
ADD_IMPORT extern const double U_HELION_MASS_ENERGY_EQUIVALENT_2018;/**< J */

ADD_IMPORT extern const double HELION_MASS_ENERGY_EQUIVALENT_IN_MEV_2018;/**< MeV */
ADD_IMPORT extern const double U_HELION_MASS_ENERGY_EQUIVALENT_IN_MEV_2018;/**< MeV */

ADD_IMPORT extern const double HELION_MASS_IN_U_2018;/**< u */
ADD_IMPORT extern const double U_HELION_MASS_IN_U_2018;/**< u */

ADD_IMPORT extern const double HELION_MOLAR_MASS_2018;/**< kg mol^-1 */
ADD_IMPORT extern const double U_HELION_MOLAR_MASS_2018;/**< kg mol^-1 */

ADD_IMPORT extern const double HELION_PROTON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_HELION_PROTON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double HELION_RELATIVE_ATOMIC_MASS_2018;/**< dimensionless */
ADD_IMPORT extern const double U_HELION_RELATIVE_ATOMIC_MASS_2018;/**< dimensionless */

ADD_IMPORT extern const double HELION_SHIELDING_SHIFT_2018;/**< dimensionless */
ADD_IMPORT extern const double U_HELION_SHIELDING_SHIFT_2018;/**< dimensionless */

ADD_IMPORT extern const double HERTZ_ATOMIC_MASS_UNIT_RELATIONSHIP_2018;/**< u */
ADD_IMPORT extern const double U_HERTZ_ATOMIC_MASS_UNIT_RELATIONSHIP_2018;/**< u */

ADD_IMPORT extern const double HERTZ_ELECTRON_VOLT_RELATIONSHIP_2018;/**< eV */
ADD_IMPORT extern const double U_HERTZ_ELECTRON_VOLT_RELATIONSHIP_2018;/**< eV */

ADD_IMPORT extern const double HERTZ_HARTREE_RELATIONSHIP_2018;/**< E_h */
ADD_IMPORT extern const double U_HERTZ_HARTREE_RELATIONSHIP_2018;/**< E_h */

ADD_IMPORT extern const double HERTZ_INVERSE_METER_RELATIONSHIP_2018;/**< m^-1 */
ADD_IMPORT extern const double U_HERTZ_INVERSE_METER_RELATIONSHIP_2018;/**< m^-1 */

ADD_IMPORT extern const double HERTZ_JOULE_RELATIONSHIP_2018;/**< J */
ADD_IMPORT extern const double U_HERTZ_JOULE_RELATIONSHIP_2018;/**< J */

ADD_IMPORT extern const double HERTZ_KELVIN_RELATIONSHIP_2018;/**< K */
ADD_IMPORT extern const double U_HERTZ_KELVIN_RELATIONSHIP_2018;/**< K */

ADD_IMPORT extern const double HERTZ_KILOGRAM_RELATIONSHIP_2018;/**< kg */
ADD_IMPORT extern const double U_HERTZ_KILOGRAM_RELATIONSHIP_2018;/**< kg */

ADD_IMPORT extern const double HYPERFINE_TRANSITION_FREQUENCY_OF_CS_133_2018;/**< Hz */
ADD_IMPORT extern const double U_HYPERFINE_TRANSITION_FREQUENCY_OF_CS_133_2018;/**< Hz */

ADD_IMPORT extern const double INVERSE_FINE_STRUCTURE_CONSTANT_2018;/**< dimensionless */
ADD_IMPORT extern const double U_INVERSE_FINE_STRUCTURE_CONSTANT_2018;/**< dimensionless */

ADD_IMPORT extern const double INVERSE_METER_ATOMIC_MASS_UNIT_RELATIONSHIP_2018;/**< u */
ADD_IMPORT extern const double U_INVERSE_METER_ATOMIC_MASS_UNIT_RELATIONSHIP_2018;/**< u */

ADD_IMPORT extern const double INVERSE_METER_ELECTRON_VOLT_RELATIONSHIP_2018;/**< eV */
ADD_IMPORT extern const double U_INVERSE_METER_ELECTRON_VOLT_RELATIONSHIP_2018;/**< eV */

ADD_IMPORT extern const double INVERSE_METER_HARTREE_RELATIONSHIP_2018;/**< E_h */
ADD_IMPORT extern const double U_INVERSE_METER_HARTREE_RELATIONSHIP_2018;/**< E_h */

ADD_IMPORT extern const double INVERSE_METER_HERTZ_RELATIONSHIP_2018;/**< Hz */
ADD_IMPORT extern const double U_INVERSE_METER_HERTZ_RELATIONSHIP_2018;/**< Hz */

ADD_IMPORT extern const double INVERSE_METER_JOULE_RELATIONSHIP_2018;/**< J */
ADD_IMPORT extern const double U_INVERSE_METER_JOULE_RELATIONSHIP_2018;/**< J */

ADD_IMPORT extern const double INVERSE_METER_KELVIN_RELATIONSHIP_2018;/**< K */
ADD_IMPORT extern const double U_INVERSE_METER_KELVIN_RELATIONSHIP_2018;/**< K */

ADD_IMPORT extern const double INVERSE_METER_KILOGRAM_RELATIONSHIP_2018;/**< kg */
ADD_IMPORT extern const double U_INVERSE_METER_KILOGRAM_RELATIONSHIP_2018;/**< kg */

ADD_IMPORT extern const double INVERSE_OF_CONDUCTANCE_QUANTUM_2018;/**< ohm */
ADD_IMPORT extern const double U_INVERSE_OF_CONDUCTANCE_QUANTUM_2018;/**< ohm */

ADD_IMPORT extern const double JOSEPHSON_CONSTANT_2018;/**< Hz V^-1 */
ADD_IMPORT extern const double U_JOSEPHSON_CONSTANT_2018;/**< Hz V^-1 */

ADD_IMPORT extern const double JOULE_ATOMIC_MASS_UNIT_RELATIONSHIP_2018;/**< u */
ADD_IMPORT extern const double U_JOULE_ATOMIC_MASS_UNIT_RELATIONSHIP_2018;/**< u */

ADD_IMPORT extern const double JOULE_ELECTRON_VOLT_RELATIONSHIP_2018;/**< eV */
ADD_IMPORT extern const double U_JOULE_ELECTRON_VOLT_RELATIONSHIP_2018;/**< eV */

ADD_IMPORT extern const double JOULE_HARTREE_RELATIONSHIP_2018;/**< E_h */
ADD_IMPORT extern const double U_JOULE_HARTREE_RELATIONSHIP_2018;/**< E_h */

ADD_IMPORT extern const double JOULE_HERTZ_RELATIONSHIP_2018;/**< Hz */
ADD_IMPORT extern const double U_JOULE_HERTZ_RELATIONSHIP_2018;/**< Hz */

ADD_IMPORT extern const double JOULE_INVERSE_METER_RELATIONSHIP_2018;/**< m^-1 */
ADD_IMPORT extern const double U_JOULE_INVERSE_METER_RELATIONSHIP_2018;/**< m^-1 */

ADD_IMPORT extern const double JOULE_KELVIN_RELATIONSHIP_2018;/**< K */
ADD_IMPORT extern const double U_JOULE_KELVIN_RELATIONSHIP_2018;/**< K */

ADD_IMPORT extern const double JOULE_KILOGRAM_RELATIONSHIP_2018;/**< kg */
ADD_IMPORT extern const double U_JOULE_KILOGRAM_RELATIONSHIP_2018;/**< kg */

ADD_IMPORT extern const double KELVIN_ATOMIC_MASS_UNIT_RELATIONSHIP_2018;/**< u */
ADD_IMPORT extern const double U_KELVIN_ATOMIC_MASS_UNIT_RELATIONSHIP_2018;/**< u */

ADD_IMPORT extern const double KELVIN_ELECTRON_VOLT_RELATIONSHIP_2018;/**< eV */
ADD_IMPORT extern const double U_KELVIN_ELECTRON_VOLT_RELATIONSHIP_2018;/**< eV */

ADD_IMPORT extern const double KELVIN_HARTREE_RELATIONSHIP_2018;/**< E_h */
ADD_IMPORT extern const double U_KELVIN_HARTREE_RELATIONSHIP_2018;/**< E_h */

ADD_IMPORT extern const double KELVIN_HERTZ_RELATIONSHIP_2018;/**< Hz */
ADD_IMPORT extern const double U_KELVIN_HERTZ_RELATIONSHIP_2018;/**< Hz */

ADD_IMPORT extern const double KELVIN_INVERSE_METER_RELATIONSHIP_2018;/**< m^-1 */
ADD_IMPORT extern const double U_KELVIN_INVERSE_METER_RELATIONSHIP_2018;/**< m^-1 */

ADD_IMPORT extern const double KELVIN_JOULE_RELATIONSHIP_2018;/**< J */
ADD_IMPORT extern const double U_KELVIN_JOULE_RELATIONSHIP_2018;/**< J */

ADD_IMPORT extern const double KELVIN_KILOGRAM_RELATIONSHIP_2018;/**< kg */
ADD_IMPORT extern const double U_KELVIN_KILOGRAM_RELATIONSHIP_2018;/**< kg */

ADD_IMPORT extern const double KILOGRAM_ATOMIC_MASS_UNIT_RELATIONSHIP_2018;/**< u */
ADD_IMPORT extern const double U_KILOGRAM_ATOMIC_MASS_UNIT_RELATIONSHIP_2018;/**< u */

ADD_IMPORT extern const double KILOGRAM_ELECTRON_VOLT_RELATIONSHIP_2018;/**< eV */
ADD_IMPORT extern const double U_KILOGRAM_ELECTRON_VOLT_RELATIONSHIP_2018;/**< eV */

ADD_IMPORT extern const double KILOGRAM_HARTREE_RELATIONSHIP_2018;/**< E_h */
ADD_IMPORT extern const double U_KILOGRAM_HARTREE_RELATIONSHIP_2018;/**< E_h */

ADD_IMPORT extern const double KILOGRAM_HERTZ_RELATIONSHIP_2018;/**< Hz */
ADD_IMPORT extern const double U_KILOGRAM_HERTZ_RELATIONSHIP_2018;/**< Hz */

ADD_IMPORT extern const double KILOGRAM_INVERSE_METER_RELATIONSHIP_2018;/**< m^-1 */
ADD_IMPORT extern const double U_KILOGRAM_INVERSE_METER_RELATIONSHIP_2018;/**< m^-1 */

ADD_IMPORT extern const double KILOGRAM_JOULE_RELATIONSHIP_2018;/**< J */
ADD_IMPORT extern const double U_KILOGRAM_JOULE_RELATIONSHIP_2018;/**< J */

ADD_IMPORT extern const double KILOGRAM_KELVIN_RELATIONSHIP_2018;/**< K */
ADD_IMPORT extern const double U_KILOGRAM_KELVIN_RELATIONSHIP_2018;/**< K */

ADD_IMPORT extern const double LATTICE_PARAMETER_OF_SILICON_2018;/**< m */
ADD_IMPORT extern const double U_LATTICE_PARAMETER_OF_SILICON_2018;/**< m */

ADD_IMPORT extern const double LATTICE_SPACING_OF_IDEAL_SI__220_2018;/**< m */
ADD_IMPORT extern const double U_LATTICE_SPACING_OF_IDEAL_SI__220_2018;/**< m */

ADD_IMPORT extern const double LOSCHMIDT_CONSTANT__273_15_K__100_KPA_2018;/**< m^-3 */
ADD_IMPORT extern const double U_LOSCHMIDT_CONSTANT__273_15_K__100_KPA_2018;/**< m^-3 */

ADD_IMPORT extern const double LOSCHMIDT_CONSTANT__273_15_K__101_325_KPA_2018;/**< m^-3 */
ADD_IMPORT extern const double U_LOSCHMIDT_CONSTANT__273_15_K__101_325_KPA_2018;/**< m^-3 */

ADD_IMPORT extern const double LUMINOUS_EFFICACY_2018;/**< lm W^-1 */
ADD_IMPORT extern const double U_LUMINOUS_EFFICACY_2018;/**< lm W^-1 */

ADD_IMPORT extern const double MAG__FLUX_QUANTUM_2018;/**< Wb */
ADD_IMPORT extern const double U_MAG__FLUX_QUANTUM_2018;/**< Wb */

ADD_IMPORT extern const double MOLAR_GAS_CONSTANT_2018;/**< J mol^-1 K^-1 */
ADD_IMPORT extern const double U_MOLAR_GAS_CONSTANT_2018;/**< J mol^-1 K^-1 */

ADD_IMPORT extern const double MOLAR_MASS_CONSTANT_2018;/**< kg mol^-1 */
ADD_IMPORT extern const double U_MOLAR_MASS_CONSTANT_2018;/**< kg mol^-1 */

ADD_IMPORT extern const double MOLAR_MASS_OF_CARBON_12_2018;/**< kg mol^-1 */
ADD_IMPORT extern const double U_MOLAR_MASS_OF_CARBON_12_2018;/**< kg mol^-1 */

ADD_IMPORT extern const double MOLAR_PLANCK_CONSTANT_2018;/**< J Hz^-1 mol^-1 */
ADD_IMPORT extern const double U_MOLAR_PLANCK_CONSTANT_2018;/**< J Hz^-1 mol^-1 */

ADD_IMPORT extern const double MOLAR_VOLUME_OF_IDEAL_GAS__273_15_K__100_KPA_2018;/**< m^3 mol^-1 */
ADD_IMPORT extern const double U_MOLAR_VOLUME_OF_IDEAL_GAS__273_15_K__100_KPA_2018;/**< m^3 mol^-1 */

ADD_IMPORT extern const double MOLAR_VOLUME_OF_IDEAL_GAS__273_15_K__101_325_KPA_2018;/**< m^3 mol^-1 */
ADD_IMPORT extern const double U_MOLAR_VOLUME_OF_IDEAL_GAS__273_15_K__101_325_KPA_2018;/**< m^3 mol^-1 */

ADD_IMPORT extern const double MOLAR_VOLUME_OF_SILICON_2018;/**< m^3 mol^-1 */
ADD_IMPORT extern const double U_MOLAR_VOLUME_OF_SILICON_2018;/**< m^3 mol^-1 */

ADD_IMPORT extern const double MOLYBDENUM_X_UNIT_2018;/**< m */
ADD_IMPORT extern const double U_MOLYBDENUM_X_UNIT_2018;/**< m */

ADD_IMPORT extern const double MUON_COMPTON_WAVELENGTH_2018;/**< m */
ADD_IMPORT extern const double U_MUON_COMPTON_WAVELENGTH_2018;/**< m */

ADD_IMPORT extern const double MUON_ELECTRON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_MUON_ELECTRON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double MUON_G_FACTOR_2018;/**< dimensionless */
ADD_IMPORT extern const double U_MUON_G_FACTOR_2018;/**< dimensionless */

ADD_IMPORT extern const double MUON_MAG__MOM_2018;/**< J T^-1 */
ADD_IMPORT extern const double U_MUON_MAG__MOM_2018;/**< J T^-1 */

ADD_IMPORT extern const double MUON_MAG__MOM__ANOMALY_2018;/**< dimensionless */
ADD_IMPORT extern const double U_MUON_MAG__MOM__ANOMALY_2018;/**< dimensionless */

ADD_IMPORT extern const double MUON_MAG__MOM__TO_BOHR_MAGNETON_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_MUON_MAG__MOM__TO_BOHR_MAGNETON_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double MUON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_MUON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double MUON_MASS_2018;/**< kg */
ADD_IMPORT extern const double U_MUON_MASS_2018;/**< kg */

ADD_IMPORT extern const double MUON_MASS_ENERGY_EQUIVALENT_2018;/**< J */
ADD_IMPORT extern const double U_MUON_MASS_ENERGY_EQUIVALENT_2018;/**< J */

ADD_IMPORT extern const double MUON_MASS_ENERGY_EQUIVALENT_IN_MEV_2018;/**< MeV */
ADD_IMPORT extern const double U_MUON_MASS_ENERGY_EQUIVALENT_IN_MEV_2018;/**< MeV */

ADD_IMPORT extern const double MUON_MASS_IN_U_2018;/**< u */
ADD_IMPORT extern const double U_MUON_MASS_IN_U_2018;/**< u */

ADD_IMPORT extern const double MUON_MOLAR_MASS_2018;/**< kg mol^-1 */
ADD_IMPORT extern const double U_MUON_MOLAR_MASS_2018;/**< kg mol^-1 */

ADD_IMPORT extern const double MUON_NEUTRON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_MUON_NEUTRON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double MUON_PROTON_MAG__MOM__RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_MUON_PROTON_MAG__MOM__RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double MUON_PROTON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_MUON_PROTON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double MUON_TAU_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_MUON_TAU_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double NATURAL_UNIT_OF_ACTION_2018;/**< J s */
ADD_IMPORT extern const double U_NATURAL_UNIT_OF_ACTION_2018;/**< J s */

ADD_IMPORT extern const double NATURAL_UNIT_OF_ACTION_IN_EV_S_2018;/**< eV s */
ADD_IMPORT extern const double U_NATURAL_UNIT_OF_ACTION_IN_EV_S_2018;/**< eV s */

ADD_IMPORT extern const double NATURAL_UNIT_OF_ENERGY_2018;/**< J */
ADD_IMPORT extern const double U_NATURAL_UNIT_OF_ENERGY_2018;/**< J */

ADD_IMPORT extern const double NATURAL_UNIT_OF_ENERGY_IN_MEV_2018;/**< MeV */
ADD_IMPORT extern const double U_NATURAL_UNIT_OF_ENERGY_IN_MEV_2018;/**< MeV */

ADD_IMPORT extern const double NATURAL_UNIT_OF_LENGTH_2018;/**< m */
ADD_IMPORT extern const double U_NATURAL_UNIT_OF_LENGTH_2018;/**< m */

ADD_IMPORT extern const double NATURAL_UNIT_OF_MASS_2018;/**< kg */
ADD_IMPORT extern const double U_NATURAL_UNIT_OF_MASS_2018;/**< kg */

ADD_IMPORT extern const double NATURAL_UNIT_OF_MOMENTUM_2018;/**< kg m s^-1 */
ADD_IMPORT extern const double U_NATURAL_UNIT_OF_MOMENTUM_2018;/**< kg m s^-1 */

ADD_IMPORT extern const double NATURAL_UNIT_OF_MOMENTUM_IN_MEV_C_2018;/**< MeV/c */
ADD_IMPORT extern const double U_NATURAL_UNIT_OF_MOMENTUM_IN_MEV_C_2018;/**< MeV/c */

ADD_IMPORT extern const double NATURAL_UNIT_OF_TIME_2018;/**< s */
ADD_IMPORT extern const double U_NATURAL_UNIT_OF_TIME_2018;/**< s */

ADD_IMPORT extern const double NATURAL_UNIT_OF_VELOCITY_2018;/**< m s^-1 */
ADD_IMPORT extern const double U_NATURAL_UNIT_OF_VELOCITY_2018;/**< m s^-1 */

ADD_IMPORT extern const double NEUTRON_COMPTON_WAVELENGTH_2018;/**< m */
ADD_IMPORT extern const double U_NEUTRON_COMPTON_WAVELENGTH_2018;/**< m */

ADD_IMPORT extern const double NEUTRON_ELECTRON_MAG__MOM__RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_NEUTRON_ELECTRON_MAG__MOM__RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double NEUTRON_ELECTRON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_NEUTRON_ELECTRON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double NEUTRON_G_FACTOR_2018;/**< dimensionless */
ADD_IMPORT extern const double U_NEUTRON_G_FACTOR_2018;/**< dimensionless */

ADD_IMPORT extern const double NEUTRON_GYROMAG__RATIO_2018;/**< s^-1 T^-1 */
ADD_IMPORT extern const double U_NEUTRON_GYROMAG__RATIO_2018;/**< s^-1 T^-1 */

ADD_IMPORT extern const double NEUTRON_GYROMAG__RATIO_IN_MHZ_T_2018;/**< MHz T^-1 */
ADD_IMPORT extern const double U_NEUTRON_GYROMAG__RATIO_IN_MHZ_T_2018;/**< MHz T^-1 */

ADD_IMPORT extern const double NEUTRON_MAG__MOM_2018;/**< J T^-1 */
ADD_IMPORT extern const double U_NEUTRON_MAG__MOM_2018;/**< J T^-1 */

ADD_IMPORT extern const double NEUTRON_MAG__MOM__TO_BOHR_MAGNETON_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_NEUTRON_MAG__MOM__TO_BOHR_MAGNETON_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double NEUTRON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_NEUTRON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double NEUTRON_MASS_2018;/**< kg */
ADD_IMPORT extern const double U_NEUTRON_MASS_2018;/**< kg */

ADD_IMPORT extern const double NEUTRON_MASS_ENERGY_EQUIVALENT_2018;/**< J */
ADD_IMPORT extern const double U_NEUTRON_MASS_ENERGY_EQUIVALENT_2018;/**< J */

ADD_IMPORT extern const double NEUTRON_MASS_ENERGY_EQUIVALENT_IN_MEV_2018;/**< MeV */
ADD_IMPORT extern const double U_NEUTRON_MASS_ENERGY_EQUIVALENT_IN_MEV_2018;/**< MeV */

ADD_IMPORT extern const double NEUTRON_MASS_IN_U_2018;/**< u */
ADD_IMPORT extern const double U_NEUTRON_MASS_IN_U_2018;/**< u */

ADD_IMPORT extern const double NEUTRON_MOLAR_MASS_2018;/**< kg mol^-1 */
ADD_IMPORT extern const double U_NEUTRON_MOLAR_MASS_2018;/**< kg mol^-1 */

ADD_IMPORT extern const double NEUTRON_MUON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_NEUTRON_MUON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double NEUTRON_PROTON_MAG__MOM__RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_NEUTRON_PROTON_MAG__MOM__RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double NEUTRON_PROTON_MASS_DIFFERENCE_2018;/**< kg */
ADD_IMPORT extern const double U_NEUTRON_PROTON_MASS_DIFFERENCE_2018;/**< kg */

ADD_IMPORT extern const double NEUTRON_PROTON_MASS_DIFFERENCE_ENERGY_EQUIVALENT_2018;/**< J */
ADD_IMPORT extern const double U_NEUTRON_PROTON_MASS_DIFFERENCE_ENERGY_EQUIVALENT_2018;/**< J */

ADD_IMPORT extern const double NEUTRON_PROTON_MASS_DIFFERENCE_ENERGY_EQUIVALENT_IN_MEV_2018;/**< MeV */
ADD_IMPORT extern const double U_NEUTRON_PROTON_MASS_DIFFERENCE_ENERGY_EQUIVALENT_IN_MEV_2018;/**< MeV */

ADD_IMPORT extern const double NEUTRON_PROTON_MASS_DIFFERENCE_IN_U_2018;/**< u */
ADD_IMPORT extern const double U_NEUTRON_PROTON_MASS_DIFFERENCE_IN_U_2018;/**< u */

ADD_IMPORT extern const double NEUTRON_PROTON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_NEUTRON_PROTON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double NEUTRON_RELATIVE_ATOMIC_MASS_2018;/**< dimensionless */
ADD_IMPORT extern const double U_NEUTRON_RELATIVE_ATOMIC_MASS_2018;/**< dimensionless */

ADD_IMPORT extern const double NEUTRON_TAU_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_NEUTRON_TAU_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double NEUTRON_TO_SHIELDED_PROTON_MAG__MOM__RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_NEUTRON_TO_SHIELDED_PROTON_MAG__MOM__RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double NEWTONIAN_CONSTANT_OF_GRAVITATION_2018;/**< m^3 kg^-1 s^-2 */
ADD_IMPORT extern const double U_NEWTONIAN_CONSTANT_OF_GRAVITATION_2018;/**< m^3 kg^-1 s^-2 */

ADD_IMPORT extern const double NEWTONIAN_CONSTANT_OF_GRAVITATION_OVER_H_BAR_C_2018;/**< (GeV/c^2)^-2 */
ADD_IMPORT extern const double U_NEWTONIAN_CONSTANT_OF_GRAVITATION_OVER_H_BAR_C_2018;/**< (GeV/c^2)^-2 */

ADD_IMPORT extern const double NUCLEAR_MAGNETON_2018;/**< J T^-1 */
ADD_IMPORT extern const double U_NUCLEAR_MAGNETON_2018;/**< J T^-1 */

ADD_IMPORT extern const double NUCLEAR_MAGNETON_IN_EV_T_2018;/**< eV T^-1 */
ADD_IMPORT extern const double U_NUCLEAR_MAGNETON_IN_EV_T_2018;/**< eV T^-1 */

ADD_IMPORT extern const double NUCLEAR_MAGNETON_IN_INVERSE_METER_PER_TESLA_2018;/**< m^-1 T^-1 */
ADD_IMPORT extern const double U_NUCLEAR_MAGNETON_IN_INVERSE_METER_PER_TESLA_2018;/**< m^-1 T^-1 */

ADD_IMPORT extern const double NUCLEAR_MAGNETON_IN_K_T_2018;/**< K T^-1 */
ADD_IMPORT extern const double U_NUCLEAR_MAGNETON_IN_K_T_2018;/**< K T^-1 */

ADD_IMPORT extern const double NUCLEAR_MAGNETON_IN_MHZ_T_2018;/**< MHz T^-1 */
ADD_IMPORT extern const double U_NUCLEAR_MAGNETON_IN_MHZ_T_2018;/**< MHz T^-1 */

ADD_IMPORT extern const double PLANCK_CONSTANT_2018;/**< J Hz^-1 */
ADD_IMPORT extern const double U_PLANCK_CONSTANT_2018;/**< J Hz^-1 */

ADD_IMPORT extern const double PLANCK_CONSTANT_IN_EV_HZ_2018;/**< eV Hz^-1 */
ADD_IMPORT extern const double U_PLANCK_CONSTANT_IN_EV_HZ_2018;/**< eV Hz^-1 */

ADD_IMPORT extern const double PLANCK_LENGTH_2018;/**< m */
ADD_IMPORT extern const double U_PLANCK_LENGTH_2018;/**< m */

ADD_IMPORT extern const double PLANCK_MASS_2018;/**< kg */
ADD_IMPORT extern const double U_PLANCK_MASS_2018;/**< kg */

ADD_IMPORT extern const double PLANCK_MASS_ENERGY_EQUIVALENT_IN_GEV_2018;/**< GeV */
ADD_IMPORT extern const double U_PLANCK_MASS_ENERGY_EQUIVALENT_IN_GEV_2018;/**< GeV */

ADD_IMPORT extern const double PLANCK_TEMPERATURE_2018;/**< K */
ADD_IMPORT extern const double U_PLANCK_TEMPERATURE_2018;/**< K */

ADD_IMPORT extern const double PLANCK_TIME_2018;/**< s */
ADD_IMPORT extern const double U_PLANCK_TIME_2018;/**< s */

ADD_IMPORT extern const double PROTON_CHARGE_TO_MASS_QUOTIENT_2018;/**< C kg^-1 */
ADD_IMPORT extern const double U_PROTON_CHARGE_TO_MASS_QUOTIENT_2018;/**< C kg^-1 */

ADD_IMPORT extern const double PROTON_COMPTON_WAVELENGTH_2018;/**< m */
ADD_IMPORT extern const double U_PROTON_COMPTON_WAVELENGTH_2018;/**< m */

ADD_IMPORT extern const double PROTON_ELECTRON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_PROTON_ELECTRON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double PROTON_G_FACTOR_2018;/**< dimensionless */
ADD_IMPORT extern const double U_PROTON_G_FACTOR_2018;/**< dimensionless */

ADD_IMPORT extern const double PROTON_GYROMAG__RATIO_2018;/**< s^-1 T^-1 */
ADD_IMPORT extern const double U_PROTON_GYROMAG__RATIO_2018;/**< s^-1 T^-1 */

ADD_IMPORT extern const double PROTON_GYROMAG__RATIO_IN_MHZ_T_2018;/**< MHz T^-1 */
ADD_IMPORT extern const double U_PROTON_GYROMAG__RATIO_IN_MHZ_T_2018;/**< MHz T^-1 */

ADD_IMPORT extern const double PROTON_MAG__MOM_2018;/**< J T^-1 */
ADD_IMPORT extern const double U_PROTON_MAG__MOM_2018;/**< J T^-1 */

ADD_IMPORT extern const double PROTON_MAG__MOM__TO_BOHR_MAGNETON_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_PROTON_MAG__MOM__TO_BOHR_MAGNETON_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double PROTON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_PROTON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double PROTON_MAG__SHIELDING_CORRECTION_2018;/**< dimensionless */
ADD_IMPORT extern const double U_PROTON_MAG__SHIELDING_CORRECTION_2018;/**< dimensionless */

ADD_IMPORT extern const double PROTON_MASS_2018;/**< kg */
ADD_IMPORT extern const double U_PROTON_MASS_2018;/**< kg */

ADD_IMPORT extern const double PROTON_MASS_ENERGY_EQUIVALENT_2018;/**< J */
ADD_IMPORT extern const double U_PROTON_MASS_ENERGY_EQUIVALENT_2018;/**< J */

ADD_IMPORT extern const double PROTON_MASS_ENERGY_EQUIVALENT_IN_MEV_2018;/**< MeV */
ADD_IMPORT extern const double U_PROTON_MASS_ENERGY_EQUIVALENT_IN_MEV_2018;/**< MeV */

ADD_IMPORT extern const double PROTON_MASS_IN_U_2018;/**< u */
ADD_IMPORT extern const double U_PROTON_MASS_IN_U_2018;/**< u */

ADD_IMPORT extern const double PROTON_MOLAR_MASS_2018;/**< kg mol^-1 */
ADD_IMPORT extern const double U_PROTON_MOLAR_MASS_2018;/**< kg mol^-1 */

ADD_IMPORT extern const double PROTON_MUON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_PROTON_MUON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double PROTON_NEUTRON_MAG__MOM__RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_PROTON_NEUTRON_MAG__MOM__RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double PROTON_NEUTRON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_PROTON_NEUTRON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double PROTON_RELATIVE_ATOMIC_MASS_2018;/**< dimensionless */
ADD_IMPORT extern const double U_PROTON_RELATIVE_ATOMIC_MASS_2018;/**< dimensionless */

ADD_IMPORT extern const double PROTON_RMS_CHARGE_RADIUS_2018;/**< m */
ADD_IMPORT extern const double U_PROTON_RMS_CHARGE_RADIUS_2018;/**< m */

ADD_IMPORT extern const double PROTON_TAU_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_PROTON_TAU_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double QUANTUM_OF_CIRCULATION_2018;/**< m^2 s^-1 */
ADD_IMPORT extern const double U_QUANTUM_OF_CIRCULATION_2018;/**< m^2 s^-1 */

ADD_IMPORT extern const double QUANTUM_OF_CIRCULATION_TIMES_2_2018;/**< m^2 s^-1 */
ADD_IMPORT extern const double U_QUANTUM_OF_CIRCULATION_TIMES_2_2018;/**< m^2 s^-1 */

ADD_IMPORT extern const double REDUCED_COMPTON_WAVELENGTH_2018;/**< m */
ADD_IMPORT extern const double U_REDUCED_COMPTON_WAVELENGTH_2018;/**< m */

ADD_IMPORT extern const double REDUCED_MUON_COMPTON_WAVELENGTH_2018;/**< m */
ADD_IMPORT extern const double U_REDUCED_MUON_COMPTON_WAVELENGTH_2018;/**< m */

ADD_IMPORT extern const double REDUCED_NEUTRON_COMPTON_WAVELENGTH_2018;/**< m */
ADD_IMPORT extern const double U_REDUCED_NEUTRON_COMPTON_WAVELENGTH_2018;/**< m */

ADD_IMPORT extern const double REDUCED_PLANCK_CONSTANT_2018;/**< J s */
ADD_IMPORT extern const double U_REDUCED_PLANCK_CONSTANT_2018;/**< J s */

ADD_IMPORT extern const double REDUCED_PLANCK_CONSTANT_IN_EV_S_2018;/**< eV s */
ADD_IMPORT extern const double U_REDUCED_PLANCK_CONSTANT_IN_EV_S_2018;/**< eV s */

ADD_IMPORT extern const double REDUCED_PLANCK_CONSTANT_TIMES_C_IN_MEV_FM_2018;/**< MeV fm */
ADD_IMPORT extern const double U_REDUCED_PLANCK_CONSTANT_TIMES_C_IN_MEV_FM_2018;/**< MeV fm */

ADD_IMPORT extern const double REDUCED_PROTON_COMPTON_WAVELENGTH_2018;/**< m */
ADD_IMPORT extern const double U_REDUCED_PROTON_COMPTON_WAVELENGTH_2018;/**< m */

ADD_IMPORT extern const double REDUCED_TAU_COMPTON_WAVELENGTH_2018;/**< m */
ADD_IMPORT extern const double U_REDUCED_TAU_COMPTON_WAVELENGTH_2018;/**< m */

ADD_IMPORT extern const double RYDBERG_CONSTANT_2018;/**< m^-1 */
ADD_IMPORT extern const double U_RYDBERG_CONSTANT_2018;/**< m^-1 */

ADD_IMPORT extern const double RYDBERG_CONSTANT_TIMES_C_IN_HZ_2018;/**< Hz */
ADD_IMPORT extern const double U_RYDBERG_CONSTANT_TIMES_C_IN_HZ_2018;/**< Hz */

ADD_IMPORT extern const double RYDBERG_CONSTANT_TIMES_HC_IN_EV_2018;/**< eV */
ADD_IMPORT extern const double U_RYDBERG_CONSTANT_TIMES_HC_IN_EV_2018;/**< eV */

ADD_IMPORT extern const double RYDBERG_CONSTANT_TIMES_HC_IN_J_2018;/**< J */
ADD_IMPORT extern const double U_RYDBERG_CONSTANT_TIMES_HC_IN_J_2018;/**< J */

ADD_IMPORT extern const double SACKUR_TETRODE_CONSTANT__1_K__100_KPA_2018;/**< dimensionless */
ADD_IMPORT extern const double U_SACKUR_TETRODE_CONSTANT__1_K__100_KPA_2018;/**< dimensionless */

ADD_IMPORT extern const double SACKUR_TETRODE_CONSTANT__1_K__101_325_KPA_2018;/**< dimensionless */
ADD_IMPORT extern const double U_SACKUR_TETRODE_CONSTANT__1_K__101_325_KPA_2018;/**< dimensionless */

ADD_IMPORT extern const double SECOND_RADIATION_CONSTANT_2018;/**< m K */
ADD_IMPORT extern const double U_SECOND_RADIATION_CONSTANT_2018;/**< m K */

ADD_IMPORT extern const double SHIELDED_HELION_GYROMAG__RATIO_2018;/**< s^-1 T^-1 */
ADD_IMPORT extern const double U_SHIELDED_HELION_GYROMAG__RATIO_2018;/**< s^-1 T^-1 */

ADD_IMPORT extern const double SHIELDED_HELION_GYROMAG__RATIO_IN_MHZ_T_2018;/**< MHz T^-1 */
ADD_IMPORT extern const double U_SHIELDED_HELION_GYROMAG__RATIO_IN_MHZ_T_2018;/**< MHz T^-1 */

ADD_IMPORT extern const double SHIELDED_HELION_MAG__MOM_2018;/**< J T^-1 */
ADD_IMPORT extern const double U_SHIELDED_HELION_MAG__MOM_2018;/**< J T^-1 */

ADD_IMPORT extern const double SHIELDED_HELION_MAG__MOM__TO_BOHR_MAGNETON_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_SHIELDED_HELION_MAG__MOM__TO_BOHR_MAGNETON_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double SHIELDED_HELION_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_SHIELDED_HELION_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double SHIELDED_HELION_TO_PROTON_MAG__MOM__RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_SHIELDED_HELION_TO_PROTON_MAG__MOM__RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double SHIELDED_HELION_TO_SHIELDED_PROTON_MAG__MOM__RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_SHIELDED_HELION_TO_SHIELDED_PROTON_MAG__MOM__RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double SHIELDED_PROTON_GYROMAG__RATIO_2018;/**< s^-1 T^-1 */
ADD_IMPORT extern const double U_SHIELDED_PROTON_GYROMAG__RATIO_2018;/**< s^-1 T^-1 */

ADD_IMPORT extern const double SHIELDED_PROTON_GYROMAG__RATIO_IN_MHZ_T_2018;/**< MHz T^-1 */
ADD_IMPORT extern const double U_SHIELDED_PROTON_GYROMAG__RATIO_IN_MHZ_T_2018;/**< MHz T^-1 */

ADD_IMPORT extern const double SHIELDED_PROTON_MAG__MOM_2018;/**< J T^-1 */
ADD_IMPORT extern const double U_SHIELDED_PROTON_MAG__MOM_2018;/**< J T^-1 */

ADD_IMPORT extern const double SHIELDED_PROTON_MAG__MOM__TO_BOHR_MAGNETON_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_SHIELDED_PROTON_MAG__MOM__TO_BOHR_MAGNETON_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double SHIELDED_PROTON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_SHIELDED_PROTON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double SHIELDING_DIFFERENCE_OF_D_AND_P_IN_HD_2018;/**< dimensionless */
ADD_IMPORT extern const double U_SHIELDING_DIFFERENCE_OF_D_AND_P_IN_HD_2018;/**< dimensionless */

ADD_IMPORT extern const double SHIELDING_DIFFERENCE_OF_T_AND_P_IN_HT_2018;/**< dimensionless */
ADD_IMPORT extern const double U_SHIELDING_DIFFERENCE_OF_T_AND_P_IN_HT_2018;/**< dimensionless */

ADD_IMPORT extern const double SPEED_OF_LIGHT_IN_VACUUM_2018;/**< m s^-1 */
ADD_IMPORT extern const double U_SPEED_OF_LIGHT_IN_VACUUM_2018;/**< m s^-1 */

ADD_IMPORT extern const double STANDARD_ACCELERATION_OF_GRAVITY_2018;/**< m s^-2 */
ADD_IMPORT extern const double U_STANDARD_ACCELERATION_OF_GRAVITY_2018;/**< m s^-2 */

ADD_IMPORT extern const double STANDARD_ATMOSPHERE_2018;/**< Pa */
ADD_IMPORT extern const double U_STANDARD_ATMOSPHERE_2018;/**< Pa */

ADD_IMPORT extern const double STANDARD_STATE_PRESSURE_2018;/**< Pa */
ADD_IMPORT extern const double U_STANDARD_STATE_PRESSURE_2018;/**< Pa */

ADD_IMPORT extern const double STEFAN_BOLTZMANN_CONSTANT_2018;/**< W m^-2 K^-4 */
ADD_IMPORT extern const double U_STEFAN_BOLTZMANN_CONSTANT_2018;/**< W m^-2 K^-4 */

ADD_IMPORT extern const double TAU_COMPTON_WAVELENGTH_2018;/**< m */
ADD_IMPORT extern const double U_TAU_COMPTON_WAVELENGTH_2018;/**< m */

ADD_IMPORT extern const double TAU_ELECTRON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_TAU_ELECTRON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double TAU_ENERGY_EQUIVALENT_2018;/**< MeV */
ADD_IMPORT extern const double U_TAU_ENERGY_EQUIVALENT_2018;/**< MeV */

ADD_IMPORT extern const double TAU_MASS_2018;/**< kg */
ADD_IMPORT extern const double U_TAU_MASS_2018;/**< kg */

ADD_IMPORT extern const double TAU_MASS_ENERGY_EQUIVALENT_2018;/**< J */
ADD_IMPORT extern const double U_TAU_MASS_ENERGY_EQUIVALENT_2018;/**< J */

ADD_IMPORT extern const double TAU_MASS_IN_U_2018;/**< u */
ADD_IMPORT extern const double U_TAU_MASS_IN_U_2018;/**< u */

ADD_IMPORT extern const double TAU_MOLAR_MASS_2018;/**< kg mol^-1 */
ADD_IMPORT extern const double U_TAU_MOLAR_MASS_2018;/**< kg mol^-1 */

ADD_IMPORT extern const double TAU_MUON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_TAU_MUON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double TAU_NEUTRON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_TAU_NEUTRON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double TAU_PROTON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_TAU_PROTON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double THOMSON_CROSS_SECTION_2018;/**< m^2 */
ADD_IMPORT extern const double U_THOMSON_CROSS_SECTION_2018;/**< m^2 */

ADD_IMPORT extern const double TRITON_ELECTRON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_TRITON_ELECTRON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double TRITON_G_FACTOR_2018;/**< dimensionless */
ADD_IMPORT extern const double U_TRITON_G_FACTOR_2018;/**< dimensionless */

ADD_IMPORT extern const double TRITON_MAG__MOM_2018;/**< J T^-1 */
ADD_IMPORT extern const double U_TRITON_MAG__MOM_2018;/**< J T^-1 */

ADD_IMPORT extern const double TRITON_MAG__MOM__TO_BOHR_MAGNETON_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_TRITON_MAG__MOM__TO_BOHR_MAGNETON_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double TRITON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_TRITON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double TRITON_MASS_2018;/**< kg */
ADD_IMPORT extern const double U_TRITON_MASS_2018;/**< kg */

ADD_IMPORT extern const double TRITON_MASS_ENERGY_EQUIVALENT_2018;/**< J */
ADD_IMPORT extern const double U_TRITON_MASS_ENERGY_EQUIVALENT_2018;/**< J */

ADD_IMPORT extern const double TRITON_MASS_ENERGY_EQUIVALENT_IN_MEV_2018;/**< MeV */
ADD_IMPORT extern const double U_TRITON_MASS_ENERGY_EQUIVALENT_IN_MEV_2018;/**< MeV */

ADD_IMPORT extern const double TRITON_MASS_IN_U_2018;/**< u */
ADD_IMPORT extern const double U_TRITON_MASS_IN_U_2018;/**< u */

ADD_IMPORT extern const double TRITON_MOLAR_MASS_2018;/**< kg mol^-1 */
ADD_IMPORT extern const double U_TRITON_MOLAR_MASS_2018;/**< kg mol^-1 */

ADD_IMPORT extern const double TRITON_PROTON_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_TRITON_PROTON_MASS_RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double TRITON_RELATIVE_ATOMIC_MASS_2018;/**< dimensionless */
ADD_IMPORT extern const double U_TRITON_RELATIVE_ATOMIC_MASS_2018;/**< dimensionless */

ADD_IMPORT extern const double TRITON_TO_PROTON_MAG__MOM__RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_TRITON_TO_PROTON_MAG__MOM__RATIO_2018;/**< dimensionless */

ADD_IMPORT extern const double UNIFIED_ATOMIC_MASS_UNIT_2018;/**< kg */
ADD_IMPORT extern const double U_UNIFIED_ATOMIC_MASS_UNIT_2018;/**< kg */

ADD_IMPORT extern const double VACUUM_ELECTRIC_PERMITTIVITY_2018;/**< F m^-1 */
ADD_IMPORT extern const double U_VACUUM_ELECTRIC_PERMITTIVITY_2018;/**< F m^-1 */

ADD_IMPORT extern const double VACUUM_MAG__PERMEABILITY_2018;/**< N A^-2 */
ADD_IMPORT extern const double U_VACUUM_MAG__PERMEABILITY_2018;/**< N A^-2 */

ADD_IMPORT extern const double VON_KLITZING_CONSTANT_2018;/**< ohm */
ADD_IMPORT extern const double U_VON_KLITZING_CONSTANT_2018;/**< ohm */

ADD_IMPORT extern const double WEAK_MIXING_ANGLE_2018;/**< dimensionless */
ADD_IMPORT extern const double U_WEAK_MIXING_ANGLE_2018;/**< dimensionless */

ADD_IMPORT extern const double WIEN_FREQUENCY_DISPLACEMENT_LAW_CONSTANT_2018;/**< Hz K^-1 */
ADD_IMPORT extern const double U_WIEN_FREQUENCY_DISPLACEMENT_LAW_CONSTANT_2018;/**< Hz K^-1 */

ADD_IMPORT extern const double WIEN_WAVELENGTH_DISPLACEMENT_LAW_CONSTANT_2018;/**< m K */
ADD_IMPORT extern const double U_WIEN_WAVELENGTH_DISPLACEMENT_LAW_CONSTANT_2018;/**< m K */

ADD_IMPORT extern const double W_TO_Z_MASS_RATIO_2018;/**< dimensionless */
ADD_IMPORT extern const double U_W_TO_Z_MASS_RATIO_2018;/**< dimensionless */

#endif

