/**
* @file
* @brief Version - autogenerated.
*/

#ifndef codata_VERSION_H
#define codata_VERSION_H
#if _MSC_VER
#define ADD_IMPORT __declspec(dllimport)
#else
#define ADD_IMPORT
#endif
ADD_IMPORT extern const char codata_version_capi_version[ 6];
#endif

