.TH codata_version 3 "@DATE@" "@VERSION@" "Library Functions Manual"

.SH NAME
\"{{{
version \- function
\"}}}

.SH LIBRARY
\"{{{
Codata library 
.RI ( libcodata ", " \-lcodata )
\"}}}

.SH SYNOPSIS
\"{{{ 
.IP Fortran 10
.BI "function version()result(" fptr ")"
.RS
.IP "" 3
.BI "character(len=:), pointer :: " fptr 
.RE

.IP C 10
.B char* ciaaw_version()

.IP Python 10
.BI str: pyciaaw.__version__
\"}}}

.SH DESCRIPTION
\"{{{
Get the library version.
\"}}}

.SH RETURN VALUE
\"{{{
.IP pointer 10 
Pointer to the version string.
\"}}}

.SH EXAMPLE
\"{{{
.PP
Fortran:
.nf
.ft CR
    use codata
    print *, "version = ", version()
.ft R
.fi

.PP
C:
.nf
.ft CR
    include <stdio.h>
    include "codata.h"
    printf("version = %s\\n", codata_version());
.ft R
.fi

.PP
Python:
.nf
.ft CR
    import pycodata
    print(f"version = {pycodata.__version__}")
.ft R
.fi
\"}}}

.SH SEE ALSO
\"{{{
.BR codata (3),
.BR codata_cli (1),
.BR codata_version (3),
.BR codata_constant_type (3)
\"}}}
