.TH codata_constant_type 3 "@DATE@" "@VERSION@" "Library Functions Manual"

.SH NAME
codata_constant_type \- data type defining a constant


.SH LIBRARY
Codata library 
.RI ( libcodata ", " \-lcodata )


.SH SYNOPSIS
.IP Fortran 10
.BI "type(codata_constant_type) :: " "c"

.IP C 10 
.BI "struct codata_constant_type" " c"



.SH DESCRIPTION
Defines a constant with 
.I the name, the value, the uncertainty and the unit.



.SH EXAMPLE
.PP
Fortran:
.nf
.ft CR
      use codata
      type(codata_constant_type), pointer :: c
      c = SPEED_OF_LIGHT_IN_VACUUM
.ft R
.fi

.PP
C:
.PP
.nf
.ft CR
      struct codata_constant_type c;
      c = SPEED_OF_LIGHT_IN_VACUUM;

.ft R
.fi



.SH SEE ALSO
.BR codata (7),
.BR codata (3),
.BR codata_cli (1),
.BR codata_version (3),
.BR codata_constant_type (3)
