.TH codata_version 3 "24 June 2026" "2.5.4" "Library Functions Manual"

.SH NAME
\"{{{
version \- function
\"}}}

.SH LIBRARY
\"{{{
Codata library 
.RI ( libcodata ", " \-lcodata )
\"}}}

.SH SYNOPSIS
\"{{{ 
.IP Fortran 10
.B character(len=:), pointer :: version()

.IP C 10
.B char* codata_version()

.IP Python 10
.B pycodata.__version__
\"}}}

.SH DESCRIPTION
\"{{{
Get the library version.
\"}}}

.SH EXAMPLE
\"{{{
.PP
Fortran:
.nf
.ft CR
      use codata
      print *, "version = ", version()
.ft R
.fi

.PP
C:
.nf
.ft CR
      include <stdio.h>
      include "codata.h"
      printf("version = %s\n", codata_version());
.ft R
.fi

.PP
Python:
.nf
.ft CR
      import pycodata
      print(f"version = {pycodata.__version__}")
.ft R
.fi
\"}}}

.SH SEE ALSO
\"{{{
.BR codata (3),
.BR codata_cli (1),
.BR codata_version (3),
.BR codata_constant_type (3)
\"}}}
