!> @file
!! @brief Autogenerated.
!! Fundamental Physical Constants --- Complete Listing
!! 2018 CODATA adjustment
!! From:  http://physics.nist.gov/constants


!> @brief Codata array
!! @details Autogenerated from NIST table.
module codata_array
use iso_fortran_env
use codata_data
implicit none

type(t_constant), dimension(10), parameter :: codata_10 = [&
codata_constant_1,&
codata_constant_2,&
codata_constant_3,&
codata_constant_4,&
codata_constant_5,&
codata_constant_6,&
codata_constant_7,&
codata_constant_8,&
codata_constant_9,&
codata_constant_10]
type(t_constant), dimension(10), parameter :: codata_20 = [&
codata_constant_11,&
codata_constant_12,&
codata_constant_13,&
codata_constant_14,&
codata_constant_15,&
codata_constant_16,&
codata_constant_17,&
codata_constant_18,&
codata_constant_19,&
codata_constant_20]
type(t_constant), dimension(10), parameter :: codata_30 = [&
codata_constant_21,&
codata_constant_22,&
codata_constant_23,&
codata_constant_24,&
codata_constant_25,&
codata_constant_26,&
codata_constant_27,&
codata_constant_28,&
codata_constant_29,&
codata_constant_30]
type(t_constant), dimension(10), parameter :: codata_40 = [&
codata_constant_31,&
codata_constant_32,&
codata_constant_33,&
codata_constant_34,&
codata_constant_35,&
codata_constant_36,&
codata_constant_37,&
codata_constant_38,&
codata_constant_39,&
codata_constant_40]
type(t_constant), dimension(10), parameter :: codata_50 = [&
codata_constant_41,&
codata_constant_42,&
codata_constant_43,&
codata_constant_44,&
codata_constant_45,&
codata_constant_46,&
codata_constant_47,&
codata_constant_48,&
codata_constant_49,&
codata_constant_50]
type(t_constant), dimension(10), parameter :: codata_60 = [&
codata_constant_51,&
codata_constant_52,&
codata_constant_53,&
codata_constant_54,&
codata_constant_55,&
codata_constant_56,&
codata_constant_57,&
codata_constant_58,&
codata_constant_59,&
codata_constant_60]
type(t_constant), dimension(10), parameter :: codata_70 = [&
codata_constant_61,&
codata_constant_62,&
codata_constant_63,&
codata_constant_64,&
codata_constant_65,&
codata_constant_66,&
codata_constant_67,&
codata_constant_68,&
codata_constant_69,&
codata_constant_70]
type(t_constant), dimension(10), parameter :: codata_80 = [&
codata_constant_71,&
codata_constant_72,&
codata_constant_73,&
codata_constant_74,&
codata_constant_75,&
codata_constant_76,&
codata_constant_77,&
codata_constant_78,&
codata_constant_79,&
codata_constant_80]
type(t_constant), dimension(10), parameter :: codata_90 = [&
codata_constant_81,&
codata_constant_82,&
codata_constant_83,&
codata_constant_84,&
codata_constant_85,&
codata_constant_86,&
codata_constant_87,&
codata_constant_88,&
codata_constant_89,&
codata_constant_90]
type(t_constant), dimension(10), parameter :: codata_100 = [&
codata_constant_91,&
codata_constant_92,&
codata_constant_93,&
codata_constant_94,&
codata_constant_95,&
codata_constant_96,&
codata_constant_97,&
codata_constant_98,&
codata_constant_99,&
codata_constant_100]
type(t_constant), dimension(10), parameter :: codata_110 = [&
codata_constant_101,&
codata_constant_102,&
codata_constant_103,&
codata_constant_104,&
codata_constant_105,&
codata_constant_106,&
codata_constant_107,&
codata_constant_108,&
codata_constant_109,&
codata_constant_110]
type(t_constant), dimension(10), parameter :: codata_120 = [&
codata_constant_111,&
codata_constant_112,&
codata_constant_113,&
codata_constant_114,&
codata_constant_115,&
codata_constant_116,&
codata_constant_117,&
codata_constant_118,&
codata_constant_119,&
codata_constant_120]
type(t_constant), dimension(10), parameter :: codata_130 = [&
codata_constant_121,&
codata_constant_122,&
codata_constant_123,&
codata_constant_124,&
codata_constant_125,&
codata_constant_126,&
codata_constant_127,&
codata_constant_128,&
codata_constant_129,&
codata_constant_130]
type(t_constant), dimension(10), parameter :: codata_140 = [&
codata_constant_131,&
codata_constant_132,&
codata_constant_133,&
codata_constant_134,&
codata_constant_135,&
codata_constant_136,&
codata_constant_137,&
codata_constant_138,&
codata_constant_139,&
codata_constant_140]
type(t_constant), dimension(10), parameter :: codata_150 = [&
codata_constant_141,&
codata_constant_142,&
codata_constant_143,&
codata_constant_144,&
codata_constant_145,&
codata_constant_146,&
codata_constant_147,&
codata_constant_148,&
codata_constant_149,&
codata_constant_150]
type(t_constant), dimension(10), parameter :: codata_160 = [&
codata_constant_151,&
codata_constant_152,&
codata_constant_153,&
codata_constant_154,&
codata_constant_155,&
codata_constant_156,&
codata_constant_157,&
codata_constant_158,&
codata_constant_159,&
codata_constant_160]
type(t_constant), dimension(10), parameter :: codata_170 = [&
codata_constant_161,&
codata_constant_162,&
codata_constant_163,&
codata_constant_164,&
codata_constant_165,&
codata_constant_166,&
codata_constant_167,&
codata_constant_168,&
codata_constant_169,&
codata_constant_170]
type(t_constant), dimension(10), parameter :: codata_180 = [&
codata_constant_171,&
codata_constant_172,&
codata_constant_173,&
codata_constant_174,&
codata_constant_175,&
codata_constant_176,&
codata_constant_177,&
codata_constant_178,&
codata_constant_179,&
codata_constant_180]
type(t_constant), dimension(10), parameter :: codata_190 = [&
codata_constant_181,&
codata_constant_182,&
codata_constant_183,&
codata_constant_184,&
codata_constant_185,&
codata_constant_186,&
codata_constant_187,&
codata_constant_188,&
codata_constant_189,&
codata_constant_190]
type(t_constant), dimension(10), parameter :: codata_200 = [&
codata_constant_191,&
codata_constant_192,&
codata_constant_193,&
codata_constant_194,&
codata_constant_195,&
codata_constant_196,&
codata_constant_197,&
codata_constant_198,&
codata_constant_199,&
codata_constant_200]
type(t_constant), dimension(10), parameter :: codata_210 = [&
codata_constant_201,&
codata_constant_202,&
codata_constant_203,&
codata_constant_204,&
codata_constant_205,&
codata_constant_206,&
codata_constant_207,&
codata_constant_208,&
codata_constant_209,&
codata_constant_210]
type(t_constant), dimension(10), parameter :: codata_220 = [&
codata_constant_211,&
codata_constant_212,&
codata_constant_213,&
codata_constant_214,&
codata_constant_215,&
codata_constant_216,&
codata_constant_217,&
codata_constant_218,&
codata_constant_219,&
codata_constant_220]
type(t_constant), dimension(10), parameter :: codata_230 = [&
codata_constant_221,&
codata_constant_222,&
codata_constant_223,&
codata_constant_224,&
codata_constant_225,&
codata_constant_226,&
codata_constant_227,&
codata_constant_228,&
codata_constant_229,&
codata_constant_230]
type(t_constant), dimension(10), parameter :: codata_240 = [&
codata_constant_231,&
codata_constant_232,&
codata_constant_233,&
codata_constant_234,&
codata_constant_235,&
codata_constant_236,&
codata_constant_237,&
codata_constant_238,&
codata_constant_239,&
codata_constant_240]
type(t_constant), dimension(10), parameter :: codata_250 = [&
codata_constant_241,&
codata_constant_242,&
codata_constant_243,&
codata_constant_244,&
codata_constant_245,&
codata_constant_246,&
codata_constant_247,&
codata_constant_248,&
codata_constant_249,&
codata_constant_250]
type(t_constant), dimension(10), parameter :: codata_260 = [&
codata_constant_251,&
codata_constant_252,&
codata_constant_253,&
codata_constant_254,&
codata_constant_255,&
codata_constant_256,&
codata_constant_257,&
codata_constant_258,&
codata_constant_259,&
codata_constant_260]
type(t_constant), dimension(10), parameter :: codata_270 = [&
codata_constant_261,&
codata_constant_262,&
codata_constant_263,&
codata_constant_264,&
codata_constant_265,&
codata_constant_266,&
codata_constant_267,&
codata_constant_268,&
codata_constant_269,&
codata_constant_270]
type(t_constant), dimension(10), parameter :: codata_280 = [&
codata_constant_271,&
codata_constant_272,&
codata_constant_273,&
codata_constant_274,&
codata_constant_275,&
codata_constant_276,&
codata_constant_277,&
codata_constant_278,&
codata_constant_279,&
codata_constant_280]
type(t_constant), dimension(10), parameter :: codata_290 = [&
codata_constant_281,&
codata_constant_282,&
codata_constant_283,&
codata_constant_284,&
codata_constant_285,&
codata_constant_286,&
codata_constant_287,&
codata_constant_288,&
codata_constant_289,&
codata_constant_290]
type(t_constant), dimension(10), parameter :: codata_300 = [&
codata_constant_291,&
codata_constant_292,&
codata_constant_293,&
codata_constant_294,&
codata_constant_295,&
codata_constant_296,&
codata_constant_297,&
codata_constant_298,&
codata_constant_299,&
codata_constant_300]
type(t_constant), dimension(10), parameter :: codata_310 = [&
codata_constant_301,&
codata_constant_302,&
codata_constant_303,&
codata_constant_304,&
codata_constant_305,&
codata_constant_306,&
codata_constant_307,&
codata_constant_308,&
codata_constant_309,&
codata_constant_310]
type(t_constant), dimension(10), parameter :: codata_320 = [&
codata_constant_311,&
codata_constant_312,&
codata_constant_313,&
codata_constant_314,&
codata_constant_315,&
codata_constant_316,&
codata_constant_317,&
codata_constant_318,&
codata_constant_319,&
codata_constant_320]
type(t_constant), dimension(10), parameter :: codata_330 = [&
codata_constant_321,&
codata_constant_322,&
codata_constant_323,&
codata_constant_324,&
codata_constant_325,&
codata_constant_326,&
codata_constant_327,&
codata_constant_328,&
codata_constant_329,&
codata_constant_330]
type(t_constant), dimension(10), parameter :: codata_340 = [&
codata_constant_331,&
codata_constant_332,&
codata_constant_333,&
codata_constant_334,&
codata_constant_335,&
codata_constant_336,&
codata_constant_337,&
codata_constant_338,&
codata_constant_339,&
codata_constant_340]
type(t_constant), dimension(10), parameter :: codata_350 = [&
codata_constant_341,&
codata_constant_342,&
codata_constant_343,&
codata_constant_344,&
codata_constant_345,&
codata_constant_346,&
codata_constant_347,&
codata_constant_348,&
codata_constant_349,&
codata_constant_350]
type(t_constant), dimension(4), parameter :: codata_354 = [&
  t_constant("WEAK MIXING ANGLE", 0.22290d0, 0.00030d0, " ") ,&
  t_constant("WIEN FREQUENCY DISPLACEMENT LAW CONSTANT", 5.878925757d10, 0.0d0, "Hz K^-1") ,&
  t_constant("WIEN WAVELENGTH DISPLACEMENT LAW CONSTANT", 2.897771955d-3, 0.0d0, "m K") ,&
  t_constant("W TO Z MASS RATIO", 0.88153d0, 0.00017d0, " ") ]

type(t_constant), dimension(354), public, parameter :: codata_constants = [&
codata_10 ,&
codata_20 ,&
codata_30 ,&
codata_40 ,&
codata_50 ,&
codata_60 ,&
codata_70 ,&
codata_80 ,&
codata_90 ,&
codata_100 ,&
codata_110 ,&
codata_120 ,&
codata_130 ,&
codata_140 ,&
codata_150 ,&
codata_160 ,&
codata_170 ,&
codata_180 ,&
codata_190 ,&
codata_200 ,&
codata_210 ,&
codata_220 ,&
codata_230 ,&
codata_240 ,&
codata_250 ,&
codata_260 ,&
codata_270 ,&
codata_280 ,&
codata_290 ,&
codata_300 ,&
codata_310 ,&
codata_320 ,&
codata_330 ,&
codata_340 ,&
codata_350 ,&
codata_354 ]

end module codata_array
