module codata__constants_2014
    !! Codata Constants - Autogenerated
    use iso_fortran_env, only: dp=>real64, int32
    use codata__constants_type
    private

integer(int32), parameter, public :: YEAR_2014 = 2014 !! Year of release.

type(codata_constant_type), parameter, public :: LATTICE_SPACING_OF_SILICON_2014 = &
codata_constant_type("{220} lattice spacing of silicon", &
192.0155714e-12_dp, 0.0000032e-12_dp, &
"m") !! {220} lattice spacing of silicon

type(codata_constant_type), parameter, public :: ALPHA_PARTICLE_ELECTRON_MASS_RATIO_2014 = &
codata_constant_type("alpha particle-electron mass ratio", &
7294.29954136_dp, 0.00000024_dp, &
"") !! alpha particle-electron mass ratio

type(codata_constant_type), parameter, public :: ALPHA_PARTICLE_MASS_2014 = &
codata_constant_type("alpha particle mass", &
6.644657230e-27_dp, 0.000000082e-27_dp, &
"kg") !! alpha particle mass

type(codata_constant_type), parameter, public :: ALPHA_PARTICLE_MASS_ENERGY_EQUIVALENT_2014 = &
codata_constant_type("alpha particle mass energy equivalent", &
5.971920097e-10_dp, 0.000000073e-10_dp, &
"J") !! alpha particle mass energy equivalent

type(codata_constant_type), parameter, public :: ALPHA_PARTICLE_MASS_ENERGY_EQUIVALENT_IN_MEV_2014 = &
codata_constant_type("alpha particle mass energy equivalent in MeV", &
3727.379378_dp, 0.000023_dp, &
"MeV") !! alpha particle mass energy equivalent in MeV

type(codata_constant_type), parameter, public :: ALPHA_PARTICLE_MASS_IN_U_2014 = &
codata_constant_type("alpha particle mass in u", &
4.001506179127_dp, 0.000000000063_dp, &
"u") !! alpha particle mass in u

type(codata_constant_type), parameter, public :: ALPHA_PARTICLE_MOLAR_MASS_2014 = &
codata_constant_type("alpha particle molar mass", &
4.001506179127e-3_dp, 0.000000000063e-3_dp, &
"kg mol^-1") !! alpha particle molar mass

type(codata_constant_type), parameter, public :: ALPHA_PARTICLE_PROTON_MASS_RATIO_2014 = &
codata_constant_type("alpha particle-proton mass ratio", &
3.97259968907_dp, 0.00000000036_dp, &
"") !! alpha particle-proton mass ratio

type(codata_constant_type), parameter, public :: ANGSTROM_STAR_2014 = &
codata_constant_type("Angstrom star", &
1.00001495e-10_dp, 0.00000090e-10_dp, &
"m") !! Angstrom star

type(codata_constant_type), parameter, public :: ATOMIC_MASS_CONSTANT_2014 = &
codata_constant_type("atomic mass constant", &
1.660539040e-27_dp, 0.000000020e-27_dp, &
"kg") !! atomic mass constant

type(codata_constant_type), parameter, public :: ATOMIC_MASS_CONSTANT_ENERGY_EQUIVALENT_2014 = &
codata_constant_type("atomic mass constant energy equivalent", &
1.492418062e-10_dp, 0.000000018e-10_dp, &
"J") !! atomic mass constant energy equivalent

type(codata_constant_type), parameter, public :: ATOMIC_MASS_CONSTANT_ENERGY_EQUIVALENT_IN_MEV_2014 = &
codata_constant_type("atomic mass constant energy equivalent in MeV", &
931.4940954_dp, 0.0000057_dp, &
"MeV") !! atomic mass constant energy equivalent in MeV

type(codata_constant_type), parameter, public :: ATOMIC_MASS_UNIT_ELECTRON_VOLT_RELATIONSHIP_2014 = &
codata_constant_type("atomic mass unit-electron volt relationship", &
931.4940954e6_dp, 0.0000057e6_dp, &
"eV") !! atomic mass unit-electron volt relationship

type(codata_constant_type), parameter, public :: ATOMIC_MASS_UNIT_HARTREE_RELATIONSHIP_2014 = &
codata_constant_type("atomic mass unit-hartree relationship", &
3.4231776902e7_dp, 0.0000000016e7_dp, &
"E_h") !! atomic mass unit-hartree relationship

type(codata_constant_type), parameter, public :: ATOMIC_MASS_UNIT_HERTZ_RELATIONSHIP_2014 = &
codata_constant_type("atomic mass unit-hertz relationship", &
2.2523427206e23_dp, 0.0000000010e23_dp, &
"Hz") !! atomic mass unit-hertz relationship

type(codata_constant_type), parameter, public :: ATOMIC_MASS_UNIT_INVERSE_METER_RELATIONSHIP_2014 = &
codata_constant_type("atomic mass unit-inverse meter relationship", &
7.5130066166e14_dp, 0.0000000034e14_dp, &
"m^-1") !! atomic mass unit-inverse meter relationship

type(codata_constant_type), parameter, public :: ATOMIC_MASS_UNIT_JOULE_RELATIONSHIP_2014 = &
codata_constant_type("atomic mass unit-joule relationship", &
1.492418062e-10_dp, 0.000000018e-10_dp, &
"J") !! atomic mass unit-joule relationship

type(codata_constant_type), parameter, public :: ATOMIC_MASS_UNIT_KELVIN_RELATIONSHIP_2014 = &
codata_constant_type("atomic mass unit-kelvin relationship", &
1.08095438e13_dp, 0.00000062e13_dp, &
"K") !! atomic mass unit-kelvin relationship

type(codata_constant_type), parameter, public :: ATOMIC_MASS_UNIT_KILOGRAM_RELATIONSHIP_2014 = &
codata_constant_type("atomic mass unit-kilogram relationship", &
1.660539040e-27_dp, 0.000000020e-27_dp, &
"kg") !! atomic mass unit-kilogram relationship

type(codata_constant_type), parameter, public :: ATOMIC_UNIT_OF_1ST_HYPERPOLARIZABILITY_2014 = &
codata_constant_type("atomic unit of 1st hyperpolarizability", &
3.206361329e-53_dp, 0.000000020e-53_dp, &
"C^3 m^3 J^-2") !! atomic unit of 1st hyperpolarizability

type(codata_constant_type), parameter, public :: ATOMIC_UNIT_OF_2ND_HYPERPOLARIZABILITY_2014 = &
codata_constant_type("atomic unit of 2nd hyperpolarizability", &
6.235380085e-65_dp, 0.000000077e-65_dp, &
"C^4 m^4 J^-3") !! atomic unit of 2nd hyperpolarizability

type(codata_constant_type), parameter, public :: ATOMIC_UNIT_OF_ACTION_2014 = &
codata_constant_type("atomic unit of action", &
1.054571800e-34_dp, 0.000000013e-34_dp, &
"J s") !! atomic unit of action

type(codata_constant_type), parameter, public :: ATOMIC_UNIT_OF_CHARGE_2014 = &
codata_constant_type("atomic unit of charge", &
1.6021766208e-19_dp, 0.0000000098e-19_dp, &
"C") !! atomic unit of charge

type(codata_constant_type), parameter, public :: ATOMIC_UNIT_OF_CHARGE_DENSITY_2014 = &
codata_constant_type("atomic unit of charge density", &
1.0812023770e12_dp, 0.0000000067e12_dp, &
"C m^-3") !! atomic unit of charge density

type(codata_constant_type), parameter, public :: ATOMIC_UNIT_OF_CURRENT_2014 = &
codata_constant_type("atomic unit of current", &
6.623618183e-3_dp, 0.000000041e-3_dp, &
"A") !! atomic unit of current

type(codata_constant_type), parameter, public :: ATOMIC_UNIT_OF_ELECTRIC_DIPOLE_MOM_2014 = &
codata_constant_type("atomic unit of electric dipole mom.", &
8.478353552e-30_dp, 0.000000052e-30_dp, &
"C m") !! atomic unit of electric dipole mom.

type(codata_constant_type), parameter, public :: ATOMIC_UNIT_OF_ELECTRIC_FIELD_2014 = &
codata_constant_type("atomic unit of electric field", &
5.142206707e11_dp, 0.000000032e11_dp, &
"V m^-1") !! atomic unit of electric field

type(codata_constant_type), parameter, public :: ATOMIC_UNIT_OF_ELECTRIC_FIELD_GRADIENT_2014 = &
codata_constant_type("atomic unit of electric field gradient", &
9.717362356e21_dp, 0.000000060e21_dp, &
"V m^-2") !! atomic unit of electric field gradient

type(codata_constant_type), parameter, public :: ATOMIC_UNIT_OF_ELECTRIC_POLARIZABILITY_2014 = &
codata_constant_type("atomic unit of electric polarizability", &
1.6487772731e-41_dp, 0.0000000011e-41_dp, &
"C^2 m^2 J^-1") !! atomic unit of electric polarizability

type(codata_constant_type), parameter, public :: ATOMIC_UNIT_OF_ELECTRIC_POTENTIAL_2014 = &
codata_constant_type("atomic unit of electric potential", &
27.21138602_dp, 0.00000017_dp, &
"V") !! atomic unit of electric potential

type(codata_constant_type), parameter, public :: ATOMIC_UNIT_OF_ELECTRIC_QUADRUPOLE_MOM_2014 = &
codata_constant_type("atomic unit of electric quadrupole mom.", &
4.486551484e-40_dp, 0.000000028e-40_dp, &
"C m^2") !! atomic unit of electric quadrupole mom.

type(codata_constant_type), parameter, public :: ATOMIC_UNIT_OF_ENERGY_2014 = &
codata_constant_type("atomic unit of energy", &
4.359744650e-18_dp, 0.000000054e-18_dp, &
"J") !! atomic unit of energy

type(codata_constant_type), parameter, public :: ATOMIC_UNIT_OF_FORCE_2014 = &
codata_constant_type("atomic unit of force", &
8.23872336e-8_dp, 0.00000010e-8_dp, &
"N") !! atomic unit of force

type(codata_constant_type), parameter, public :: ATOMIC_UNIT_OF_LENGTH_2014 = &
codata_constant_type("atomic unit of length", &
0.52917721067e-10_dp, 0.00000000012e-10_dp, &
"m") !! atomic unit of length

type(codata_constant_type), parameter, public :: ATOMIC_UNIT_OF_MAG_DIPOLE_MOM_2014 = &
codata_constant_type("atomic unit of mag. dipole mom.", &
1.854801999e-23_dp, 0.000000011e-23_dp, &
"J T^-1") !! atomic unit of mag. dipole mom.

type(codata_constant_type), parameter, public :: ATOMIC_UNIT_OF_MAG_FLUX_DENSITY_2014 = &
codata_constant_type("atomic unit of mag. flux density", &
2.350517550e5_dp, 0.000000014e5_dp, &
"T") !! atomic unit of mag. flux density

type(codata_constant_type), parameter, public :: ATOMIC_UNIT_OF_MAGNETIZABILITY_2014 = &
codata_constant_type("atomic unit of magnetizability", &
7.8910365886e-29_dp, 0.0000000090e-29_dp, &
"J T^-2") !! atomic unit of magnetizability

type(codata_constant_type), parameter, public :: ATOMIC_UNIT_OF_MASS_2014 = &
codata_constant_type("atomic unit of mass", &
9.10938356e-31_dp, 0.00000011e-31_dp, &
"kg") !! atomic unit of mass

type(codata_constant_type), parameter, public :: ATOMIC_UNIT_OF_MOMUM_2014 = &
codata_constant_type("atomic unit of mom.um", &
1.992851882e-24_dp, 0.000000024e-24_dp, &
"kg m s^-1") !! atomic unit of mom.um

type(codata_constant_type), parameter, public :: ATOMIC_UNIT_OF_PERMITTIVITY_2014 = &
codata_constant_type("atomic unit of permittivity", &
1.112650056e-10_dp, 0.0_dp, &
"F m^-1") !! atomic unit of permittivity

type(codata_constant_type), parameter, public :: ATOMIC_UNIT_OF_TIME_2014 = &
codata_constant_type("atomic unit of time", &
2.418884326509e-17_dp, 0.000000000014e-17_dp, &
"s") !! atomic unit of time

type(codata_constant_type), parameter, public :: ATOMIC_UNIT_OF_VELOCITY_2014 = &
codata_constant_type("atomic unit of velocity", &
2.18769126277e6_dp, 0.00000000050e6_dp, &
"m s^-1") !! atomic unit of velocity

type(codata_constant_type), parameter, public :: AVOGADRO_CONSTANT_2014 = &
codata_constant_type("Avogadro constant", &
6.022140857e23_dp, 0.000000074e23_dp, &
"mol^-1") !! Avogadro constant

type(codata_constant_type), parameter, public :: BOHR_MAGNETON_2014 = &
codata_constant_type("Bohr magneton", &
927.4009994e-26_dp, 0.0000057e-26_dp, &
"J T^-1") !! Bohr magneton

type(codata_constant_type), parameter, public :: BOHR_MAGNETON_IN_EV_T_2014 = &
codata_constant_type("Bohr magneton in eV/T", &
5.7883818012e-5_dp, 0.0000000026e-5_dp, &
"eV T^-1") !! Bohr magneton in eV/T

type(codata_constant_type), parameter, public :: BOHR_MAGNETON_IN_HZ_T_2014 = &
codata_constant_type("Bohr magneton in Hz/T", &
13.996245042e9_dp, 0.000000086e9_dp, &
"Hz T^-1") !! Bohr magneton in Hz/T

type(codata_constant_type), parameter, public :: BOHR_MAGNETON_IN_INVERSE_METERS_PER_TESLA_2014 = &
codata_constant_type("Bohr magneton in inverse meters per tesla", &
46.68644814_dp, 0.00000029_dp, &
"m^-1 T^-1") !! Bohr magneton in inverse meters per tesla

type(codata_constant_type), parameter, public :: BOHR_MAGNETON_IN_K_T_2014 = &
codata_constant_type("Bohr magneton in K/T", &
0.67171405_dp, 0.00000039_dp, &
"K T^-1") !! Bohr magneton in K/T

type(codata_constant_type), parameter, public :: BOHR_RADIUS_2014 = &
codata_constant_type("Bohr radius", &
0.52917721067e-10_dp, 0.00000000012e-10_dp, &
"m") !! Bohr radius

type(codata_constant_type), parameter, public :: BOLTZMANN_CONSTANT_2014 = &
codata_constant_type("Boltzmann constant", &
1.38064852e-23_dp, 0.00000079e-23_dp, &
"J K^-1") !! Boltzmann constant

type(codata_constant_type), parameter, public :: BOLTZMANN_CONSTANT_IN_EV_K_2014 = &
codata_constant_type("Boltzmann constant in eV/K", &
8.6173303e-5_dp, 0.0000050e-5_dp, &
"eV K^-1") !! Boltzmann constant in eV/K

type(codata_constant_type), parameter, public :: BOLTZMANN_CONSTANT_IN_HZ_K_2014 = &
codata_constant_type("Boltzmann constant in Hz/K", &
2.0836612e10_dp, 0.0000012e10_dp, &
"Hz K^-1") !! Boltzmann constant in Hz/K

type(codata_constant_type), parameter, public :: BOLTZMANN_CONSTANT_IN_INVERSE_METERS_PER_KELVIN_2014 = &
codata_constant_type("Boltzmann constant in inverse meters per kelvin", &
69.503457_dp, 0.000040_dp, &
"m^-1 K^-1") !! Boltzmann constant in inverse meters per kelvin

type(codata_constant_type), parameter, public :: CHARACTERISTIC_IMPEDANCE_OF_VACUUM_2014 = &
codata_constant_type("characteristic impedance of vacuum", &
376.730313461_dp, 0.0_dp, &
"ohm") !! characteristic impedance of vacuum

type(codata_constant_type), parameter, public :: CLASSICAL_ELECTRON_RADIUS_2014 = &
codata_constant_type("classical electron radius", &
2.8179403227e-15_dp, 0.0000000019e-15_dp, &
"m") !! classical electron radius

type(codata_constant_type), parameter, public :: COMPTON_WAVELENGTH_2014 = &
codata_constant_type("Compton wavelength", &
2.4263102367e-12_dp, 0.0000000011e-12_dp, &
"m") !! Compton wavelength

type(codata_constant_type), parameter, public :: COMPTON_WAVELENGTH_OVER_2_PI_2014 = &
codata_constant_type("Compton wavelength over 2 pi", &
386.15926764e-15_dp, 0.00000018e-15_dp, &
"m") !! Compton wavelength over 2 pi

type(codata_constant_type), parameter, public :: CONDUCTANCE_QUANTUM_2014 = &
codata_constant_type("conductance quantum", &
7.7480917310e-5_dp, 0.0000000018e-5_dp, &
"S") !! conductance quantum

type(codata_constant_type), parameter, public :: CONVENTIONAL_VALUE_OF_JOSEPHSON_CONSTANT_2014 = &
codata_constant_type("conventional value of Josephson constant", &
483597.9e9_dp, 0.0_dp, &
"Hz V^-1") !! conventional value of Josephson constant

type(codata_constant_type), parameter, public :: CONVENTIONAL_VALUE_OF_VON_KLITZING_CONSTANT_2014 = &
codata_constant_type("conventional value of von Klitzing constant", &
25812.807_dp, 0.0_dp, &
"ohm") !! conventional value of von Klitzing constant

type(codata_constant_type), parameter, public :: CU_X_UNIT_2014 = &
codata_constant_type("Cu x unit", &
1.00207697e-13_dp, 0.00000028e-13_dp, &
"m") !! Cu x unit

type(codata_constant_type), parameter, public :: DEUTERON_ELECTRON_MAG_MOM_RATIO_2014 = &
codata_constant_type("deuteron-electron mag. mom. ratio", &
-4.664345535e-4_dp, 0.000000026e-4_dp, &
"") !! deuteron-electron mag. mom. ratio

type(codata_constant_type), parameter, public :: DEUTERON_ELECTRON_MASS_RATIO_2014 = &
codata_constant_type("deuteron-electron mass ratio", &
3670.48296785_dp, 0.00000013_dp, &
"") !! deuteron-electron mass ratio

type(codata_constant_type), parameter, public :: DEUTERON_G_FACTOR_2014 = &
codata_constant_type("deuteron g factor", &
0.8574382311_dp, 0.0000000048_dp, &
"") !! deuteron g factor

type(codata_constant_type), parameter, public :: DEUTERON_MAG_MOM_2014 = &
codata_constant_type("deuteron mag. mom.", &
0.4330735040e-26_dp, 0.0000000036e-26_dp, &
"J T^-1") !! deuteron mag. mom.

type(codata_constant_type), parameter, public :: DEUTERON_MAG_MOM_TO_BOHR_MAGNETON_RATIO_2014 = &
codata_constant_type("deuteron mag. mom. to Bohr magneton ratio", &
0.4669754554e-3_dp, 0.0000000026e-3_dp, &
"") !! deuteron mag. mom. to Bohr magneton ratio

type(codata_constant_type), parameter, public :: DEUTERON_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO_2014 = &
codata_constant_type("deuteron mag. mom. to nuclear magneton ratio", &
0.8574382311_dp, 0.0000000048_dp, &
"") !! deuteron mag. mom. to nuclear magneton ratio

type(codata_constant_type), parameter, public :: DEUTERON_MASS_2014 = &
codata_constant_type("deuteron mass", &
3.343583719e-27_dp, 0.000000041e-27_dp, &
"kg") !! deuteron mass

type(codata_constant_type), parameter, public :: DEUTERON_MASS_ENERGY_EQUIVALENT_2014 = &
codata_constant_type("deuteron mass energy equivalent", &
3.005063183e-10_dp, 0.000000037e-10_dp, &
"J") !! deuteron mass energy equivalent

type(codata_constant_type), parameter, public :: DEUTERON_MASS_ENERGY_EQUIVALENT_IN_MEV_2014 = &
codata_constant_type("deuteron mass energy equivalent in MeV", &
1875.612928_dp, 0.000012_dp, &
"MeV") !! deuteron mass energy equivalent in MeV

type(codata_constant_type), parameter, public :: DEUTERON_MASS_IN_U_2014 = &
codata_constant_type("deuteron mass in u", &
2.013553212745_dp, 0.000000000040_dp, &
"u") !! deuteron mass in u

type(codata_constant_type), parameter, public :: DEUTERON_MOLAR_MASS_2014 = &
codata_constant_type("deuteron molar mass", &
2.013553212745e-3_dp, 0.000000000040e-3_dp, &
"kg mol^-1") !! deuteron molar mass

type(codata_constant_type), parameter, public :: DEUTERON_NEUTRON_MAG_MOM_RATIO_2014 = &
codata_constant_type("deuteron-neutron mag. mom. ratio", &
-0.44820652_dp, 0.00000011_dp, &
"") !! deuteron-neutron mag. mom. ratio

type(codata_constant_type), parameter, public :: DEUTERON_PROTON_MAG_MOM_RATIO_2014 = &
codata_constant_type("deuteron-proton mag. mom. ratio", &
0.3070122077_dp, 0.0000000015_dp, &
"") !! deuteron-proton mag. mom. ratio

type(codata_constant_type), parameter, public :: DEUTERON_PROTON_MASS_RATIO_2014 = &
codata_constant_type("deuteron-proton mass ratio", &
1.99900750087_dp, 0.00000000019_dp, &
"") !! deuteron-proton mass ratio

type(codata_constant_type), parameter, public :: DEUTERON_RMS_CHARGE_RADIUS_2014 = &
codata_constant_type("deuteron rms charge radius", &
2.1413e-15_dp, 0.0025e-15_dp, &
"m") !! deuteron rms charge radius

type(codata_constant_type), parameter, public :: ELECTRIC_CONSTANT_2014 = &
codata_constant_type("electric constant", &
8.854187817e-12_dp, 0.0_dp, &
"F m^-1") !! electric constant

type(codata_constant_type), parameter, public :: ELECTRON_CHARGE_TO_MASS_QUOTIENT_2014 = &
codata_constant_type("electron charge to mass quotient", &
-1.758820024e11_dp, 0.000000011e11_dp, &
"C kg^-1") !! electron charge to mass quotient

type(codata_constant_type), parameter, public :: ELECTRON_DEUTERON_MAG_MOM_RATIO_2014 = &
codata_constant_type("electron-deuteron mag. mom. ratio", &
-2143.923499_dp, 0.000012_dp, &
"") !! electron-deuteron mag. mom. ratio

type(codata_constant_type), parameter, public :: ELECTRON_DEUTERON_MASS_RATIO_2014 = &
codata_constant_type("electron-deuteron mass ratio", &
2.724437107484e-4_dp, 0.000000000096e-4_dp, &
"") !! electron-deuteron mass ratio

type(codata_constant_type), parameter, public :: ELECTRON_G_FACTOR_2014 = &
codata_constant_type("electron g factor", &
-2.00231930436182_dp, 0.00000000000052_dp, &
"") !! electron g factor

type(codata_constant_type), parameter, public :: ELECTRON_GYROMAG_RATIO_2014 = &
codata_constant_type("electron gyromag. ratio", &
1.760859644e11_dp, 0.000000011e11_dp, &
"s^-1 T^-1") !! electron gyromag. ratio

type(codata_constant_type), parameter, public :: ELECTRON_GYROMAG_RATIO_OVER_2_PI_2014 = &
codata_constant_type("electron gyromag. ratio over 2 pi", &
28024.95164_dp, 0.00017_dp, &
"MHz T^-1") !! electron gyromag. ratio over 2 pi

type(codata_constant_type), parameter, public :: ELECTRON_HELION_MASS_RATIO_2014 = &
codata_constant_type("electron-helion mass ratio", &
1.819543074854e-4_dp, 0.000000000088e-4_dp, &
"") !! electron-helion mass ratio

type(codata_constant_type), parameter, public :: ELECTRON_MAG_MOM_2014 = &
codata_constant_type("electron mag. mom.", &
-928.4764620e-26_dp, 0.0000057e-26_dp, &
"J T^-1") !! electron mag. mom.

type(codata_constant_type), parameter, public :: ELECTRON_MAG_MOM_ANOMALY_2014 = &
codata_constant_type("electron mag. mom. anomaly", &
1.15965218091e-3_dp, 0.00000000026e-3_dp, &
"") !! electron mag. mom. anomaly

type(codata_constant_type), parameter, public :: ELECTRON_MAG_MOM_TO_BOHR_MAGNETON_RATIO_2014 = &
codata_constant_type("electron mag. mom. to Bohr magneton ratio", &
-1.00115965218091_dp, 0.00000000000026_dp, &
"") !! electron mag. mom. to Bohr magneton ratio

type(codata_constant_type), parameter, public :: ELECTRON_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO_2014 = &
codata_constant_type("electron mag. mom. to nuclear magneton ratio", &
-1838.28197234_dp, 0.00000017_dp, &
"") !! electron mag. mom. to nuclear magneton ratio

type(codata_constant_type), parameter, public :: ELECTRON_MASS_2014 = &
codata_constant_type("electron mass", &
9.10938356e-31_dp, 0.00000011e-31_dp, &
"kg") !! electron mass

type(codata_constant_type), parameter, public :: ELECTRON_MASS_ENERGY_EQUIVALENT_2014 = &
codata_constant_type("electron mass energy equivalent", &
8.18710565e-14_dp, 0.00000010e-14_dp, &
"J") !! electron mass energy equivalent

type(codata_constant_type), parameter, public :: ELECTRON_MASS_ENERGY_EQUIVALENT_IN_MEV_2014 = &
codata_constant_type("electron mass energy equivalent in MeV", &
0.5109989461_dp, 0.0000000031_dp, &
"MeV") !! electron mass energy equivalent in MeV

type(codata_constant_type), parameter, public :: ELECTRON_MASS_IN_U_2014 = &
codata_constant_type("electron mass in u", &
5.48579909070e-4_dp, 0.00000000016e-4_dp, &
"u") !! electron mass in u

type(codata_constant_type), parameter, public :: ELECTRON_MOLAR_MASS_2014 = &
codata_constant_type("electron molar mass", &
5.48579909070e-7_dp, 0.00000000016e-7_dp, &
"kg mol^-1") !! electron molar mass

type(codata_constant_type), parameter, public :: ELECTRON_MUON_MAG_MOM_RATIO_2014 = &
codata_constant_type("electron-muon mag. mom. ratio", &
206.7669880_dp, 0.0000046_dp, &
"") !! electron-muon mag. mom. ratio

type(codata_constant_type), parameter, public :: ELECTRON_MUON_MASS_RATIO_2014 = &
codata_constant_type("electron-muon mass ratio", &
4.83633170e-3_dp, 0.00000011e-3_dp, &
"") !! electron-muon mass ratio

type(codata_constant_type), parameter, public :: ELECTRON_NEUTRON_MAG_MOM_RATIO_2014 = &
codata_constant_type("electron-neutron mag. mom. ratio", &
960.92050_dp, 0.00023_dp, &
"") !! electron-neutron mag. mom. ratio

type(codata_constant_type), parameter, public :: ELECTRON_NEUTRON_MASS_RATIO_2014 = &
codata_constant_type("electron-neutron mass ratio", &
5.4386734428e-4_dp, 0.0000000027e-4_dp, &
"") !! electron-neutron mass ratio

type(codata_constant_type), parameter, public :: ELECTRON_PROTON_MAG_MOM_RATIO_2014 = &
codata_constant_type("electron-proton mag. mom. ratio", &
-658.2106866_dp, 0.0000020_dp, &
"") !! electron-proton mag. mom. ratio

type(codata_constant_type), parameter, public :: ELECTRON_PROTON_MASS_RATIO_2014 = &
codata_constant_type("electron-proton mass ratio", &
5.44617021352e-4_dp, 0.00000000052e-4_dp, &
"") !! electron-proton mass ratio

type(codata_constant_type), parameter, public :: ELECTRON_TAU_MASS_RATIO_2014 = &
codata_constant_type("electron-tau mass ratio", &
2.87592e-4_dp, 0.00026e-4_dp, &
"") !! electron-tau mass ratio

type(codata_constant_type), parameter, public :: ELECTRON_TO_ALPHA_PARTICLE_MASS_RATIO_2014 = &
codata_constant_type("electron to alpha particle mass ratio", &
1.370933554798e-4_dp, 0.000000000045e-4_dp, &
"") !! electron to alpha particle mass ratio

type(codata_constant_type), parameter, public :: ELECTRON_TO_SHIELDED_HELION_MAG_MOM_RATIO_2014 = &
codata_constant_type("electron to shielded helion mag. mom. ratio", &
864.058257_dp, 0.000010_dp, &
"") !! electron to shielded helion mag. mom. ratio

type(codata_constant_type), parameter, public :: ELECTRON_TO_SHIELDED_PROTON_MAG_MOM_RATIO_2014 = &
codata_constant_type("electron to shielded proton mag. mom. ratio", &
-658.2275971_dp, 0.0000072_dp, &
"") !! electron to shielded proton mag. mom. ratio

type(codata_constant_type), parameter, public :: ELECTRON_TRITON_MASS_RATIO_2014 = &
codata_constant_type("electron-triton mass ratio", &
1.819200062203e-4_dp, 0.000000000084e-4_dp, &
"") !! electron-triton mass ratio

type(codata_constant_type), parameter, public :: ELECTRON_VOLT_2014 = &
codata_constant_type("electron volt", &
1.6021766208e-19_dp, 0.0000000098e-19_dp, &
"J") !! electron volt

type(codata_constant_type), parameter, public :: ELECTRON_VOLT_ATOMIC_MASS_UNIT_RELATIONSHIP_2014 = &
codata_constant_type("electron volt-atomic mass unit relationship", &
1.0735441105e-9_dp, 0.0000000066e-9_dp, &
"u") !! electron volt-atomic mass unit relationship

type(codata_constant_type), parameter, public :: ELECTRON_VOLT_HARTREE_RELATIONSHIP_2014 = &
codata_constant_type("electron volt-hartree relationship", &
3.674932248e-2_dp, 0.000000023e-2_dp, &
"E_h") !! electron volt-hartree relationship

type(codata_constant_type), parameter, public :: ELECTRON_VOLT_HERTZ_RELATIONSHIP_2014 = &
codata_constant_type("electron volt-hertz relationship", &
2.417989262e14_dp, 0.000000015e14_dp, &
"Hz") !! electron volt-hertz relationship

type(codata_constant_type), parameter, public :: ELECTRON_VOLT_INVERSE_METER_RELATIONSHIP_2014 = &
codata_constant_type("electron volt-inverse meter relationship", &
8.065544005e5_dp, 0.000000050e5_dp, &
"m^-1") !! electron volt-inverse meter relationship

type(codata_constant_type), parameter, public :: ELECTRON_VOLT_JOULE_RELATIONSHIP_2014 = &
codata_constant_type("electron volt-joule relationship", &
1.6021766208e-19_dp, 0.0000000098e-19_dp, &
"J") !! electron volt-joule relationship

type(codata_constant_type), parameter, public :: ELECTRON_VOLT_KELVIN_RELATIONSHIP_2014 = &
codata_constant_type("electron volt-kelvin relationship", &
1.16045221e4_dp, 0.00000067e4_dp, &
"K") !! electron volt-kelvin relationship

type(codata_constant_type), parameter, public :: ELECTRON_VOLT_KILOGRAM_RELATIONSHIP_2014 = &
codata_constant_type("electron volt-kilogram relationship", &
1.782661907e-36_dp, 0.000000011e-36_dp, &
"kg") !! electron volt-kilogram relationship

type(codata_constant_type), parameter, public :: ELEMENTARY_CHARGE_2014 = &
codata_constant_type("elementary charge", &
1.6021766208e-19_dp, 0.0000000098e-19_dp, &
"C") !! elementary charge

type(codata_constant_type), parameter, public :: ELEMENTARY_CHARGE_OVER_H_2014 = &
codata_constant_type("elementary charge over h", &
2.417989262e14_dp, 0.000000015e14_dp, &
"A J^-1") !! elementary charge over h

type(codata_constant_type), parameter, public :: FARADAY_CONSTANT_2014 = &
codata_constant_type("Faraday constant", &
96485.33289_dp, 0.00059_dp, &
"C mol^-1") !! Faraday constant

type(codata_constant_type), parameter, public :: FARADAY_CONSTANT_FOR_CONVENTIONAL_ELECTRIC_CURRENT_2014 = &
codata_constant_type("Faraday constant for conventional electric current", &
96485.3251_dp, 0.0012_dp, &
"C_90 mol^-1") !! Faraday constant for conventional electric current

type(codata_constant_type), parameter, public :: FERMI_COUPLING_CONSTANT_2014 = &
codata_constant_type("Fermi coupling constant", &
1.1663787e-5_dp, 0.0000006e-5_dp, &
"GeV^-2") !! Fermi coupling constant

type(codata_constant_type), parameter, public :: FINE_STRUCTURE_CONSTANT_2014 = &
codata_constant_type("fine-structure constant", &
7.2973525664e-3_dp, 0.0000000017e-3_dp, &
"") !! fine-structure constant

type(codata_constant_type), parameter, public :: FIRST_RADIATION_CONSTANT_2014 = &
codata_constant_type("first radiation constant", &
3.741771790e-16_dp, 0.000000046e-16_dp, &
"W m^2") !! first radiation constant

type(codata_constant_type), parameter, public :: FIRST_RADIATION_CONSTANT_FOR_SPECTRAL_RADIANCE_2014 = &
codata_constant_type("first radiation constant for spectral radiance", &
1.191042953e-16_dp, 0.000000015e-16_dp, &
"W m^2 sr^-1") !! first radiation constant for spectral radiance

type(codata_constant_type), parameter, public :: HARTREE_ATOMIC_MASS_UNIT_RELATIONSHIP_2014 = &
codata_constant_type("hartree-atomic mass unit relationship", &
2.9212623197e-8_dp, 0.0000000013e-8_dp, &
"u") !! hartree-atomic mass unit relationship

type(codata_constant_type), parameter, public :: HARTREE_ELECTRON_VOLT_RELATIONSHIP_2014 = &
codata_constant_type("hartree-electron volt relationship", &
27.21138602_dp, 0.00000017_dp, &
"eV") !! hartree-electron volt relationship

type(codata_constant_type), parameter, public :: HARTREE_ENERGY_2014 = &
codata_constant_type("Hartree energy", &
4.359744650e-18_dp, 0.000000054e-18_dp, &
"J") !! Hartree energy

type(codata_constant_type), parameter, public :: HARTREE_ENERGY_IN_EV_2014 = &
codata_constant_type("Hartree energy in eV", &
27.21138602_dp, 0.00000017_dp, &
"eV") !! Hartree energy in eV

type(codata_constant_type), parameter, public :: HARTREE_HERTZ_RELATIONSHIP_2014 = &
codata_constant_type("hartree-hertz relationship", &
6.579683920711e15_dp, 0.000000000039e15_dp, &
"Hz") !! hartree-hertz relationship

type(codata_constant_type), parameter, public :: HARTREE_INVERSE_METER_RELATIONSHIP_2014 = &
codata_constant_type("hartree-inverse meter relationship", &
2.194746313702e7_dp, 0.000000000013e7_dp, &
"m^-1") !! hartree-inverse meter relationship

type(codata_constant_type), parameter, public :: HARTREE_JOULE_RELATIONSHIP_2014 = &
codata_constant_type("hartree-joule relationship", &
4.359744650e-18_dp, 0.000000054e-18_dp, &
"J") !! hartree-joule relationship

type(codata_constant_type), parameter, public :: HARTREE_KELVIN_RELATIONSHIP_2014 = &
codata_constant_type("hartree-kelvin relationship", &
3.1577513e5_dp, 0.0000018e5_dp, &
"K") !! hartree-kelvin relationship

type(codata_constant_type), parameter, public :: HARTREE_KILOGRAM_RELATIONSHIP_2014 = &
codata_constant_type("hartree-kilogram relationship", &
4.850870129e-35_dp, 0.000000060e-35_dp, &
"kg") !! hartree-kilogram relationship

type(codata_constant_type), parameter, public :: HELION_ELECTRON_MASS_RATIO_2014 = &
codata_constant_type("helion-electron mass ratio", &
5495.88527922_dp, 0.00000027_dp, &
"") !! helion-electron mass ratio

type(codata_constant_type), parameter, public :: HELION_G_FACTOR_2014 = &
codata_constant_type("helion g factor", &
-4.255250616_dp, 0.000000050_dp, &
"") !! helion g factor

type(codata_constant_type), parameter, public :: HELION_MAG_MOM_2014 = &
codata_constant_type("helion mag. mom.", &
-1.074617522e-26_dp, 0.000000014e-26_dp, &
"J T^-1") !! helion mag. mom.

type(codata_constant_type), parameter, public :: HELION_MAG_MOM_TO_BOHR_MAGNETON_RATIO_2014 = &
codata_constant_type("helion mag. mom. to Bohr magneton ratio", &
-1.158740958e-3_dp, 0.000000014e-3_dp, &
"") !! helion mag. mom. to Bohr magneton ratio

type(codata_constant_type), parameter, public :: HELION_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO_2014 = &
codata_constant_type("helion mag. mom. to nuclear magneton ratio", &
-2.127625308_dp, 0.000000025_dp, &
"") !! helion mag. mom. to nuclear magneton ratio

type(codata_constant_type), parameter, public :: HELION_MASS_2014 = &
codata_constant_type("helion mass", &
5.006412700e-27_dp, 0.000000062e-27_dp, &
"kg") !! helion mass

type(codata_constant_type), parameter, public :: HELION_MASS_ENERGY_EQUIVALENT_2014 = &
codata_constant_type("helion mass energy equivalent", &
4.499539341e-10_dp, 0.000000055e-10_dp, &
"J") !! helion mass energy equivalent

type(codata_constant_type), parameter, public :: HELION_MASS_ENERGY_EQUIVALENT_IN_MEV_2014 = &
codata_constant_type("helion mass energy equivalent in MeV", &
2808.391586_dp, 0.000017_dp, &
"MeV") !! helion mass energy equivalent in MeV

type(codata_constant_type), parameter, public :: HELION_MASS_IN_U_2014 = &
codata_constant_type("helion mass in u", &
3.01493224673_dp, 0.00000000012_dp, &
"u") !! helion mass in u

type(codata_constant_type), parameter, public :: HELION_MOLAR_MASS_2014 = &
codata_constant_type("helion molar mass", &
3.01493224673e-3_dp, 0.00000000012e-3_dp, &
"kg mol^-1") !! helion molar mass

type(codata_constant_type), parameter, public :: HELION_PROTON_MASS_RATIO_2014 = &
codata_constant_type("helion-proton mass ratio", &
2.99315267046_dp, 0.00000000029_dp, &
"") !! helion-proton mass ratio

type(codata_constant_type), parameter, public :: HERTZ_ATOMIC_MASS_UNIT_RELATIONSHIP_2014 = &
codata_constant_type("hertz-atomic mass unit relationship", &
4.4398216616e-24_dp, 0.0000000020e-24_dp, &
"u") !! hertz-atomic mass unit relationship

type(codata_constant_type), parameter, public :: HERTZ_ELECTRON_VOLT_RELATIONSHIP_2014 = &
codata_constant_type("hertz-electron volt relationship", &
4.135667662e-15_dp, 0.000000025e-15_dp, &
"eV") !! hertz-electron volt relationship

type(codata_constant_type), parameter, public :: HERTZ_HARTREE_RELATIONSHIP_2014 = &
codata_constant_type("hertz-hartree relationship", &
1.5198298460088e-16_dp, 0.0000000000090e-16_dp, &
"E_h") !! hertz-hartree relationship

type(codata_constant_type), parameter, public :: HERTZ_INVERSE_METER_RELATIONSHIP_2014 = &
codata_constant_type("hertz-inverse meter relationship", &
3.335640951e-9_dp, 0.0_dp, &
"m^-1") !! hertz-inverse meter relationship

type(codata_constant_type), parameter, public :: HERTZ_JOULE_RELATIONSHIP_2014 = &
codata_constant_type("hertz-joule relationship", &
6.626070040e-34_dp, 0.000000081e-34_dp, &
"J") !! hertz-joule relationship

type(codata_constant_type), parameter, public :: HERTZ_KELVIN_RELATIONSHIP_2014 = &
codata_constant_type("hertz-kelvin relationship", &
4.7992447e-11_dp, 0.0000028e-11_dp, &
"K") !! hertz-kelvin relationship

type(codata_constant_type), parameter, public :: HERTZ_KILOGRAM_RELATIONSHIP_2014 = &
codata_constant_type("hertz-kilogram relationship", &
7.372497201e-51_dp, 0.000000091e-51_dp, &
"kg") !! hertz-kilogram relationship

type(codata_constant_type), parameter, public :: INVERSE_FINE_STRUCTURE_CONSTANT_2014 = &
codata_constant_type("inverse fine-structure constant", &
137.035999139_dp, 0.000000031_dp, &
"") !! inverse fine-structure constant

type(codata_constant_type), parameter, public :: INVERSE_METER_ATOMIC_MASS_UNIT_RELATIONSHIP_2014 = &
codata_constant_type("inverse meter-atomic mass unit relationship", &
1.33102504900e-15_dp, 0.00000000061e-15_dp, &
"u") !! inverse meter-atomic mass unit relationship

type(codata_constant_type), parameter, public :: INVERSE_METER_ELECTRON_VOLT_RELATIONSHIP_2014 = &
codata_constant_type("inverse meter-electron volt relationship", &
1.2398419739e-6_dp, 0.0000000076e-6_dp, &
"eV") !! inverse meter-electron volt relationship

type(codata_constant_type), parameter, public :: INVERSE_METER_HARTREE_RELATIONSHIP_2014 = &
codata_constant_type("inverse meter-hartree relationship", &
4.556335252767e-8_dp, 0.000000000027e-8_dp, &
"E_h") !! inverse meter-hartree relationship

type(codata_constant_type), parameter, public :: INVERSE_METER_HERTZ_RELATIONSHIP_2014 = &
codata_constant_type("inverse meter-hertz relationship", &
299792458_dp, 0.0_dp, &
"Hz") !! inverse meter-hertz relationship

type(codata_constant_type), parameter, public :: INVERSE_METER_JOULE_RELATIONSHIP_2014 = &
codata_constant_type("inverse meter-joule relationship", &
1.986445824e-25_dp, 0.000000024e-25_dp, &
"J") !! inverse meter-joule relationship

type(codata_constant_type), parameter, public :: INVERSE_METER_KELVIN_RELATIONSHIP_2014 = &
codata_constant_type("inverse meter-kelvin relationship", &
1.43877736e-2_dp, 0.00000083e-2_dp, &
"K") !! inverse meter-kelvin relationship

type(codata_constant_type), parameter, public :: INVERSE_METER_KILOGRAM_RELATIONSHIP_2014 = &
codata_constant_type("inverse meter-kilogram relationship", &
2.210219057e-42_dp, 0.000000027e-42_dp, &
"kg") !! inverse meter-kilogram relationship

type(codata_constant_type), parameter, public :: INVERSE_OF_CONDUCTANCE_QUANTUM_2014 = &
codata_constant_type("inverse of conductance quantum", &
12906.4037278_dp, 0.0000029_dp, &
"ohm") !! inverse of conductance quantum

type(codata_constant_type), parameter, public :: JOSEPHSON_CONSTANT_2014 = &
codata_constant_type("Josephson constant", &
483597.8525e9_dp, 0.0030e9_dp, &
"Hz V^-1") !! Josephson constant

type(codata_constant_type), parameter, public :: JOULE_ATOMIC_MASS_UNIT_RELATIONSHIP_2014 = &
codata_constant_type("joule-atomic mass unit relationship", &
6.700535363e9_dp, 0.000000082e9_dp, &
"u") !! joule-atomic mass unit relationship

type(codata_constant_type), parameter, public :: JOULE_ELECTRON_VOLT_RELATIONSHIP_2014 = &
codata_constant_type("joule-electron volt relationship", &
6.241509126e18_dp, 0.000000038e18_dp, &
"eV") !! joule-electron volt relationship

type(codata_constant_type), parameter, public :: JOULE_HARTREE_RELATIONSHIP_2014 = &
codata_constant_type("joule-hartree relationship", &
2.293712317e17_dp, 0.000000028e17_dp, &
"E_h") !! joule-hartree relationship

type(codata_constant_type), parameter, public :: JOULE_HERTZ_RELATIONSHIP_2014 = &
codata_constant_type("joule-hertz relationship", &
1.509190205e33_dp, 0.000000019e33_dp, &
"Hz") !! joule-hertz relationship

type(codata_constant_type), parameter, public :: JOULE_INVERSE_METER_RELATIONSHIP_2014 = &
codata_constant_type("joule-inverse meter relationship", &
5.034116651e24_dp, 0.000000062e24_dp, &
"m^-1") !! joule-inverse meter relationship

type(codata_constant_type), parameter, public :: JOULE_KELVIN_RELATIONSHIP_2014 = &
codata_constant_type("joule-kelvin relationship", &
7.2429731e22_dp, 0.0000042e22_dp, &
"K") !! joule-kelvin relationship

type(codata_constant_type), parameter, public :: JOULE_KILOGRAM_RELATIONSHIP_2014 = &
codata_constant_type("joule-kilogram relationship", &
1.112650056e-17_dp, 0.0_dp, &
"kg") !! joule-kilogram relationship

type(codata_constant_type), parameter, public :: KELVIN_ATOMIC_MASS_UNIT_RELATIONSHIP_2014 = &
codata_constant_type("kelvin-atomic mass unit relationship", &
9.2510842e-14_dp, 0.0000053e-14_dp, &
"u") !! kelvin-atomic mass unit relationship

type(codata_constant_type), parameter, public :: KELVIN_ELECTRON_VOLT_RELATIONSHIP_2014 = &
codata_constant_type("kelvin-electron volt relationship", &
8.6173303e-5_dp, 0.0000050e-5_dp, &
"eV") !! kelvin-electron volt relationship

type(codata_constant_type), parameter, public :: KELVIN_HARTREE_RELATIONSHIP_2014 = &
codata_constant_type("kelvin-hartree relationship", &
3.1668105e-6_dp, 0.0000018e-6_dp, &
"E_h") !! kelvin-hartree relationship

type(codata_constant_type), parameter, public :: KELVIN_HERTZ_RELATIONSHIP_2014 = &
codata_constant_type("kelvin-hertz relationship", &
2.0836612e10_dp, 0.0000012e10_dp, &
"Hz") !! kelvin-hertz relationship

type(codata_constant_type), parameter, public :: KELVIN_INVERSE_METER_RELATIONSHIP_2014 = &
codata_constant_type("kelvin-inverse meter relationship", &
69.503457_dp, 0.000040_dp, &
"m^-1") !! kelvin-inverse meter relationship

type(codata_constant_type), parameter, public :: KELVIN_JOULE_RELATIONSHIP_2014 = &
codata_constant_type("kelvin-joule relationship", &
1.38064852e-23_dp, 0.00000079e-23_dp, &
"J") !! kelvin-joule relationship

type(codata_constant_type), parameter, public :: KELVIN_KILOGRAM_RELATIONSHIP_2014 = &
codata_constant_type("kelvin-kilogram relationship", &
1.53617865e-40_dp, 0.00000088e-40_dp, &
"kg") !! kelvin-kilogram relationship

type(codata_constant_type), parameter, public :: KILOGRAM_ATOMIC_MASS_UNIT_RELATIONSHIP_2014 = &
codata_constant_type("kilogram-atomic mass unit relationship", &
6.022140857e26_dp, 0.000000074e26_dp, &
"u") !! kilogram-atomic mass unit relationship

type(codata_constant_type), parameter, public :: KILOGRAM_ELECTRON_VOLT_RELATIONSHIP_2014 = &
codata_constant_type("kilogram-electron volt relationship", &
5.609588650e35_dp, 0.000000034e35_dp, &
"eV") !! kilogram-electron volt relationship

type(codata_constant_type), parameter, public :: KILOGRAM_HARTREE_RELATIONSHIP_2014 = &
codata_constant_type("kilogram-hartree relationship", &
2.061485823e34_dp, 0.000000025e34_dp, &
"E_h") !! kilogram-hartree relationship

type(codata_constant_type), parameter, public :: KILOGRAM_HERTZ_RELATIONSHIP_2014 = &
codata_constant_type("kilogram-hertz relationship", &
1.356392512e50_dp, 0.000000017e50_dp, &
"Hz") !! kilogram-hertz relationship

type(codata_constant_type), parameter, public :: KILOGRAM_INVERSE_METER_RELATIONSHIP_2014 = &
codata_constant_type("kilogram-inverse meter relationship", &
4.524438411e41_dp, 0.000000056e41_dp, &
"m^-1") !! kilogram-inverse meter relationship

type(codata_constant_type), parameter, public :: KILOGRAM_JOULE_RELATIONSHIP_2014 = &
codata_constant_type("kilogram-joule relationship", &
8.987551787e16_dp, 0.0_dp, &
"J") !! kilogram-joule relationship

type(codata_constant_type), parameter, public :: KILOGRAM_KELVIN_RELATIONSHIP_2014 = &
codata_constant_type("kilogram-kelvin relationship", &
6.5096595e39_dp, 0.0000037e39_dp, &
"K") !! kilogram-kelvin relationship

type(codata_constant_type), parameter, public :: LATTICE_PARAMETER_OF_SILICON_2014 = &
codata_constant_type("lattice parameter of silicon", &
543.1020504e-12_dp, 0.0000089e-12_dp, &
"m") !! lattice parameter of silicon

type(codata_constant_type), parameter, public :: LOSCHMIDT_CONSTANT_273_15_K_100_KPA_2014 = &
codata_constant_type("Loschmidt constant (273.15 K, 100 kPa)", &
2.6516467e25_dp, 0.0000015e25_dp, &
"m^-3") !! Loschmidt constant (273.15 K, 100 kPa)

type(codata_constant_type), parameter, public :: LOSCHMIDT_CONSTANT_273_15_K_101_325_KPA_2014 = &
codata_constant_type("Loschmidt constant (273.15 K, 101.325 kPa)", &
2.6867811e25_dp, 0.0000015e25_dp, &
"m^-3") !! Loschmidt constant (273.15 K, 101.325 kPa)

type(codata_constant_type), parameter, public :: MAG_CONSTANT_2014 = &
codata_constant_type("mag. constant", &
12.566370614e-7_dp, 0.0_dp, &
"N A^-2") !! mag. constant

type(codata_constant_type), parameter, public :: MAG_FLUX_QUANTUM_2014 = &
codata_constant_type("mag. flux quantum", &
2.067833831e-15_dp, 0.000000013e-15_dp, &
"Wb") !! mag. flux quantum

type(codata_constant_type), parameter, public :: MOLAR_GAS_CONSTANT_2014 = &
codata_constant_type("molar gas constant", &
8.3144598_dp, 0.0000048_dp, &
"J mol^-1 K^-1") !! molar gas constant

type(codata_constant_type), parameter, public :: MOLAR_MASS_CONSTANT_2014 = &
codata_constant_type("molar mass constant", &
1e-3_dp, 0.0_dp, &
"kg mol^-1") !! molar mass constant

type(codata_constant_type), parameter, public :: MOLAR_MASS_OF_CARBON_12_2014 = &
codata_constant_type("molar mass of carbon-12", &
12e-3_dp, 0.0_dp, &
"kg mol^-1") !! molar mass of carbon-12

type(codata_constant_type), parameter, public :: MOLAR_PLANCK_CONSTANT_2014 = &
codata_constant_type("molar Planck constant", &
3.9903127110e-10_dp, 0.0000000018e-10_dp, &
"J s mol^-1") !! molar Planck constant

type(codata_constant_type), parameter, public :: MOLAR_PLANCK_CONSTANT_TIMES_C_2014 = &
codata_constant_type("molar Planck constant times c", &
0.119626565582_dp, 0.000000000054_dp, &
"J m mol^-1") !! molar Planck constant times c

type(codata_constant_type), parameter, public :: MOLAR_VOLUME_OF_IDEAL_GAS_273_15_K_100_KPA_2014 = &
codata_constant_type("molar volume of ideal gas (273.15 K, 100 kPa)", &
22.710947e-3_dp, 0.000013e-3_dp, &
"m^3 mol^-1") !! molar volume of ideal gas (273.15 K, 100 kPa)

type(codata_constant_type), parameter, public :: MOLAR_VOLUME_OF_IDEAL_GAS_273_15_K_101_325_KPA_2014 = &
codata_constant_type("molar volume of ideal gas (273.15 K, 101.325 kPa)", &
22.413962e-3_dp, 0.000013e-3_dp, &
"m^3 mol^-1") !! molar volume of ideal gas (273.15 K, 101.325 kPa)

type(codata_constant_type), parameter, public :: MOLAR_VOLUME_OF_SILICON_2014 = &
codata_constant_type("molar volume of silicon", &
12.05883214e-6_dp, 0.00000061e-6_dp, &
"m^3 mol^-1") !! molar volume of silicon

type(codata_constant_type), parameter, public :: MO_X_UNIT_2014 = &
codata_constant_type("Mo x unit", &
1.00209952e-13_dp, 0.00000053e-13_dp, &
"m") !! Mo x unit

type(codata_constant_type), parameter, public :: MUON_COMPTON_WAVELENGTH_2014 = &
codata_constant_type("muon Compton wavelength", &
11.73444111e-15_dp, 0.00000026e-15_dp, &
"m") !! muon Compton wavelength

type(codata_constant_type), parameter, public :: MUON_COMPTON_WAVELENGTH_OVER_2_PI_2014 = &
codata_constant_type("muon Compton wavelength over 2 pi", &
1.867594308e-15_dp, 0.000000042e-15_dp, &
"m") !! muon Compton wavelength over 2 pi

type(codata_constant_type), parameter, public :: MUON_ELECTRON_MASS_RATIO_2014 = &
codata_constant_type("muon-electron mass ratio", &
206.7682826_dp, 0.0000046_dp, &
"") !! muon-electron mass ratio

type(codata_constant_type), parameter, public :: MUON_G_FACTOR_2014 = &
codata_constant_type("muon g factor", &
-2.0023318418_dp, 0.0000000013_dp, &
"") !! muon g factor

type(codata_constant_type), parameter, public :: MUON_MAG_MOM_2014 = &
codata_constant_type("muon mag. mom.", &
-4.49044826e-26_dp, 0.00000010e-26_dp, &
"J T^-1") !! muon mag. mom.

type(codata_constant_type), parameter, public :: MUON_MAG_MOM_ANOMALY_2014 = &
codata_constant_type("muon mag. mom. anomaly", &
1.16592089e-3_dp, 0.00000063e-3_dp, &
"") !! muon mag. mom. anomaly

type(codata_constant_type), parameter, public :: MUON_MAG_MOM_TO_BOHR_MAGNETON_RATIO_2014 = &
codata_constant_type("muon mag. mom. to Bohr magneton ratio", &
-4.84197048e-3_dp, 0.00000011e-3_dp, &
"") !! muon mag. mom. to Bohr magneton ratio

type(codata_constant_type), parameter, public :: MUON_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO_2014 = &
codata_constant_type("muon mag. mom. to nuclear magneton ratio", &
-8.89059705_dp, 0.00000020_dp, &
"") !! muon mag. mom. to nuclear magneton ratio

type(codata_constant_type), parameter, public :: MUON_MASS_2014 = &
codata_constant_type("muon mass", &
1.883531594e-28_dp, 0.000000048e-28_dp, &
"kg") !! muon mass

type(codata_constant_type), parameter, public :: MUON_MASS_ENERGY_EQUIVALENT_2014 = &
codata_constant_type("muon mass energy equivalent", &
1.692833774e-11_dp, 0.000000043e-11_dp, &
"J") !! muon mass energy equivalent

type(codata_constant_type), parameter, public :: MUON_MASS_ENERGY_EQUIVALENT_IN_MEV_2014 = &
codata_constant_type("muon mass energy equivalent in MeV", &
105.6583745_dp, 0.0000024_dp, &
"MeV") !! muon mass energy equivalent in MeV

type(codata_constant_type), parameter, public :: MUON_MASS_IN_U_2014 = &
codata_constant_type("muon mass in u", &
0.1134289257_dp, 0.0000000025_dp, &
"u") !! muon mass in u

type(codata_constant_type), parameter, public :: MUON_MOLAR_MASS_2014 = &
codata_constant_type("muon molar mass", &
0.1134289257e-3_dp, 0.0000000025e-3_dp, &
"kg mol^-1") !! muon molar mass

type(codata_constant_type), parameter, public :: MUON_NEUTRON_MASS_RATIO_2014 = &
codata_constant_type("muon-neutron mass ratio", &
0.1124545167_dp, 0.0000000025_dp, &
"") !! muon-neutron mass ratio

type(codata_constant_type), parameter, public :: MUON_PROTON_MAG_MOM_RATIO_2014 = &
codata_constant_type("muon-proton mag. mom. ratio", &
-3.183345142_dp, 0.000000071_dp, &
"") !! muon-proton mag. mom. ratio

type(codata_constant_type), parameter, public :: MUON_PROTON_MASS_RATIO_2014 = &
codata_constant_type("muon-proton mass ratio", &
0.1126095262_dp, 0.0000000025_dp, &
"") !! muon-proton mass ratio

type(codata_constant_type), parameter, public :: MUON_TAU_MASS_RATIO_2014 = &
codata_constant_type("muon-tau mass ratio", &
5.94649e-2_dp, 0.00054e-2_dp, &
"") !! muon-tau mass ratio

type(codata_constant_type), parameter, public :: NATURAL_UNIT_OF_ACTION_2014 = &
codata_constant_type("natural unit of action", &
1.054571800e-34_dp, 0.000000013e-34_dp, &
"J s") !! natural unit of action

type(codata_constant_type), parameter, public :: NATURAL_UNIT_OF_ACTION_IN_EV_S_2014 = &
codata_constant_type("natural unit of action in eV s", &
6.582119514e-16_dp, 0.000000040e-16_dp, &
"eV s") !! natural unit of action in eV s

type(codata_constant_type), parameter, public :: NATURAL_UNIT_OF_ENERGY_2014 = &
codata_constant_type("natural unit of energy", &
8.18710565e-14_dp, 0.00000010e-14_dp, &
"J") !! natural unit of energy

type(codata_constant_type), parameter, public :: NATURAL_UNIT_OF_ENERGY_IN_MEV_2014 = &
codata_constant_type("natural unit of energy in MeV", &
0.5109989461_dp, 0.0000000031_dp, &
"MeV") !! natural unit of energy in MeV

type(codata_constant_type), parameter, public :: NATURAL_UNIT_OF_LENGTH_2014 = &
codata_constant_type("natural unit of length", &
386.15926764e-15_dp, 0.00000018e-15_dp, &
"m") !! natural unit of length

type(codata_constant_type), parameter, public :: NATURAL_UNIT_OF_MASS_2014 = &
codata_constant_type("natural unit of mass", &
9.10938356e-31_dp, 0.00000011e-31_dp, &
"kg") !! natural unit of mass

type(codata_constant_type), parameter, public :: NATURAL_UNIT_OF_MOMUM_2014 = &
codata_constant_type("natural unit of mom.um", &
2.730924488e-22_dp, 0.000000034e-22_dp, &
"kg m s^-1") !! natural unit of mom.um

type(codata_constant_type), parameter, public :: NATURAL_UNIT_OF_MOMUM_IN_MEV_C_2014 = &
codata_constant_type("natural unit of mom.um in MeV/c", &
0.5109989461_dp, 0.0000000031_dp, &
"MeV/c") !! natural unit of mom.um in MeV/c

type(codata_constant_type), parameter, public :: NATURAL_UNIT_OF_TIME_2014 = &
codata_constant_type("natural unit of time", &
1.28808866712e-21_dp, 0.00000000058e-21_dp, &
"s") !! natural unit of time

type(codata_constant_type), parameter, public :: NATURAL_UNIT_OF_VELOCITY_2014 = &
codata_constant_type("natural unit of velocity", &
299792458_dp, 0.0_dp, &
"m s^-1") !! natural unit of velocity

type(codata_constant_type), parameter, public :: NEUTRON_COMPTON_WAVELENGTH_2014 = &
codata_constant_type("neutron Compton wavelength", &
1.31959090481e-15_dp, 0.00000000088e-15_dp, &
"m") !! neutron Compton wavelength

type(codata_constant_type), parameter, public :: NEUTRON_COMPTON_WAVELENGTH_OVER_2_PI_2014 = &
codata_constant_type("neutron Compton wavelength over 2 pi", &
0.21001941536e-15_dp, 0.00000000014e-15_dp, &
"m") !! neutron Compton wavelength over 2 pi

type(codata_constant_type), parameter, public :: NEUTRON_ELECTRON_MAG_MOM_RATIO_2014 = &
codata_constant_type("neutron-electron mag. mom. ratio", &
1.04066882e-3_dp, 0.00000025e-3_dp, &
"") !! neutron-electron mag. mom. ratio

type(codata_constant_type), parameter, public :: NEUTRON_ELECTRON_MASS_RATIO_2014 = &
codata_constant_type("neutron-electron mass ratio", &
1838.68366158_dp, 0.00000090_dp, &
"") !! neutron-electron mass ratio

type(codata_constant_type), parameter, public :: NEUTRON_G_FACTOR_2014 = &
codata_constant_type("neutron g factor", &
-3.82608545_dp, 0.00000090_dp, &
"") !! neutron g factor

type(codata_constant_type), parameter, public :: NEUTRON_GYROMAG_RATIO_2014 = &
codata_constant_type("neutron gyromag. ratio", &
1.83247172e8_dp, 0.00000043e8_dp, &
"s^-1 T^-1") !! neutron gyromag. ratio

type(codata_constant_type), parameter, public :: NEUTRON_GYROMAG_RATIO_OVER_2_PI_2014 = &
codata_constant_type("neutron gyromag. ratio over 2 pi", &
29.1646933_dp, 0.0000069_dp, &
"MHz T^-1") !! neutron gyromag. ratio over 2 pi

type(codata_constant_type), parameter, public :: NEUTRON_MAG_MOM_2014 = &
codata_constant_type("neutron mag. mom.", &
-0.96623650e-26_dp, 0.00000023e-26_dp, &
"J T^-1") !! neutron mag. mom.

type(codata_constant_type), parameter, public :: NEUTRON_MAG_MOM_TO_BOHR_MAGNETON_RATIO_2014 = &
codata_constant_type("neutron mag. mom. to Bohr magneton ratio", &
-1.04187563e-3_dp, 0.00000025e-3_dp, &
"") !! neutron mag. mom. to Bohr magneton ratio

type(codata_constant_type), parameter, public :: NEUTRON_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO_2014 = &
codata_constant_type("neutron mag. mom. to nuclear magneton ratio", &
-1.91304273_dp, 0.00000045_dp, &
"") !! neutron mag. mom. to nuclear magneton ratio

type(codata_constant_type), parameter, public :: NEUTRON_MASS_2014 = &
codata_constant_type("neutron mass", &
1.674927471e-27_dp, 0.000000021e-27_dp, &
"kg") !! neutron mass

type(codata_constant_type), parameter, public :: NEUTRON_MASS_ENERGY_EQUIVALENT_2014 = &
codata_constant_type("neutron mass energy equivalent", &
1.505349739e-10_dp, 0.000000019e-10_dp, &
"J") !! neutron mass energy equivalent

type(codata_constant_type), parameter, public :: NEUTRON_MASS_ENERGY_EQUIVALENT_IN_MEV_2014 = &
codata_constant_type("neutron mass energy equivalent in MeV", &
939.5654133_dp, 0.0000058_dp, &
"MeV") !! neutron mass energy equivalent in MeV

type(codata_constant_type), parameter, public :: NEUTRON_MASS_IN_U_2014 = &
codata_constant_type("neutron mass in u", &
1.00866491588_dp, 0.00000000049_dp, &
"u") !! neutron mass in u

type(codata_constant_type), parameter, public :: NEUTRON_MOLAR_MASS_2014 = &
codata_constant_type("neutron molar mass", &
1.00866491588e-3_dp, 0.00000000049e-3_dp, &
"kg mol^-1") !! neutron molar mass

type(codata_constant_type), parameter, public :: NEUTRON_MUON_MASS_RATIO_2014 = &
codata_constant_type("neutron-muon mass ratio", &
8.89248408_dp, 0.00000020_dp, &
"") !! neutron-muon mass ratio

type(codata_constant_type), parameter, public :: NEUTRON_PROTON_MAG_MOM_RATIO_2014 = &
codata_constant_type("neutron-proton mag. mom. ratio", &
-0.68497934_dp, 0.00000016_dp, &
"") !! neutron-proton mag. mom. ratio

type(codata_constant_type), parameter, public :: NEUTRON_PROTON_MASS_DIFFERENCE_2014 = &
codata_constant_type("neutron-proton mass difference", &
2.30557377e-30_dp, 0.00000085e-30_dp, &
"") !! neutron-proton mass difference

type(codata_constant_type), parameter, public :: NEUTRON_PROTON_MASS_DIFFERENCE_ENERGY_EQUIVALENT_2014 = &
codata_constant_type("neutron-proton mass difference energy equivalent", &
2.07214637e-13_dp, 0.00000076e-13_dp, &
"") !! neutron-proton mass difference energy equivalent

type(codata_constant_type), parameter, public :: NEUTRON_PROTON_MASS_DIFFERENCE_ENERGY_EQUIVALENT_IN_MEV_2014 = &
codata_constant_type("neutron-proton mass difference energy equivalent in MeV", &
1.29333205_dp, 0.00000048_dp, &
"") !! neutron-proton mass difference energy equivalent in MeV

type(codata_constant_type), parameter, public :: NEUTRON_PROTON_MASS_DIFFERENCE_IN_U_2014 = &
codata_constant_type("neutron-proton mass difference in u", &
0.00138844900_dp, 0.00000000051_dp, &
"") !! neutron-proton mass difference in u

type(codata_constant_type), parameter, public :: NEUTRON_PROTON_MASS_RATIO_2014 = &
codata_constant_type("neutron-proton mass ratio", &
1.00137841898_dp, 0.00000000051_dp, &
"") !! neutron-proton mass ratio

type(codata_constant_type), parameter, public :: NEUTRON_TAU_MASS_RATIO_2014 = &
codata_constant_type("neutron-tau mass ratio", &
0.528790_dp, 0.000048_dp, &
"") !! neutron-tau mass ratio

type(codata_constant_type), parameter, public :: NEUTRON_TO_SHIELDED_PROTON_MAG_MOM_RATIO_2014 = &
codata_constant_type("neutron to shielded proton mag. mom. ratio", &
-0.68499694_dp, 0.00000016_dp, &
"") !! neutron to shielded proton mag. mom. ratio

type(codata_constant_type), parameter, public :: NEWTONIAN_CONSTANT_OF_GRAVITATION_2014 = &
codata_constant_type("Newtonian constant of gravitation", &
6.67408e-11_dp, 0.00031e-11_dp, &
"m^3 kg^-1 s^-2") !! Newtonian constant of gravitation

type(codata_constant_type), parameter, public :: NEWTONIAN_CONSTANT_OF_GRAVITATION_OVER_H_BAR_C_2014 = &
codata_constant_type("Newtonian constant of gravitation over h-bar c", &
6.70861e-39_dp, 0.00031e-39_dp, &
"(GeV/c^2)^-2") !! Newtonian constant of gravitation over h-bar c

type(codata_constant_type), parameter, public :: NUCLEAR_MAGNETON_2014 = &
codata_constant_type("nuclear magneton", &
5.050783699e-27_dp, 0.000000031e-27_dp, &
"J T^-1") !! nuclear magneton

type(codata_constant_type), parameter, public :: NUCLEAR_MAGNETON_IN_EV_T_2014 = &
codata_constant_type("nuclear magneton in eV/T", &
3.1524512550e-8_dp, 0.0000000015e-8_dp, &
"eV T^-1") !! nuclear magneton in eV/T

type(codata_constant_type), parameter, public :: NUCLEAR_MAGNETON_IN_INVERSE_METERS_PER_TESLA_2014 = &
codata_constant_type("nuclear magneton in inverse meters per tesla", &
2.542623432e-2_dp, 0.000000016e-2_dp, &
"m^-1 T^-1") !! nuclear magneton in inverse meters per tesla

type(codata_constant_type), parameter, public :: NUCLEAR_MAGNETON_IN_K_T_2014 = &
codata_constant_type("nuclear magneton in K/T", &
3.6582690e-4_dp, 0.0000021e-4_dp, &
"K T^-1") !! nuclear magneton in K/T

type(codata_constant_type), parameter, public :: NUCLEAR_MAGNETON_IN_MHZ_T_2014 = &
codata_constant_type("nuclear magneton in MHz/T", &
7.622593285_dp, 0.000000047_dp, &
"MHz T^-1") !! nuclear magneton in MHz/T

type(codata_constant_type), parameter, public :: PLANCK_CONSTANT_2014 = &
codata_constant_type("Planck constant", &
6.626070040e-34_dp, 0.000000081e-34_dp, &
"J s") !! Planck constant

type(codata_constant_type), parameter, public :: PLANCK_CONSTANT_IN_EV_S_2014 = &
codata_constant_type("Planck constant in eV s", &
4.135667662e-15_dp, 0.000000025e-15_dp, &
"eV s") !! Planck constant in eV s

type(codata_constant_type), parameter, public :: PLANCK_CONSTANT_OVER_2_PI_2014 = &
codata_constant_type("Planck constant over 2 pi", &
1.054571800e-34_dp, 0.000000013e-34_dp, &
"J s") !! Planck constant over 2 pi

type(codata_constant_type), parameter, public :: PLANCK_CONSTANT_OVER_2_PI_IN_EV_S_2014 = &
codata_constant_type("Planck constant over 2 pi in eV s", &
6.582119514e-16_dp, 0.000000040e-16_dp, &
"eV s") !! Planck constant over 2 pi in eV s

type(codata_constant_type), parameter, public :: PLANCK_CONSTANT_OVER_2_PI_TIMES_C_IN_MEV_FM_2014 = &
codata_constant_type("Planck constant over 2 pi times c in MeV fm", &
197.3269788_dp, 0.0000012_dp, &
"MeV fm") !! Planck constant over 2 pi times c in MeV fm

type(codata_constant_type), parameter, public :: PLANCK_LENGTH_2014 = &
codata_constant_type("Planck length", &
1.616229e-35_dp, 0.000038e-35_dp, &
"m") !! Planck length

type(codata_constant_type), parameter, public :: PLANCK_MASS_2014 = &
codata_constant_type("Planck mass", &
2.176470e-8_dp, 0.000051e-8_dp, &
"kg") !! Planck mass

type(codata_constant_type), parameter, public :: PLANCK_MASS_ENERGY_EQUIVALENT_IN_GEV_2014 = &
codata_constant_type("Planck mass energy equivalent in GeV", &
1.220910e19_dp, 0.000029e19_dp, &
"GeV") !! Planck mass energy equivalent in GeV

type(codata_constant_type), parameter, public :: PLANCK_TEMPERATURE_2014 = &
codata_constant_type("Planck temperature", &
1.416808e32_dp, 0.000033e32_dp, &
"K") !! Planck temperature

type(codata_constant_type), parameter, public :: PLANCK_TIME_2014 = &
codata_constant_type("Planck time", &
5.39116e-44_dp, 0.00013e-44_dp, &
"s") !! Planck time

type(codata_constant_type), parameter, public :: PROTON_CHARGE_TO_MASS_QUOTIENT_2014 = &
codata_constant_type("proton charge to mass quotient", &
9.578833226e7_dp, 0.000000059e7_dp, &
"C kg^-1") !! proton charge to mass quotient

type(codata_constant_type), parameter, public :: PROTON_COMPTON_WAVELENGTH_2014 = &
codata_constant_type("proton Compton wavelength", &
1.32140985396e-15_dp, 0.00000000061e-15_dp, &
"m") !! proton Compton wavelength

type(codata_constant_type), parameter, public :: PROTON_COMPTON_WAVELENGTH_OVER_2_PI_2014 = &
codata_constant_type("proton Compton wavelength over 2 pi", &
0.210308910109e-15_dp, 0.000000000097e-15_dp, &
"m") !! proton Compton wavelength over 2 pi

type(codata_constant_type), parameter, public :: PROTON_ELECTRON_MASS_RATIO_2014 = &
codata_constant_type("proton-electron mass ratio", &
1836.15267389_dp, 0.00000017_dp, &
"") !! proton-electron mass ratio

type(codata_constant_type), parameter, public :: PROTON_G_FACTOR_2014 = &
codata_constant_type("proton g factor", &
5.585694702_dp, 0.000000017_dp, &
"") !! proton g factor

type(codata_constant_type), parameter, public :: PROTON_GYROMAG_RATIO_2014 = &
codata_constant_type("proton gyromag. ratio", &
2.675221900e8_dp, 0.000000018e8_dp, &
"s^-1 T^-1") !! proton gyromag. ratio

type(codata_constant_type), parameter, public :: PROTON_GYROMAG_RATIO_OVER_2_PI_2014 = &
codata_constant_type("proton gyromag. ratio over 2 pi", &
42.57747892_dp, 0.00000029_dp, &
"MHz T^-1") !! proton gyromag. ratio over 2 pi

type(codata_constant_type), parameter, public :: PROTON_MAG_MOM_2014 = &
codata_constant_type("proton mag. mom.", &
1.4106067873e-26_dp, 0.0000000097e-26_dp, &
"J T^-1") !! proton mag. mom.

type(codata_constant_type), parameter, public :: PROTON_MAG_MOM_TO_BOHR_MAGNETON_RATIO_2014 = &
codata_constant_type("proton mag. mom. to Bohr magneton ratio", &
1.5210322053e-3_dp, 0.0000000046e-3_dp, &
"") !! proton mag. mom. to Bohr magneton ratio

type(codata_constant_type), parameter, public :: PROTON_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO_2014 = &
codata_constant_type("proton mag. mom. to nuclear magneton ratio", &
2.7928473508_dp, 0.0000000085_dp, &
"") !! proton mag. mom. to nuclear magneton ratio

type(codata_constant_type), parameter, public :: PROTON_MAG_SHIELDING_CORRECTION_2014 = &
codata_constant_type("proton mag. shielding correction", &
25.691e-6_dp, 0.011e-6_dp, &
"") !! proton mag. shielding correction

type(codata_constant_type), parameter, public :: PROTON_MASS_2014 = &
codata_constant_type("proton mass", &
1.672621898e-27_dp, 0.000000021e-27_dp, &
"kg") !! proton mass

type(codata_constant_type), parameter, public :: PROTON_MASS_ENERGY_EQUIVALENT_2014 = &
codata_constant_type("proton mass energy equivalent", &
1.503277593e-10_dp, 0.000000018e-10_dp, &
"J") !! proton mass energy equivalent

type(codata_constant_type), parameter, public :: PROTON_MASS_ENERGY_EQUIVALENT_IN_MEV_2014 = &
codata_constant_type("proton mass energy equivalent in MeV", &
938.2720813_dp, 0.0000058_dp, &
"MeV") !! proton mass energy equivalent in MeV

type(codata_constant_type), parameter, public :: PROTON_MASS_IN_U_2014 = &
codata_constant_type("proton mass in u", &
1.007276466879_dp, 0.000000000091_dp, &
"u") !! proton mass in u

type(codata_constant_type), parameter, public :: PROTON_MOLAR_MASS_2014 = &
codata_constant_type("proton molar mass", &
1.007276466879e-3_dp, 0.000000000091e-3_dp, &
"kg mol^-1") !! proton molar mass

type(codata_constant_type), parameter, public :: PROTON_MUON_MASS_RATIO_2014 = &
codata_constant_type("proton-muon mass ratio", &
8.88024338_dp, 0.00000020_dp, &
"") !! proton-muon mass ratio

type(codata_constant_type), parameter, public :: PROTON_NEUTRON_MAG_MOM_RATIO_2014 = &
codata_constant_type("proton-neutron mag. mom. ratio", &
-1.45989805_dp, 0.00000034_dp, &
"") !! proton-neutron mag. mom. ratio

type(codata_constant_type), parameter, public :: PROTON_NEUTRON_MASS_RATIO_2014 = &
codata_constant_type("proton-neutron mass ratio", &
0.99862347844_dp, 0.00000000051_dp, &
"") !! proton-neutron mass ratio

type(codata_constant_type), parameter, public :: PROTON_RMS_CHARGE_RADIUS_2014 = &
codata_constant_type("proton rms charge radius", &
0.8751e-15_dp, 0.0061e-15_dp, &
"m") !! proton rms charge radius

type(codata_constant_type), parameter, public :: PROTON_TAU_MASS_RATIO_2014 = &
codata_constant_type("proton-tau mass ratio", &
0.528063_dp, 0.000048_dp, &
"") !! proton-tau mass ratio

type(codata_constant_type), parameter, public :: QUANTUM_OF_CIRCULATION_2014 = &
codata_constant_type("quantum of circulation", &
3.6369475486e-4_dp, 0.0000000017e-4_dp, &
"m^2 s^-1") !! quantum of circulation

type(codata_constant_type), parameter, public :: QUANTUM_OF_CIRCULATION_TIMES_2_2014 = &
codata_constant_type("quantum of circulation times 2", &
7.2738950972e-4_dp, 0.0000000033e-4_dp, &
"m^2 s^-1") !! quantum of circulation times 2

type(codata_constant_type), parameter, public :: RYDBERG_CONSTANT_2014 = &
codata_constant_type("Rydberg constant", &
10973731.568508_dp, 0.000065_dp, &
"m^-1") !! Rydberg constant

type(codata_constant_type), parameter, public :: RYDBERG_CONSTANT_TIMES_C_IN_HZ_2014 = &
codata_constant_type("Rydberg constant times c in Hz", &
3.289841960355e15_dp, 0.000000000019e15_dp, &
"Hz") !! Rydberg constant times c in Hz

type(codata_constant_type), parameter, public :: RYDBERG_CONSTANT_TIMES_HC_IN_EV_2014 = &
codata_constant_type("Rydberg constant times hc in eV", &
13.605693009_dp, 0.000000084_dp, &
"eV") !! Rydberg constant times hc in eV

type(codata_constant_type), parameter, public :: RYDBERG_CONSTANT_TIMES_HC_IN_J_2014 = &
codata_constant_type("Rydberg constant times hc in J", &
2.179872325e-18_dp, 0.000000027e-18_dp, &
"J") !! Rydberg constant times hc in J

type(codata_constant_type), parameter, public :: SACKUR_TETRODE_CONSTANT_1_K_100_KPA_2014 = &
codata_constant_type("Sackur-Tetrode constant (1 K, 100 kPa)", &
-1.1517084_dp, 0.0000014_dp, &
"") !! Sackur-Tetrode constant (1 K, 100 kPa)

type(codata_constant_type), parameter, public :: SACKUR_TETRODE_CONSTANT_1_K_101_325_KPA_2014 = &
codata_constant_type("Sackur-Tetrode constant (1 K, 101.325 kPa)", &
-1.1648714_dp, 0.0000014_dp, &
"") !! Sackur-Tetrode constant (1 K, 101.325 kPa)

type(codata_constant_type), parameter, public :: SECOND_RADIATION_CONSTANT_2014 = &
codata_constant_type("second radiation constant", &
1.43877736e-2_dp, 0.00000083e-2_dp, &
"m K") !! second radiation constant

type(codata_constant_type), parameter, public :: SHIELDED_HELION_GYROMAG_RATIO_2014 = &
codata_constant_type("shielded helion gyromag. ratio", &
2.037894585e8_dp, 0.000000027e8_dp, &
"s^-1 T^-1") !! shielded helion gyromag. ratio

type(codata_constant_type), parameter, public :: SHIELDED_HELION_GYROMAG_RATIO_OVER_2_PI_2014 = &
codata_constant_type("shielded helion gyromag. ratio over 2 pi", &
32.43409966_dp, 0.00000043_dp, &
"MHz T^-1") !! shielded helion gyromag. ratio over 2 pi

type(codata_constant_type), parameter, public :: SHIELDED_HELION_MAG_MOM_2014 = &
codata_constant_type("shielded helion mag. mom.", &
-1.074553080e-26_dp, 0.000000014e-26_dp, &
"J T^-1") !! shielded helion mag. mom.

type(codata_constant_type), parameter, public :: SHIELDED_HELION_MAG_MOM_TO_BOHR_MAGNETON_RATIO_2014 = &
codata_constant_type("shielded helion mag. mom. to Bohr magneton ratio", &
-1.158671471e-3_dp, 0.000000014e-3_dp, &
"") !! shielded helion mag. mom. to Bohr magneton ratio

type(codata_constant_type), parameter, public :: SHIELDED_HELION_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO_2014 = &
codata_constant_type("shielded helion mag. mom. to nuclear magneton ratio", &
-2.127497720_dp, 0.000000025_dp, &
"") !! shielded helion mag. mom. to nuclear magneton ratio

type(codata_constant_type), parameter, public :: SHIELDED_HELION_TO_PROTON_MAG_MOM_RATIO_2014 = &
codata_constant_type("shielded helion to proton mag. mom. ratio", &
-0.7617665603_dp, 0.0000000092_dp, &
"") !! shielded helion to proton mag. mom. ratio

type(codata_constant_type), parameter, public :: SHIELDED_HELION_TO_SHIELDED_PROTON_MAG_MOM_RATIO_2014 = &
codata_constant_type("shielded helion to shielded proton mag. mom. ratio", &
-0.7617861313_dp, 0.0000000033_dp, &
"") !! shielded helion to shielded proton mag. mom. ratio

type(codata_constant_type), parameter, public :: SHIELDED_PROTON_GYROMAG_RATIO_2014 = &
codata_constant_type("shielded proton gyromag. ratio", &
2.675153171e8_dp, 0.000000033e8_dp, &
"s^-1 T^-1") !! shielded proton gyromag. ratio

type(codata_constant_type), parameter, public :: SHIELDED_PROTON_GYROMAG_RATIO_OVER_2_PI_2014 = &
codata_constant_type("shielded proton gyromag. ratio over 2 pi", &
42.57638507_dp, 0.00000053_dp, &
"MHz T^-1") !! shielded proton gyromag. ratio over 2 pi

type(codata_constant_type), parameter, public :: SHIELDED_PROTON_MAG_MOM_2014 = &
codata_constant_type("shielded proton mag. mom.", &
1.410570547e-26_dp, 0.000000018e-26_dp, &
"J T^-1") !! shielded proton mag. mom.

type(codata_constant_type), parameter, public :: SHIELDED_PROTON_MAG_MOM_TO_BOHR_MAGNETON_RATIO_2014 = &
codata_constant_type("shielded proton mag. mom. to Bohr magneton ratio", &
1.520993128e-3_dp, 0.000000017e-3_dp, &
"") !! shielded proton mag. mom. to Bohr magneton ratio

type(codata_constant_type), parameter, public :: SHIELDED_PROTON_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO_2014 = &
codata_constant_type("shielded proton mag. mom. to nuclear magneton ratio", &
2.792775600_dp, 0.000000030_dp, &
"") !! shielded proton mag. mom. to nuclear magneton ratio

type(codata_constant_type), parameter, public :: SPEED_OF_LIGHT_IN_VACUUM_2014 = &
codata_constant_type("speed of light in vacuum", &
299792458_dp, 0.0_dp, &
"m s^-1") !! speed of light in vacuum

type(codata_constant_type), parameter, public :: STANDARD_ACCELERATION_OF_GRAVITY_2014 = &
codata_constant_type("standard acceleration of gravity", &
9.80665_dp, 0.0_dp, &
"m s^-2") !! standard acceleration of gravity

type(codata_constant_type), parameter, public :: STANDARD_ATMOSPHERE_2014 = &
codata_constant_type("standard atmosphere", &
101325_dp, 0.0_dp, &
"Pa") !! standard atmosphere

type(codata_constant_type), parameter, public :: STANDARD_STATE_PRESSURE_2014 = &
codata_constant_type("standard-state pressure", &
100000_dp, 0.0_dp, &
"Pa") !! standard-state pressure

type(codata_constant_type), parameter, public :: STEFAN_BOLTZMANN_CONSTANT_2014 = &
codata_constant_type("Stefan-Boltzmann constant", &
5.670367e-8_dp, 0.000013e-8_dp, &
"W m^-2 K^-4") !! Stefan-Boltzmann constant

type(codata_constant_type), parameter, public :: TAU_COMPTON_WAVELENGTH_2014 = &
codata_constant_type("tau Compton wavelength", &
0.697787e-15_dp, 0.000063e-15_dp, &
"m") !! tau Compton wavelength

type(codata_constant_type), parameter, public :: TAU_COMPTON_WAVELENGTH_OVER_2_PI_2014 = &
codata_constant_type("tau Compton wavelength over 2 pi", &
0.111056e-15_dp, 0.000010e-15_dp, &
"m") !! tau Compton wavelength over 2 pi

type(codata_constant_type), parameter, public :: TAU_ELECTRON_MASS_RATIO_2014 = &
codata_constant_type("tau-electron mass ratio", &
3477.15_dp, 0.31_dp, &
"") !! tau-electron mass ratio

type(codata_constant_type), parameter, public :: TAU_MASS_2014 = &
codata_constant_type("tau mass", &
3.16747e-27_dp, 0.00029e-27_dp, &
"kg") !! tau mass

type(codata_constant_type), parameter, public :: TAU_MASS_ENERGY_EQUIVALENT_2014 = &
codata_constant_type("tau mass energy equivalent", &
2.84678e-10_dp, 0.00026e-10_dp, &
"J") !! tau mass energy equivalent

type(codata_constant_type), parameter, public :: TAU_MASS_ENERGY_EQUIVALENT_IN_MEV_2014 = &
codata_constant_type("tau mass energy equivalent in MeV", &
1776.82_dp, 0.16_dp, &
"MeV") !! tau mass energy equivalent in MeV

type(codata_constant_type), parameter, public :: TAU_MASS_IN_U_2014 = &
codata_constant_type("tau mass in u", &
1.90749_dp, 0.00017_dp, &
"u") !! tau mass in u

type(codata_constant_type), parameter, public :: TAU_MOLAR_MASS_2014 = &
codata_constant_type("tau molar mass", &
1.90749e-3_dp, 0.00017e-3_dp, &
"kg mol^-1") !! tau molar mass

type(codata_constant_type), parameter, public :: TAU_MUON_MASS_RATIO_2014 = &
codata_constant_type("tau-muon mass ratio", &
16.8167_dp, 0.0015_dp, &
"") !! tau-muon mass ratio

type(codata_constant_type), parameter, public :: TAU_NEUTRON_MASS_RATIO_2014 = &
codata_constant_type("tau-neutron mass ratio", &
1.89111_dp, 0.00017_dp, &
"") !! tau-neutron mass ratio

type(codata_constant_type), parameter, public :: TAU_PROTON_MASS_RATIO_2014 = &
codata_constant_type("tau-proton mass ratio", &
1.89372_dp, 0.00017_dp, &
"") !! tau-proton mass ratio

type(codata_constant_type), parameter, public :: THOMSON_CROSS_SECTION_2014 = &
codata_constant_type("Thomson cross section", &
0.66524587158e-28_dp, 0.00000000091e-28_dp, &
"m^2") !! Thomson cross section

type(codata_constant_type), parameter, public :: TRITON_ELECTRON_MASS_RATIO_2014 = &
codata_constant_type("triton-electron mass ratio", &
5496.92153588_dp, 0.00000026_dp, &
"") !! triton-electron mass ratio

type(codata_constant_type), parameter, public :: TRITON_G_FACTOR_2014 = &
codata_constant_type("triton g factor", &
5.957924920_dp, 0.000000028_dp, &
"") !! triton g factor

type(codata_constant_type), parameter, public :: TRITON_MAG_MOM_2014 = &
codata_constant_type("triton mag. mom.", &
1.504609503e-26_dp, 0.000000012e-26_dp, &
"J T^-1") !! triton mag. mom.

type(codata_constant_type), parameter, public :: TRITON_MAG_MOM_TO_BOHR_MAGNETON_RATIO_2014 = &
codata_constant_type("triton mag. mom. to Bohr magneton ratio", &
1.6223936616e-3_dp, 0.0000000076e-3_dp, &
"") !! triton mag. mom. to Bohr magneton ratio

type(codata_constant_type), parameter, public :: TRITON_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO_2014 = &
codata_constant_type("triton mag. mom. to nuclear magneton ratio", &
2.978962460_dp, 0.000000014_dp, &
"") !! triton mag. mom. to nuclear magneton ratio

type(codata_constant_type), parameter, public :: TRITON_MASS_2014 = &
codata_constant_type("triton mass", &
5.007356665e-27_dp, 0.000000062e-27_dp, &
"kg") !! triton mass

type(codata_constant_type), parameter, public :: TRITON_MASS_ENERGY_EQUIVALENT_2014 = &
codata_constant_type("triton mass energy equivalent", &
4.500387735e-10_dp, 0.000000055e-10_dp, &
"J") !! triton mass energy equivalent

type(codata_constant_type), parameter, public :: TRITON_MASS_ENERGY_EQUIVALENT_IN_MEV_2014 = &
codata_constant_type("triton mass energy equivalent in MeV", &
2808.921112_dp, 0.000017_dp, &
"MeV") !! triton mass energy equivalent in MeV

type(codata_constant_type), parameter, public :: TRITON_MASS_IN_U_2014 = &
codata_constant_type("triton mass in u", &
3.01550071632_dp, 0.00000000011_dp, &
"u") !! triton mass in u

type(codata_constant_type), parameter, public :: TRITON_MOLAR_MASS_2014 = &
codata_constant_type("triton molar mass", &
3.01550071632e-3_dp, 0.00000000011e-3_dp, &
"kg mol^-1") !! triton molar mass

type(codata_constant_type), parameter, public :: TRITON_PROTON_MASS_RATIO_2014 = &
codata_constant_type("triton-proton mass ratio", &
2.99371703348_dp, 0.00000000022_dp, &
"") !! triton-proton mass ratio

type(codata_constant_type), parameter, public :: UNIFIED_ATOMIC_MASS_UNIT_2014 = &
codata_constant_type("unified atomic mass unit", &
1.660539040e-27_dp, 0.000000020e-27_dp, &
"kg") !! unified atomic mass unit

type(codata_constant_type), parameter, public :: VON_KLITZING_CONSTANT_2014 = &
codata_constant_type("von Klitzing constant", &
25812.8074555_dp, 0.0000059_dp, &
"ohm") !! von Klitzing constant

type(codata_constant_type), parameter, public :: WEAK_MIXING_ANGLE_2014 = &
codata_constant_type("weak mixing angle", &
0.2223_dp, 0.0021_dp, &
"") !! weak mixing angle

type(codata_constant_type), parameter, public :: WIEN_FREQUENCY_DISPLACEMENT_LAW_CONSTANT_2014 = &
codata_constant_type("Wien frequency displacement law constant", &
5.8789238e10_dp, 0.0000034e10_dp, &
"Hz K^-1") !! Wien frequency displacement law constant

type(codata_constant_type), parameter, public :: WIEN_WAVELENGTH_DISPLACEMENT_LAW_CONSTANT_2014 = &
codata_constant_type("Wien wavelength displacement law constant", &
2.8977729e-3_dp, 0.0000017e-3_dp, &
"m K") !! Wien wavelength displacement law constant

end module codata__constants_2014