! NAME
!     codata - Fundamental physical constants.
! SYNOPSIS
!     use codata (Fortran)
!     #include "codata.h" (C)
!     import pycodata (Python)
! DESCRIPTION
!     codata is a Fortran library providing the fundamental physical constants
!     according to CODATA.
!     A C API allows usage from C, or can be used as a basis for other wrappers.
!     Python wrapper allows easy usage from Python.
! 
!     The latest codata constants were released in 2022.
!     All values for the codata constants are provided as double precision reals in
!     a derived type codata_constant_type.
!     The names are quite long and can be aliased with shorter names.
!     A module level interface to\_real is available for getting the constant value
!     or uncertainty of a constant.
! 
!     The latest values (2022) do not have the year as a suffix in their name.
!     Older values can be used and they feature the year as a suffix in their name.
! 
! EXAMPLE
!     Minimal example in Fortran.
! 
!         program example_in_f
!         use iso_fortran_env
!         use codata
!         implicit none
! 
!         print '(A)', '########## EXAMPLE IN FORTRAN ##########'
! 
!         print '(A)', '# VERSION'
!         print *, "version = ", get_version()
! 
!         print '(A)', '# CONSTANTS'
!         print *, "c = ",  SPEED_OF_LIGHT_IN_VACUUM%value
! 
!         print '(A)', '# UNCERTAINTY'
!         print *, "u(c) = ", SPEED_OF_LIGHT_IN_VACUUM%uncertainty
! 
!         print '(A)', '# OLDER VALUES'
!         print '(A, F23.16)', "Mu_2022(latest) = ", MOLAR_MASS_CONSTANT%value
!         print '(A, F23.16)', "Mu_2018 = ", MOLAR_MASS_CONSTANT_2018%value
!         print '(A, F23.16)', "Mu_2014 = ",  MOLAR_MASS_CONSTANT_2014%value
!         print '(A, F23.16)', "Mu_2010 = ",  MOLAR_MASS_CONSTANT_2010%value
!         end program
! 
!     Minimal example in C.
! 
!         #include <stdio.h>
!         #include "codata.h"
! 
!         int main(void){
! 
!         printf("########## EXAMPLE IN C ##########\n");
! 
!         printf("%s\n","# VERSION");
!         printf("version = %s\n", codata_get_version());
! 
!         printf("%s\n","# CONSTANTS");
!         printf("c = %f\n", SPEED_OF_LIGHT_IN_VACUUM.value);
! 
!         printf("%s\n","# UNCERTAINTY");
!         printf("u(c) = %f\n", SPEED_OF_LIGHT_IN_VACUUM.uncertainty);
! 
!         printf("%s\n","# OLDER VALUES");
!         printf("Mu_2022(latest) = %23.16f\n", MOLAR_MASS_CONSTANT.value);
!         printf("Mu_2018 = %23.16f\n", MOLAR_MASS_CONSTANT_2018.value);
!         printf("Mu_2014 = %23.16f\n", MOLAR_MASS_CONSTANT_2014.value);
!         printf("Mu_2010 = %23.16f\n", MOLAR_MASS_CONSTANT_2010.value);
! 
!         return 0;
!         }
! 
!     Minimal example in Python
! 
!         r"""EXAMPLE in PYTHON"""
!         import sys
!         sys.path.insert(0, "../py/src/")
!         import pycodata
! 
!         print("########## EXAMPLE IN PYTHON ##########")
!         print("# VERSION")
!         print(f"version = {pycodata.__version__}")
! 
!         print("# Constants")
!         print(f"c =", pycodata.SPEED_OF_LIGHT_IN_VACUUM["value"])
! 
!         print("# UNCERTAINTY")
!         print(f"u(c) = ", pycodata.SPEED_OF_LIGHT_IN_VACUUM["uncertainty"])
! 
!         print("# OLDER VALUES")
!         print(f"Mu_2022 = ", pycodata.MOLAR_MASS_CONSTANT["value"])
!         print(f"Mu_2018 = ", pycodata.constants_2018.MOLAR_MASS_CONSTANT_2018["value"])
!         print(f"Mu_2014 = ", pycodata.constants_2014.MOLAR_MASS_CONSTANT_2014["value"])
!         print(f"Mu_2010 = ", pycodata.constants_2010.MOLAR_MASS_CONSTANT_2010["value"])
! 
! SEE ALSO
!     List of constants:
! 
!         o ALPHA_PARTICLE_ELECTRON_MASS_RATIO
!         o ALPHA_PARTICLE_MASS
!         o ALPHA_PARTICLE_MASS_ENERGY_EQUIVALENT
!         o ALPHA_PARTICLE_MASS_ENERGY_EQUIVALENT_IN_MEV
!         o ALPHA_PARTICLE_MASS_IN_U
!         o ALPHA_PARTICLE_MOLAR_MASS
!         o ALPHA_PARTICLE_PROTON_MASS_RATIO
!         o ALPHA_PARTICLE_RELATIVE_ATOMIC_MASS
!         o ALPHA_PARTICLE_RMS_CHARGE_RADIUS
!         o ANGSTROM_STAR
!         o ATOMIC_MASS_CONSTANT
!         o ATOMIC_MASS_CONSTANT_ENERGY_EQUIVALENT
!         o ATOMIC_MASS_CONSTANT_ENERGY_EQUIVALENT_IN_MEV
!         o ATOMIC_MASS_UNIT_ELECTRON_VOLT_RELATIONSHIP
!         o ATOMIC_MASS_UNIT_HARTREE_RELATIONSHIP
!         o ATOMIC_MASS_UNIT_HERTZ_RELATIONSHIP
!         o ATOMIC_MASS_UNIT_INVERSE_METER_RELATIONSHIP
!         o ATOMIC_MASS_UNIT_JOULE_RELATIONSHIP
!         o ATOMIC_MASS_UNIT_KELVIN_RELATIONSHIP
!         o ATOMIC_MASS_UNIT_KILOGRAM_RELATIONSHIP
!         o ATOMIC_UNIT_OF_1ST_HYPERPOLARIZABILITY
!         o ATOMIC_UNIT_OF_2ND_HYPERPOLARIZABILITY
!         o ATOMIC_UNIT_OF_ACTION
!         o ATOMIC_UNIT_OF_CHARGE
!         o ATOMIC_UNIT_OF_CHARGE_DENSITY
!         o ATOMIC_UNIT_OF_CURRENT
!         o ATOMIC_UNIT_OF_ELECTRIC_DIPOLE_MOM
!         o ATOMIC_UNIT_OF_ELECTRIC_FIELD
!         o ATOMIC_UNIT_OF_ELECTRIC_FIELD_GRADIENT
!         o ATOMIC_UNIT_OF_ELECTRIC_POLARIZABILITY
!         o ATOMIC_UNIT_OF_ELECTRIC_POTENTIAL
!         o ATOMIC_UNIT_OF_ELECTRIC_QUADRUPOLE_MOM
!         o ATOMIC_UNIT_OF_ENERGY
!         o ATOMIC_UNIT_OF_FORCE
!         o ATOMIC_UNIT_OF_LENGTH
!         o ATOMIC_UNIT_OF_MAG_DIPOLE_MOM
!         o ATOMIC_UNIT_OF_MAG_FLUX_DENSITY
!         o ATOMIC_UNIT_OF_MAGNETIZABILITY
!         o ATOMIC_UNIT_OF_MASS
!         o ATOMIC_UNIT_OF_MOMENTUM
!         o ATOMIC_UNIT_OF_PERMITTIVITY
!         o ATOMIC_UNIT_OF_TIME
!         o ATOMIC_UNIT_OF_VELOCITY
!         o AVOGADRO_CONSTANT
!         o BOHR_MAGNETON
!         o BOHR_MAGNETON_IN_EV_T
!         o BOHR_MAGNETON_IN_HZ_T
!         o BOHR_MAGNETON_IN_INVERSE_METER_PER_TESLA
!         o BOHR_MAGNETON_IN_K_T
!         o BOHR_RADIUS
!         o BOLTZMANN_CONSTANT
!         o BOLTZMANN_CONSTANT_IN_EV_K
!         o BOLTZMANN_CONSTANT_IN_HZ_K
!         o BOLTZMANN_CONSTANT_IN_INVERSE_METER_PER_KELVIN
!         o CHARACTERISTIC_IMPEDANCE_OF_VACUUM
!         o CLASSICAL_ELECTRON_RADIUS
!         o COMPTON_WAVELENGTH
!         o CONDUCTANCE_QUANTUM
!         o CONVENTIONAL_VALUE_OF_AMPERE_90
!         o CONVENTIONAL_VALUE_OF_COULOMB_90
!         o CONVENTIONAL_VALUE_OF_FARAD_90
!         o CONVENTIONAL_VALUE_OF_HENRY_90
!         o CONVENTIONAL_VALUE_OF_JOSEPHSON_CONSTANT
!         o CONVENTIONAL_VALUE_OF_OHM_90
!         o CONVENTIONAL_VALUE_OF_VOLT_90
!         o CONVENTIONAL_VALUE_OF_VON_KLITZING_CONSTANT
!         o CONVENTIONAL_VALUE_OF_WATT_90
!         o COPPER_X_UNIT
!         o DEUTERON_ELECTRON_MAG_MOM_RATIO
!         o DEUTERON_ELECTRON_MASS_RATIO
!         o DEUTERON_G_FACTOR
!         o DEUTERON_MAG_MOM
!         o DEUTERON_MAG_MOM_TO_BOHR_MAGNETON_RATIO
!         o DEUTERON_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO
!         o DEUTERON_MASS
!         o DEUTERON_MASS_ENERGY_EQUIVALENT
!         o DEUTERON_MASS_ENERGY_EQUIVALENT_IN_MEV
!         o DEUTERON_MASS_IN_U
!         o DEUTERON_MOLAR_MASS
!         o DEUTERON_NEUTRON_MAG_MOM_RATIO
!         o DEUTERON_PROTON_MAG_MOM_RATIO
!         o DEUTERON_PROTON_MASS_RATIO
!         o DEUTERON_RELATIVE_ATOMIC_MASS
!         o DEUTERON_RMS_CHARGE_RADIUS
!         o ELECTRON_CHARGE_TO_MASS_QUOTIENT
!         o ELECTRON_DEUTERON_MAG_MOM_RATIO
!         o ELECTRON_DEUTERON_MASS_RATIO
!         o ELECTRON_G_FACTOR
!         o ELECTRON_GYROMAG_RATIO
!         o ELECTRON_GYROMAG_RATIO_IN_MHZ_T
!         o ELECTRON_HELION_MASS_RATIO
!         o ELECTRON_MAG_MOM
!         o ELECTRON_MAG_MOM_ANOMALY
!         o ELECTRON_MAG_MOM_TO_BOHR_MAGNETON_RATIO
!         o ELECTRON_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO
!         o ELECTRON_MASS
!         o ELECTRON_MASS_ENERGY_EQUIVALENT
!         o ELECTRON_MASS_ENERGY_EQUIVALENT_IN_MEV
!         o ELECTRON_MASS_IN_U
!         o ELECTRON_MOLAR_MASS
!         o ELECTRON_MUON_MAG_MOM_RATIO
!         o ELECTRON_MUON_MASS_RATIO
!         o ELECTRON_NEUTRON_MAG_MOM_RATIO
!         o ELECTRON_NEUTRON_MASS_RATIO
!         o ELECTRON_PROTON_MAG_MOM_RATIO
!         o ELECTRON_PROTON_MASS_RATIO
!         o ELECTRON_RELATIVE_ATOMIC_MASS
!         o ELECTRON_TAU_MASS_RATIO
!         o ELECTRON_TO_ALPHA_PARTICLE_MASS_RATIO
!         o ELECTRON_TO_SHIELDED_HELION_MAG_MOM_RATIO
!         o ELECTRON_TO_SHIELDED_PROTON_MAG_MOM_RATIO
!         o ELECTRON_TRITON_MASS_RATIO
!         o ELECTRON_VOLT
!         o ELECTRON_VOLT_ATOMIC_MASS_UNIT_RELATIONSHIP
!         o ELECTRON_VOLT_HARTREE_RELATIONSHIP
!         o ELECTRON_VOLT_HERTZ_RELATIONSHIP
!         o ELECTRON_VOLT_INVERSE_METER_RELATIONSHIP
!         o ELECTRON_VOLT_JOULE_RELATIONSHIP
!         o ELECTRON_VOLT_KELVIN_RELATIONSHIP
!         o ELECTRON_VOLT_KILOGRAM_RELATIONSHIP
!         o ELEMENTARY_CHARGE
!         o ELEMENTARY_CHARGE_OVER_H_BAR
!         o FARADAY_CONSTANT
!         o FERMI_COUPLING_CONSTANT
!         o FINE_STRUCTURE_CONSTANT
!         o FIRST_RADIATION_CONSTANT
!         o FIRST_RADIATION_CONSTANT_FOR_SPECTRAL_RADIANCE
!         o HARTREE_ATOMIC_MASS_UNIT_RELATIONSHIP
!         o HARTREE_ELECTRON_VOLT_RELATIONSHIP
!         o HARTREE_ENERGY
!         o HARTREE_ENERGY_IN_EV
!         o HARTREE_HERTZ_RELATIONSHIP
!         o HARTREE_INVERSE_METER_RELATIONSHIP
!         o HARTREE_JOULE_RELATIONSHIP
!         o HARTREE_KELVIN_RELATIONSHIP
!         o HARTREE_KILOGRAM_RELATIONSHIP
!         o HELION_ELECTRON_MASS_RATIO
!         o HELION_G_FACTOR
!         o HELION_MAG_MOM
!         o HELION_MAG_MOM_TO_BOHR_MAGNETON_RATIO
!         o HELION_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO
!         o HELION_MASS
!         o HELION_MASS_ENERGY_EQUIVALENT
!         o HELION_MASS_ENERGY_EQUIVALENT_IN_MEV
!         o HELION_MASS_IN_U
!         o HELION_MOLAR_MASS
!         o HELION_PROTON_MASS_RATIO
!         o HELION_RELATIVE_ATOMIC_MASS
!         o HELION_SHIELDING_SHIFT
!         o HERTZ_ATOMIC_MASS_UNIT_RELATIONSHIP
!         o HERTZ_ELECTRON_VOLT_RELATIONSHIP
!         o HERTZ_HARTREE_RELATIONSHIP
!         o HERTZ_INVERSE_METER_RELATIONSHIP
!         o HERTZ_JOULE_RELATIONSHIP
!         o HERTZ_KELVIN_RELATIONSHIP
!         o HERTZ_KILOGRAM_RELATIONSHIP
!         o HYPERFINE_TRANSITION_FREQUENCY_OF_CS_133
!         o INVERSE_FINE_STRUCTURE_CONSTANT
!         o INVERSE_METER_ATOMIC_MASS_UNIT_RELATIONSHIP
!         o INVERSE_METER_ELECTRON_VOLT_RELATIONSHIP
!         o INVERSE_METER_HARTREE_RELATIONSHIP
!         o INVERSE_METER_HERTZ_RELATIONSHIP
!         o INVERSE_METER_JOULE_RELATIONSHIP
!         o INVERSE_METER_KELVIN_RELATIONSHIP
!         o INVERSE_METER_KILOGRAM_RELATIONSHIP
!         o INVERSE_OF_CONDUCTANCE_QUANTUM
!         o JOSEPHSON_CONSTANT
!         o JOULE_ATOMIC_MASS_UNIT_RELATIONSHIP
!         o JOULE_ELECTRON_VOLT_RELATIONSHIP
!         o JOULE_HARTREE_RELATIONSHIP
!         o JOULE_HERTZ_RELATIONSHIP
!         o JOULE_INVERSE_METER_RELATIONSHIP
!         o JOULE_KELVIN_RELATIONSHIP
!         o JOULE_KILOGRAM_RELATIONSHIP
!         o KELVIN_ATOMIC_MASS_UNIT_RELATIONSHIP
!         o KELVIN_ELECTRON_VOLT_RELATIONSHIP
!         o KELVIN_HARTREE_RELATIONSHIP
!         o KELVIN_HERTZ_RELATIONSHIP
!         o KELVIN_INVERSE_METER_RELATIONSHIP
!         o KELVIN_JOULE_RELATIONSHIP
!         o KELVIN_KILOGRAM_RELATIONSHIP
!         o KILOGRAM_ATOMIC_MASS_UNIT_RELATIONSHIP
!         o KILOGRAM_ELECTRON_VOLT_RELATIONSHIP
!         o KILOGRAM_HARTREE_RELATIONSHIP
!         o KILOGRAM_HERTZ_RELATIONSHIP
!         o KILOGRAM_INVERSE_METER_RELATIONSHIP
!         o KILOGRAM_JOULE_RELATIONSHIP
!         o KILOGRAM_KELVIN_RELATIONSHIP
!         o LATTICE_PARAMETER_OF_SILICON
!         o LATTICE_SPACING_OF_IDEAL_SI_220
!         o LOSCHMIDT_CONSTANT_273_15_K_100_KPA
!         o LOSCHMIDT_CONSTANT_273_15_K_101_325_KPA
!         o LUMINOUS_EFFICACY
!         o MAG_FLUX_QUANTUM
!         o MOLAR_GAS_CONSTANT
!         o MOLAR_MASS_CONSTANT
!         o MOLAR_MASS_OF_CARBON_12
!         o MOLAR_PLANCK_CONSTANT
!         o MOLAR_VOLUME_OF_IDEAL_GAS_273_15_K_100_KPA
!         o MOLAR_VOLUME_OF_IDEAL_GAS_273_15_K_101_325_KPA
!         o MOLAR_VOLUME_OF_SILICON
!         o MOLYBDENUM_X_UNIT
!         o MUON_COMPTON_WAVELENGTH
!         o MUON_ELECTRON_MASS_RATIO
!         o MUON_G_FACTOR
!         o MUON_MAG_MOM
!         o MUON_MAG_MOM_ANOMALY
!         o MUON_MAG_MOM_TO_BOHR_MAGNETON_RATIO
!         o MUON_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO
!         o MUON_MASS
!         o MUON_MASS_ENERGY_EQUIVALENT
!         o MUON_MASS_ENERGY_EQUIVALENT_IN_MEV
!         o MUON_MASS_IN_U
!         o MUON_MOLAR_MASS
!         o MUON_NEUTRON_MASS_RATIO
!         o MUON_PROTON_MAG_MOM_RATIO
!         o MUON_PROTON_MASS_RATIO
!         o MUON_TAU_MASS_RATIO
!         o NATURAL_UNIT_OF_ACTION
!         o NATURAL_UNIT_OF_ACTION_IN_EV_S
!         o NATURAL_UNIT_OF_ENERGY
!         o NATURAL_UNIT_OF_ENERGY_IN_MEV
!         o NATURAL_UNIT_OF_LENGTH
!         o NATURAL_UNIT_OF_MASS
!         o NATURAL_UNIT_OF_MOMENTUM
!         o NATURAL_UNIT_OF_MOMENTUM_IN_MEV_C
!         o NATURAL_UNIT_OF_TIME
!         o NATURAL_UNIT_OF_VELOCITY
!         o NEUTRON_COMPTON_WAVELENGTH
!         o NEUTRON_ELECTRON_MAG_MOM_RATIO
!         o NEUTRON_ELECTRON_MASS_RATIO
!         o NEUTRON_G_FACTOR
!         o NEUTRON_GYROMAG_RATIO
!         o NEUTRON_GYROMAG_RATIO_IN_MHZ_T
!         o NEUTRON_MAG_MOM
!         o NEUTRON_MAG_MOM_TO_BOHR_MAGNETON_RATIO
!         o NEUTRON_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO
!         o NEUTRON_MASS
!         o NEUTRON_MASS_ENERGY_EQUIVALENT
!         o NEUTRON_MASS_ENERGY_EQUIVALENT_IN_MEV
!         o NEUTRON_MASS_IN_U
!         o NEUTRON_MOLAR_MASS
!         o NEUTRON_MUON_MASS_RATIO
!         o NEUTRON_PROTON_MAG_MOM_RATIO
!         o NEUTRON_PROTON_MASS_DIFFERENCE
!         o NEUTRON_PROTON_MASS_DIFFERENCE_ENERGY_EQUIVALENT
!         o NEUTRON_PROTON_MASS_DIFFERENCE_ENERGY_EQUIVALENT_IN_MEV
!         o NEUTRON_PROTON_MASS_DIFFERENCE_IN_U
!         o NEUTRON_PROTON_MASS_RATIO
!         o NEUTRON_RELATIVE_ATOMIC_MASS
!         o NEUTRON_TAU_MASS_RATIO
!         o NEUTRON_TO_SHIELDED_PROTON_MAG_MOM_RATIO
!         o NEWTONIAN_CONSTANT_OF_GRAVITATION
!         o NEWTONIAN_CONSTANT_OF_GRAVITATION_OVER_H_BAR_C
!         o NUCLEAR_MAGNETON
!         o NUCLEAR_MAGNETON_IN_EV_T
!         o NUCLEAR_MAGNETON_IN_INVERSE_METER_PER_TESLA
!         o NUCLEAR_MAGNETON_IN_K_T
!         o NUCLEAR_MAGNETON_IN_MHZ_T
!         o PLANCK_CONSTANT
!         o PLANCK_CONSTANT_IN_EV_HZ
!         o PLANCK_LENGTH
!         o PLANCK_MASS
!         o PLANCK_MASS_ENERGY_EQUIVALENT_IN_GEV
!         o PLANCK_TEMPERATURE
!         o PLANCK_TIME
!         o PROTON_CHARGE_TO_MASS_QUOTIENT
!         o PROTON_COMPTON_WAVELENGTH
!         o PROTON_ELECTRON_MASS_RATIO
!         o PROTON_G_FACTOR
!         o PROTON_GYROMAG_RATIO
!         o PROTON_GYROMAG_RATIO_IN_MHZ_T
!         o PROTON_MAG_MOM
!         o PROTON_MAG_MOM_TO_BOHR_MAGNETON_RATIO
!         o PROTON_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO
!         o PROTON_MAG_SHIELDING_CORRECTION
!         o PROTON_MASS
!         o PROTON_MASS_ENERGY_EQUIVALENT
!         o PROTON_MASS_ENERGY_EQUIVALENT_IN_MEV
!         o PROTON_MASS_IN_U
!         o PROTON_MOLAR_MASS
!         o PROTON_MUON_MASS_RATIO
!         o PROTON_NEUTRON_MAG_MOM_RATIO
!         o PROTON_NEUTRON_MASS_RATIO
!         o PROTON_RELATIVE_ATOMIC_MASS
!         o PROTON_RMS_CHARGE_RADIUS
!         o PROTON_TAU_MASS_RATIO
!         o QUANTUM_OF_CIRCULATION
!         o QUANTUM_OF_CIRCULATION_TIMES_2
!         o REDUCED_COMPTON_WAVELENGTH
!         o REDUCED_MUON_COMPTON_WAVELENGTH
!         o REDUCED_NEUTRON_COMPTON_WAVELENGTH
!         o REDUCED_PLANCK_CONSTANT
!         o REDUCED_PLANCK_CONSTANT_IN_EV_S
!         o REDUCED_PLANCK_CONSTANT_TIMES_C_IN_MEV_FM
!         o REDUCED_PROTON_COMPTON_WAVELENGTH
!         o REDUCED_TAU_COMPTON_WAVELENGTH
!         o RYDBERG_CONSTANT
!         o RYDBERG_CONSTANT_TIMES_C_IN_HZ
!         o RYDBERG_CONSTANT_TIMES_HC_IN_EV
!         o RYDBERG_CONSTANT_TIMES_HC_IN_J
!         o SACKUR_TETRODE_CONSTANT_1_K_100_KPA
!         o SACKUR_TETRODE_CONSTANT_1_K_101_325_KPA
!         o SECOND_RADIATION_CONSTANT
!         o SHIELDED_HELION_GYROMAG_RATIO
!         o SHIELDED_HELION_GYROMAG_RATIO_IN_MHZ_T
!         o SHIELDED_HELION_MAG_MOM
!         o SHIELDED_HELION_MAG_MOM_TO_BOHR_MAGNETON_RATIO
!         o SHIELDED_HELION_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO
!         o SHIELDED_HELION_TO_PROTON_MAG_MOM_RATIO
!         o SHIELDED_HELION_TO_SHIELDED_PROTON_MAG_MOM_RATIO
!         o SHIELDED_PROTON_GYROMAG_RATIO
!         o SHIELDED_PROTON_GYROMAG_RATIO_IN_MHZ_T
!         o SHIELDED_PROTON_MAG_MOM
!         o SHIELDED_PROTON_MAG_MOM_TO_BOHR_MAGNETON_RATIO
!         o SHIELDED_PROTON_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO
!         o SHIELDING_DIFFERENCE_OF_D_AND_P_IN_HD
!         o SHIELDING_DIFFERENCE_OF_T_AND_P_IN_HT
!         o SPEED_OF_LIGHT_IN_VACUUM
!         o STANDARD_ACCELERATION_OF_GRAVITY
!         o STANDARD_ATMOSPHERE
!         o STANDARD_STATE_PRESSURE
!         o STEFAN_BOLTZMANN_CONSTANT
!         o TAU_COMPTON_WAVELENGTH
!         o TAU_ELECTRON_MASS_RATIO
!         o TAU_ENERGY_EQUIVALENT
!         o TAU_MASS
!         o TAU_MASS_ENERGY_EQUIVALENT
!         o TAU_MASS_IN_U
!         o TAU_MOLAR_MASS
!         o TAU_MUON_MASS_RATIO
!         o TAU_NEUTRON_MASS_RATIO
!         o TAU_PROTON_MASS_RATIO
!         o THOMSON_CROSS_SECTION
!         o TRITON_ELECTRON_MASS_RATIO
!         o TRITON_G_FACTOR
!         o TRITON_MAG_MOM
!         o TRITON_MAG_MOM_TO_BOHR_MAGNETON_RATIO
!         o TRITON_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO
!         o TRITON_MASS
!         o TRITON_MASS_ENERGY_EQUIVALENT
!         o TRITON_MASS_ENERGY_EQUIVALENT_IN_MEV
!         o TRITON_MASS_IN_U
!         o TRITON_MOLAR_MASS
!         o TRITON_PROTON_MASS_RATIO
!         o TRITON_RELATIVE_ATOMIC_MASS
!         o TRITON_TO_PROTON_MAG_MOM_RATIO
!         o UNIFIED_ATOMIC_MASS_UNIT
!         o VACUUM_ELECTRIC_PERMITTIVITY
!         o VACUUM_MAG_PERMEABILITY
!         o VON_KLITZING_CONSTANT
!         o WEAK_MIXING_ANGLE
!         o WIEN_FREQUENCY_DISPLACEMENT_LAW_CONSTANT
!         o WIEN_WAVELENGTH_DISPLACEMENT_LAW_CONSTANT
!         o W_TO_Z_MASS_RATIO
module codata
    !! Main module for the Codata library.
    !!
    !! The latest values (2022) do not have the year as a suffix in their name.
    !! Older values can be used and they feature the year as a suffix in their name.

use codata__constants_2022
use codata__constants_2018
use codata__constants_2014
use codata__constants_2010
use codata__constants_type
use codata__constants_2022_capi
use codata__constants_2018_capi
use codata__constants_2014_capi
use codata__constants_2010_capi
use codata__constants_type_capi
use codata__api
use codata__capi
implicit none


end module codata
