module codata__constants_latest
!! Constants latest - autogenerated.
use iso_fortran_env
use iso_c_binding
implicit none
private
 
integer(int32), parameter, public :: YEAR = 2018
integer(c_int), protected, public, bind(C,name="YEAR") ::capi_YEAR = YEAR

end module codata__constants_latest
