module codata
!! Codata constants - autogenerated.
use iso_c_binding
implicit none
 
integer(c_int), protected, bind(C,name="YEAR") :: YEAR = 2018

real(c_double), protected, bind(C,name="ALPHA_PARTICLE_ELECTRON_MASS_RATIO") :: &
ALPHA_PARTICLE_ELECTRON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_ALPHA_PARTICLE_ELECTRON_MASS_RATIO") :: &
U_ALPHA_PARTICLE_ELECTRON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="ALPHA_PARTICLE_MASS") :: &
ALPHA_PARTICLE_MASS= !! 
real(c_double), protected, bind(C,name="U_ALPHA_PARTICLE_MASS") :: &
U_ALPHA_PARTICLE_MASS= !! 

real(c_double), protected, bind(C,name="ALPHA_PARTICLE_MASS_ENERGY_EQUIVALENT") :: &
ALPHA_PARTICLE_MASS_ENERGY_EQUIVALENT= !! 
real(c_double), protected, bind(C,name="U_ALPHA_PARTICLE_MASS_ENERGY_EQUIVALENT") :: &
U_ALPHA_PARTICLE_MASS_ENERGY_EQUIVALENT= !! 

real(c_double), protected, bind(C,name="ALPHA_PARTICLE_MASS_ENERGY_EQUIVALENT_IN_MEV") :: &
ALPHA_PARTICLE_MASS_ENERGY_EQUIVALENT_IN_MEV= !! 
real(c_double), protected, bind(C,name="U_ALPHA_PARTICLE_MASS_ENERGY_EQUIVALENT_IN_MEV") :: &
U_ALPHA_PARTICLE_MASS_ENERGY_EQUIVALENT_IN_MEV= !! 

real(c_double), protected, bind(C,name="ALPHA_PARTICLE_MASS_IN_U") :: &
ALPHA_PARTICLE_MASS_IN_U= !! 
real(c_double), protected, bind(C,name="U_ALPHA_PARTICLE_MASS_IN_U") :: &
U_ALPHA_PARTICLE_MASS_IN_U= !! 

real(c_double), protected, bind(C,name="ALPHA_PARTICLE_MOLAR_MASS") :: &
ALPHA_PARTICLE_MOLAR_MASS= !! 
real(c_double), protected, bind(C,name="U_ALPHA_PARTICLE_MOLAR_MASS") :: &
U_ALPHA_PARTICLE_MOLAR_MASS= !! 

real(c_double), protected, bind(C,name="ALPHA_PARTICLE_PROTON_MASS_RATIO") :: &
ALPHA_PARTICLE_PROTON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_ALPHA_PARTICLE_PROTON_MASS_RATIO") :: &
U_ALPHA_PARTICLE_PROTON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="ALPHA_PARTICLE_RELATIVE_ATOMIC_MASS") :: &
ALPHA_PARTICLE_RELATIVE_ATOMIC_MASS= !! 
real(c_double), protected, bind(C,name="U_ALPHA_PARTICLE_RELATIVE_ATOMIC_MASS") :: &
U_ALPHA_PARTICLE_RELATIVE_ATOMIC_MASS= !! 

real(c_double), protected, bind(C,name="ANGSTROM_STAR") :: &
ANGSTROM_STAR= !! 
real(c_double), protected, bind(C,name="U_ANGSTROM_STAR") :: &
U_ANGSTROM_STAR= !! 

real(c_double), protected, bind(C,name="ATOMIC_MASS_CONSTANT") :: &
ATOMIC_MASS_CONSTANT= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_MASS_CONSTANT") :: &
U_ATOMIC_MASS_CONSTANT= !! 

real(c_double), protected, bind(C,name="ATOMIC_MASS_CONSTANT_ENERGY_EQUIVALENT") :: &
ATOMIC_MASS_CONSTANT_ENERGY_EQUIVALENT= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_MASS_CONSTANT_ENERGY_EQUIVALENT") :: &
U_ATOMIC_MASS_CONSTANT_ENERGY_EQUIVALENT= !! 

real(c_double), protected, bind(C,name="ATOMIC_MASS_CONSTANT_ENERGY_EQUIVALENT_IN_MEV") :: &
ATOMIC_MASS_CONSTANT_ENERGY_EQUIVALENT_IN_MEV= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_MASS_CONSTANT_ENERGY_EQUIVALENT_IN_MEV") :: &
U_ATOMIC_MASS_CONSTANT_ENERGY_EQUIVALENT_IN_MEV= !! 

real(c_double), protected, bind(C,name="ATOMIC_MASS_UNIT_ELECTRON_VOLT_RELATIONSHIP") :: &
ATOMIC_MASS_UNIT_ELECTRON_VOLT_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_MASS_UNIT_ELECTRON_VOLT_RELATIONSHIP") :: &
U_ATOMIC_MASS_UNIT_ELECTRON_VOLT_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="ATOMIC_MASS_UNIT_HARTREE_RELATIONSHIP") :: &
ATOMIC_MASS_UNIT_HARTREE_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_MASS_UNIT_HARTREE_RELATIONSHIP") :: &
U_ATOMIC_MASS_UNIT_HARTREE_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="ATOMIC_MASS_UNIT_HERTZ_RELATIONSHIP") :: &
ATOMIC_MASS_UNIT_HERTZ_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_MASS_UNIT_HERTZ_RELATIONSHIP") :: &
U_ATOMIC_MASS_UNIT_HERTZ_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="ATOMIC_MASS_UNIT_INVERSE_METER_RELATIONSHIP") :: &
ATOMIC_MASS_UNIT_INVERSE_METER_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_MASS_UNIT_INVERSE_METER_RELATIONSHIP") :: &
U_ATOMIC_MASS_UNIT_INVERSE_METER_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="ATOMIC_MASS_UNIT_JOULE_RELATIONSHIP") :: &
ATOMIC_MASS_UNIT_JOULE_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_MASS_UNIT_JOULE_RELATIONSHIP") :: &
U_ATOMIC_MASS_UNIT_JOULE_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="ATOMIC_MASS_UNIT_KELVIN_RELATIONSHIP") :: &
ATOMIC_MASS_UNIT_KELVIN_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_MASS_UNIT_KELVIN_RELATIONSHIP") :: &
U_ATOMIC_MASS_UNIT_KELVIN_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="ATOMIC_MASS_UNIT_KILOGRAM_RELATIONSHIP") :: &
ATOMIC_MASS_UNIT_KILOGRAM_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_MASS_UNIT_KILOGRAM_RELATIONSHIP") :: &
U_ATOMIC_MASS_UNIT_KILOGRAM_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="ATOMIC_UNIT_OF_1ST_HYPERPOLARIZABILITY") :: &
ATOMIC_UNIT_OF_1ST_HYPERPOLARIZABILITY= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_UNIT_OF_1ST_HYPERPOLARIZABILITY") :: &
U_ATOMIC_UNIT_OF_1ST_HYPERPOLARIZABILITY= !! 

real(c_double), protected, bind(C,name="ATOMIC_UNIT_OF_2ND_HYPERPOLARIZABILITY") :: &
ATOMIC_UNIT_OF_2ND_HYPERPOLARIZABILITY= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_UNIT_OF_2ND_HYPERPOLARIZABILITY") :: &
U_ATOMIC_UNIT_OF_2ND_HYPERPOLARIZABILITY= !! 

real(c_double), protected, bind(C,name="ATOMIC_UNIT_OF_ACTION") :: &
ATOMIC_UNIT_OF_ACTION= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_UNIT_OF_ACTION") :: &
U_ATOMIC_UNIT_OF_ACTION= !! 

real(c_double), protected, bind(C,name="ATOMIC_UNIT_OF_CHARGE") :: &
ATOMIC_UNIT_OF_CHARGE= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_UNIT_OF_CHARGE") :: &
U_ATOMIC_UNIT_OF_CHARGE= !! 

real(c_double), protected, bind(C,name="ATOMIC_UNIT_OF_CHARGE_DENSITY") :: &
ATOMIC_UNIT_OF_CHARGE_DENSITY= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_UNIT_OF_CHARGE_DENSITY") :: &
U_ATOMIC_UNIT_OF_CHARGE_DENSITY= !! 

real(c_double), protected, bind(C,name="ATOMIC_UNIT_OF_CURRENT") :: &
ATOMIC_UNIT_OF_CURRENT= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_UNIT_OF_CURRENT") :: &
U_ATOMIC_UNIT_OF_CURRENT= !! 

real(c_double), protected, bind(C,name="ATOMIC_UNIT_OF_ELECTRIC_DIPOLE_MOM") :: &
ATOMIC_UNIT_OF_ELECTRIC_DIPOLE_MOM= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_UNIT_OF_ELECTRIC_DIPOLE_MOM") :: &
U_ATOMIC_UNIT_OF_ELECTRIC_DIPOLE_MOM= !! 

real(c_double), protected, bind(C,name="ATOMIC_UNIT_OF_ELECTRIC_FIELD") :: &
ATOMIC_UNIT_OF_ELECTRIC_FIELD= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_UNIT_OF_ELECTRIC_FIELD") :: &
U_ATOMIC_UNIT_OF_ELECTRIC_FIELD= !! 

real(c_double), protected, bind(C,name="ATOMIC_UNIT_OF_ELECTRIC_FIELD_GRADIENT") :: &
ATOMIC_UNIT_OF_ELECTRIC_FIELD_GRADIENT= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_UNIT_OF_ELECTRIC_FIELD_GRADIENT") :: &
U_ATOMIC_UNIT_OF_ELECTRIC_FIELD_GRADIENT= !! 

real(c_double), protected, bind(C,name="ATOMIC_UNIT_OF_ELECTRIC_POLARIZABILITY") :: &
ATOMIC_UNIT_OF_ELECTRIC_POLARIZABILITY= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_UNIT_OF_ELECTRIC_POLARIZABILITY") :: &
U_ATOMIC_UNIT_OF_ELECTRIC_POLARIZABILITY= !! 

real(c_double), protected, bind(C,name="ATOMIC_UNIT_OF_ELECTRIC_POTENTIAL") :: &
ATOMIC_UNIT_OF_ELECTRIC_POTENTIAL= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_UNIT_OF_ELECTRIC_POTENTIAL") :: &
U_ATOMIC_UNIT_OF_ELECTRIC_POTENTIAL= !! 

real(c_double), protected, bind(C,name="ATOMIC_UNIT_OF_ELECTRIC_QUADRUPOLE_MOM") :: &
ATOMIC_UNIT_OF_ELECTRIC_QUADRUPOLE_MOM= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_UNIT_OF_ELECTRIC_QUADRUPOLE_MOM") :: &
U_ATOMIC_UNIT_OF_ELECTRIC_QUADRUPOLE_MOM= !! 

real(c_double), protected, bind(C,name="ATOMIC_UNIT_OF_ENERGY") :: &
ATOMIC_UNIT_OF_ENERGY= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_UNIT_OF_ENERGY") :: &
U_ATOMIC_UNIT_OF_ENERGY= !! 

real(c_double), protected, bind(C,name="ATOMIC_UNIT_OF_FORCE") :: &
ATOMIC_UNIT_OF_FORCE= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_UNIT_OF_FORCE") :: &
U_ATOMIC_UNIT_OF_FORCE= !! 

real(c_double), protected, bind(C,name="ATOMIC_UNIT_OF_LENGTH") :: &
ATOMIC_UNIT_OF_LENGTH= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_UNIT_OF_LENGTH") :: &
U_ATOMIC_UNIT_OF_LENGTH= !! 

real(c_double), protected, bind(C,name="ATOMIC_UNIT_OF_MAG__DIPOLE_MOM") :: &
ATOMIC_UNIT_OF_MAG__DIPOLE_MOM= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_UNIT_OF_MAG__DIPOLE_MOM") :: &
U_ATOMIC_UNIT_OF_MAG__DIPOLE_MOM= !! 

real(c_double), protected, bind(C,name="ATOMIC_UNIT_OF_MAG__FLUX_DENSITY") :: &
ATOMIC_UNIT_OF_MAG__FLUX_DENSITY= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_UNIT_OF_MAG__FLUX_DENSITY") :: &
U_ATOMIC_UNIT_OF_MAG__FLUX_DENSITY= !! 

real(c_double), protected, bind(C,name="ATOMIC_UNIT_OF_MAGNETIZABILITY") :: &
ATOMIC_UNIT_OF_MAGNETIZABILITY= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_UNIT_OF_MAGNETIZABILITY") :: &
U_ATOMIC_UNIT_OF_MAGNETIZABILITY= !! 

real(c_double), protected, bind(C,name="ATOMIC_UNIT_OF_MASS") :: &
ATOMIC_UNIT_OF_MASS= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_UNIT_OF_MASS") :: &
U_ATOMIC_UNIT_OF_MASS= !! 

real(c_double), protected, bind(C,name="ATOMIC_UNIT_OF_MOMENTUM") :: &
ATOMIC_UNIT_OF_MOMENTUM= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_UNIT_OF_MOMENTUM") :: &
U_ATOMIC_UNIT_OF_MOMENTUM= !! 

real(c_double), protected, bind(C,name="ATOMIC_UNIT_OF_PERMITTIVITY") :: &
ATOMIC_UNIT_OF_PERMITTIVITY= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_UNIT_OF_PERMITTIVITY") :: &
U_ATOMIC_UNIT_OF_PERMITTIVITY= !! 

real(c_double), protected, bind(C,name="ATOMIC_UNIT_OF_TIME") :: &
ATOMIC_UNIT_OF_TIME= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_UNIT_OF_TIME") :: &
U_ATOMIC_UNIT_OF_TIME= !! 

real(c_double), protected, bind(C,name="ATOMIC_UNIT_OF_VELOCITY") :: &
ATOMIC_UNIT_OF_VELOCITY= !! 
real(c_double), protected, bind(C,name="U_ATOMIC_UNIT_OF_VELOCITY") :: &
U_ATOMIC_UNIT_OF_VELOCITY= !! 

real(c_double), protected, bind(C,name="AVOGADRO_CONSTANT") :: &
AVOGADRO_CONSTANT= !! 
real(c_double), protected, bind(C,name="U_AVOGADRO_CONSTANT") :: &
U_AVOGADRO_CONSTANT= !! 

real(c_double), protected, bind(C,name="BOHR_MAGNETON") :: &
BOHR_MAGNETON= !! 
real(c_double), protected, bind(C,name="U_BOHR_MAGNETON") :: &
U_BOHR_MAGNETON= !! 

real(c_double), protected, bind(C,name="BOHR_MAGNETON_IN_EV_T") :: &
BOHR_MAGNETON_IN_EV_T= !! 
real(c_double), protected, bind(C,name="U_BOHR_MAGNETON_IN_EV_T") :: &
U_BOHR_MAGNETON_IN_EV_T= !! 

real(c_double), protected, bind(C,name="BOHR_MAGNETON_IN_HZ_T") :: &
BOHR_MAGNETON_IN_HZ_T= !! 
real(c_double), protected, bind(C,name="U_BOHR_MAGNETON_IN_HZ_T") :: &
U_BOHR_MAGNETON_IN_HZ_T= !! 

real(c_double), protected, bind(C,name="BOHR_MAGNETON_IN_INVERSE_METER_PER_TESLA") :: &
BOHR_MAGNETON_IN_INVERSE_METER_PER_TESLA= !! 
real(c_double), protected, bind(C,name="U_BOHR_MAGNETON_IN_INVERSE_METER_PER_TESLA") :: &
U_BOHR_MAGNETON_IN_INVERSE_METER_PER_TESLA= !! 

real(c_double), protected, bind(C,name="BOHR_MAGNETON_IN_K_T") :: &
BOHR_MAGNETON_IN_K_T= !! 
real(c_double), protected, bind(C,name="U_BOHR_MAGNETON_IN_K_T") :: &
U_BOHR_MAGNETON_IN_K_T= !! 

real(c_double), protected, bind(C,name="BOHR_RADIUS") :: &
BOHR_RADIUS= !! 
real(c_double), protected, bind(C,name="U_BOHR_RADIUS") :: &
U_BOHR_RADIUS= !! 

real(c_double), protected, bind(C,name="BOLTZMANN_CONSTANT") :: &
BOLTZMANN_CONSTANT= !! 
real(c_double), protected, bind(C,name="U_BOLTZMANN_CONSTANT") :: &
U_BOLTZMANN_CONSTANT= !! 

real(c_double), protected, bind(C,name="BOLTZMANN_CONSTANT_IN_EV_K") :: &
BOLTZMANN_CONSTANT_IN_EV_K= !! 
real(c_double), protected, bind(C,name="U_BOLTZMANN_CONSTANT_IN_EV_K") :: &
U_BOLTZMANN_CONSTANT_IN_EV_K= !! 

real(c_double), protected, bind(C,name="BOLTZMANN_CONSTANT_IN_HZ_K") :: &
BOLTZMANN_CONSTANT_IN_HZ_K= !! 
real(c_double), protected, bind(C,name="U_BOLTZMANN_CONSTANT_IN_HZ_K") :: &
U_BOLTZMANN_CONSTANT_IN_HZ_K= !! 

real(c_double), protected, bind(C,name="BOLTZMANN_CONSTANT_IN_INVERSE_METER_PER_KELVIN") :: &
BOLTZMANN_CONSTANT_IN_INVERSE_METER_PER_KELVIN= !! 
real(c_double), protected, bind(C,name="U_BOLTZMANN_CONSTANT_IN_INVERSE_METER_PER_KELVIN") :: &
U_BOLTZMANN_CONSTANT_IN_INVERSE_METER_PER_KELVIN= !! 

real(c_double), protected, bind(C,name="CHARACTERISTIC_IMPEDANCE_OF_VACUUM") :: &
CHARACTERISTIC_IMPEDANCE_OF_VACUUM= !! 
real(c_double), protected, bind(C,name="U_CHARACTERISTIC_IMPEDANCE_OF_VACUUM") :: &
U_CHARACTERISTIC_IMPEDANCE_OF_VACUUM= !! 

real(c_double), protected, bind(C,name="CLASSICAL_ELECTRON_RADIUS") :: &
CLASSICAL_ELECTRON_RADIUS= !! 
real(c_double), protected, bind(C,name="U_CLASSICAL_ELECTRON_RADIUS") :: &
U_CLASSICAL_ELECTRON_RADIUS= !! 

real(c_double), protected, bind(C,name="COMPTON_WAVELENGTH") :: &
COMPTON_WAVELENGTH= !! 
real(c_double), protected, bind(C,name="U_COMPTON_WAVELENGTH") :: &
U_COMPTON_WAVELENGTH= !! 

real(c_double), protected, bind(C,name="CONDUCTANCE_QUANTUM") :: &
CONDUCTANCE_QUANTUM= !! 
real(c_double), protected, bind(C,name="U_CONDUCTANCE_QUANTUM") :: &
U_CONDUCTANCE_QUANTUM= !! 

real(c_double), protected, bind(C,name="CONVENTIONAL_VALUE_OF_AMPERE_90") :: &
CONVENTIONAL_VALUE_OF_AMPERE_90= !! 
real(c_double), protected, bind(C,name="U_CONVENTIONAL_VALUE_OF_AMPERE_90") :: &
U_CONVENTIONAL_VALUE_OF_AMPERE_90= !! 

real(c_double), protected, bind(C,name="CONVENTIONAL_VALUE_OF_COULOMB_90") :: &
CONVENTIONAL_VALUE_OF_COULOMB_90= !! 
real(c_double), protected, bind(C,name="U_CONVENTIONAL_VALUE_OF_COULOMB_90") :: &
U_CONVENTIONAL_VALUE_OF_COULOMB_90= !! 

real(c_double), protected, bind(C,name="CONVENTIONAL_VALUE_OF_FARAD_90") :: &
CONVENTIONAL_VALUE_OF_FARAD_90= !! 
real(c_double), protected, bind(C,name="U_CONVENTIONAL_VALUE_OF_FARAD_90") :: &
U_CONVENTIONAL_VALUE_OF_FARAD_90= !! 

real(c_double), protected, bind(C,name="CONVENTIONAL_VALUE_OF_HENRY_90") :: &
CONVENTIONAL_VALUE_OF_HENRY_90= !! 
real(c_double), protected, bind(C,name="U_CONVENTIONAL_VALUE_OF_HENRY_90") :: &
U_CONVENTIONAL_VALUE_OF_HENRY_90= !! 

real(c_double), protected, bind(C,name="CONVENTIONAL_VALUE_OF_JOSEPHSON_CONSTANT") :: &
CONVENTIONAL_VALUE_OF_JOSEPHSON_CONSTANT= !! 
real(c_double), protected, bind(C,name="U_CONVENTIONAL_VALUE_OF_JOSEPHSON_CONSTANT") :: &
U_CONVENTIONAL_VALUE_OF_JOSEPHSON_CONSTANT= !! 

real(c_double), protected, bind(C,name="CONVENTIONAL_VALUE_OF_OHM_90") :: &
CONVENTIONAL_VALUE_OF_OHM_90= !! 
real(c_double), protected, bind(C,name="U_CONVENTIONAL_VALUE_OF_OHM_90") :: &
U_CONVENTIONAL_VALUE_OF_OHM_90= !! 

real(c_double), protected, bind(C,name="CONVENTIONAL_VALUE_OF_VOLT_90") :: &
CONVENTIONAL_VALUE_OF_VOLT_90= !! 
real(c_double), protected, bind(C,name="U_CONVENTIONAL_VALUE_OF_VOLT_90") :: &
U_CONVENTIONAL_VALUE_OF_VOLT_90= !! 

real(c_double), protected, bind(C,name="CONVENTIONAL_VALUE_OF_VON_KLITZING_CONSTANT") :: &
CONVENTIONAL_VALUE_OF_VON_KLITZING_CONSTANT= !! 
real(c_double), protected, bind(C,name="U_CONVENTIONAL_VALUE_OF_VON_KLITZING_CONSTANT") :: &
U_CONVENTIONAL_VALUE_OF_VON_KLITZING_CONSTANT= !! 

real(c_double), protected, bind(C,name="CONVENTIONAL_VALUE_OF_WATT_90") :: &
CONVENTIONAL_VALUE_OF_WATT_90= !! 
real(c_double), protected, bind(C,name="U_CONVENTIONAL_VALUE_OF_WATT_90") :: &
U_CONVENTIONAL_VALUE_OF_WATT_90= !! 

real(c_double), protected, bind(C,name="COPPER_X_UNIT") :: &
COPPER_X_UNIT= !! 
real(c_double), protected, bind(C,name="U_COPPER_X_UNIT") :: &
U_COPPER_X_UNIT= !! 

real(c_double), protected, bind(C,name="DEUTERON_ELECTRON_MAG__MOM__RATIO") :: &
DEUTERON_ELECTRON_MAG__MOM__RATIO= !! 
real(c_double), protected, bind(C,name="U_DEUTERON_ELECTRON_MAG__MOM__RATIO") :: &
U_DEUTERON_ELECTRON_MAG__MOM__RATIO= !! 

real(c_double), protected, bind(C,name="DEUTERON_ELECTRON_MASS_RATIO") :: &
DEUTERON_ELECTRON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_DEUTERON_ELECTRON_MASS_RATIO") :: &
U_DEUTERON_ELECTRON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="DEUTERON_G_FACTOR") :: &
DEUTERON_G_FACTOR= !! 
real(c_double), protected, bind(C,name="U_DEUTERON_G_FACTOR") :: &
U_DEUTERON_G_FACTOR= !! 

real(c_double), protected, bind(C,name="DEUTERON_MAG__MOM") :: &
DEUTERON_MAG__MOM= !! 
real(c_double), protected, bind(C,name="U_DEUTERON_MAG__MOM") :: &
U_DEUTERON_MAG__MOM= !! 

real(c_double), protected, bind(C,name="DEUTERON_MAG__MOM__TO_BOHR_MAGNETON_RATIO") :: &
DEUTERON_MAG__MOM__TO_BOHR_MAGNETON_RATIO= !! 
real(c_double), protected, bind(C,name="U_DEUTERON_MAG__MOM__TO_BOHR_MAGNETON_RATIO") :: &
U_DEUTERON_MAG__MOM__TO_BOHR_MAGNETON_RATIO= !! 

real(c_double), protected, bind(C,name="DEUTERON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO") :: &
DEUTERON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO= !! 
real(c_double), protected, bind(C,name="U_DEUTERON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO") :: &
U_DEUTERON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO= !! 

real(c_double), protected, bind(C,name="DEUTERON_MASS") :: &
DEUTERON_MASS= !! 
real(c_double), protected, bind(C,name="U_DEUTERON_MASS") :: &
U_DEUTERON_MASS= !! 

real(c_double), protected, bind(C,name="DEUTERON_MASS_ENERGY_EQUIVALENT") :: &
DEUTERON_MASS_ENERGY_EQUIVALENT= !! 
real(c_double), protected, bind(C,name="U_DEUTERON_MASS_ENERGY_EQUIVALENT") :: &
U_DEUTERON_MASS_ENERGY_EQUIVALENT= !! 

real(c_double), protected, bind(C,name="DEUTERON_MASS_ENERGY_EQUIVALENT_IN_MEV") :: &
DEUTERON_MASS_ENERGY_EQUIVALENT_IN_MEV= !! 
real(c_double), protected, bind(C,name="U_DEUTERON_MASS_ENERGY_EQUIVALENT_IN_MEV") :: &
U_DEUTERON_MASS_ENERGY_EQUIVALENT_IN_MEV= !! 

real(c_double), protected, bind(C,name="DEUTERON_MASS_IN_U") :: &
DEUTERON_MASS_IN_U= !! 
real(c_double), protected, bind(C,name="U_DEUTERON_MASS_IN_U") :: &
U_DEUTERON_MASS_IN_U= !! 

real(c_double), protected, bind(C,name="DEUTERON_MOLAR_MASS") :: &
DEUTERON_MOLAR_MASS= !! 
real(c_double), protected, bind(C,name="U_DEUTERON_MOLAR_MASS") :: &
U_DEUTERON_MOLAR_MASS= !! 

real(c_double), protected, bind(C,name="DEUTERON_NEUTRON_MAG__MOM__RATIO") :: &
DEUTERON_NEUTRON_MAG__MOM__RATIO= !! 
real(c_double), protected, bind(C,name="U_DEUTERON_NEUTRON_MAG__MOM__RATIO") :: &
U_DEUTERON_NEUTRON_MAG__MOM__RATIO= !! 

real(c_double), protected, bind(C,name="DEUTERON_PROTON_MAG__MOM__RATIO") :: &
DEUTERON_PROTON_MAG__MOM__RATIO= !! 
real(c_double), protected, bind(C,name="U_DEUTERON_PROTON_MAG__MOM__RATIO") :: &
U_DEUTERON_PROTON_MAG__MOM__RATIO= !! 

real(c_double), protected, bind(C,name="DEUTERON_PROTON_MASS_RATIO") :: &
DEUTERON_PROTON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_DEUTERON_PROTON_MASS_RATIO") :: &
U_DEUTERON_PROTON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="DEUTERON_RELATIVE_ATOMIC_MASS") :: &
DEUTERON_RELATIVE_ATOMIC_MASS= !! 
real(c_double), protected, bind(C,name="U_DEUTERON_RELATIVE_ATOMIC_MASS") :: &
U_DEUTERON_RELATIVE_ATOMIC_MASS= !! 

real(c_double), protected, bind(C,name="DEUTERON_RMS_CHARGE_RADIUS") :: &
DEUTERON_RMS_CHARGE_RADIUS= !! 
real(c_double), protected, bind(C,name="U_DEUTERON_RMS_CHARGE_RADIUS") :: &
U_DEUTERON_RMS_CHARGE_RADIUS= !! 

real(c_double), protected, bind(C,name="ELECTRON_CHARGE_TO_MASS_QUOTIENT") :: &
ELECTRON_CHARGE_TO_MASS_QUOTIENT= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_CHARGE_TO_MASS_QUOTIENT") :: &
U_ELECTRON_CHARGE_TO_MASS_QUOTIENT= !! 

real(c_double), protected, bind(C,name="ELECTRON_DEUTERON_MAG__MOM__RATIO") :: &
ELECTRON_DEUTERON_MAG__MOM__RATIO= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_DEUTERON_MAG__MOM__RATIO") :: &
U_ELECTRON_DEUTERON_MAG__MOM__RATIO= !! 

real(c_double), protected, bind(C,name="ELECTRON_DEUTERON_MASS_RATIO") :: &
ELECTRON_DEUTERON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_DEUTERON_MASS_RATIO") :: &
U_ELECTRON_DEUTERON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="ELECTRON_G_FACTOR") :: &
ELECTRON_G_FACTOR= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_G_FACTOR") :: &
U_ELECTRON_G_FACTOR= !! 

real(c_double), protected, bind(C,name="ELECTRON_GYROMAG__RATIO") :: &
ELECTRON_GYROMAG__RATIO= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_GYROMAG__RATIO") :: &
U_ELECTRON_GYROMAG__RATIO= !! 

real(c_double), protected, bind(C,name="ELECTRON_GYROMAG__RATIO_IN_MHZ_T") :: &
ELECTRON_GYROMAG__RATIO_IN_MHZ_T= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_GYROMAG__RATIO_IN_MHZ_T") :: &
U_ELECTRON_GYROMAG__RATIO_IN_MHZ_T= !! 

real(c_double), protected, bind(C,name="ELECTRON_HELION_MASS_RATIO") :: &
ELECTRON_HELION_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_HELION_MASS_RATIO") :: &
U_ELECTRON_HELION_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="ELECTRON_MAG__MOM") :: &
ELECTRON_MAG__MOM= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_MAG__MOM") :: &
U_ELECTRON_MAG__MOM= !! 

real(c_double), protected, bind(C,name="ELECTRON_MAG__MOM__ANOMALY") :: &
ELECTRON_MAG__MOM__ANOMALY= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_MAG__MOM__ANOMALY") :: &
U_ELECTRON_MAG__MOM__ANOMALY= !! 

real(c_double), protected, bind(C,name="ELECTRON_MAG__MOM__TO_BOHR_MAGNETON_RATIO") :: &
ELECTRON_MAG__MOM__TO_BOHR_MAGNETON_RATIO= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_MAG__MOM__TO_BOHR_MAGNETON_RATIO") :: &
U_ELECTRON_MAG__MOM__TO_BOHR_MAGNETON_RATIO= !! 

real(c_double), protected, bind(C,name="ELECTRON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO") :: &
ELECTRON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO") :: &
U_ELECTRON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO= !! 

real(c_double), protected, bind(C,name="ELECTRON_MASS") :: &
ELECTRON_MASS= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_MASS") :: &
U_ELECTRON_MASS= !! 

real(c_double), protected, bind(C,name="ELECTRON_MASS_ENERGY_EQUIVALENT") :: &
ELECTRON_MASS_ENERGY_EQUIVALENT= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_MASS_ENERGY_EQUIVALENT") :: &
U_ELECTRON_MASS_ENERGY_EQUIVALENT= !! 

real(c_double), protected, bind(C,name="ELECTRON_MASS_ENERGY_EQUIVALENT_IN_MEV") :: &
ELECTRON_MASS_ENERGY_EQUIVALENT_IN_MEV= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_MASS_ENERGY_EQUIVALENT_IN_MEV") :: &
U_ELECTRON_MASS_ENERGY_EQUIVALENT_IN_MEV= !! 

real(c_double), protected, bind(C,name="ELECTRON_MASS_IN_U") :: &
ELECTRON_MASS_IN_U= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_MASS_IN_U") :: &
U_ELECTRON_MASS_IN_U= !! 

real(c_double), protected, bind(C,name="ELECTRON_MOLAR_MASS") :: &
ELECTRON_MOLAR_MASS= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_MOLAR_MASS") :: &
U_ELECTRON_MOLAR_MASS= !! 

real(c_double), protected, bind(C,name="ELECTRON_MUON_MAG__MOM__RATIO") :: &
ELECTRON_MUON_MAG__MOM__RATIO= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_MUON_MAG__MOM__RATIO") :: &
U_ELECTRON_MUON_MAG__MOM__RATIO= !! 

real(c_double), protected, bind(C,name="ELECTRON_MUON_MASS_RATIO") :: &
ELECTRON_MUON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_MUON_MASS_RATIO") :: &
U_ELECTRON_MUON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="ELECTRON_NEUTRON_MAG__MOM__RATIO") :: &
ELECTRON_NEUTRON_MAG__MOM__RATIO= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_NEUTRON_MAG__MOM__RATIO") :: &
U_ELECTRON_NEUTRON_MAG__MOM__RATIO= !! 

real(c_double), protected, bind(C,name="ELECTRON_NEUTRON_MASS_RATIO") :: &
ELECTRON_NEUTRON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_NEUTRON_MASS_RATIO") :: &
U_ELECTRON_NEUTRON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="ELECTRON_PROTON_MAG__MOM__RATIO") :: &
ELECTRON_PROTON_MAG__MOM__RATIO= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_PROTON_MAG__MOM__RATIO") :: &
U_ELECTRON_PROTON_MAG__MOM__RATIO= !! 

real(c_double), protected, bind(C,name="ELECTRON_PROTON_MASS_RATIO") :: &
ELECTRON_PROTON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_PROTON_MASS_RATIO") :: &
U_ELECTRON_PROTON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="ELECTRON_RELATIVE_ATOMIC_MASS") :: &
ELECTRON_RELATIVE_ATOMIC_MASS= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_RELATIVE_ATOMIC_MASS") :: &
U_ELECTRON_RELATIVE_ATOMIC_MASS= !! 

real(c_double), protected, bind(C,name="ELECTRON_TAU_MASS_RATIO") :: &
ELECTRON_TAU_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_TAU_MASS_RATIO") :: &
U_ELECTRON_TAU_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="ELECTRON_TO_ALPHA_PARTICLE_MASS_RATIO") :: &
ELECTRON_TO_ALPHA_PARTICLE_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_TO_ALPHA_PARTICLE_MASS_RATIO") :: &
U_ELECTRON_TO_ALPHA_PARTICLE_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="ELECTRON_TO_SHIELDED_HELION_MAG__MOM__RATIO") :: &
ELECTRON_TO_SHIELDED_HELION_MAG__MOM__RATIO= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_TO_SHIELDED_HELION_MAG__MOM__RATIO") :: &
U_ELECTRON_TO_SHIELDED_HELION_MAG__MOM__RATIO= !! 

real(c_double), protected, bind(C,name="ELECTRON_TO_SHIELDED_PROTON_MAG__MOM__RATIO") :: &
ELECTRON_TO_SHIELDED_PROTON_MAG__MOM__RATIO= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_TO_SHIELDED_PROTON_MAG__MOM__RATIO") :: &
U_ELECTRON_TO_SHIELDED_PROTON_MAG__MOM__RATIO= !! 

real(c_double), protected, bind(C,name="ELECTRON_TRITON_MASS_RATIO") :: &
ELECTRON_TRITON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_TRITON_MASS_RATIO") :: &
U_ELECTRON_TRITON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="ELECTRON_VOLT") :: &
ELECTRON_VOLT= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_VOLT") :: &
U_ELECTRON_VOLT= !! 

real(c_double), protected, bind(C,name="ELECTRON_VOLT_ATOMIC_MASS_UNIT_RELATIONSHIP") :: &
ELECTRON_VOLT_ATOMIC_MASS_UNIT_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_VOLT_ATOMIC_MASS_UNIT_RELATIONSHIP") :: &
U_ELECTRON_VOLT_ATOMIC_MASS_UNIT_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="ELECTRON_VOLT_HARTREE_RELATIONSHIP") :: &
ELECTRON_VOLT_HARTREE_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_VOLT_HARTREE_RELATIONSHIP") :: &
U_ELECTRON_VOLT_HARTREE_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="ELECTRON_VOLT_HERTZ_RELATIONSHIP") :: &
ELECTRON_VOLT_HERTZ_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_VOLT_HERTZ_RELATIONSHIP") :: &
U_ELECTRON_VOLT_HERTZ_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="ELECTRON_VOLT_INVERSE_METER_RELATIONSHIP") :: &
ELECTRON_VOLT_INVERSE_METER_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_VOLT_INVERSE_METER_RELATIONSHIP") :: &
U_ELECTRON_VOLT_INVERSE_METER_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="ELECTRON_VOLT_JOULE_RELATIONSHIP") :: &
ELECTRON_VOLT_JOULE_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_VOLT_JOULE_RELATIONSHIP") :: &
U_ELECTRON_VOLT_JOULE_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="ELECTRON_VOLT_KELVIN_RELATIONSHIP") :: &
ELECTRON_VOLT_KELVIN_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_VOLT_KELVIN_RELATIONSHIP") :: &
U_ELECTRON_VOLT_KELVIN_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="ELECTRON_VOLT_KILOGRAM_RELATIONSHIP") :: &
ELECTRON_VOLT_KILOGRAM_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_ELECTRON_VOLT_KILOGRAM_RELATIONSHIP") :: &
U_ELECTRON_VOLT_KILOGRAM_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="ELEMENTARY_CHARGE") :: &
ELEMENTARY_CHARGE= !! 
real(c_double), protected, bind(C,name="U_ELEMENTARY_CHARGE") :: &
U_ELEMENTARY_CHARGE= !! 

real(c_double), protected, bind(C,name="ELEMENTARY_CHARGE_OVER_H_BAR") :: &
ELEMENTARY_CHARGE_OVER_H_BAR= !! 
real(c_double), protected, bind(C,name="U_ELEMENTARY_CHARGE_OVER_H_BAR") :: &
U_ELEMENTARY_CHARGE_OVER_H_BAR= !! 

real(c_double), protected, bind(C,name="FARADAY_CONSTANT") :: &
FARADAY_CONSTANT= !! 
real(c_double), protected, bind(C,name="U_FARADAY_CONSTANT") :: &
U_FARADAY_CONSTANT= !! 

real(c_double), protected, bind(C,name="FERMI_COUPLING_CONSTANT") :: &
FERMI_COUPLING_CONSTANT= !! 
real(c_double), protected, bind(C,name="U_FERMI_COUPLING_CONSTANT") :: &
U_FERMI_COUPLING_CONSTANT= !! 

real(c_double), protected, bind(C,name="FINE_STRUCTURE_CONSTANT") :: &
FINE_STRUCTURE_CONSTANT= !! 
real(c_double), protected, bind(C,name="U_FINE_STRUCTURE_CONSTANT") :: &
U_FINE_STRUCTURE_CONSTANT= !! 

real(c_double), protected, bind(C,name="FIRST_RADIATION_CONSTANT") :: &
FIRST_RADIATION_CONSTANT= !! 
real(c_double), protected, bind(C,name="U_FIRST_RADIATION_CONSTANT") :: &
U_FIRST_RADIATION_CONSTANT= !! 

real(c_double), protected, bind(C,name="FIRST_RADIATION_CONSTANT_FOR_SPECTRAL_RADIANCE") :: &
FIRST_RADIATION_CONSTANT_FOR_SPECTRAL_RADIANCE= !! 
real(c_double), protected, bind(C,name="U_FIRST_RADIATION_CONSTANT_FOR_SPECTRAL_RADIANCE") :: &
U_FIRST_RADIATION_CONSTANT_FOR_SPECTRAL_RADIANCE= !! 

real(c_double), protected, bind(C,name="HARTREE_ATOMIC_MASS_UNIT_RELATIONSHIP") :: &
HARTREE_ATOMIC_MASS_UNIT_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_HARTREE_ATOMIC_MASS_UNIT_RELATIONSHIP") :: &
U_HARTREE_ATOMIC_MASS_UNIT_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="HARTREE_ELECTRON_VOLT_RELATIONSHIP") :: &
HARTREE_ELECTRON_VOLT_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_HARTREE_ELECTRON_VOLT_RELATIONSHIP") :: &
U_HARTREE_ELECTRON_VOLT_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="HARTREE_ENERGY") :: &
HARTREE_ENERGY= !! 
real(c_double), protected, bind(C,name="U_HARTREE_ENERGY") :: &
U_HARTREE_ENERGY= !! 

real(c_double), protected, bind(C,name="HARTREE_ENERGY_IN_EV") :: &
HARTREE_ENERGY_IN_EV= !! 
real(c_double), protected, bind(C,name="U_HARTREE_ENERGY_IN_EV") :: &
U_HARTREE_ENERGY_IN_EV= !! 

real(c_double), protected, bind(C,name="HARTREE_HERTZ_RELATIONSHIP") :: &
HARTREE_HERTZ_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_HARTREE_HERTZ_RELATIONSHIP") :: &
U_HARTREE_HERTZ_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="HARTREE_INVERSE_METER_RELATIONSHIP") :: &
HARTREE_INVERSE_METER_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_HARTREE_INVERSE_METER_RELATIONSHIP") :: &
U_HARTREE_INVERSE_METER_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="HARTREE_JOULE_RELATIONSHIP") :: &
HARTREE_JOULE_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_HARTREE_JOULE_RELATIONSHIP") :: &
U_HARTREE_JOULE_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="HARTREE_KELVIN_RELATIONSHIP") :: &
HARTREE_KELVIN_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_HARTREE_KELVIN_RELATIONSHIP") :: &
U_HARTREE_KELVIN_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="HARTREE_KILOGRAM_RELATIONSHIP") :: &
HARTREE_KILOGRAM_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_HARTREE_KILOGRAM_RELATIONSHIP") :: &
U_HARTREE_KILOGRAM_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="HELION_ELECTRON_MASS_RATIO") :: &
HELION_ELECTRON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_HELION_ELECTRON_MASS_RATIO") :: &
U_HELION_ELECTRON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="HELION_G_FACTOR") :: &
HELION_G_FACTOR= !! 
real(c_double), protected, bind(C,name="U_HELION_G_FACTOR") :: &
U_HELION_G_FACTOR= !! 

real(c_double), protected, bind(C,name="HELION_MAG__MOM") :: &
HELION_MAG__MOM= !! 
real(c_double), protected, bind(C,name="U_HELION_MAG__MOM") :: &
U_HELION_MAG__MOM= !! 

real(c_double), protected, bind(C,name="HELION_MAG__MOM__TO_BOHR_MAGNETON_RATIO") :: &
HELION_MAG__MOM__TO_BOHR_MAGNETON_RATIO= !! 
real(c_double), protected, bind(C,name="U_HELION_MAG__MOM__TO_BOHR_MAGNETON_RATIO") :: &
U_HELION_MAG__MOM__TO_BOHR_MAGNETON_RATIO= !! 

real(c_double), protected, bind(C,name="HELION_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO") :: &
HELION_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO= !! 
real(c_double), protected, bind(C,name="U_HELION_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO") :: &
U_HELION_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO= !! 

real(c_double), protected, bind(C,name="HELION_MASS") :: &
HELION_MASS= !! 
real(c_double), protected, bind(C,name="U_HELION_MASS") :: &
U_HELION_MASS= !! 

real(c_double), protected, bind(C,name="HELION_MASS_ENERGY_EQUIVALENT") :: &
HELION_MASS_ENERGY_EQUIVALENT= !! 
real(c_double), protected, bind(C,name="U_HELION_MASS_ENERGY_EQUIVALENT") :: &
U_HELION_MASS_ENERGY_EQUIVALENT= !! 

real(c_double), protected, bind(C,name="HELION_MASS_ENERGY_EQUIVALENT_IN_MEV") :: &
HELION_MASS_ENERGY_EQUIVALENT_IN_MEV= !! 
real(c_double), protected, bind(C,name="U_HELION_MASS_ENERGY_EQUIVALENT_IN_MEV") :: &
U_HELION_MASS_ENERGY_EQUIVALENT_IN_MEV= !! 

real(c_double), protected, bind(C,name="HELION_MASS_IN_U") :: &
HELION_MASS_IN_U= !! 
real(c_double), protected, bind(C,name="U_HELION_MASS_IN_U") :: &
U_HELION_MASS_IN_U= !! 

real(c_double), protected, bind(C,name="HELION_MOLAR_MASS") :: &
HELION_MOLAR_MASS= !! 
real(c_double), protected, bind(C,name="U_HELION_MOLAR_MASS") :: &
U_HELION_MOLAR_MASS= !! 

real(c_double), protected, bind(C,name="HELION_PROTON_MASS_RATIO") :: &
HELION_PROTON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_HELION_PROTON_MASS_RATIO") :: &
U_HELION_PROTON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="HELION_RELATIVE_ATOMIC_MASS") :: &
HELION_RELATIVE_ATOMIC_MASS= !! 
real(c_double), protected, bind(C,name="U_HELION_RELATIVE_ATOMIC_MASS") :: &
U_HELION_RELATIVE_ATOMIC_MASS= !! 

real(c_double), protected, bind(C,name="HELION_SHIELDING_SHIFT") :: &
HELION_SHIELDING_SHIFT= !! 
real(c_double), protected, bind(C,name="U_HELION_SHIELDING_SHIFT") :: &
U_HELION_SHIELDING_SHIFT= !! 

real(c_double), protected, bind(C,name="HERTZ_ATOMIC_MASS_UNIT_RELATIONSHIP") :: &
HERTZ_ATOMIC_MASS_UNIT_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_HERTZ_ATOMIC_MASS_UNIT_RELATIONSHIP") :: &
U_HERTZ_ATOMIC_MASS_UNIT_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="HERTZ_ELECTRON_VOLT_RELATIONSHIP") :: &
HERTZ_ELECTRON_VOLT_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_HERTZ_ELECTRON_VOLT_RELATIONSHIP") :: &
U_HERTZ_ELECTRON_VOLT_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="HERTZ_HARTREE_RELATIONSHIP") :: &
HERTZ_HARTREE_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_HERTZ_HARTREE_RELATIONSHIP") :: &
U_HERTZ_HARTREE_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="HERTZ_INVERSE_METER_RELATIONSHIP") :: &
HERTZ_INVERSE_METER_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_HERTZ_INVERSE_METER_RELATIONSHIP") :: &
U_HERTZ_INVERSE_METER_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="HERTZ_JOULE_RELATIONSHIP") :: &
HERTZ_JOULE_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_HERTZ_JOULE_RELATIONSHIP") :: &
U_HERTZ_JOULE_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="HERTZ_KELVIN_RELATIONSHIP") :: &
HERTZ_KELVIN_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_HERTZ_KELVIN_RELATIONSHIP") :: &
U_HERTZ_KELVIN_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="HERTZ_KILOGRAM_RELATIONSHIP") :: &
HERTZ_KILOGRAM_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_HERTZ_KILOGRAM_RELATIONSHIP") :: &
U_HERTZ_KILOGRAM_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="HYPERFINE_TRANSITION_FREQUENCY_OF_CS_133") :: &
HYPERFINE_TRANSITION_FREQUENCY_OF_CS_133= !! 
real(c_double), protected, bind(C,name="U_HYPERFINE_TRANSITION_FREQUENCY_OF_CS_133") :: &
U_HYPERFINE_TRANSITION_FREQUENCY_OF_CS_133= !! 

real(c_double), protected, bind(C,name="INVERSE_FINE_STRUCTURE_CONSTANT") :: &
INVERSE_FINE_STRUCTURE_CONSTANT= !! 
real(c_double), protected, bind(C,name="U_INVERSE_FINE_STRUCTURE_CONSTANT") :: &
U_INVERSE_FINE_STRUCTURE_CONSTANT= !! 

real(c_double), protected, bind(C,name="INVERSE_METER_ATOMIC_MASS_UNIT_RELATIONSHIP") :: &
INVERSE_METER_ATOMIC_MASS_UNIT_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_INVERSE_METER_ATOMIC_MASS_UNIT_RELATIONSHIP") :: &
U_INVERSE_METER_ATOMIC_MASS_UNIT_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="INVERSE_METER_ELECTRON_VOLT_RELATIONSHIP") :: &
INVERSE_METER_ELECTRON_VOLT_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_INVERSE_METER_ELECTRON_VOLT_RELATIONSHIP") :: &
U_INVERSE_METER_ELECTRON_VOLT_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="INVERSE_METER_HARTREE_RELATIONSHIP") :: &
INVERSE_METER_HARTREE_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_INVERSE_METER_HARTREE_RELATIONSHIP") :: &
U_INVERSE_METER_HARTREE_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="INVERSE_METER_HERTZ_RELATIONSHIP") :: &
INVERSE_METER_HERTZ_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_INVERSE_METER_HERTZ_RELATIONSHIP") :: &
U_INVERSE_METER_HERTZ_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="INVERSE_METER_JOULE_RELATIONSHIP") :: &
INVERSE_METER_JOULE_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_INVERSE_METER_JOULE_RELATIONSHIP") :: &
U_INVERSE_METER_JOULE_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="INVERSE_METER_KELVIN_RELATIONSHIP") :: &
INVERSE_METER_KELVIN_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_INVERSE_METER_KELVIN_RELATIONSHIP") :: &
U_INVERSE_METER_KELVIN_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="INVERSE_METER_KILOGRAM_RELATIONSHIP") :: &
INVERSE_METER_KILOGRAM_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_INVERSE_METER_KILOGRAM_RELATIONSHIP") :: &
U_INVERSE_METER_KILOGRAM_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="INVERSE_OF_CONDUCTANCE_QUANTUM") :: &
INVERSE_OF_CONDUCTANCE_QUANTUM= !! 
real(c_double), protected, bind(C,name="U_INVERSE_OF_CONDUCTANCE_QUANTUM") :: &
U_INVERSE_OF_CONDUCTANCE_QUANTUM= !! 

real(c_double), protected, bind(C,name="JOSEPHSON_CONSTANT") :: &
JOSEPHSON_CONSTANT= !! 
real(c_double), protected, bind(C,name="U_JOSEPHSON_CONSTANT") :: &
U_JOSEPHSON_CONSTANT= !! 

real(c_double), protected, bind(C,name="JOULE_ATOMIC_MASS_UNIT_RELATIONSHIP") :: &
JOULE_ATOMIC_MASS_UNIT_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_JOULE_ATOMIC_MASS_UNIT_RELATIONSHIP") :: &
U_JOULE_ATOMIC_MASS_UNIT_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="JOULE_ELECTRON_VOLT_RELATIONSHIP") :: &
JOULE_ELECTRON_VOLT_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_JOULE_ELECTRON_VOLT_RELATIONSHIP") :: &
U_JOULE_ELECTRON_VOLT_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="JOULE_HARTREE_RELATIONSHIP") :: &
JOULE_HARTREE_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_JOULE_HARTREE_RELATIONSHIP") :: &
U_JOULE_HARTREE_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="JOULE_HERTZ_RELATIONSHIP") :: &
JOULE_HERTZ_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_JOULE_HERTZ_RELATIONSHIP") :: &
U_JOULE_HERTZ_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="JOULE_INVERSE_METER_RELATIONSHIP") :: &
JOULE_INVERSE_METER_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_JOULE_INVERSE_METER_RELATIONSHIP") :: &
U_JOULE_INVERSE_METER_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="JOULE_KELVIN_RELATIONSHIP") :: &
JOULE_KELVIN_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_JOULE_KELVIN_RELATIONSHIP") :: &
U_JOULE_KELVIN_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="JOULE_KILOGRAM_RELATIONSHIP") :: &
JOULE_KILOGRAM_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_JOULE_KILOGRAM_RELATIONSHIP") :: &
U_JOULE_KILOGRAM_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="KELVIN_ATOMIC_MASS_UNIT_RELATIONSHIP") :: &
KELVIN_ATOMIC_MASS_UNIT_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_KELVIN_ATOMIC_MASS_UNIT_RELATIONSHIP") :: &
U_KELVIN_ATOMIC_MASS_UNIT_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="KELVIN_ELECTRON_VOLT_RELATIONSHIP") :: &
KELVIN_ELECTRON_VOLT_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_KELVIN_ELECTRON_VOLT_RELATIONSHIP") :: &
U_KELVIN_ELECTRON_VOLT_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="KELVIN_HARTREE_RELATIONSHIP") :: &
KELVIN_HARTREE_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_KELVIN_HARTREE_RELATIONSHIP") :: &
U_KELVIN_HARTREE_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="KELVIN_HERTZ_RELATIONSHIP") :: &
KELVIN_HERTZ_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_KELVIN_HERTZ_RELATIONSHIP") :: &
U_KELVIN_HERTZ_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="KELVIN_INVERSE_METER_RELATIONSHIP") :: &
KELVIN_INVERSE_METER_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_KELVIN_INVERSE_METER_RELATIONSHIP") :: &
U_KELVIN_INVERSE_METER_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="KELVIN_JOULE_RELATIONSHIP") :: &
KELVIN_JOULE_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_KELVIN_JOULE_RELATIONSHIP") :: &
U_KELVIN_JOULE_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="KELVIN_KILOGRAM_RELATIONSHIP") :: &
KELVIN_KILOGRAM_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_KELVIN_KILOGRAM_RELATIONSHIP") :: &
U_KELVIN_KILOGRAM_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="KILOGRAM_ATOMIC_MASS_UNIT_RELATIONSHIP") :: &
KILOGRAM_ATOMIC_MASS_UNIT_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_KILOGRAM_ATOMIC_MASS_UNIT_RELATIONSHIP") :: &
U_KILOGRAM_ATOMIC_MASS_UNIT_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="KILOGRAM_ELECTRON_VOLT_RELATIONSHIP") :: &
KILOGRAM_ELECTRON_VOLT_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_KILOGRAM_ELECTRON_VOLT_RELATIONSHIP") :: &
U_KILOGRAM_ELECTRON_VOLT_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="KILOGRAM_HARTREE_RELATIONSHIP") :: &
KILOGRAM_HARTREE_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_KILOGRAM_HARTREE_RELATIONSHIP") :: &
U_KILOGRAM_HARTREE_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="KILOGRAM_HERTZ_RELATIONSHIP") :: &
KILOGRAM_HERTZ_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_KILOGRAM_HERTZ_RELATIONSHIP") :: &
U_KILOGRAM_HERTZ_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="KILOGRAM_INVERSE_METER_RELATIONSHIP") :: &
KILOGRAM_INVERSE_METER_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_KILOGRAM_INVERSE_METER_RELATIONSHIP") :: &
U_KILOGRAM_INVERSE_METER_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="KILOGRAM_JOULE_RELATIONSHIP") :: &
KILOGRAM_JOULE_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_KILOGRAM_JOULE_RELATIONSHIP") :: &
U_KILOGRAM_JOULE_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="KILOGRAM_KELVIN_RELATIONSHIP") :: &
KILOGRAM_KELVIN_RELATIONSHIP= !! 
real(c_double), protected, bind(C,name="U_KILOGRAM_KELVIN_RELATIONSHIP") :: &
U_KILOGRAM_KELVIN_RELATIONSHIP= !! 

real(c_double), protected, bind(C,name="LATTICE_PARAMETER_OF_SILICON") :: &
LATTICE_PARAMETER_OF_SILICON= !! 
real(c_double), protected, bind(C,name="U_LATTICE_PARAMETER_OF_SILICON") :: &
U_LATTICE_PARAMETER_OF_SILICON= !! 

real(c_double), protected, bind(C,name="LATTICE_SPACING_OF_IDEAL_SI__220") :: &
LATTICE_SPACING_OF_IDEAL_SI__220= !! 
real(c_double), protected, bind(C,name="U_LATTICE_SPACING_OF_IDEAL_SI__220") :: &
U_LATTICE_SPACING_OF_IDEAL_SI__220= !! 

real(c_double), protected, bind(C,name="LOSCHMIDT_CONSTANT__273_15_K__100_KPA") :: &
LOSCHMIDT_CONSTANT__273_15_K__100_KPA= !! 
real(c_double), protected, bind(C,name="U_LOSCHMIDT_CONSTANT__273_15_K__100_KPA") :: &
U_LOSCHMIDT_CONSTANT__273_15_K__100_KPA= !! 

real(c_double), protected, bind(C,name="LOSCHMIDT_CONSTANT__273_15_K__101_325_KPA") :: &
LOSCHMIDT_CONSTANT__273_15_K__101_325_KPA= !! 
real(c_double), protected, bind(C,name="U_LOSCHMIDT_CONSTANT__273_15_K__101_325_KPA") :: &
U_LOSCHMIDT_CONSTANT__273_15_K__101_325_KPA= !! 

real(c_double), protected, bind(C,name="LUMINOUS_EFFICACY") :: &
LUMINOUS_EFFICACY= !! 
real(c_double), protected, bind(C,name="U_LUMINOUS_EFFICACY") :: &
U_LUMINOUS_EFFICACY= !! 

real(c_double), protected, bind(C,name="MAG__FLUX_QUANTUM") :: &
MAG__FLUX_QUANTUM= !! 
real(c_double), protected, bind(C,name="U_MAG__FLUX_QUANTUM") :: &
U_MAG__FLUX_QUANTUM= !! 

real(c_double), protected, bind(C,name="MOLAR_GAS_CONSTANT") :: &
MOLAR_GAS_CONSTANT= !! 
real(c_double), protected, bind(C,name="U_MOLAR_GAS_CONSTANT") :: &
U_MOLAR_GAS_CONSTANT= !! 

real(c_double), protected, bind(C,name="MOLAR_MASS_CONSTANT") :: &
MOLAR_MASS_CONSTANT= !! 
real(c_double), protected, bind(C,name="U_MOLAR_MASS_CONSTANT") :: &
U_MOLAR_MASS_CONSTANT= !! 

real(c_double), protected, bind(C,name="MOLAR_MASS_OF_CARBON_12") :: &
MOLAR_MASS_OF_CARBON_12= !! 
real(c_double), protected, bind(C,name="U_MOLAR_MASS_OF_CARBON_12") :: &
U_MOLAR_MASS_OF_CARBON_12= !! 

real(c_double), protected, bind(C,name="MOLAR_PLANCK_CONSTANT") :: &
MOLAR_PLANCK_CONSTANT= !! 
real(c_double), protected, bind(C,name="U_MOLAR_PLANCK_CONSTANT") :: &
U_MOLAR_PLANCK_CONSTANT= !! 

real(c_double), protected, bind(C,name="MOLAR_VOLUME_OF_IDEAL_GAS__273_15_K__100_KPA") :: &
MOLAR_VOLUME_OF_IDEAL_GAS__273_15_K__100_KPA= !! 
real(c_double), protected, bind(C,name="U_MOLAR_VOLUME_OF_IDEAL_GAS__273_15_K__100_KPA") :: &
U_MOLAR_VOLUME_OF_IDEAL_GAS__273_15_K__100_KPA= !! 

real(c_double), protected, bind(C,name="MOLAR_VOLUME_OF_IDEAL_GAS__273_15_K__101_325_KPA") :: &
MOLAR_VOLUME_OF_IDEAL_GAS__273_15_K__101_325_KPA= !! 
real(c_double), protected, bind(C,name="U_MOLAR_VOLUME_OF_IDEAL_GAS__273_15_K__101_325_KPA") :: &
U_MOLAR_VOLUME_OF_IDEAL_GAS__273_15_K__101_325_KPA= !! 

real(c_double), protected, bind(C,name="MOLAR_VOLUME_OF_SILICON") :: &
MOLAR_VOLUME_OF_SILICON= !! 
real(c_double), protected, bind(C,name="U_MOLAR_VOLUME_OF_SILICON") :: &
U_MOLAR_VOLUME_OF_SILICON= !! 

real(c_double), protected, bind(C,name="MOLYBDENUM_X_UNIT") :: &
MOLYBDENUM_X_UNIT= !! 
real(c_double), protected, bind(C,name="U_MOLYBDENUM_X_UNIT") :: &
U_MOLYBDENUM_X_UNIT= !! 

real(c_double), protected, bind(C,name="MUON_COMPTON_WAVELENGTH") :: &
MUON_COMPTON_WAVELENGTH= !! 
real(c_double), protected, bind(C,name="U_MUON_COMPTON_WAVELENGTH") :: &
U_MUON_COMPTON_WAVELENGTH= !! 

real(c_double), protected, bind(C,name="MUON_ELECTRON_MASS_RATIO") :: &
MUON_ELECTRON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_MUON_ELECTRON_MASS_RATIO") :: &
U_MUON_ELECTRON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="MUON_G_FACTOR") :: &
MUON_G_FACTOR= !! 
real(c_double), protected, bind(C,name="U_MUON_G_FACTOR") :: &
U_MUON_G_FACTOR= !! 

real(c_double), protected, bind(C,name="MUON_MAG__MOM") :: &
MUON_MAG__MOM= !! 
real(c_double), protected, bind(C,name="U_MUON_MAG__MOM") :: &
U_MUON_MAG__MOM= !! 

real(c_double), protected, bind(C,name="MUON_MAG__MOM__ANOMALY") :: &
MUON_MAG__MOM__ANOMALY= !! 
real(c_double), protected, bind(C,name="U_MUON_MAG__MOM__ANOMALY") :: &
U_MUON_MAG__MOM__ANOMALY= !! 

real(c_double), protected, bind(C,name="MUON_MAG__MOM__TO_BOHR_MAGNETON_RATIO") :: &
MUON_MAG__MOM__TO_BOHR_MAGNETON_RATIO= !! 
real(c_double), protected, bind(C,name="U_MUON_MAG__MOM__TO_BOHR_MAGNETON_RATIO") :: &
U_MUON_MAG__MOM__TO_BOHR_MAGNETON_RATIO= !! 

real(c_double), protected, bind(C,name="MUON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO") :: &
MUON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO= !! 
real(c_double), protected, bind(C,name="U_MUON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO") :: &
U_MUON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO= !! 

real(c_double), protected, bind(C,name="MUON_MASS") :: &
MUON_MASS= !! 
real(c_double), protected, bind(C,name="U_MUON_MASS") :: &
U_MUON_MASS= !! 

real(c_double), protected, bind(C,name="MUON_MASS_ENERGY_EQUIVALENT") :: &
MUON_MASS_ENERGY_EQUIVALENT= !! 
real(c_double), protected, bind(C,name="U_MUON_MASS_ENERGY_EQUIVALENT") :: &
U_MUON_MASS_ENERGY_EQUIVALENT= !! 

real(c_double), protected, bind(C,name="MUON_MASS_ENERGY_EQUIVALENT_IN_MEV") :: &
MUON_MASS_ENERGY_EQUIVALENT_IN_MEV= !! 
real(c_double), protected, bind(C,name="U_MUON_MASS_ENERGY_EQUIVALENT_IN_MEV") :: &
U_MUON_MASS_ENERGY_EQUIVALENT_IN_MEV= !! 

real(c_double), protected, bind(C,name="MUON_MASS_IN_U") :: &
MUON_MASS_IN_U= !! 
real(c_double), protected, bind(C,name="U_MUON_MASS_IN_U") :: &
U_MUON_MASS_IN_U= !! 

real(c_double), protected, bind(C,name="MUON_MOLAR_MASS") :: &
MUON_MOLAR_MASS= !! 
real(c_double), protected, bind(C,name="U_MUON_MOLAR_MASS") :: &
U_MUON_MOLAR_MASS= !! 

real(c_double), protected, bind(C,name="MUON_NEUTRON_MASS_RATIO") :: &
MUON_NEUTRON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_MUON_NEUTRON_MASS_RATIO") :: &
U_MUON_NEUTRON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="MUON_PROTON_MAG__MOM__RATIO") :: &
MUON_PROTON_MAG__MOM__RATIO= !! 
real(c_double), protected, bind(C,name="U_MUON_PROTON_MAG__MOM__RATIO") :: &
U_MUON_PROTON_MAG__MOM__RATIO= !! 

real(c_double), protected, bind(C,name="MUON_PROTON_MASS_RATIO") :: &
MUON_PROTON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_MUON_PROTON_MASS_RATIO") :: &
U_MUON_PROTON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="MUON_TAU_MASS_RATIO") :: &
MUON_TAU_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_MUON_TAU_MASS_RATIO") :: &
U_MUON_TAU_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="NATURAL_UNIT_OF_ACTION") :: &
NATURAL_UNIT_OF_ACTION= !! 
real(c_double), protected, bind(C,name="U_NATURAL_UNIT_OF_ACTION") :: &
U_NATURAL_UNIT_OF_ACTION= !! 

real(c_double), protected, bind(C,name="NATURAL_UNIT_OF_ACTION_IN_EV_S") :: &
NATURAL_UNIT_OF_ACTION_IN_EV_S= !! 
real(c_double), protected, bind(C,name="U_NATURAL_UNIT_OF_ACTION_IN_EV_S") :: &
U_NATURAL_UNIT_OF_ACTION_IN_EV_S= !! 

real(c_double), protected, bind(C,name="NATURAL_UNIT_OF_ENERGY") :: &
NATURAL_UNIT_OF_ENERGY= !! 
real(c_double), protected, bind(C,name="U_NATURAL_UNIT_OF_ENERGY") :: &
U_NATURAL_UNIT_OF_ENERGY= !! 

real(c_double), protected, bind(C,name="NATURAL_UNIT_OF_ENERGY_IN_MEV") :: &
NATURAL_UNIT_OF_ENERGY_IN_MEV= !! 
real(c_double), protected, bind(C,name="U_NATURAL_UNIT_OF_ENERGY_IN_MEV") :: &
U_NATURAL_UNIT_OF_ENERGY_IN_MEV= !! 

real(c_double), protected, bind(C,name="NATURAL_UNIT_OF_LENGTH") :: &
NATURAL_UNIT_OF_LENGTH= !! 
real(c_double), protected, bind(C,name="U_NATURAL_UNIT_OF_LENGTH") :: &
U_NATURAL_UNIT_OF_LENGTH= !! 

real(c_double), protected, bind(C,name="NATURAL_UNIT_OF_MASS") :: &
NATURAL_UNIT_OF_MASS= !! 
real(c_double), protected, bind(C,name="U_NATURAL_UNIT_OF_MASS") :: &
U_NATURAL_UNIT_OF_MASS= !! 

real(c_double), protected, bind(C,name="NATURAL_UNIT_OF_MOMENTUM") :: &
NATURAL_UNIT_OF_MOMENTUM= !! 
real(c_double), protected, bind(C,name="U_NATURAL_UNIT_OF_MOMENTUM") :: &
U_NATURAL_UNIT_OF_MOMENTUM= !! 

real(c_double), protected, bind(C,name="NATURAL_UNIT_OF_MOMENTUM_IN_MEV_C") :: &
NATURAL_UNIT_OF_MOMENTUM_IN_MEV_C= !! 
real(c_double), protected, bind(C,name="U_NATURAL_UNIT_OF_MOMENTUM_IN_MEV_C") :: &
U_NATURAL_UNIT_OF_MOMENTUM_IN_MEV_C= !! 

real(c_double), protected, bind(C,name="NATURAL_UNIT_OF_TIME") :: &
NATURAL_UNIT_OF_TIME= !! 
real(c_double), protected, bind(C,name="U_NATURAL_UNIT_OF_TIME") :: &
U_NATURAL_UNIT_OF_TIME= !! 

real(c_double), protected, bind(C,name="NATURAL_UNIT_OF_VELOCITY") :: &
NATURAL_UNIT_OF_VELOCITY= !! 
real(c_double), protected, bind(C,name="U_NATURAL_UNIT_OF_VELOCITY") :: &
U_NATURAL_UNIT_OF_VELOCITY= !! 

real(c_double), protected, bind(C,name="NEUTRON_COMPTON_WAVELENGTH") :: &
NEUTRON_COMPTON_WAVELENGTH= !! 
real(c_double), protected, bind(C,name="U_NEUTRON_COMPTON_WAVELENGTH") :: &
U_NEUTRON_COMPTON_WAVELENGTH= !! 

real(c_double), protected, bind(C,name="NEUTRON_ELECTRON_MAG__MOM__RATIO") :: &
NEUTRON_ELECTRON_MAG__MOM__RATIO= !! 
real(c_double), protected, bind(C,name="U_NEUTRON_ELECTRON_MAG__MOM__RATIO") :: &
U_NEUTRON_ELECTRON_MAG__MOM__RATIO= !! 

real(c_double), protected, bind(C,name="NEUTRON_ELECTRON_MASS_RATIO") :: &
NEUTRON_ELECTRON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_NEUTRON_ELECTRON_MASS_RATIO") :: &
U_NEUTRON_ELECTRON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="NEUTRON_G_FACTOR") :: &
NEUTRON_G_FACTOR= !! 
real(c_double), protected, bind(C,name="U_NEUTRON_G_FACTOR") :: &
U_NEUTRON_G_FACTOR= !! 

real(c_double), protected, bind(C,name="NEUTRON_GYROMAG__RATIO") :: &
NEUTRON_GYROMAG__RATIO= !! 
real(c_double), protected, bind(C,name="U_NEUTRON_GYROMAG__RATIO") :: &
U_NEUTRON_GYROMAG__RATIO= !! 

real(c_double), protected, bind(C,name="NEUTRON_GYROMAG__RATIO_IN_MHZ_T") :: &
NEUTRON_GYROMAG__RATIO_IN_MHZ_T= !! 
real(c_double), protected, bind(C,name="U_NEUTRON_GYROMAG__RATIO_IN_MHZ_T") :: &
U_NEUTRON_GYROMAG__RATIO_IN_MHZ_T= !! 

real(c_double), protected, bind(C,name="NEUTRON_MAG__MOM") :: &
NEUTRON_MAG__MOM= !! 
real(c_double), protected, bind(C,name="U_NEUTRON_MAG__MOM") :: &
U_NEUTRON_MAG__MOM= !! 

real(c_double), protected, bind(C,name="NEUTRON_MAG__MOM__TO_BOHR_MAGNETON_RATIO") :: &
NEUTRON_MAG__MOM__TO_BOHR_MAGNETON_RATIO= !! 
real(c_double), protected, bind(C,name="U_NEUTRON_MAG__MOM__TO_BOHR_MAGNETON_RATIO") :: &
U_NEUTRON_MAG__MOM__TO_BOHR_MAGNETON_RATIO= !! 

real(c_double), protected, bind(C,name="NEUTRON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO") :: &
NEUTRON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO= !! 
real(c_double), protected, bind(C,name="U_NEUTRON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO") :: &
U_NEUTRON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO= !! 

real(c_double), protected, bind(C,name="NEUTRON_MASS") :: &
NEUTRON_MASS= !! 
real(c_double), protected, bind(C,name="U_NEUTRON_MASS") :: &
U_NEUTRON_MASS= !! 

real(c_double), protected, bind(C,name="NEUTRON_MASS_ENERGY_EQUIVALENT") :: &
NEUTRON_MASS_ENERGY_EQUIVALENT= !! 
real(c_double), protected, bind(C,name="U_NEUTRON_MASS_ENERGY_EQUIVALENT") :: &
U_NEUTRON_MASS_ENERGY_EQUIVALENT= !! 

real(c_double), protected, bind(C,name="NEUTRON_MASS_ENERGY_EQUIVALENT_IN_MEV") :: &
NEUTRON_MASS_ENERGY_EQUIVALENT_IN_MEV= !! 
real(c_double), protected, bind(C,name="U_NEUTRON_MASS_ENERGY_EQUIVALENT_IN_MEV") :: &
U_NEUTRON_MASS_ENERGY_EQUIVALENT_IN_MEV= !! 

real(c_double), protected, bind(C,name="NEUTRON_MASS_IN_U") :: &
NEUTRON_MASS_IN_U= !! 
real(c_double), protected, bind(C,name="U_NEUTRON_MASS_IN_U") :: &
U_NEUTRON_MASS_IN_U= !! 

real(c_double), protected, bind(C,name="NEUTRON_MOLAR_MASS") :: &
NEUTRON_MOLAR_MASS= !! 
real(c_double), protected, bind(C,name="U_NEUTRON_MOLAR_MASS") :: &
U_NEUTRON_MOLAR_MASS= !! 

real(c_double), protected, bind(C,name="NEUTRON_MUON_MASS_RATIO") :: &
NEUTRON_MUON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_NEUTRON_MUON_MASS_RATIO") :: &
U_NEUTRON_MUON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="NEUTRON_PROTON_MAG__MOM__RATIO") :: &
NEUTRON_PROTON_MAG__MOM__RATIO= !! 
real(c_double), protected, bind(C,name="U_NEUTRON_PROTON_MAG__MOM__RATIO") :: &
U_NEUTRON_PROTON_MAG__MOM__RATIO= !! 

real(c_double), protected, bind(C,name="NEUTRON_PROTON_MASS_DIFFERENCE") :: &
NEUTRON_PROTON_MASS_DIFFERENCE= !! 
real(c_double), protected, bind(C,name="U_NEUTRON_PROTON_MASS_DIFFERENCE") :: &
U_NEUTRON_PROTON_MASS_DIFFERENCE= !! 

real(c_double), protected, bind(C,name="NEUTRON_PROTON_MASS_DIFFERENCE_ENERGY_EQUIVALENT") :: &
NEUTRON_PROTON_MASS_DIFFERENCE_ENERGY_EQUIVALENT= !! 
real(c_double), protected, bind(C,name="U_NEUTRON_PROTON_MASS_DIFFERENCE_ENERGY_EQUIVALENT") :: &
U_NEUTRON_PROTON_MASS_DIFFERENCE_ENERGY_EQUIVALENT= !! 

real(c_double), protected, bind(C,name="NEUTRON_PROTON_MASS_DIFFERENCE_ENERGY_EQUIVALENT_IN_MEV") :: &
NEUTRON_PROTON_MASS_DIFFERENCE_ENERGY_EQUIVALENT_IN_MEV= !! 
real(c_double), protected, bind(C,name="U_NEUTRON_PROTON_MASS_DIFFERENCE_ENERGY_EQUIVALENT_IN_MEV") :: &
U_NEUTRON_PROTON_MASS_DIFFERENCE_ENERGY_EQUIVALENT_IN_MEV= !! 

real(c_double), protected, bind(C,name="NEUTRON_PROTON_MASS_DIFFERENCE_IN_U") :: &
NEUTRON_PROTON_MASS_DIFFERENCE_IN_U= !! 
real(c_double), protected, bind(C,name="U_NEUTRON_PROTON_MASS_DIFFERENCE_IN_U") :: &
U_NEUTRON_PROTON_MASS_DIFFERENCE_IN_U= !! 

real(c_double), protected, bind(C,name="NEUTRON_PROTON_MASS_RATIO") :: &
NEUTRON_PROTON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_NEUTRON_PROTON_MASS_RATIO") :: &
U_NEUTRON_PROTON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="NEUTRON_RELATIVE_ATOMIC_MASS") :: &
NEUTRON_RELATIVE_ATOMIC_MASS= !! 
real(c_double), protected, bind(C,name="U_NEUTRON_RELATIVE_ATOMIC_MASS") :: &
U_NEUTRON_RELATIVE_ATOMIC_MASS= !! 

real(c_double), protected, bind(C,name="NEUTRON_TAU_MASS_RATIO") :: &
NEUTRON_TAU_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_NEUTRON_TAU_MASS_RATIO") :: &
U_NEUTRON_TAU_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="NEUTRON_TO_SHIELDED_PROTON_MAG__MOM__RATIO") :: &
NEUTRON_TO_SHIELDED_PROTON_MAG__MOM__RATIO= !! 
real(c_double), protected, bind(C,name="U_NEUTRON_TO_SHIELDED_PROTON_MAG__MOM__RATIO") :: &
U_NEUTRON_TO_SHIELDED_PROTON_MAG__MOM__RATIO= !! 

real(c_double), protected, bind(C,name="NEWTONIAN_CONSTANT_OF_GRAVITATION") :: &
NEWTONIAN_CONSTANT_OF_GRAVITATION= !! 
real(c_double), protected, bind(C,name="U_NEWTONIAN_CONSTANT_OF_GRAVITATION") :: &
U_NEWTONIAN_CONSTANT_OF_GRAVITATION= !! 

real(c_double), protected, bind(C,name="NEWTONIAN_CONSTANT_OF_GRAVITATION_OVER_H_BAR_C") :: &
NEWTONIAN_CONSTANT_OF_GRAVITATION_OVER_H_BAR_C= !! 
real(c_double), protected, bind(C,name="U_NEWTONIAN_CONSTANT_OF_GRAVITATION_OVER_H_BAR_C") :: &
U_NEWTONIAN_CONSTANT_OF_GRAVITATION_OVER_H_BAR_C= !! 

real(c_double), protected, bind(C,name="NUCLEAR_MAGNETON") :: &
NUCLEAR_MAGNETON= !! 
real(c_double), protected, bind(C,name="U_NUCLEAR_MAGNETON") :: &
U_NUCLEAR_MAGNETON= !! 

real(c_double), protected, bind(C,name="NUCLEAR_MAGNETON_IN_EV_T") :: &
NUCLEAR_MAGNETON_IN_EV_T= !! 
real(c_double), protected, bind(C,name="U_NUCLEAR_MAGNETON_IN_EV_T") :: &
U_NUCLEAR_MAGNETON_IN_EV_T= !! 

real(c_double), protected, bind(C,name="NUCLEAR_MAGNETON_IN_INVERSE_METER_PER_TESLA") :: &
NUCLEAR_MAGNETON_IN_INVERSE_METER_PER_TESLA= !! 
real(c_double), protected, bind(C,name="U_NUCLEAR_MAGNETON_IN_INVERSE_METER_PER_TESLA") :: &
U_NUCLEAR_MAGNETON_IN_INVERSE_METER_PER_TESLA= !! 

real(c_double), protected, bind(C,name="NUCLEAR_MAGNETON_IN_K_T") :: &
NUCLEAR_MAGNETON_IN_K_T= !! 
real(c_double), protected, bind(C,name="U_NUCLEAR_MAGNETON_IN_K_T") :: &
U_NUCLEAR_MAGNETON_IN_K_T= !! 

real(c_double), protected, bind(C,name="NUCLEAR_MAGNETON_IN_MHZ_T") :: &
NUCLEAR_MAGNETON_IN_MHZ_T= !! 
real(c_double), protected, bind(C,name="U_NUCLEAR_MAGNETON_IN_MHZ_T") :: &
U_NUCLEAR_MAGNETON_IN_MHZ_T= !! 

real(c_double), protected, bind(C,name="PLANCK_CONSTANT") :: &
PLANCK_CONSTANT= !! 
real(c_double), protected, bind(C,name="U_PLANCK_CONSTANT") :: &
U_PLANCK_CONSTANT= !! 

real(c_double), protected, bind(C,name="PLANCK_CONSTANT_IN_EV_HZ") :: &
PLANCK_CONSTANT_IN_EV_HZ= !! 
real(c_double), protected, bind(C,name="U_PLANCK_CONSTANT_IN_EV_HZ") :: &
U_PLANCK_CONSTANT_IN_EV_HZ= !! 

real(c_double), protected, bind(C,name="PLANCK_LENGTH") :: &
PLANCK_LENGTH= !! 
real(c_double), protected, bind(C,name="U_PLANCK_LENGTH") :: &
U_PLANCK_LENGTH= !! 

real(c_double), protected, bind(C,name="PLANCK_MASS") :: &
PLANCK_MASS= !! 
real(c_double), protected, bind(C,name="U_PLANCK_MASS") :: &
U_PLANCK_MASS= !! 

real(c_double), protected, bind(C,name="PLANCK_MASS_ENERGY_EQUIVALENT_IN_GEV") :: &
PLANCK_MASS_ENERGY_EQUIVALENT_IN_GEV= !! 
real(c_double), protected, bind(C,name="U_PLANCK_MASS_ENERGY_EQUIVALENT_IN_GEV") :: &
U_PLANCK_MASS_ENERGY_EQUIVALENT_IN_GEV= !! 

real(c_double), protected, bind(C,name="PLANCK_TEMPERATURE") :: &
PLANCK_TEMPERATURE= !! 
real(c_double), protected, bind(C,name="U_PLANCK_TEMPERATURE") :: &
U_PLANCK_TEMPERATURE= !! 

real(c_double), protected, bind(C,name="PLANCK_TIME") :: &
PLANCK_TIME= !! 
real(c_double), protected, bind(C,name="U_PLANCK_TIME") :: &
U_PLANCK_TIME= !! 

real(c_double), protected, bind(C,name="PROTON_CHARGE_TO_MASS_QUOTIENT") :: &
PROTON_CHARGE_TO_MASS_QUOTIENT= !! 
real(c_double), protected, bind(C,name="U_PROTON_CHARGE_TO_MASS_QUOTIENT") :: &
U_PROTON_CHARGE_TO_MASS_QUOTIENT= !! 

real(c_double), protected, bind(C,name="PROTON_COMPTON_WAVELENGTH") :: &
PROTON_COMPTON_WAVELENGTH= !! 
real(c_double), protected, bind(C,name="U_PROTON_COMPTON_WAVELENGTH") :: &
U_PROTON_COMPTON_WAVELENGTH= !! 

real(c_double), protected, bind(C,name="PROTON_ELECTRON_MASS_RATIO") :: &
PROTON_ELECTRON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_PROTON_ELECTRON_MASS_RATIO") :: &
U_PROTON_ELECTRON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="PROTON_G_FACTOR") :: &
PROTON_G_FACTOR= !! 
real(c_double), protected, bind(C,name="U_PROTON_G_FACTOR") :: &
U_PROTON_G_FACTOR= !! 

real(c_double), protected, bind(C,name="PROTON_GYROMAG__RATIO") :: &
PROTON_GYROMAG__RATIO= !! 
real(c_double), protected, bind(C,name="U_PROTON_GYROMAG__RATIO") :: &
U_PROTON_GYROMAG__RATIO= !! 

real(c_double), protected, bind(C,name="PROTON_GYROMAG__RATIO_IN_MHZ_T") :: &
PROTON_GYROMAG__RATIO_IN_MHZ_T= !! 
real(c_double), protected, bind(C,name="U_PROTON_GYROMAG__RATIO_IN_MHZ_T") :: &
U_PROTON_GYROMAG__RATIO_IN_MHZ_T= !! 

real(c_double), protected, bind(C,name="PROTON_MAG__MOM") :: &
PROTON_MAG__MOM= !! 
real(c_double), protected, bind(C,name="U_PROTON_MAG__MOM") :: &
U_PROTON_MAG__MOM= !! 

real(c_double), protected, bind(C,name="PROTON_MAG__MOM__TO_BOHR_MAGNETON_RATIO") :: &
PROTON_MAG__MOM__TO_BOHR_MAGNETON_RATIO= !! 
real(c_double), protected, bind(C,name="U_PROTON_MAG__MOM__TO_BOHR_MAGNETON_RATIO") :: &
U_PROTON_MAG__MOM__TO_BOHR_MAGNETON_RATIO= !! 

real(c_double), protected, bind(C,name="PROTON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO") :: &
PROTON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO= !! 
real(c_double), protected, bind(C,name="U_PROTON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO") :: &
U_PROTON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO= !! 

real(c_double), protected, bind(C,name="PROTON_MAG__SHIELDING_CORRECTION") :: &
PROTON_MAG__SHIELDING_CORRECTION= !! 
real(c_double), protected, bind(C,name="U_PROTON_MAG__SHIELDING_CORRECTION") :: &
U_PROTON_MAG__SHIELDING_CORRECTION= !! 

real(c_double), protected, bind(C,name="PROTON_MASS") :: &
PROTON_MASS= !! 
real(c_double), protected, bind(C,name="U_PROTON_MASS") :: &
U_PROTON_MASS= !! 

real(c_double), protected, bind(C,name="PROTON_MASS_ENERGY_EQUIVALENT") :: &
PROTON_MASS_ENERGY_EQUIVALENT= !! 
real(c_double), protected, bind(C,name="U_PROTON_MASS_ENERGY_EQUIVALENT") :: &
U_PROTON_MASS_ENERGY_EQUIVALENT= !! 

real(c_double), protected, bind(C,name="PROTON_MASS_ENERGY_EQUIVALENT_IN_MEV") :: &
PROTON_MASS_ENERGY_EQUIVALENT_IN_MEV= !! 
real(c_double), protected, bind(C,name="U_PROTON_MASS_ENERGY_EQUIVALENT_IN_MEV") :: &
U_PROTON_MASS_ENERGY_EQUIVALENT_IN_MEV= !! 

real(c_double), protected, bind(C,name="PROTON_MASS_IN_U") :: &
PROTON_MASS_IN_U= !! 
real(c_double), protected, bind(C,name="U_PROTON_MASS_IN_U") :: &
U_PROTON_MASS_IN_U= !! 

real(c_double), protected, bind(C,name="PROTON_MOLAR_MASS") :: &
PROTON_MOLAR_MASS= !! 
real(c_double), protected, bind(C,name="U_PROTON_MOLAR_MASS") :: &
U_PROTON_MOLAR_MASS= !! 

real(c_double), protected, bind(C,name="PROTON_MUON_MASS_RATIO") :: &
PROTON_MUON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_PROTON_MUON_MASS_RATIO") :: &
U_PROTON_MUON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="PROTON_NEUTRON_MAG__MOM__RATIO") :: &
PROTON_NEUTRON_MAG__MOM__RATIO= !! 
real(c_double), protected, bind(C,name="U_PROTON_NEUTRON_MAG__MOM__RATIO") :: &
U_PROTON_NEUTRON_MAG__MOM__RATIO= !! 

real(c_double), protected, bind(C,name="PROTON_NEUTRON_MASS_RATIO") :: &
PROTON_NEUTRON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_PROTON_NEUTRON_MASS_RATIO") :: &
U_PROTON_NEUTRON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="PROTON_RELATIVE_ATOMIC_MASS") :: &
PROTON_RELATIVE_ATOMIC_MASS= !! 
real(c_double), protected, bind(C,name="U_PROTON_RELATIVE_ATOMIC_MASS") :: &
U_PROTON_RELATIVE_ATOMIC_MASS= !! 

real(c_double), protected, bind(C,name="PROTON_RMS_CHARGE_RADIUS") :: &
PROTON_RMS_CHARGE_RADIUS= !! 
real(c_double), protected, bind(C,name="U_PROTON_RMS_CHARGE_RADIUS") :: &
U_PROTON_RMS_CHARGE_RADIUS= !! 

real(c_double), protected, bind(C,name="PROTON_TAU_MASS_RATIO") :: &
PROTON_TAU_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_PROTON_TAU_MASS_RATIO") :: &
U_PROTON_TAU_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="QUANTUM_OF_CIRCULATION") :: &
QUANTUM_OF_CIRCULATION= !! 
real(c_double), protected, bind(C,name="U_QUANTUM_OF_CIRCULATION") :: &
U_QUANTUM_OF_CIRCULATION= !! 

real(c_double), protected, bind(C,name="QUANTUM_OF_CIRCULATION_TIMES_2") :: &
QUANTUM_OF_CIRCULATION_TIMES_2= !! 
real(c_double), protected, bind(C,name="U_QUANTUM_OF_CIRCULATION_TIMES_2") :: &
U_QUANTUM_OF_CIRCULATION_TIMES_2= !! 

real(c_double), protected, bind(C,name="REDUCED_COMPTON_WAVELENGTH") :: &
REDUCED_COMPTON_WAVELENGTH= !! 
real(c_double), protected, bind(C,name="U_REDUCED_COMPTON_WAVELENGTH") :: &
U_REDUCED_COMPTON_WAVELENGTH= !! 

real(c_double), protected, bind(C,name="REDUCED_MUON_COMPTON_WAVELENGTH") :: &
REDUCED_MUON_COMPTON_WAVELENGTH= !! 
real(c_double), protected, bind(C,name="U_REDUCED_MUON_COMPTON_WAVELENGTH") :: &
U_REDUCED_MUON_COMPTON_WAVELENGTH= !! 

real(c_double), protected, bind(C,name="REDUCED_NEUTRON_COMPTON_WAVELENGTH") :: &
REDUCED_NEUTRON_COMPTON_WAVELENGTH= !! 
real(c_double), protected, bind(C,name="U_REDUCED_NEUTRON_COMPTON_WAVELENGTH") :: &
U_REDUCED_NEUTRON_COMPTON_WAVELENGTH= !! 

real(c_double), protected, bind(C,name="REDUCED_PLANCK_CONSTANT") :: &
REDUCED_PLANCK_CONSTANT= !! 
real(c_double), protected, bind(C,name="U_REDUCED_PLANCK_CONSTANT") :: &
U_REDUCED_PLANCK_CONSTANT= !! 

real(c_double), protected, bind(C,name="REDUCED_PLANCK_CONSTANT_IN_EV_S") :: &
REDUCED_PLANCK_CONSTANT_IN_EV_S= !! 
real(c_double), protected, bind(C,name="U_REDUCED_PLANCK_CONSTANT_IN_EV_S") :: &
U_REDUCED_PLANCK_CONSTANT_IN_EV_S= !! 

real(c_double), protected, bind(C,name="REDUCED_PLANCK_CONSTANT_TIMES_C_IN_MEV_FM") :: &
REDUCED_PLANCK_CONSTANT_TIMES_C_IN_MEV_FM= !! 
real(c_double), protected, bind(C,name="U_REDUCED_PLANCK_CONSTANT_TIMES_C_IN_MEV_FM") :: &
U_REDUCED_PLANCK_CONSTANT_TIMES_C_IN_MEV_FM= !! 

real(c_double), protected, bind(C,name="REDUCED_PROTON_COMPTON_WAVELENGTH") :: &
REDUCED_PROTON_COMPTON_WAVELENGTH= !! 
real(c_double), protected, bind(C,name="U_REDUCED_PROTON_COMPTON_WAVELENGTH") :: &
U_REDUCED_PROTON_COMPTON_WAVELENGTH= !! 

real(c_double), protected, bind(C,name="REDUCED_TAU_COMPTON_WAVELENGTH") :: &
REDUCED_TAU_COMPTON_WAVELENGTH= !! 
real(c_double), protected, bind(C,name="U_REDUCED_TAU_COMPTON_WAVELENGTH") :: &
U_REDUCED_TAU_COMPTON_WAVELENGTH= !! 

real(c_double), protected, bind(C,name="RYDBERG_CONSTANT") :: &
RYDBERG_CONSTANT= !! 
real(c_double), protected, bind(C,name="U_RYDBERG_CONSTANT") :: &
U_RYDBERG_CONSTANT= !! 

real(c_double), protected, bind(C,name="RYDBERG_CONSTANT_TIMES_C_IN_HZ") :: &
RYDBERG_CONSTANT_TIMES_C_IN_HZ= !! 
real(c_double), protected, bind(C,name="U_RYDBERG_CONSTANT_TIMES_C_IN_HZ") :: &
U_RYDBERG_CONSTANT_TIMES_C_IN_HZ= !! 

real(c_double), protected, bind(C,name="RYDBERG_CONSTANT_TIMES_HC_IN_EV") :: &
RYDBERG_CONSTANT_TIMES_HC_IN_EV= !! 
real(c_double), protected, bind(C,name="U_RYDBERG_CONSTANT_TIMES_HC_IN_EV") :: &
U_RYDBERG_CONSTANT_TIMES_HC_IN_EV= !! 

real(c_double), protected, bind(C,name="RYDBERG_CONSTANT_TIMES_HC_IN_J") :: &
RYDBERG_CONSTANT_TIMES_HC_IN_J= !! 
real(c_double), protected, bind(C,name="U_RYDBERG_CONSTANT_TIMES_HC_IN_J") :: &
U_RYDBERG_CONSTANT_TIMES_HC_IN_J= !! 

real(c_double), protected, bind(C,name="SACKUR_TETRODE_CONSTANT__1_K__100_KPA") :: &
SACKUR_TETRODE_CONSTANT__1_K__100_KPA= !! 
real(c_double), protected, bind(C,name="U_SACKUR_TETRODE_CONSTANT__1_K__100_KPA") :: &
U_SACKUR_TETRODE_CONSTANT__1_K__100_KPA= !! 

real(c_double), protected, bind(C,name="SACKUR_TETRODE_CONSTANT__1_K__101_325_KPA") :: &
SACKUR_TETRODE_CONSTANT__1_K__101_325_KPA= !! 
real(c_double), protected, bind(C,name="U_SACKUR_TETRODE_CONSTANT__1_K__101_325_KPA") :: &
U_SACKUR_TETRODE_CONSTANT__1_K__101_325_KPA= !! 

real(c_double), protected, bind(C,name="SECOND_RADIATION_CONSTANT") :: &
SECOND_RADIATION_CONSTANT= !! 
real(c_double), protected, bind(C,name="U_SECOND_RADIATION_CONSTANT") :: &
U_SECOND_RADIATION_CONSTANT= !! 

real(c_double), protected, bind(C,name="SHIELDED_HELION_GYROMAG__RATIO") :: &
SHIELDED_HELION_GYROMAG__RATIO= !! 
real(c_double), protected, bind(C,name="U_SHIELDED_HELION_GYROMAG__RATIO") :: &
U_SHIELDED_HELION_GYROMAG__RATIO= !! 

real(c_double), protected, bind(C,name="SHIELDED_HELION_GYROMAG__RATIO_IN_MHZ_T") :: &
SHIELDED_HELION_GYROMAG__RATIO_IN_MHZ_T= !! 
real(c_double), protected, bind(C,name="U_SHIELDED_HELION_GYROMAG__RATIO_IN_MHZ_T") :: &
U_SHIELDED_HELION_GYROMAG__RATIO_IN_MHZ_T= !! 

real(c_double), protected, bind(C,name="SHIELDED_HELION_MAG__MOM") :: &
SHIELDED_HELION_MAG__MOM= !! 
real(c_double), protected, bind(C,name="U_SHIELDED_HELION_MAG__MOM") :: &
U_SHIELDED_HELION_MAG__MOM= !! 

real(c_double), protected, bind(C,name="SHIELDED_HELION_MAG__MOM__TO_BOHR_MAGNETON_RATIO") :: &
SHIELDED_HELION_MAG__MOM__TO_BOHR_MAGNETON_RATIO= !! 
real(c_double), protected, bind(C,name="U_SHIELDED_HELION_MAG__MOM__TO_BOHR_MAGNETON_RATIO") :: &
U_SHIELDED_HELION_MAG__MOM__TO_BOHR_MAGNETON_RATIO= !! 

real(c_double), protected, bind(C,name="SHIELDED_HELION_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO") :: &
SHIELDED_HELION_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO= !! 
real(c_double), protected, bind(C,name="U_SHIELDED_HELION_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO") :: &
U_SHIELDED_HELION_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO= !! 

real(c_double), protected, bind(C,name="SHIELDED_HELION_TO_PROTON_MAG__MOM__RATIO") :: &
SHIELDED_HELION_TO_PROTON_MAG__MOM__RATIO= !! 
real(c_double), protected, bind(C,name="U_SHIELDED_HELION_TO_PROTON_MAG__MOM__RATIO") :: &
U_SHIELDED_HELION_TO_PROTON_MAG__MOM__RATIO= !! 

real(c_double), protected, bind(C,name="SHIELDED_HELION_TO_SHIELDED_PROTON_MAG__MOM__RATIO") :: &
SHIELDED_HELION_TO_SHIELDED_PROTON_MAG__MOM__RATIO= !! 
real(c_double), protected, bind(C,name="U_SHIELDED_HELION_TO_SHIELDED_PROTON_MAG__MOM__RATIO") :: &
U_SHIELDED_HELION_TO_SHIELDED_PROTON_MAG__MOM__RATIO= !! 

real(c_double), protected, bind(C,name="SHIELDED_PROTON_GYROMAG__RATIO") :: &
SHIELDED_PROTON_GYROMAG__RATIO= !! 
real(c_double), protected, bind(C,name="U_SHIELDED_PROTON_GYROMAG__RATIO") :: &
U_SHIELDED_PROTON_GYROMAG__RATIO= !! 

real(c_double), protected, bind(C,name="SHIELDED_PROTON_GYROMAG__RATIO_IN_MHZ_T") :: &
SHIELDED_PROTON_GYROMAG__RATIO_IN_MHZ_T= !! 
real(c_double), protected, bind(C,name="U_SHIELDED_PROTON_GYROMAG__RATIO_IN_MHZ_T") :: &
U_SHIELDED_PROTON_GYROMAG__RATIO_IN_MHZ_T= !! 

real(c_double), protected, bind(C,name="SHIELDED_PROTON_MAG__MOM") :: &
SHIELDED_PROTON_MAG__MOM= !! 
real(c_double), protected, bind(C,name="U_SHIELDED_PROTON_MAG__MOM") :: &
U_SHIELDED_PROTON_MAG__MOM= !! 

real(c_double), protected, bind(C,name="SHIELDED_PROTON_MAG__MOM__TO_BOHR_MAGNETON_RATIO") :: &
SHIELDED_PROTON_MAG__MOM__TO_BOHR_MAGNETON_RATIO= !! 
real(c_double), protected, bind(C,name="U_SHIELDED_PROTON_MAG__MOM__TO_BOHR_MAGNETON_RATIO") :: &
U_SHIELDED_PROTON_MAG__MOM__TO_BOHR_MAGNETON_RATIO= !! 

real(c_double), protected, bind(C,name="SHIELDED_PROTON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO") :: &
SHIELDED_PROTON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO= !! 
real(c_double), protected, bind(C,name="U_SHIELDED_PROTON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO") :: &
U_SHIELDED_PROTON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO= !! 

real(c_double), protected, bind(C,name="SHIELDING_DIFFERENCE_OF_D_AND_P_IN_HD") :: &
SHIELDING_DIFFERENCE_OF_D_AND_P_IN_HD= !! 
real(c_double), protected, bind(C,name="U_SHIELDING_DIFFERENCE_OF_D_AND_P_IN_HD") :: &
U_SHIELDING_DIFFERENCE_OF_D_AND_P_IN_HD= !! 

real(c_double), protected, bind(C,name="SHIELDING_DIFFERENCE_OF_T_AND_P_IN_HT") :: &
SHIELDING_DIFFERENCE_OF_T_AND_P_IN_HT= !! 
real(c_double), protected, bind(C,name="U_SHIELDING_DIFFERENCE_OF_T_AND_P_IN_HT") :: &
U_SHIELDING_DIFFERENCE_OF_T_AND_P_IN_HT= !! 

real(c_double), protected, bind(C,name="SPEED_OF_LIGHT_IN_VACUUM") :: &
SPEED_OF_LIGHT_IN_VACUUM= !! 
real(c_double), protected, bind(C,name="U_SPEED_OF_LIGHT_IN_VACUUM") :: &
U_SPEED_OF_LIGHT_IN_VACUUM= !! 

real(c_double), protected, bind(C,name="STANDARD_ACCELERATION_OF_GRAVITY") :: &
STANDARD_ACCELERATION_OF_GRAVITY= !! 
real(c_double), protected, bind(C,name="U_STANDARD_ACCELERATION_OF_GRAVITY") :: &
U_STANDARD_ACCELERATION_OF_GRAVITY= !! 

real(c_double), protected, bind(C,name="STANDARD_ATMOSPHERE") :: &
STANDARD_ATMOSPHERE= !! 
real(c_double), protected, bind(C,name="U_STANDARD_ATMOSPHERE") :: &
U_STANDARD_ATMOSPHERE= !! 

real(c_double), protected, bind(C,name="STANDARD_STATE_PRESSURE") :: &
STANDARD_STATE_PRESSURE= !! 
real(c_double), protected, bind(C,name="U_STANDARD_STATE_PRESSURE") :: &
U_STANDARD_STATE_PRESSURE= !! 

real(c_double), protected, bind(C,name="STEFAN_BOLTZMANN_CONSTANT") :: &
STEFAN_BOLTZMANN_CONSTANT= !! 
real(c_double), protected, bind(C,name="U_STEFAN_BOLTZMANN_CONSTANT") :: &
U_STEFAN_BOLTZMANN_CONSTANT= !! 

real(c_double), protected, bind(C,name="TAU_COMPTON_WAVELENGTH") :: &
TAU_COMPTON_WAVELENGTH= !! 
real(c_double), protected, bind(C,name="U_TAU_COMPTON_WAVELENGTH") :: &
U_TAU_COMPTON_WAVELENGTH= !! 

real(c_double), protected, bind(C,name="TAU_ELECTRON_MASS_RATIO") :: &
TAU_ELECTRON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_TAU_ELECTRON_MASS_RATIO") :: &
U_TAU_ELECTRON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="TAU_ENERGY_EQUIVALENT") :: &
TAU_ENERGY_EQUIVALENT= !! 
real(c_double), protected, bind(C,name="U_TAU_ENERGY_EQUIVALENT") :: &
U_TAU_ENERGY_EQUIVALENT= !! 

real(c_double), protected, bind(C,name="TAU_MASS") :: &
TAU_MASS= !! 
real(c_double), protected, bind(C,name="U_TAU_MASS") :: &
U_TAU_MASS= !! 

real(c_double), protected, bind(C,name="TAU_MASS_ENERGY_EQUIVALENT") :: &
TAU_MASS_ENERGY_EQUIVALENT= !! 
real(c_double), protected, bind(C,name="U_TAU_MASS_ENERGY_EQUIVALENT") :: &
U_TAU_MASS_ENERGY_EQUIVALENT= !! 

real(c_double), protected, bind(C,name="TAU_MASS_IN_U") :: &
TAU_MASS_IN_U= !! 
real(c_double), protected, bind(C,name="U_TAU_MASS_IN_U") :: &
U_TAU_MASS_IN_U= !! 

real(c_double), protected, bind(C,name="TAU_MOLAR_MASS") :: &
TAU_MOLAR_MASS= !! 
real(c_double), protected, bind(C,name="U_TAU_MOLAR_MASS") :: &
U_TAU_MOLAR_MASS= !! 

real(c_double), protected, bind(C,name="TAU_MUON_MASS_RATIO") :: &
TAU_MUON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_TAU_MUON_MASS_RATIO") :: &
U_TAU_MUON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="TAU_NEUTRON_MASS_RATIO") :: &
TAU_NEUTRON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_TAU_NEUTRON_MASS_RATIO") :: &
U_TAU_NEUTRON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="TAU_PROTON_MASS_RATIO") :: &
TAU_PROTON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_TAU_PROTON_MASS_RATIO") :: &
U_TAU_PROTON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="THOMSON_CROSS_SECTION") :: &
THOMSON_CROSS_SECTION= !! 
real(c_double), protected, bind(C,name="U_THOMSON_CROSS_SECTION") :: &
U_THOMSON_CROSS_SECTION= !! 

real(c_double), protected, bind(C,name="TRITON_ELECTRON_MASS_RATIO") :: &
TRITON_ELECTRON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_TRITON_ELECTRON_MASS_RATIO") :: &
U_TRITON_ELECTRON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="TRITON_G_FACTOR") :: &
TRITON_G_FACTOR= !! 
real(c_double), protected, bind(C,name="U_TRITON_G_FACTOR") :: &
U_TRITON_G_FACTOR= !! 

real(c_double), protected, bind(C,name="TRITON_MAG__MOM") :: &
TRITON_MAG__MOM= !! 
real(c_double), protected, bind(C,name="U_TRITON_MAG__MOM") :: &
U_TRITON_MAG__MOM= !! 

real(c_double), protected, bind(C,name="TRITON_MAG__MOM__TO_BOHR_MAGNETON_RATIO") :: &
TRITON_MAG__MOM__TO_BOHR_MAGNETON_RATIO= !! 
real(c_double), protected, bind(C,name="U_TRITON_MAG__MOM__TO_BOHR_MAGNETON_RATIO") :: &
U_TRITON_MAG__MOM__TO_BOHR_MAGNETON_RATIO= !! 

real(c_double), protected, bind(C,name="TRITON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO") :: &
TRITON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO= !! 
real(c_double), protected, bind(C,name="U_TRITON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO") :: &
U_TRITON_MAG__MOM__TO_NUCLEAR_MAGNETON_RATIO= !! 

real(c_double), protected, bind(C,name="TRITON_MASS") :: &
TRITON_MASS= !! 
real(c_double), protected, bind(C,name="U_TRITON_MASS") :: &
U_TRITON_MASS= !! 

real(c_double), protected, bind(C,name="TRITON_MASS_ENERGY_EQUIVALENT") :: &
TRITON_MASS_ENERGY_EQUIVALENT= !! 
real(c_double), protected, bind(C,name="U_TRITON_MASS_ENERGY_EQUIVALENT") :: &
U_TRITON_MASS_ENERGY_EQUIVALENT= !! 

real(c_double), protected, bind(C,name="TRITON_MASS_ENERGY_EQUIVALENT_IN_MEV") :: &
TRITON_MASS_ENERGY_EQUIVALENT_IN_MEV= !! 
real(c_double), protected, bind(C,name="U_TRITON_MASS_ENERGY_EQUIVALENT_IN_MEV") :: &
U_TRITON_MASS_ENERGY_EQUIVALENT_IN_MEV= !! 

real(c_double), protected, bind(C,name="TRITON_MASS_IN_U") :: &
TRITON_MASS_IN_U= !! 
real(c_double), protected, bind(C,name="U_TRITON_MASS_IN_U") :: &
U_TRITON_MASS_IN_U= !! 

real(c_double), protected, bind(C,name="TRITON_MOLAR_MASS") :: &
TRITON_MOLAR_MASS= !! 
real(c_double), protected, bind(C,name="U_TRITON_MOLAR_MASS") :: &
U_TRITON_MOLAR_MASS= !! 

real(c_double), protected, bind(C,name="TRITON_PROTON_MASS_RATIO") :: &
TRITON_PROTON_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_TRITON_PROTON_MASS_RATIO") :: &
U_TRITON_PROTON_MASS_RATIO= !! 

real(c_double), protected, bind(C,name="TRITON_RELATIVE_ATOMIC_MASS") :: &
TRITON_RELATIVE_ATOMIC_MASS= !! 
real(c_double), protected, bind(C,name="U_TRITON_RELATIVE_ATOMIC_MASS") :: &
U_TRITON_RELATIVE_ATOMIC_MASS= !! 

real(c_double), protected, bind(C,name="TRITON_TO_PROTON_MAG__MOM__RATIO") :: &
TRITON_TO_PROTON_MAG__MOM__RATIO= !! 
real(c_double), protected, bind(C,name="U_TRITON_TO_PROTON_MAG__MOM__RATIO") :: &
U_TRITON_TO_PROTON_MAG__MOM__RATIO= !! 

real(c_double), protected, bind(C,name="UNIFIED_ATOMIC_MASS_UNIT") :: &
UNIFIED_ATOMIC_MASS_UNIT= !! 
real(c_double), protected, bind(C,name="U_UNIFIED_ATOMIC_MASS_UNIT") :: &
U_UNIFIED_ATOMIC_MASS_UNIT= !! 

real(c_double), protected, bind(C,name="VACUUM_ELECTRIC_PERMITTIVITY") :: &
VACUUM_ELECTRIC_PERMITTIVITY= !! 
real(c_double), protected, bind(C,name="U_VACUUM_ELECTRIC_PERMITTIVITY") :: &
U_VACUUM_ELECTRIC_PERMITTIVITY= !! 

real(c_double), protected, bind(C,name="VACUUM_MAG__PERMEABILITY") :: &
VACUUM_MAG__PERMEABILITY= !! 
real(c_double), protected, bind(C,name="U_VACUUM_MAG__PERMEABILITY") :: &
U_VACUUM_MAG__PERMEABILITY= !! 

real(c_double), protected, bind(C,name="VON_KLITZING_CONSTANT") :: &
VON_KLITZING_CONSTANT= !! 
real(c_double), protected, bind(C,name="U_VON_KLITZING_CONSTANT") :: &
U_VON_KLITZING_CONSTANT= !! 

real(c_double), protected, bind(C,name="WEAK_MIXING_ANGLE") :: &
WEAK_MIXING_ANGLE= !! 
real(c_double), protected, bind(C,name="U_WEAK_MIXING_ANGLE") :: &
U_WEAK_MIXING_ANGLE= !! 

real(c_double), protected, bind(C,name="WIEN_FREQUENCY_DISPLACEMENT_LAW_CONSTANT") :: &
WIEN_FREQUENCY_DISPLACEMENT_LAW_CONSTANT= !! 
real(c_double), protected, bind(C,name="U_WIEN_FREQUENCY_DISPLACEMENT_LAW_CONSTANT") :: &
U_WIEN_FREQUENCY_DISPLACEMENT_LAW_CONSTANT= !! 

real(c_double), protected, bind(C,name="WIEN_WAVELENGTH_DISPLACEMENT_LAW_CONSTANT") :: &
WIEN_WAVELENGTH_DISPLACEMENT_LAW_CONSTANT= !! 
real(c_double), protected, bind(C,name="U_WIEN_WAVELENGTH_DISPLACEMENT_LAW_CONSTANT") :: &
U_WIEN_WAVELENGTH_DISPLACEMENT_LAW_CONSTANT= !! 

real(c_double), protected, bind(C,name="W_TO_Z_MASS_RATIO") :: &
W_TO_Z_MASS_RATIO= !! 
real(c_double), protected, bind(C,name="U_W_TO_Z_MASS_RATIO") :: &
U_W_TO_Z_MASS_RATIO= !! 

end module codata
