!> @file
!! @brief Autogenerated.
!! Fundamental Physical Constants --- Complete Listing
!! 2018 CODATA adjustment
!! From:  http://physics.nist.gov/constants


!> @brief Codata data
!! @details Autogenerated from NIST table.
module codata_data
use iso_fortran_env
implicit none

type :: t_constant
  character(len=60) :: name
  real(real64) :: value
  real(real64) :: uncertainty
  character(len=25) :: unit
end type t_constant

type(t_constant), parameter :: codata_constant_1=t_constant(&
"ALPHA PARTICLE-ELECTRON MASS RATIO", 7294.29954142d0, 0.00000024d0, " ") 

type(t_constant), parameter :: codata_constant_2=t_constant(&
"ALPHA PARTICLE MASS", 6.6446573357d-27, 0.0000000020d-27, "kg") 

type(t_constant), parameter :: codata_constant_3=t_constant(&
"ALPHA PARTICLE MASS ENERGY EQUIVALENT", 5.9719201914d-10, 0.0000000018d-10, "J") 

type(t_constant), parameter :: codata_constant_4=t_constant(&
"ALPHA PARTICLE MASS ENERGY EQUIVALENT IN MEV", 3727.3794066d0, 0.0000011d0, "MeV") 

type(t_constant), parameter :: codata_constant_5=t_constant(&
"ALPHA PARTICLE MASS IN U", 4.001506179127d0, 0.000000000063d0, "u") 

type(t_constant), parameter :: codata_constant_6=t_constant(&
"ALPHA PARTICLE MOLAR MASS", 4.0015061777d-3, 0.0000000012d-3, "kg mol^-1") 

type(t_constant), parameter :: codata_constant_7=t_constant(&
"ALPHA PARTICLE-PROTON MASS RATIO", 3.97259969009d0, 0.00000000022d0, " ") 

type(t_constant), parameter :: codata_constant_8=t_constant(&
"ALPHA PARTICLE RELATIVE ATOMIC MASS", 4.001506179127d0, 0.000000000063d0, " ") 

type(t_constant), parameter :: codata_constant_9=t_constant(&
"ANGSTROM STAR", 1.00001495d-10, 0.00000090d-10, "m") 

type(t_constant), parameter :: codata_constant_10=t_constant(&
"ATOMIC MASS CONSTANT", 1.66053906660d-27, 0.00000000050d-27, "kg") 

type(t_constant), parameter :: codata_constant_11=t_constant(&
"ATOMIC MASS CONSTANT ENERGY EQUIVALENT", 1.49241808560d-10, 0.00000000045d-10, "J") 

type(t_constant), parameter :: codata_constant_12=t_constant(&
"ATOMIC MASS CONSTANT ENERGY EQUIVALENT IN MEV", 931.49410242d0, 0.00000028d0, "MeV") 

type(t_constant), parameter :: codata_constant_13=t_constant(&
"ATOMIC MASS UNIT-ELECTRON VOLT RELATIONSHIP", 9.3149410242d8, 0.0000000028d8, "eV") 

type(t_constant), parameter :: codata_constant_14=t_constant(&
"ATOMIC MASS UNIT-HARTREE RELATIONSHIP", 3.4231776874d7, 0.0000000010d7, "E_h") 

type(t_constant), parameter :: codata_constant_15=t_constant(&
"ATOMIC MASS UNIT-HERTZ RELATIONSHIP", 2.25234271871d23, 0.00000000068d23, "Hz") 

type(t_constant), parameter :: codata_constant_16=t_constant(&
"ATOMIC MASS UNIT-INVERSE METER RELATIONSHIP", 7.5130066104d14, 0.0000000023d14, "m^-1") 

type(t_constant), parameter :: codata_constant_17=t_constant(&
"ATOMIC MASS UNIT-JOULE RELATIONSHIP", 1.49241808560d-10, 0.00000000045d-10, "J") 

type(t_constant), parameter :: codata_constant_18=t_constant(&
"ATOMIC MASS UNIT-KELVIN RELATIONSHIP", 1.08095401916d13, 0.00000000033d13, "K") 

type(t_constant), parameter :: codata_constant_19=t_constant(&
"ATOMIC MASS UNIT-KILOGRAM RELATIONSHIP", 1.66053906660d-27, 0.00000000050d-27, "kg") 

type(t_constant), parameter :: codata_constant_20=t_constant(&
"ATOMIC UNIT OF 1ST HYPERPOLARIZABILITY", 3.2063613061d-53, 0.0000000015d-53, "C^3 m^3 J^-2") 

type(t_constant), parameter :: codata_constant_21=t_constant(&
"ATOMIC UNIT OF 2ND HYPERPOLARIZABILITY", 6.2353799905d-65, 0.0000000038d-65, "C^4 m^4 J^-3") 

type(t_constant), parameter :: codata_constant_22=t_constant(&
"ATOMIC UNIT OF ACTION", 1.054571817d-34, 0.0d0, "J s") 

type(t_constant), parameter :: codata_constant_23=t_constant(&
"ATOMIC UNIT OF CHARGE", 1.602176634d-19, 0.0d0, "C") 

type(t_constant), parameter :: codata_constant_24=t_constant(&
"ATOMIC UNIT OF CHARGE DENSITY", 1.08120238457d12, 0.00000000049d12, "C m^-3") 

type(t_constant), parameter :: codata_constant_25=t_constant(&
"ATOMIC UNIT OF CURRENT", 6.623618237510d-3, 0.000000000013d-3, "A") 

type(t_constant), parameter :: codata_constant_26=t_constant(&
"ATOMIC UNIT OF ELECTRIC DIPOLE MOM", 8.4783536255d-30, 0.0000000013d-30, "C m") 

type(t_constant), parameter :: codata_constant_27=t_constant(&
"ATOMIC UNIT OF ELECTRIC FIELD", 5.14220674763d11, 0.00000000078d11, "V m^-1") 

type(t_constant), parameter :: codata_constant_28=t_constant(&
"ATOMIC UNIT OF ELECTRIC FIELD GRADIENT", 9.7173624292d21, 0.0000000029d21, "V m^-2") 

type(t_constant), parameter :: codata_constant_29=t_constant(&
"ATOMIC UNIT OF ELECTRIC POLARIZABILITY", 1.64877727436d-41, 0.00000000050d-41, "C^2 m^2 J^-1") 

type(t_constant), parameter :: codata_constant_30=t_constant(&
"ATOMIC UNIT OF ELECTRIC POTENTIAL", 27.211386245988d0, 0.000000000053d0, "V") 

type(t_constant), parameter :: codata_constant_31=t_constant(&
"ATOMIC UNIT OF ELECTRIC QUADRUPOLE MOM", 4.4865515246d-40, 0.0000000014d-40, "C m^2") 

type(t_constant), parameter :: codata_constant_32=t_constant(&
"ATOMIC UNIT OF ENERGY", 4.3597447222071d-18, 0.0000000000085d-18, "J") 

type(t_constant), parameter :: codata_constant_33=t_constant(&
"ATOMIC UNIT OF FORCE", 8.2387234983d-8, 0.0000000012d-8, "N") 

type(t_constant), parameter :: codata_constant_34=t_constant(&
"ATOMIC UNIT OF LENGTH", 5.29177210903d-11, 0.00000000080d-11, "m") 

type(t_constant), parameter :: codata_constant_35=t_constant(&
"ATOMIC UNIT OF MAG. DIPOLE MOM", 1.85480201566d-23, 0.00000000056d-23, "J T^-1") 

type(t_constant), parameter :: codata_constant_36=t_constant(&
"ATOMIC UNIT OF MAG. FLUX DENSITY", 2.35051756758d5, 0.00000000071d5, "T") 

type(t_constant), parameter :: codata_constant_37=t_constant(&
"ATOMIC UNIT OF MAGNETIZABILITY", 7.8910366008d-29, 0.0000000048d-29, "J T^-2") 

type(t_constant), parameter :: codata_constant_38=t_constant(&
"ATOMIC UNIT OF MASS", 9.1093837015d-31, 0.0000000028d-31, "kg") 

type(t_constant), parameter :: codata_constant_39=t_constant(&
"ATOMIC UNIT OF MOMENTUM", 1.99285191410d-24, 0.00000000030d-24, "kg m s^-1") 

type(t_constant), parameter :: codata_constant_40=t_constant(&
"ATOMIC UNIT OF PERMITTIVITY", 1.11265005545d-10, 0.00000000017d-10, "F m^-1") 

type(t_constant), parameter :: codata_constant_41=t_constant(&
"ATOMIC UNIT OF TIME", 2.4188843265857d-17, 0.0000000000047d-17, "s") 

type(t_constant), parameter :: codata_constant_42=t_constant(&
"ATOMIC UNIT OF VELOCITY", 2.18769126364d6, 0.00000000033d6, "m s^-1") 

type(t_constant), parameter :: codata_constant_43=t_constant(&
"AVOGADRO CONSTANT", 6.02214076d23, 0.0d0, "mol^-1") 

type(t_constant), parameter :: codata_constant_44=t_constant(&
"BOHR MAGNETON", 9.2740100783d-24, 0.0000000028d-24, "J T^-1") 

type(t_constant), parameter :: codata_constant_45=t_constant(&
"BOHR MAGNETON IN EV/T", 5.7883818060d-5, 0.0000000017d-5, "eV T^-1") 

type(t_constant), parameter :: codata_constant_46=t_constant(&
"BOHR MAGNETON IN HZ/T", 1.39962449361d10, 0.00000000042d10, "Hz T^-1") 

type(t_constant), parameter :: codata_constant_47=t_constant(&
"BOHR MAGNETON IN INVERSE METER PER TESLA", 46.686447783d0, 0.000000014d0, "m^-1 T^-1") 

type(t_constant), parameter :: codata_constant_48=t_constant(&
"BOHR MAGNETON IN K/T", 0.67171381563d0, 0.00000000020d0, "K T^-1") 

type(t_constant), parameter :: codata_constant_49=t_constant(&
"BOHR RADIUS", 5.29177210903d-11, 0.00000000080d-11, "m") 

type(t_constant), parameter :: codata_constant_50=t_constant(&
"BOLTZMANN CONSTANT", 1.380649d-23, 0.0d0, "J K^-1") 

type(t_constant), parameter :: codata_constant_51=t_constant(&
"BOLTZMANN CONSTANT IN EV/K", 8.617333262d-5, 0.0d0, "eV K^-1") 

type(t_constant), parameter :: codata_constant_52=t_constant(&
"BOLTZMANN CONSTANT IN HZ/K", 2.083661912d10, 0.0d0, "Hz K^-1") 

type(t_constant), parameter :: codata_constant_53=t_constant(&
"BOLTZMANN CONSTANT IN INVERSE METER PER KELVIN", 69.50348004d0, 0.0d0, "m^-1 K^-1") 

type(t_constant), parameter :: codata_constant_54=t_constant(&
"CHARACTERISTIC IMPEDANCE OF VACUUM", 376.730313668d0, 0.000000057d0, "ohm") 

type(t_constant), parameter :: codata_constant_55=t_constant(&
"CLASSICAL ELECTRON RADIUS", 2.8179403262d-15, 0.0000000013d-15, "m") 

type(t_constant), parameter :: codata_constant_56=t_constant(&
"COMPTON WAVELENGTH", 2.42631023867d-12, 0.00000000073d-12, "m") 

type(t_constant), parameter :: codata_constant_57=t_constant(&
"CONDUCTANCE QUANTUM", 7.748091729d-5, 0.0d0, "S") 

type(t_constant), parameter :: codata_constant_58=t_constant(&
"CONVENTIONAL VALUE OF AMPERE-90", 1.00000008887d0, 0.0d0, "A") 

type(t_constant), parameter :: codata_constant_59=t_constant(&
"CONVENTIONAL VALUE OF COULOMB-90", 1.00000008887d0, 0.0d0, "C") 

type(t_constant), parameter :: codata_constant_60=t_constant(&
"CONVENTIONAL VALUE OF FARAD-90", 0.99999998220d0, 0.0d0, "F") 

type(t_constant), parameter :: codata_constant_61=t_constant(&
"CONVENTIONAL VALUE OF HENRY-90", 1.00000001779d0, 0.0d0, "H") 

type(t_constant), parameter :: codata_constant_62=t_constant(&
"CONVENTIONAL VALUE OF JOSEPHSON CONSTANT", 483597.9d9, 0.0d0, "Hz V^-1") 

type(t_constant), parameter :: codata_constant_63=t_constant(&
"CONVENTIONAL VALUE OF OHM-90", 1.00000001779d0, 0.0d0, "ohm") 

type(t_constant), parameter :: codata_constant_64=t_constant(&
"CONVENTIONAL VALUE OF VOLT-90", 1.00000010666d0, 0.0d0, "V") 

type(t_constant), parameter :: codata_constant_65=t_constant(&
"CONVENTIONAL VALUE OF VON KLITZING CONSTANT", 25812.807d0, 0.0d0, "ohm") 

type(t_constant), parameter :: codata_constant_66=t_constant(&
"CONVENTIONAL VALUE OF WATT-90", 1.00000019553d0, 0.0d0, "W") 

type(t_constant), parameter :: codata_constant_67=t_constant(&
"COPPER X UNIT", 1.00207697d-13, 0.00000028d-13, "m") 

type(t_constant), parameter :: codata_constant_68=t_constant(&
"DEUTERON-ELECTRON MAG. MOM. RATIO", -4.664345551d-4, 0.000000012d-4, " ") 

type(t_constant), parameter :: codata_constant_69=t_constant(&
"DEUTERON-ELECTRON MASS RATIO", 3670.48296788d0, 0.00000013d0, " ") 

type(t_constant), parameter :: codata_constant_70=t_constant(&
"DEUTERON G FACTOR", 0.8574382338d0, 0.0000000022d0, " ") 

type(t_constant), parameter :: codata_constant_71=t_constant(&
"DEUTERON MAG. MOM", 4.330735094d-27, 0.000000011d-27, "J T^-1") 

type(t_constant), parameter :: codata_constant_72=t_constant(&
"DEUTERON MAG. MOM. TO BOHR MAGNETON RATIO", 4.669754570d-4, 0.000000012d-4, " ") 

type(t_constant), parameter :: codata_constant_73=t_constant(&
"DEUTERON MAG. MOM. TO NUCLEAR MAGNETON RATIO", 0.8574382338d0, 0.0000000022d0, " ") 

type(t_constant), parameter :: codata_constant_74=t_constant(&
"DEUTERON MASS", 3.3435837724d-27, 0.0000000010d-27, "kg") 

type(t_constant), parameter :: codata_constant_75=t_constant(&
"DEUTERON MASS ENERGY EQUIVALENT", 3.00506323102d-10, 0.00000000091d-10, "J") 

type(t_constant), parameter :: codata_constant_76=t_constant(&
"DEUTERON MASS ENERGY EQUIVALENT IN MEV", 1875.61294257d0, 0.00000057d0, "MeV") 

type(t_constant), parameter :: codata_constant_77=t_constant(&
"DEUTERON MASS IN U", 2.013553212745d0, 0.000000000040d0, "u") 

type(t_constant), parameter :: codata_constant_78=t_constant(&
"DEUTERON MOLAR MASS", 2.01355321205d-3, 0.00000000061d-3, "kg mol^-1") 

type(t_constant), parameter :: codata_constant_79=t_constant(&
"DEUTERON-NEUTRON MAG. MOM. RATIO", -0.44820653d0, 0.00000011d0, " ") 

type(t_constant), parameter :: codata_constant_80=t_constant(&
"DEUTERON-PROTON MAG. MOM. RATIO", 0.30701220939d0, 0.00000000079d0, " ") 

type(t_constant), parameter :: codata_constant_81=t_constant(&
"DEUTERON-PROTON MASS RATIO", 1.99900750139d0, 0.00000000011d0, " ") 

type(t_constant), parameter :: codata_constant_82=t_constant(&
"DEUTERON RELATIVE ATOMIC MASS", 2.013553212745d0, 0.000000000040d0, " ") 

type(t_constant), parameter :: codata_constant_83=t_constant(&
"DEUTERON RMS CHARGE RADIUS", 2.12799d-15, 0.00074d-15, "m") 

type(t_constant), parameter :: codata_constant_84=t_constant(&
"ELECTRON CHARGE TO MASS QUOTIENT", -1.75882001076d11, 0.00000000053d11, "C kg^-1") 

type(t_constant), parameter :: codata_constant_85=t_constant(&
"ELECTRON-DEUTERON MAG. MOM. RATIO", -2143.9234915d0, 0.0000056d0, " ") 

type(t_constant), parameter :: codata_constant_86=t_constant(&
"ELECTRON-DEUTERON MASS RATIO", 2.724437107462d-4, 0.000000000096d-4, " ") 

type(t_constant), parameter :: codata_constant_87=t_constant(&
"ELECTRON G FACTOR", -2.00231930436256d0, 0.00000000000035d0, " ") 

type(t_constant), parameter :: codata_constant_88=t_constant(&
"ELECTRON GYROMAG. RATIO", 1.76085963023d11, 0.00000000053d11, "s^-1 T^-1") 

type(t_constant), parameter :: codata_constant_89=t_constant(&
"ELECTRON GYROMAG. RATIO IN MHZ/T", 28024.9514242d0, 0.0000085d0, "MHz T^-1") 

type(t_constant), parameter :: codata_constant_90=t_constant(&
"ELECTRON-HELION MASS RATIO", 1.819543074573d-4, 0.000000000079d-4, " ") 

type(t_constant), parameter :: codata_constant_91=t_constant(&
"ELECTRON MAG. MOM", -9.2847647043d-24, 0.0000000028d-24, "J T^-1") 

type(t_constant), parameter :: codata_constant_92=t_constant(&
"ELECTRON MAG. MOM. ANOMALY", 1.15965218128d-3, 0.00000000018d-3, " ") 

type(t_constant), parameter :: codata_constant_93=t_constant(&
"ELECTRON MAG. MOM. TO BOHR MAGNETON RATIO", -1.00115965218128d0, 0.00000000000018d0, " ") 

type(t_constant), parameter :: codata_constant_94=t_constant(&
"ELECTRON MAG. MOM. TO NUCLEAR MAGNETON RATIO", -1838.28197188d0, 0.00000011d0, " ") 

type(t_constant), parameter :: codata_constant_95=t_constant(&
"ELECTRON MASS", 9.1093837015d-31, 0.0000000028d-31, "kg") 

type(t_constant), parameter :: codata_constant_96=t_constant(&
"ELECTRON MASS ENERGY EQUIVALENT", 8.1871057769d-14, 0.0000000025d-14, "J") 

type(t_constant), parameter :: codata_constant_97=t_constant(&
"ELECTRON MASS ENERGY EQUIVALENT IN MEV", 0.51099895000d0, 0.00000000015d0, "MeV") 

type(t_constant), parameter :: codata_constant_98=t_constant(&
"ELECTRON MASS IN U", 5.48579909065d-4, 0.00000000016d-4, "u") 

type(t_constant), parameter :: codata_constant_99=t_constant(&
"ELECTRON MOLAR MASS", 5.4857990888d-7, 0.0000000017d-7, "kg mol^-1") 

type(t_constant), parameter :: codata_constant_100=t_constant(&
"ELECTRON-MUON MAG. MOM. RATIO", 206.7669883d0, 0.0000046d0, " ") 

type(t_constant), parameter :: codata_constant_101=t_constant(&
"ELECTRON-MUON MASS RATIO", 4.83633169d-3, 0.00000011d-3, " ") 

type(t_constant), parameter :: codata_constant_102=t_constant(&
"ELECTRON-NEUTRON MAG. MOM. RATIO", 960.92050d0, 0.00023d0, " ") 

type(t_constant), parameter :: codata_constant_103=t_constant(&
"ELECTRON-NEUTRON MASS RATIO", 5.4386734424d-4, 0.0000000026d-4, " ") 

type(t_constant), parameter :: codata_constant_104=t_constant(&
"ELECTRON-PROTON MAG. MOM. RATIO", -658.21068789d0, 0.00000020d0, " ") 

type(t_constant), parameter :: codata_constant_105=t_constant(&
"ELECTRON-PROTON MASS RATIO", 5.44617021487d-4, 0.00000000033d-4, " ") 

type(t_constant), parameter :: codata_constant_106=t_constant(&
"ELECTRON RELATIVE ATOMIC MASS", 5.48579909065d-4, 0.00000000016d-4, " ") 

type(t_constant), parameter :: codata_constant_107=t_constant(&
"ELECTRON-TAU MASS RATIO", 2.87585d-4, 0.00019d-4, " ") 

type(t_constant), parameter :: codata_constant_108=t_constant(&
"ELECTRON TO ALPHA PARTICLE MASS RATIO", 1.370933554787d-4, 0.000000000045d-4, " ") 

type(t_constant), parameter :: codata_constant_109=t_constant(&
"ELECTRON TO SHIELDED HELION MAG. MOM. RATIO", 864.058257d0, 0.000010d0, " ") 

type(t_constant), parameter :: codata_constant_110=t_constant(&
"ELECTRON TO SHIELDED PROTON MAG. MOM. RATIO", -658.2275971d0, 0.0000072d0, " ") 

type(t_constant), parameter :: codata_constant_111=t_constant(&
"ELECTRON-TRITON MASS RATIO", 1.819200062251d-4, 0.000000000090d-4, " ") 

type(t_constant), parameter :: codata_constant_112=t_constant(&
"ELECTRON VOLT", 1.602176634d-19, 0.0d0, "J") 

type(t_constant), parameter :: codata_constant_113=t_constant(&
"ELECTRON VOLT-ATOMIC MASS UNIT RELATIONSHIP", 1.07354410233d-9, 0.00000000032d-9, "u") 

type(t_constant), parameter :: codata_constant_114=t_constant(&
"ELECTRON VOLT-HARTREE RELATIONSHIP", 3.6749322175655d-2, 0.0000000000071d-2, "E_h") 

type(t_constant), parameter :: codata_constant_115=t_constant(&
"ELECTRON VOLT-HERTZ RELATIONSHIP", 2.417989242d14, 0.0d0, "Hz") 

type(t_constant), parameter :: codata_constant_116=t_constant(&
"ELECTRON VOLT-INVERSE METER RELATIONSHIP", 8.065543937d5, 0.0d0, "m^-1") 

type(t_constant), parameter :: codata_constant_117=t_constant(&
"ELECTRON VOLT-JOULE RELATIONSHIP", 1.602176634d-19, 0.0d0, "J") 

type(t_constant), parameter :: codata_constant_118=t_constant(&
"ELECTRON VOLT-KELVIN RELATIONSHIP", 1.160451812d4, 0.0d0, "K") 

type(t_constant), parameter :: codata_constant_119=t_constant(&
"ELECTRON VOLT-KILOGRAM RELATIONSHIP", 1.782661921d-36, 0.0d0, "kg") 

type(t_constant), parameter :: codata_constant_120=t_constant(&
"ELEMENTARY CHARGE", 1.602176634d-19, 0.0d0, "C") 

type(t_constant), parameter :: codata_constant_121=t_constant(&
"ELEMENTARY CHARGE OVER H-BAR", 1.519267447d15, 0.0d0, "A J^-1") 

type(t_constant), parameter :: codata_constant_122=t_constant(&
"FARADAY CONSTANT", 96485.33212d0, 0.0d0, "C mol^-1") 

type(t_constant), parameter :: codata_constant_123=t_constant(&
"FERMI COUPLING CONSTANT", 1.1663787d-5, 0.0000006d-5, "GeV^-2") 

type(t_constant), parameter :: codata_constant_124=t_constant(&
"FINE-STRUCTURE CONSTANT", 7.2973525693d-3, 0.0000000011d-3, " ") 

type(t_constant), parameter :: codata_constant_125=t_constant(&
"FIRST RADIATION CONSTANT", 3.741771852d-16, 0.0d0, "W m^2") 

type(t_constant), parameter :: codata_constant_126=t_constant(&
"FIRST RADIATION CONSTANT FOR SPECTRAL RADIANCE", 1.191042972d-16, 0.0d0, "W m^2 sr^-1") 

type(t_constant), parameter :: codata_constant_127=t_constant(&
"HARTREE-ATOMIC MASS UNIT RELATIONSHIP", 2.92126232205d-8, 0.00000000088d-8, "u") 

type(t_constant), parameter :: codata_constant_128=t_constant(&
"HARTREE-ELECTRON VOLT RELATIONSHIP", 27.211386245988d0, 0.000000000053d0, "eV") 

type(t_constant), parameter :: codata_constant_129=t_constant(&
"HARTREE ENERGY", 4.3597447222071d-18, 0.0000000000085d-18, "J") 

type(t_constant), parameter :: codata_constant_130=t_constant(&
"HARTREE ENERGY IN EV", 27.211386245988d0, 0.000000000053d0, "eV") 

type(t_constant), parameter :: codata_constant_131=t_constant(&
"HARTREE-HERTZ RELATIONSHIP", 6.579683920502d15, 0.000000000013d15, "Hz") 

type(t_constant), parameter :: codata_constant_132=t_constant(&
"HARTREE-INVERSE METER RELATIONSHIP", 2.1947463136320d7, 0.0000000000043d7, "m^-1") 

type(t_constant), parameter :: codata_constant_133=t_constant(&
"HARTREE-JOULE RELATIONSHIP", 4.3597447222071d-18, 0.0000000000085d-18, "J") 

type(t_constant), parameter :: codata_constant_134=t_constant(&
"HARTREE-KELVIN RELATIONSHIP", 3.1577502480407d5, 0.0000000000061d5, "K") 

type(t_constant), parameter :: codata_constant_135=t_constant(&
"HARTREE-KILOGRAM RELATIONSHIP", 4.8508702095432d-35, 0.0000000000094d-35, "kg") 

type(t_constant), parameter :: codata_constant_136=t_constant(&
"HELION-ELECTRON MASS RATIO", 5495.88528007d0, 0.00000024d0, " ") 

type(t_constant), parameter :: codata_constant_137=t_constant(&
"HELION G FACTOR", -4.255250615d0, 0.000000050d0, " ") 

type(t_constant), parameter :: codata_constant_138=t_constant(&
"HELION MAG. MOM", -1.074617532d-26, 0.000000013d-26, "J T^-1") 

type(t_constant), parameter :: codata_constant_139=t_constant(&
"HELION MAG. MOM. TO BOHR MAGNETON RATIO", -1.158740958d-3, 0.000000014d-3, " ") 

type(t_constant), parameter :: codata_constant_140=t_constant(&
"HELION MAG. MOM. TO NUCLEAR MAGNETON RATIO", -2.127625307d0, 0.000000025d0, " ") 

type(t_constant), parameter :: codata_constant_141=t_constant(&
"HELION MASS", 5.0064127796d-27, 0.0000000015d-27, "kg") 

type(t_constant), parameter :: codata_constant_142=t_constant(&
"HELION MASS ENERGY EQUIVALENT", 4.4995394125d-10, 0.0000000014d-10, "J") 

type(t_constant), parameter :: codata_constant_143=t_constant(&
"HELION MASS ENERGY EQUIVALENT IN MEV", 2808.39160743d0, 0.00000085d0, "MeV") 

type(t_constant), parameter :: codata_constant_144=t_constant(&
"HELION MASS IN U", 3.014932247175d0, 0.000000000097d0, "u") 

type(t_constant), parameter :: codata_constant_145=t_constant(&
"HELION MOLAR MASS", 3.01493224613d-3, 0.00000000091d-3, "kg mol^-1") 

type(t_constant), parameter :: codata_constant_146=t_constant(&
"HELION-PROTON MASS RATIO", 2.99315267167d0, 0.00000000013d0, " ") 

type(t_constant), parameter :: codata_constant_147=t_constant(&
"HELION RELATIVE ATOMIC MASS", 3.014932247175d0, 0.000000000097d0, " ") 

type(t_constant), parameter :: codata_constant_148=t_constant(&
"HELION SHIELDING SHIFT", 5.996743d-5, 0.000010d-5, " ") 

type(t_constant), parameter :: codata_constant_149=t_constant(&
"HERTZ-ATOMIC MASS UNIT RELATIONSHIP", 4.4398216652d-24, 0.0000000013d-24, "u") 

type(t_constant), parameter :: codata_constant_150=t_constant(&
"HERTZ-ELECTRON VOLT RELATIONSHIP", 4.135667696d-15, 0.0d0, "eV") 

type(t_constant), parameter :: codata_constant_151=t_constant(&
"HERTZ-HARTREE RELATIONSHIP", 1.5198298460570d-16, 0.0000000000029d-16, "E_h") 

type(t_constant), parameter :: codata_constant_152=t_constant(&
"HERTZ-INVERSE METER RELATIONSHIP", 3.335640951d-9, 0.0d0, "m^-1") 

type(t_constant), parameter :: codata_constant_153=t_constant(&
"HERTZ-JOULE RELATIONSHIP", 6.62607015d-34, 0.0d0, "J") 

type(t_constant), parameter :: codata_constant_154=t_constant(&
"HERTZ-KELVIN RELATIONSHIP", 4.799243073d-11, 0.0d0, "K") 

type(t_constant), parameter :: codata_constant_155=t_constant(&
"HERTZ-KILOGRAM RELATIONSHIP", 7.372497323d-51, 0.0d0, "kg") 

type(t_constant), parameter :: codata_constant_156=t_constant(&
"HYPERFINE TRANSITION FREQUENCY OF CS-133", 9192631770.0d0, 0.0d0, "Hz") 

type(t_constant), parameter :: codata_constant_157=t_constant(&
"INVERSE FINE-STRUCTURE CONSTANT", 137.035999084d0, 0.000000021d0, " ") 

type(t_constant), parameter :: codata_constant_158=t_constant(&
"INVERSE METER-ATOMIC MASS UNIT RELATIONSHIP", 1.33102505010d-15, 0.00000000040d-15, "u") 

type(t_constant), parameter :: codata_constant_159=t_constant(&
"INVERSE METER-ELECTRON VOLT RELATIONSHIP", 1.239841984d-6, 0.0d0, "eV") 

type(t_constant), parameter :: codata_constant_160=t_constant(&
"INVERSE METER-HARTREE RELATIONSHIP", 4.5563352529120d-8, 0.0000000000088d-8, "E_h") 

type(t_constant), parameter :: codata_constant_161=t_constant(&
"INVERSE METER-HERTZ RELATIONSHIP", 299792458.0d0, 0.0d0, "Hz") 

type(t_constant), parameter :: codata_constant_162=t_constant(&
"INVERSE METER-JOULE RELATIONSHIP", 1.986445857d-25, 0.0d0, "J") 

type(t_constant), parameter :: codata_constant_163=t_constant(&
"INVERSE METER-KELVIN RELATIONSHIP", 1.438776877d-2, 0.0d0, "K") 

type(t_constant), parameter :: codata_constant_164=t_constant(&
"INVERSE METER-KILOGRAM RELATIONSHIP", 2.210219094d-42, 0.0d0, "kg") 

type(t_constant), parameter :: codata_constant_165=t_constant(&
"INVERSE OF CONDUCTANCE QUANTUM", 12906.40372d0, 0.0d0, "ohm") 

type(t_constant), parameter :: codata_constant_166=t_constant(&
"JOSEPHSON CONSTANT", 483597.8484d9, 0.0d0, "Hz V^-1") 

type(t_constant), parameter :: codata_constant_167=t_constant(&
"JOULE-ATOMIC MASS UNIT RELATIONSHIP", 6.7005352565d9, 0.0000000020d9, "u") 

type(t_constant), parameter :: codata_constant_168=t_constant(&
"JOULE-ELECTRON VOLT RELATIONSHIP", 6.241509074d18, 0.0d0, "eV") 

type(t_constant), parameter :: codata_constant_169=t_constant(&
"JOULE-HARTREE RELATIONSHIP", 2.2937122783963d17, 0.0000000000045d17, "E_h") 

type(t_constant), parameter :: codata_constant_170=t_constant(&
"JOULE-HERTZ RELATIONSHIP", 1.509190179d33, 0.0d0, "Hz") 

type(t_constant), parameter :: codata_constant_171=t_constant(&
"JOULE-INVERSE METER RELATIONSHIP", 5.034116567d24, 0.0d0, "m^-1") 

type(t_constant), parameter :: codata_constant_172=t_constant(&
"JOULE-KELVIN RELATIONSHIP", 7.242970516d22, 0.0d0, "K") 

type(t_constant), parameter :: codata_constant_173=t_constant(&
"JOULE-KILOGRAM RELATIONSHIP", 1.112650056d-17, 0.0d0, "kg") 

type(t_constant), parameter :: codata_constant_174=t_constant(&
"KELVIN-ATOMIC MASS UNIT RELATIONSHIP", 9.2510873014d-14, 0.0000000028d-14, "u") 

type(t_constant), parameter :: codata_constant_175=t_constant(&
"KELVIN-ELECTRON VOLT RELATIONSHIP", 8.617333262d-5, 0.0d0, "eV") 

type(t_constant), parameter :: codata_constant_176=t_constant(&
"KELVIN-HARTREE RELATIONSHIP", 3.1668115634556d-6, 0.0000000000061d-6, "E_h") 

type(t_constant), parameter :: codata_constant_177=t_constant(&
"KELVIN-HERTZ RELATIONSHIP", 2.083661912d10, 0.0d0, "Hz") 

type(t_constant), parameter :: codata_constant_178=t_constant(&
"KELVIN-INVERSE METER RELATIONSHIP", 69.50348004d0, 0.0d0, "m^-1") 

type(t_constant), parameter :: codata_constant_179=t_constant(&
"KELVIN-JOULE RELATIONSHIP", 1.380649d-23, 0.0d0, "J") 

type(t_constant), parameter :: codata_constant_180=t_constant(&
"KELVIN-KILOGRAM RELATIONSHIP", 1.536179187d-40, 0.0d0, "kg") 

type(t_constant), parameter :: codata_constant_181=t_constant(&
"KILOGRAM-ATOMIC MASS UNIT RELATIONSHIP", 6.0221407621d26, 0.0000000018d26, "u") 

type(t_constant), parameter :: codata_constant_182=t_constant(&
"KILOGRAM-ELECTRON VOLT RELATIONSHIP", 5.609588603d35, 0.0d0, "eV") 

type(t_constant), parameter :: codata_constant_183=t_constant(&
"KILOGRAM-HARTREE RELATIONSHIP", 2.0614857887409d34, 0.0000000000040d34, "E_h") 

type(t_constant), parameter :: codata_constant_184=t_constant(&
"KILOGRAM-HERTZ RELATIONSHIP", 1.356392489d50, 0.0d0, "Hz") 

type(t_constant), parameter :: codata_constant_185=t_constant(&
"KILOGRAM-INVERSE METER RELATIONSHIP", 4.524438335d41, 0.0d0, "m^-1") 

type(t_constant), parameter :: codata_constant_186=t_constant(&
"KILOGRAM-JOULE RELATIONSHIP", 8.987551787d16, 0.0d0, "J") 

type(t_constant), parameter :: codata_constant_187=t_constant(&
"KILOGRAM-KELVIN RELATIONSHIP", 6.509657260d39, 0.0d0, "K") 

type(t_constant), parameter :: codata_constant_188=t_constant(&
"LATTICE PARAMETER OF SILICON", 5.431020511d-10, 0.000000089d-10, "m") 

type(t_constant), parameter :: codata_constant_189=t_constant(&
"LATTICE SPACING OF IDEAL SI (220", 1.920155716d-10, 0.000000032d-10, "m") 

type(t_constant), parameter :: codata_constant_190=t_constant(&
"LOSCHMIDT CONSTANT (273.15 K, 100 KPA", 2.651645804d25, 0.0d0, "m^-3") 

type(t_constant), parameter :: codata_constant_191=t_constant(&
"LOSCHMIDT CONSTANT (273.15 K, 101.325 KPA", 2.686780111d25, 0.0d0, "m^-3") 

type(t_constant), parameter :: codata_constant_192=t_constant(&
"LUMINOUS EFFICACY", 683.0d0, 0.0d0, "lm W^-1") 

type(t_constant), parameter :: codata_constant_193=t_constant(&
"MAG. FLUX QUANTUM", 2.067833848d-15, 0.0d0, "Wb") 

type(t_constant), parameter :: codata_constant_194=t_constant(&
"MOLAR GAS CONSTANT", 8.314462618d0, 0.0d0, "J mol^-1 K^-1") 

type(t_constant), parameter :: codata_constant_195=t_constant(&
"MOLAR MASS CONSTANT", 0.99999999965d-3, 0.00000000030d-3, "kg mol^-1") 

type(t_constant), parameter :: codata_constant_196=t_constant(&
"MOLAR MASS OF CARBON-12", 11.9999999958d-3, 0.0000000036d-3, "kg mol^-1") 

type(t_constant), parameter :: codata_constant_197=t_constant(&
"MOLAR PLANCK CONSTANT", 3.990312712d-10, 0.0d0, "J Hz^-1 mol^-1") 

type(t_constant), parameter :: codata_constant_198=t_constant(&
"MOLAR VOLUME OF IDEAL GAS (273.15 K, 100 KPA", 22.71095464d-3, 0.0d0, "m^3 mol^-1") 

type(t_constant), parameter :: codata_constant_199=t_constant(&
"MOLAR VOLUME OF IDEAL GAS (273.15 K, 101.325 KPA", 22.41396954d-3, 0.0d0, "m^3 mol^-1") 

type(t_constant), parameter :: codata_constant_200=t_constant(&
"MOLAR VOLUME OF SILICON", 1.205883199d-5, 0.000000060d-5, "m^3 mol^-1") 

type(t_constant), parameter :: codata_constant_201=t_constant(&
"MOLYBDENUM X UNIT", 1.00209952d-13, 0.00000053d-13, "m") 

type(t_constant), parameter :: codata_constant_202=t_constant(&
"MUON COMPTON WAVELENGTH", 1.173444110d-14, 0.000000026d-14, "m") 

type(t_constant), parameter :: codata_constant_203=t_constant(&
"MUON-ELECTRON MASS RATIO", 206.7682830d0, 0.0000046d0, " ") 

type(t_constant), parameter :: codata_constant_204=t_constant(&
"MUON G FACTOR", -2.0023318418d0, 0.0000000013d0, " ") 

type(t_constant), parameter :: codata_constant_205=t_constant(&
"MUON MAG. MOM", -4.49044830d-26, 0.00000010d-26, "J T^-1") 

type(t_constant), parameter :: codata_constant_206=t_constant(&
"MUON MAG. MOM. ANOMALY", 1.16592089d-3, 0.00000063d-3, " ") 

type(t_constant), parameter :: codata_constant_207=t_constant(&
"MUON MAG. MOM. TO BOHR MAGNETON RATIO", -4.84197047d-3, 0.00000011d-3, " ") 

type(t_constant), parameter :: codata_constant_208=t_constant(&
"MUON MAG. MOM. TO NUCLEAR MAGNETON RATIO", -8.89059703d0, 0.00000020d0, " ") 

type(t_constant), parameter :: codata_constant_209=t_constant(&
"MUON MASS", 1.883531627d-28, 0.000000042d-28, "kg") 

type(t_constant), parameter :: codata_constant_210=t_constant(&
"MUON MASS ENERGY EQUIVALENT", 1.692833804d-11, 0.000000038d-11, "J") 

type(t_constant), parameter :: codata_constant_211=t_constant(&
"MUON MASS ENERGY EQUIVALENT IN MEV", 105.6583755d0, 0.0000023d0, "MeV") 

type(t_constant), parameter :: codata_constant_212=t_constant(&
"MUON MASS IN U", 0.1134289259d0, 0.0000000025d0, "u") 

type(t_constant), parameter :: codata_constant_213=t_constant(&
"MUON MOLAR MASS", 1.134289259d-4, 0.000000025d-4, "kg mol^-1") 

type(t_constant), parameter :: codata_constant_214=t_constant(&
"MUON-NEUTRON MASS RATIO", 0.1124545170d0, 0.0000000025d0, " ") 

type(t_constant), parameter :: codata_constant_215=t_constant(&
"MUON-PROTON MAG. MOM. RATIO", -3.183345142d0, 0.000000071d0, " ") 

type(t_constant), parameter :: codata_constant_216=t_constant(&
"MUON-PROTON MASS RATIO", 0.1126095264d0, 0.0000000025d0, " ") 

type(t_constant), parameter :: codata_constant_217=t_constant(&
"MUON-TAU MASS RATIO", 5.94635d-2, 0.00040d-2, " ") 

type(t_constant), parameter :: codata_constant_218=t_constant(&
"NATURAL UNIT OF ACTION", 1.054571817d-34, 0.0d0, "J s") 

type(t_constant), parameter :: codata_constant_219=t_constant(&
"NATURAL UNIT OF ACTION IN EV S", 6.582119569d-16, 0.0d0, "eV s") 

type(t_constant), parameter :: codata_constant_220=t_constant(&
"NATURAL UNIT OF ENERGY", 8.1871057769d-14, 0.0000000025d-14, "J") 

type(t_constant), parameter :: codata_constant_221=t_constant(&
"NATURAL UNIT OF ENERGY IN MEV", 0.51099895000d0, 0.00000000015d0, "MeV") 

type(t_constant), parameter :: codata_constant_222=t_constant(&
"NATURAL UNIT OF LENGTH", 3.8615926796d-13, 0.0000000012d-13, "m") 

type(t_constant), parameter :: codata_constant_223=t_constant(&
"NATURAL UNIT OF MASS", 9.1093837015d-31, 0.0000000028d-31, "kg") 

type(t_constant), parameter :: codata_constant_224=t_constant(&
"NATURAL UNIT OF MOMENTUM", 2.73092453075d-22, 0.00000000082d-22, "kg m s^-1") 

type(t_constant), parameter :: codata_constant_225=t_constant(&
"NATURAL UNIT OF MOMENTUM IN MEV/C", 0.51099895000d0, 0.00000000015d0, "MeV/c") 

type(t_constant), parameter :: codata_constant_226=t_constant(&
"NATURAL UNIT OF TIME", 1.28808866819d-21, 0.00000000039d-21, "s") 

type(t_constant), parameter :: codata_constant_227=t_constant(&
"NATURAL UNIT OF VELOCITY", 299792458.0d0, 0.0d0, "m s^-1") 

type(t_constant), parameter :: codata_constant_228=t_constant(&
"NEUTRON COMPTON WAVELENGTH", 1.31959090581d-15, 0.00000000075d-15, "m") 

type(t_constant), parameter :: codata_constant_229=t_constant(&
"NEUTRON-ELECTRON MAG. MOM. RATIO", 1.04066882d-3, 0.00000025d-3, " ") 

type(t_constant), parameter :: codata_constant_230=t_constant(&
"NEUTRON-ELECTRON MASS RATIO", 1838.68366173d0, 0.00000089d0, " ") 

type(t_constant), parameter :: codata_constant_231=t_constant(&
"NEUTRON G FACTOR", -3.82608545d0, 0.00000090d0, " ") 

type(t_constant), parameter :: codata_constant_232=t_constant(&
"NEUTRON GYROMAG. RATIO", 1.83247171d8, 0.00000043d8, "s^-1 T^-1") 

type(t_constant), parameter :: codata_constant_233=t_constant(&
"NEUTRON GYROMAG. RATIO IN MHZ/T", 29.1646931d0, 0.0000069d0, "MHz T^-1") 

type(t_constant), parameter :: codata_constant_234=t_constant(&
"NEUTRON MAG. MOM", -9.6623651d-27, 0.0000023d-27, "J T^-1") 

type(t_constant), parameter :: codata_constant_235=t_constant(&
"NEUTRON MAG. MOM. TO BOHR MAGNETON RATIO", -1.04187563d-3, 0.00000025d-3, " ") 

type(t_constant), parameter :: codata_constant_236=t_constant(&
"NEUTRON MAG. MOM. TO NUCLEAR MAGNETON RATIO", -1.91304273d0, 0.00000045d0, " ") 

type(t_constant), parameter :: codata_constant_237=t_constant(&
"NEUTRON MASS", 1.67492749804d-27, 0.00000000095d-27, "kg") 

type(t_constant), parameter :: codata_constant_238=t_constant(&
"NEUTRON MASS ENERGY EQUIVALENT", 1.50534976287d-10, 0.00000000086d-10, "J") 

type(t_constant), parameter :: codata_constant_239=t_constant(&
"NEUTRON MASS ENERGY EQUIVALENT IN MEV", 939.56542052d0, 0.00000054d0, "MeV") 

type(t_constant), parameter :: codata_constant_240=t_constant(&
"NEUTRON MASS IN U", 1.00866491595d0, 0.00000000049d0, "u") 

type(t_constant), parameter :: codata_constant_241=t_constant(&
"NEUTRON MOLAR MASS", 1.00866491560d-3, 0.00000000057d-3, "kg mol^-1") 

type(t_constant), parameter :: codata_constant_242=t_constant(&
"NEUTRON-MUON MASS RATIO", 8.89248406d0, 0.00000020d0, " ") 

type(t_constant), parameter :: codata_constant_243=t_constant(&
"NEUTRON-PROTON MAG. MOM. RATIO", -0.68497934d0, 0.00000016d0, " ") 

type(t_constant), parameter :: codata_constant_244=t_constant(&
"NEUTRON-PROTON MASS DIFFERENCE", 2.30557435d-30, 0.00000082d-30, "kg") 

type(t_constant), parameter :: codata_constant_245=t_constant(&
"NEUTRON-PROTON MASS DIFFERENCE ENERGY EQUIVALENT", 2.07214689d-13, 0.00000074d-13, "J") 

type(t_constant), parameter :: codata_constant_246=t_constant(&
"NEUTRON-PROTON MASS DIFFERENCE ENERGY EQUIVALENT IN MEV", 1.29333236d0, 0.00000046d0, "MeV") 

type(t_constant), parameter :: codata_constant_247=t_constant(&
"NEUTRON-PROTON MASS DIFFERENCE IN U", 1.38844933d-3, 0.00000049d-3, "u") 

type(t_constant), parameter :: codata_constant_248=t_constant(&
"NEUTRON-PROTON MASS RATIO", 1.00137841931d0, 0.00000000049d0, " ") 

type(t_constant), parameter :: codata_constant_249=t_constant(&
"NEUTRON RELATIVE ATOMIC MASS", 1.00866491595d0, 0.00000000049d0, " ") 

type(t_constant), parameter :: codata_constant_250=t_constant(&
"NEUTRON-TAU MASS RATIO", 0.528779d0, 0.000036d0, " ") 

type(t_constant), parameter :: codata_constant_251=t_constant(&
"NEUTRON TO SHIELDED PROTON MAG. MOM. RATIO", -0.68499694d0, 0.00000016d0, " ") 

type(t_constant), parameter :: codata_constant_252=t_constant(&
"NEWTONIAN CONSTANT OF GRAVITATION", 6.67430d-11, 0.00015d-11, "m^3 kg^-1 s^-2") 

type(t_constant), parameter :: codata_constant_253=t_constant(&
"NEWTONIAN CONSTANT OF GRAVITATION OVER H-BAR C", 6.70883d-39, 0.00015d-39, "(GeV/c^2)^-2") 

type(t_constant), parameter :: codata_constant_254=t_constant(&
"NUCLEAR MAGNETON", 5.0507837461d-27, 0.0000000015d-27, "J T^-1") 

type(t_constant), parameter :: codata_constant_255=t_constant(&
"NUCLEAR MAGNETON IN EV/T", 3.15245125844d-8, 0.00000000096d-8, "eV T^-1") 

type(t_constant), parameter :: codata_constant_256=t_constant(&
"NUCLEAR MAGNETON IN INVERSE METER PER TESLA", 2.54262341353d-2, 0.00000000078d-2, "m^-1 T^-1") 

type(t_constant), parameter :: codata_constant_257=t_constant(&
"NUCLEAR MAGNETON IN K/T", 3.6582677756d-4, 0.0000000011d-4, "K T^-1") 

type(t_constant), parameter :: codata_constant_258=t_constant(&
"NUCLEAR MAGNETON IN MHZ/T", 7.6225932291d0, 0.0000000023d0, "MHz T^-1") 

type(t_constant), parameter :: codata_constant_259=t_constant(&
"PLANCK CONSTANT", 6.62607015d-34, 0.0d0, "J Hz^-1") 

type(t_constant), parameter :: codata_constant_260=t_constant(&
"PLANCK CONSTANT IN EV/HZ", 4.135667696d-15, 0.0d0, "eV Hz^-1") 

type(t_constant), parameter :: codata_constant_261=t_constant(&
"PLANCK LENGTH", 1.616255d-35, 0.000018d-35, "m") 

type(t_constant), parameter :: codata_constant_262=t_constant(&
"PLANCK MASS", 2.176434d-8, 0.000024d-8, "kg") 

type(t_constant), parameter :: codata_constant_263=t_constant(&
"PLANCK MASS ENERGY EQUIVALENT IN GEV", 1.220890d19, 0.000014d19, "GeV") 

type(t_constant), parameter :: codata_constant_264=t_constant(&
"PLANCK TEMPERATURE", 1.416784d32, 0.000016d32, "K") 

type(t_constant), parameter :: codata_constant_265=t_constant(&
"PLANCK TIME", 5.391247d-44, 0.000060d-44, "s") 

type(t_constant), parameter :: codata_constant_266=t_constant(&
"PROTON CHARGE TO MASS QUOTIENT", 9.5788331560d7, 0.0000000029d7, "C kg^-1") 

type(t_constant), parameter :: codata_constant_267=t_constant(&
"PROTON COMPTON WAVELENGTH", 1.32140985539d-15, 0.00000000040d-15, "m") 

type(t_constant), parameter :: codata_constant_268=t_constant(&
"PROTON-ELECTRON MASS RATIO", 1836.15267343d0, 0.00000011d0, " ") 

type(t_constant), parameter :: codata_constant_269=t_constant(&
"PROTON G FACTOR", 5.5856946893d0, 0.0000000016d0, " ") 

type(t_constant), parameter :: codata_constant_270=t_constant(&
"PROTON GYROMAG. RATIO", 2.6752218744d8, 0.0000000011d8, "s^-1 T^-1") 

type(t_constant), parameter :: codata_constant_271=t_constant(&
"PROTON GYROMAG. RATIO IN MHZ/T", 42.577478518d0, 0.000000018d0, "MHz T^-1") 

type(t_constant), parameter :: codata_constant_272=t_constant(&
"PROTON MAG. MOM", 1.41060679736d-26, 0.00000000060d-26, "J T^-1") 

type(t_constant), parameter :: codata_constant_273=t_constant(&
"PROTON MAG. MOM. TO BOHR MAGNETON RATIO", 1.52103220230d-3, 0.00000000046d-3, " ") 

type(t_constant), parameter :: codata_constant_274=t_constant(&
"PROTON MAG. MOM. TO NUCLEAR MAGNETON RATIO", 2.79284734463d0, 0.00000000082d0, " ") 

type(t_constant), parameter :: codata_constant_275=t_constant(&
"PROTON MAG. SHIELDING CORRECTION", 2.5689d-5, 0.0011d-5, " ") 

type(t_constant), parameter :: codata_constant_276=t_constant(&
"PROTON MASS", 1.67262192369d-27, 0.00000000051d-27, "kg") 

type(t_constant), parameter :: codata_constant_277=t_constant(&
"PROTON MASS ENERGY EQUIVALENT", 1.50327761598d-10, 0.00000000046d-10, "J") 

type(t_constant), parameter :: codata_constant_278=t_constant(&
"PROTON MASS ENERGY EQUIVALENT IN MEV", 938.27208816d0, 0.00000029d0, "MeV") 

type(t_constant), parameter :: codata_constant_279=t_constant(&
"PROTON MASS IN U", 1.007276466621d0, 0.000000000053d0, "u") 

type(t_constant), parameter :: codata_constant_280=t_constant(&
"PROTON MOLAR MASS", 1.00727646627d-3, 0.00000000031d-3, "kg mol^-1") 

type(t_constant), parameter :: codata_constant_281=t_constant(&
"PROTON-MUON MASS RATIO", 8.88024337d0, 0.00000020d0, " ") 

type(t_constant), parameter :: codata_constant_282=t_constant(&
"PROTON-NEUTRON MAG. MOM. RATIO", -1.45989805d0, 0.00000034d0, " ") 

type(t_constant), parameter :: codata_constant_283=t_constant(&
"PROTON-NEUTRON MASS RATIO", 0.99862347812d0, 0.00000000049d0, " ") 

type(t_constant), parameter :: codata_constant_284=t_constant(&
"PROTON RELATIVE ATOMIC MASS", 1.007276466621d0, 0.000000000053d0, " ") 

type(t_constant), parameter :: codata_constant_285=t_constant(&
"PROTON RMS CHARGE RADIUS", 8.414d-16, 0.019d-16, "m") 

type(t_constant), parameter :: codata_constant_286=t_constant(&
"PROTON-TAU MASS RATIO", 0.528051d0, 0.000036d0, " ") 

type(t_constant), parameter :: codata_constant_287=t_constant(&
"QUANTUM OF CIRCULATION", 3.6369475516d-4, 0.0000000011d-4, "m^2 s^-1") 

type(t_constant), parameter :: codata_constant_288=t_constant(&
"QUANTUM OF CIRCULATION TIMES 2", 7.2738951032d-4, 0.0000000022d-4, "m^2 s^-1") 

type(t_constant), parameter :: codata_constant_289=t_constant(&
"REDUCED COMPTON WAVELENGTH", 3.8615926796d-13, 0.0000000012d-13, "m") 

type(t_constant), parameter :: codata_constant_290=t_constant(&
"REDUCED MUON COMPTON WAVELENGTH", 1.867594306d-15, 0.000000042d-15, "m") 

type(t_constant), parameter :: codata_constant_291=t_constant(&
"REDUCED NEUTRON COMPTON WAVELENGTH", 2.1001941552d-16, 0.0000000012d-16, "m") 

type(t_constant), parameter :: codata_constant_292=t_constant(&
"REDUCED PLANCK CONSTANT", 1.054571817d-34, 0.0d0, "J s") 

type(t_constant), parameter :: codata_constant_293=t_constant(&
"REDUCED PLANCK CONSTANT IN EV S", 6.582119569d-16, 0.0d0, "eV s") 

type(t_constant), parameter :: codata_constant_294=t_constant(&
"REDUCED PLANCK CONSTANT TIMES C IN MEV FM", 197.3269804d0, 0.0d0, "MeV fm") 

type(t_constant), parameter :: codata_constant_295=t_constant(&
"REDUCED PROTON COMPTON WAVELENGTH", 2.10308910336d-16, 0.00000000064d-16, "m") 

type(t_constant), parameter :: codata_constant_296=t_constant(&
"REDUCED TAU COMPTON WAVELENGTH", 1.110538d-16, 0.000075d-16, "m") 

type(t_constant), parameter :: codata_constant_297=t_constant(&
"RYDBERG CONSTANT", 10973731.568160d0, 0.000021d0, "m^-1") 

type(t_constant), parameter :: codata_constant_298=t_constant(&
"RYDBERG CONSTANT TIMES C IN HZ", 3.2898419602508d15, 0.0000000000064d15, "Hz") 

type(t_constant), parameter :: codata_constant_299=t_constant(&
"RYDBERG CONSTANT TIMES HC IN EV", 13.605693122994d0, 0.000000000026d0, "eV") 

type(t_constant), parameter :: codata_constant_300=t_constant(&
"RYDBERG CONSTANT TIMES HC IN J", 2.1798723611035d-18, 0.0000000000042d-18, "J") 

type(t_constant), parameter :: codata_constant_301=t_constant(&
"SACKUR-TETRODE CONSTANT (1 K, 100 KPA", -1.15170753706d0, 0.00000000045d0, " ") 

type(t_constant), parameter :: codata_constant_302=t_constant(&
"SACKUR-TETRODE CONSTANT (1 K, 101.325 KPA", -1.16487052358d0, 0.00000000045d0, " ") 

type(t_constant), parameter :: codata_constant_303=t_constant(&
"SECOND RADIATION CONSTANT", 1.438776877d-2, 0.0d0, "m K") 

type(t_constant), parameter :: codata_constant_304=t_constant(&
"SHIELDED HELION GYROMAG. RATIO", 2.037894569d8, 0.000000024d8, "s^-1 T^-1") 

type(t_constant), parameter :: codata_constant_305=t_constant(&
"SHIELDED HELION GYROMAG. RATIO IN MHZ/T", 32.43409942d0, 0.00000038d0, "MHz T^-1") 

type(t_constant), parameter :: codata_constant_306=t_constant(&
"SHIELDED HELION MAG. MOM", -1.074553090d-26, 0.000000013d-26, "J T^-1") 

type(t_constant), parameter :: codata_constant_307=t_constant(&
"SHIELDED HELION MAG. MOM. TO BOHR MAGNETON RATIO", -1.158671471d-3, 0.000000014d-3, " ") 

type(t_constant), parameter :: codata_constant_308=t_constant(&
"SHIELDED HELION MAG. MOM. TO NUCLEAR MAGNETON RATIO", -2.127497719d0, 0.000000025d0, " ") 

type(t_constant), parameter :: codata_constant_309=t_constant(&
"SHIELDED HELION TO PROTON MAG. MOM. RATIO", -0.7617665618d0, 0.0000000089d0, " ") 

type(t_constant), parameter :: codata_constant_310=t_constant(&
"SHIELDED HELION TO SHIELDED PROTON MAG. MOM. RATIO", -0.7617861313d0, 0.0000000033d0, " ") 

type(t_constant), parameter :: codata_constant_311=t_constant(&
"SHIELDED PROTON GYROMAG. RATIO", 2.675153151d8, 0.000000029d8, "s^-1 T^-1") 

type(t_constant), parameter :: codata_constant_312=t_constant(&
"SHIELDED PROTON GYROMAG. RATIO IN MHZ/T", 42.57638474d0, 0.00000046d0, "MHz T^-1") 

type(t_constant), parameter :: codata_constant_313=t_constant(&
"SHIELDED PROTON MAG. MOM", 1.410570560d-26, 0.000000015d-26, "J T^-1") 

type(t_constant), parameter :: codata_constant_314=t_constant(&
"SHIELDED PROTON MAG. MOM. TO BOHR MAGNETON RATIO", 1.520993128d-3, 0.000000017d-3, " ") 

type(t_constant), parameter :: codata_constant_315=t_constant(&
"SHIELDED PROTON MAG. MOM. TO NUCLEAR MAGNETON RATIO", 2.792775599d0, 0.000000030d0, " ") 

type(t_constant), parameter :: codata_constant_316=t_constant(&
"SHIELDING DIFFERENCE OF D AND P IN HD", 2.0200d-8, 0.0020d-8, " ") 

type(t_constant), parameter :: codata_constant_317=t_constant(&
"SHIELDING DIFFERENCE OF T AND P IN HT", 2.4140d-8, 0.0020d-8, " ") 

type(t_constant), parameter :: codata_constant_318=t_constant(&
"SPEED OF LIGHT IN VACUUM", 299792458.0d0, 0.0d0, "m s^-1") 

type(t_constant), parameter :: codata_constant_319=t_constant(&
"STANDARD ACCELERATION OF GRAVITY", 9.80665d0, 0.0d0, "m s^-2") 

type(t_constant), parameter :: codata_constant_320=t_constant(&
"STANDARD ATMOSPHERE", 101325.0d0, 0.0d0, "Pa") 

type(t_constant), parameter :: codata_constant_321=t_constant(&
"STANDARD-STATE PRESSURE", 100000.0d0, 0.0d0, "Pa") 

type(t_constant), parameter :: codata_constant_322=t_constant(&
"STEFAN-BOLTZMANN CONSTANT", 5.670374419d-8, 0.0d0, "W m^-2 K^-4") 

type(t_constant), parameter :: codata_constant_323=t_constant(&
"TAU COMPTON WAVELENGTH", 6.97771d-16, 0.00047d-16, "m") 

type(t_constant), parameter :: codata_constant_324=t_constant(&
"TAU-ELECTRON MASS RATIO", 3477.23d0, 0.23d0, " ") 

type(t_constant), parameter :: codata_constant_325=t_constant(&
"TAU ENERGY EQUIVALENT", 1776.86d0, 0.12d0, "MeV") 

type(t_constant), parameter :: codata_constant_326=t_constant(&
"TAU MASS", 3.16754d-27, 0.00021d-27, "kg") 

type(t_constant), parameter :: codata_constant_327=t_constant(&
"TAU MASS ENERGY EQUIVALENT", 2.84684d-10, 0.00019d-10, "J") 

type(t_constant), parameter :: codata_constant_328=t_constant(&
"TAU MASS IN U", 1.90754d0, 0.00013d0, "u") 

type(t_constant), parameter :: codata_constant_329=t_constant(&
"TAU MOLAR MASS", 1.90754d-3, 0.00013d-3, "kg mol^-1") 

type(t_constant), parameter :: codata_constant_330=t_constant(&
"TAU-MUON MASS RATIO", 16.8170d0, 0.0011d0, " ") 

type(t_constant), parameter :: codata_constant_331=t_constant(&
"TAU-NEUTRON MASS RATIO", 1.89115d0, 0.00013d0, " ") 

type(t_constant), parameter :: codata_constant_332=t_constant(&
"TAU-PROTON MASS RATIO", 1.89376d0, 0.00013d0, " ") 

type(t_constant), parameter :: codata_constant_333=t_constant(&
"THOMSON CROSS SECTION", 6.6524587321d-29, 0.0000000060d-29, "m^2") 

type(t_constant), parameter :: codata_constant_334=t_constant(&
"TRITON-ELECTRON MASS RATIO", 5496.92153573d0, 0.00000027d0, " ") 

type(t_constant), parameter :: codata_constant_335=t_constant(&
"TRITON G FACTOR", 5.957924931d0, 0.000000012d0, " ") 

type(t_constant), parameter :: codata_constant_336=t_constant(&
"TRITON MAG. MOM", 1.5046095202d-26, 0.0000000030d-26, "J T^-1") 

type(t_constant), parameter :: codata_constant_337=t_constant(&
"TRITON MAG. MOM. TO BOHR MAGNETON RATIO", 1.6223936651d-3, 0.0000000032d-3, " ") 

type(t_constant), parameter :: codata_constant_338=t_constant(&
"TRITON MAG. MOM. TO NUCLEAR MAGNETON RATIO", 2.9789624656d0, 0.0000000059d0, " ") 

type(t_constant), parameter :: codata_constant_339=t_constant(&
"TRITON MASS", 5.0073567446d-27, 0.0000000015d-27, "kg") 

type(t_constant), parameter :: codata_constant_340=t_constant(&
"TRITON MASS ENERGY EQUIVALENT", 4.5003878060d-10, 0.0000000014d-10, "J") 

type(t_constant), parameter :: codata_constant_341=t_constant(&
"TRITON MASS ENERGY EQUIVALENT IN MEV", 2808.92113298d0, 0.00000085d0, "MeV") 

type(t_constant), parameter :: codata_constant_342=t_constant(&
"TRITON MASS IN U", 3.01550071621d0, 0.00000000012d0, "u") 

type(t_constant), parameter :: codata_constant_343=t_constant(&
"TRITON MOLAR MASS", 3.01550071517d-3, 0.00000000092d-3, "kg mol^-1") 

type(t_constant), parameter :: codata_constant_344=t_constant(&
"TRITON-PROTON MASS RATIO", 2.99371703414d0, 0.00000000015d0, " ") 

type(t_constant), parameter :: codata_constant_345=t_constant(&
"TRITON RELATIVE ATOMIC MASS", 3.01550071621d0, 0.00000000012d0, " ") 

type(t_constant), parameter :: codata_constant_346=t_constant(&
"TRITON TO PROTON MAG. MOM. RATIO", 1.0666399191d0, 0.0000000021d0, " ") 

type(t_constant), parameter :: codata_constant_347=t_constant(&
"UNIFIED ATOMIC MASS UNIT", 1.66053906660d-27, 0.00000000050d-27, "kg") 

type(t_constant), parameter :: codata_constant_348=t_constant(&
"VACUUM ELECTRIC PERMITTIVITY", 8.8541878128d-12, 0.0000000013d-12, "F m^-1") 

type(t_constant), parameter :: codata_constant_349=t_constant(&
"VACUUM MAG. PERMEABILITY", 1.25663706212d-6, 0.00000000019d-6, "N A^-2") 

type(t_constant), parameter :: codata_constant_350=t_constant(&
"VON KLITZING CONSTANT", 25812.80745d0, 0.0d0, "ohm") 

end module codata_data
