!> @file
!! @brief Codata module - autogenerated.


!> @brief Codata constants
!! @details Autogenerated from NIST table.
module codata_last
use iso_fortran_env
use codata_base
implicit none
private

type(codata_t_constant), dimension(10), parameter :: codata10 = [&
  codata_t_constant("alpha particle-electron mass ratio", 7294.29954142d0, 0.00000024d0, " ") ,&
  codata_t_constant("alpha particle mass", 6.6446573357d-27, 0.0000000020d-27, "kg") ,&
  codata_t_constant("alpha particle mass energy equivalent", 5.9719201914d-10, 0.0000000018d-10, "J") ,&
  codata_t_constant("alpha particle mass energy equivalent in MeV", 3727.3794066d0, 0.0000011d0, "MeV") ,&
  codata_t_constant("alpha particle mass in u", 4.001506179127d0, 0.000000000063d0, "u") ,&
  codata_t_constant("alpha particle molar mass", 4.0015061777d-3, 0.0000000012d-3, "kg mol^-1") ,&
  codata_t_constant("alpha particle-proton mass ratio", 3.97259969009d0, 0.00000000022d0, " ") ,&
  codata_t_constant("alpha particle relative atomic mass", 4.001506179127d0, 0.000000000063d0, " ") ,&
  codata_t_constant("Angstrom star", 1.00001495d-10, 0.00000090d-10, "m") ,&
  codata_t_constant("atomic mass constant", 1.66053906660d-27, 0.00000000050d-27, "kg") ]

type(codata_t_constant), dimension(10), parameter :: codata20 = [&
  codata_t_constant("atomic mass constant energy equivalent", 1.49241808560d-10, 0.00000000045d-10, "J") ,&
  codata_t_constant("atomic mass constant energy equivalent in MeV", 931.49410242d0, 0.00000028d0, "MeV") ,&
  codata_t_constant("atomic mass unit-electron volt relationship", 9.3149410242d8, 0.0000000028d8, "eV") ,&
  codata_t_constant("atomic mass unit-hartree relationship", 3.4231776874d7, 0.0000000010d7, "E_h") ,&
  codata_t_constant("atomic mass unit-hertz relationship", 2.25234271871d23, 0.00000000068d23, "Hz") ,&
  codata_t_constant("atomic mass unit-inverse meter relationship", 7.5130066104d14, 0.0000000023d14, "m^-1") ,&
  codata_t_constant("atomic mass unit-joule relationship", 1.49241808560d-10, 0.00000000045d-10, "J") ,&
  codata_t_constant("atomic mass unit-kelvin relationship", 1.08095401916d13, 0.00000000033d13, "K") ,&
  codata_t_constant("atomic mass unit-kilogram relationship", 1.66053906660d-27, 0.00000000050d-27, "kg") ,&
  codata_t_constant("atomic unit of 1st hyperpolarizability", 3.2063613061d-53, 0.0000000015d-53, "C^3 m^3 J^-2") ]

type(codata_t_constant), dimension(10), parameter :: codata30 = [&
  codata_t_constant("atomic unit of 2nd hyperpolarizability", 6.2353799905d-65, 0.0000000038d-65, "C^4 m^4 J^-3") ,&
  codata_t_constant("atomic unit of action", 1.054571817d-34, 0.0d0, "J s") ,&
  codata_t_constant("atomic unit of charge", 1.602176634d-19, 0.0d0, "C") ,&
  codata_t_constant("atomic unit of charge density", 1.08120238457d12, 0.00000000049d12, "C m^-3") ,&
  codata_t_constant("atomic unit of current", 6.623618237510d-3, 0.000000000013d-3, "A") ,&
  codata_t_constant("atomic unit of electric dipole mom", 8.4783536255d-30, 0.0000000013d-30, "C m") ,&
  codata_t_constant("atomic unit of electric field", 5.14220674763d11, 0.00000000078d11, "V m^-1") ,&
  codata_t_constant("atomic unit of electric field gradient", 9.7173624292d21, 0.0000000029d21, "V m^-2") ,&
  codata_t_constant("atomic unit of electric polarizability", 1.64877727436d-41, 0.00000000050d-41, "C^2 m^2 J^-1") ,&
  codata_t_constant("atomic unit of electric potential", 27.211386245988d0, 0.000000000053d0, "V") ]

type(codata_t_constant), dimension(10), parameter :: codata40 = [&
  codata_t_constant("atomic unit of electric quadrupole mom", 4.4865515246d-40, 0.0000000014d-40, "C m^2") ,&
  codata_t_constant("atomic unit of energy", 4.3597447222071d-18, 0.0000000000085d-18, "J") ,&
  codata_t_constant("atomic unit of force", 8.2387234983d-8, 0.0000000012d-8, "N") ,&
  codata_t_constant("atomic unit of length", 5.29177210903d-11, 0.00000000080d-11, "m") ,&
  codata_t_constant("atomic unit of mag. dipole mom", 1.85480201566d-23, 0.00000000056d-23, "J T^-1") ,&
  codata_t_constant("atomic unit of mag. flux density", 2.35051756758d5, 0.00000000071d5, "T") ,&
  codata_t_constant("atomic unit of magnetizability", 7.8910366008d-29, 0.0000000048d-29, "J T^-2") ,&
  codata_t_constant("atomic unit of mass", 9.1093837015d-31, 0.0000000028d-31, "kg") ,&
  codata_t_constant("atomic unit of momentum", 1.99285191410d-24, 0.00000000030d-24, "kg m s^-1") ,&
  codata_t_constant("atomic unit of permittivity", 1.11265005545d-10, 0.00000000017d-10, "F m^-1") ]

type(codata_t_constant), dimension(10), parameter :: codata50 = [&
  codata_t_constant("atomic unit of time", 2.4188843265857d-17, 0.0000000000047d-17, "s") ,&
  codata_t_constant("atomic unit of velocity", 2.18769126364d6, 0.00000000033d6, "m s^-1") ,&
  codata_t_constant("Avogadro constant", 6.02214076d23, 0.0d0, "mol^-1") ,&
  codata_t_constant("Bohr magneton", 9.2740100783d-24, 0.0000000028d-24, "J T^-1") ,&
  codata_t_constant("Bohr magneton in eV/T", 5.7883818060d-5, 0.0000000017d-5, "eV T^-1") ,&
  codata_t_constant("Bohr magneton in Hz/T", 1.39962449361d10, 0.00000000042d10, "Hz T^-1") ,&
  codata_t_constant("Bohr magneton in inverse meter per tesla", 46.686447783d0, 0.000000014d0, "m^-1 T^-1") ,&
  codata_t_constant("Bohr magneton in K/T", 0.67171381563d0, 0.00000000020d0, "K T^-1") ,&
  codata_t_constant("Bohr radius", 5.29177210903d-11, 0.00000000080d-11, "m") ,&
  codata_t_constant("Boltzmann constant", 1.380649d-23, 0.0d0, "J K^-1") ]

type(codata_t_constant), dimension(10), parameter :: codata60 = [&
  codata_t_constant("Boltzmann constant in eV/K", 8.617333262d-5, 0.0d0, "eV K^-1") ,&
  codata_t_constant("Boltzmann constant in Hz/K", 2.083661912d10, 0.0d0, "Hz K^-1") ,&
  codata_t_constant("Boltzmann constant in inverse meter per kelvin", 69.50348004d0, 0.0d0, "m^-1 K^-1") ,&
  codata_t_constant("characteristic impedance of vacuum", 376.730313668d0, 0.000000057d0, "ohm") ,&
  codata_t_constant("classical electron radius", 2.8179403262d-15, 0.0000000013d-15, "m") ,&
  codata_t_constant("Compton wavelength", 2.42631023867d-12, 0.00000000073d-12, "m") ,&
  codata_t_constant("conductance quantum", 7.748091729d-5, 0.0d0, "S") ,&
  codata_t_constant("conventional value of ampere-90", 1.00000008887d0, 0.0d0, "A") ,&
  codata_t_constant("conventional value of coulomb-90", 1.00000008887d0, 0.0d0, "C") ,&
  codata_t_constant("conventional value of farad-90", 0.99999998220d0, 0.0d0, "F") ]

type(codata_t_constant), dimension(10), parameter :: codata70 = [&
  codata_t_constant("conventional value of henry-90", 1.00000001779d0, 0.0d0, "H") ,&
  codata_t_constant("conventional value of Josephson constant", 483597.9d9, 0.0d0, "Hz V^-1") ,&
  codata_t_constant("conventional value of ohm-90", 1.00000001779d0, 0.0d0, "ohm") ,&
  codata_t_constant("conventional value of volt-90", 1.00000010666d0, 0.0d0, "V") ,&
  codata_t_constant("conventional value of von Klitzing constant", 25812.807d0, 0.0d0, "ohm") ,&
  codata_t_constant("conventional value of watt-90", 1.00000019553d0, 0.0d0, "W") ,&
  codata_t_constant("Copper x unit", 1.00207697d-13, 0.00000028d-13, "m") ,&
  codata_t_constant("deuteron-electron mag. mom. ratio", -4.664345551d-4, 0.000000012d-4, " ") ,&
  codata_t_constant("deuteron-electron mass ratio", 3670.48296788d0, 0.00000013d0, " ") ,&
  codata_t_constant("deuteron g factor", 0.8574382338d0, 0.0000000022d0, " ") ]

type(codata_t_constant), dimension(10), parameter :: codata80 = [&
  codata_t_constant("deuteron mag. mom", 4.330735094d-27, 0.000000011d-27, "J T^-1") ,&
  codata_t_constant("deuteron mag. mom. to Bohr magneton ratio", 4.669754570d-4, 0.000000012d-4, " ") ,&
  codata_t_constant("deuteron mag. mom. to nuclear magneton ratio", 0.8574382338d0, 0.0000000022d0, " ") ,&
  codata_t_constant("deuteron mass", 3.3435837724d-27, 0.0000000010d-27, "kg") ,&
  codata_t_constant("deuteron mass energy equivalent", 3.00506323102d-10, 0.00000000091d-10, "J") ,&
  codata_t_constant("deuteron mass energy equivalent in MeV", 1875.61294257d0, 0.00000057d0, "MeV") ,&
  codata_t_constant("deuteron mass in u", 2.013553212745d0, 0.000000000040d0, "u") ,&
  codata_t_constant("deuteron molar mass", 2.01355321205d-3, 0.00000000061d-3, "kg mol^-1") ,&
  codata_t_constant("deuteron-neutron mag. mom. ratio", -0.44820653d0, 0.00000011d0, " ") ,&
  codata_t_constant("deuteron-proton mag. mom. ratio", 0.30701220939d0, 0.00000000079d0, " ") ]

type(codata_t_constant), dimension(10), parameter :: codata90 = [&
  codata_t_constant("deuteron-proton mass ratio", 1.99900750139d0, 0.00000000011d0, " ") ,&
  codata_t_constant("deuteron relative atomic mass", 2.013553212745d0, 0.000000000040d0, " ") ,&
  codata_t_constant("deuteron rms charge radius", 2.12799d-15, 0.00074d-15, "m") ,&
  codata_t_constant("electron charge to mass quotient", -1.75882001076d11, 0.00000000053d11, "C kg^-1") ,&
  codata_t_constant("electron-deuteron mag. mom. ratio", -2143.9234915d0, 0.0000056d0, " ") ,&
  codata_t_constant("electron-deuteron mass ratio", 2.724437107462d-4, 0.000000000096d-4, " ") ,&
  codata_t_constant("electron g factor", -2.00231930436256d0, 0.00000000000035d0, " ") ,&
  codata_t_constant("electron gyromag. ratio", 1.76085963023d11, 0.00000000053d11, "s^-1 T^-1") ,&
  codata_t_constant("electron gyromag. ratio in MHz/T", 28024.9514242d0, 0.0000085d0, "MHz T^-1") ,&
  codata_t_constant("electron-helion mass ratio", 1.819543074573d-4, 0.000000000079d-4, " ") ]

type(codata_t_constant), dimension(10), parameter :: codata100 = [&
  codata_t_constant("electron mag. mom", -9.2847647043d-24, 0.0000000028d-24, "J T^-1") ,&
  codata_t_constant("electron mag. mom. anomaly", 1.15965218128d-3, 0.00000000018d-3, " ") ,&
  codata_t_constant("electron mag. mom. to Bohr magneton ratio", -1.00115965218128d0, 0.00000000000018d0, " ") ,&
  codata_t_constant("electron mag. mom. to nuclear magneton ratio", -1838.28197188d0, 0.00000011d0, " ") ,&
  codata_t_constant("electron mass", 9.1093837015d-31, 0.0000000028d-31, "kg") ,&
  codata_t_constant("electron mass energy equivalent", 8.1871057769d-14, 0.0000000025d-14, "J") ,&
  codata_t_constant("electron mass energy equivalent in MeV", 0.51099895000d0, 0.00000000015d0, "MeV") ,&
  codata_t_constant("electron mass in u", 5.48579909065d-4, 0.00000000016d-4, "u") ,&
  codata_t_constant("electron molar mass", 5.4857990888d-7, 0.0000000017d-7, "kg mol^-1") ,&
  codata_t_constant("electron-muon mag. mom. ratio", 206.7669883d0, 0.0000046d0, " ") ]

type(codata_t_constant), dimension(10), parameter :: codata110 = [&
  codata_t_constant("electron-muon mass ratio", 4.83633169d-3, 0.00000011d-3, " ") ,&
  codata_t_constant("electron-neutron mag. mom. ratio", 960.92050d0, 0.00023d0, " ") ,&
  codata_t_constant("electron-neutron mass ratio", 5.4386734424d-4, 0.0000000026d-4, " ") ,&
  codata_t_constant("electron-proton mag. mom. ratio", -658.21068789d0, 0.00000020d0, " ") ,&
  codata_t_constant("electron-proton mass ratio", 5.44617021487d-4, 0.00000000033d-4, " ") ,&
  codata_t_constant("electron relative atomic mass", 5.48579909065d-4, 0.00000000016d-4, " ") ,&
  codata_t_constant("electron-tau mass ratio", 2.87585d-4, 0.00019d-4, " ") ,&
  codata_t_constant("electron to alpha particle mass ratio", 1.370933554787d-4, 0.000000000045d-4, " ") ,&
  codata_t_constant("electron to shielded helion mag. mom. ratio", 864.058257d0, 0.000010d0, " ") ,&
  codata_t_constant("electron to shielded proton mag. mom. ratio", -658.2275971d0, 0.0000072d0, " ") ]

type(codata_t_constant), dimension(10), parameter :: codata120 = [&
  codata_t_constant("electron-triton mass ratio", 1.819200062251d-4, 0.000000000090d-4, " ") ,&
  codata_t_constant("electron volt", 1.602176634d-19, 0.0d0, "J") ,&
  codata_t_constant("electron volt-atomic mass unit relationship", 1.07354410233d-9, 0.00000000032d-9, "u") ,&
  codata_t_constant("electron volt-hartree relationship", 3.6749322175655d-2, 0.0000000000071d-2, "E_h") ,&
  codata_t_constant("electron volt-hertz relationship", 2.417989242d14, 0.0d0, "Hz") ,&
  codata_t_constant("electron volt-inverse meter relationship", 8.065543937d5, 0.0d0, "m^-1") ,&
  codata_t_constant("electron volt-joule relationship", 1.602176634d-19, 0.0d0, "J") ,&
  codata_t_constant("electron volt-kelvin relationship", 1.160451812d4, 0.0d0, "K") ,&
  codata_t_constant("electron volt-kilogram relationship", 1.782661921d-36, 0.0d0, "kg") ,&
  codata_t_constant("elementary charge", 1.602176634d-19, 0.0d0, "C") ]

type(codata_t_constant), dimension(10), parameter :: codata130 = [&
  codata_t_constant("elementary charge over h-bar", 1.519267447d15, 0.0d0, "A J^-1") ,&
  codata_t_constant("Faraday constant", 96485.33212d0, 0.0d0, "C mol^-1") ,&
  codata_t_constant("Fermi coupling constant", 1.1663787d-5, 0.0000006d-5, "GeV^-2") ,&
  codata_t_constant("fine-structure constant", 7.2973525693d-3, 0.0000000011d-3, " ") ,&
  codata_t_constant("first radiation constant", 3.741771852d-16, 0.0d0, "W m^2") ,&
  codata_t_constant("first radiation constant for spectral radiance", 1.191042972d-16, 0.0d0, "W m^2 sr^-1") ,&
  codata_t_constant("hartree-atomic mass unit relationship", 2.92126232205d-8, 0.00000000088d-8, "u") ,&
  codata_t_constant("hartree-electron volt relationship", 27.211386245988d0, 0.000000000053d0, "eV") ,&
  codata_t_constant("Hartree energy", 4.3597447222071d-18, 0.0000000000085d-18, "J") ,&
  codata_t_constant("Hartree energy in eV", 27.211386245988d0, 0.000000000053d0, "eV") ]

type(codata_t_constant), dimension(10), parameter :: codata140 = [&
  codata_t_constant("hartree-hertz relationship", 6.579683920502d15, 0.000000000013d15, "Hz") ,&
  codata_t_constant("hartree-inverse meter relationship", 2.1947463136320d7, 0.0000000000043d7, "m^-1") ,&
  codata_t_constant("hartree-joule relationship", 4.3597447222071d-18, 0.0000000000085d-18, "J") ,&
  codata_t_constant("hartree-kelvin relationship", 3.1577502480407d5, 0.0000000000061d5, "K") ,&
  codata_t_constant("hartree-kilogram relationship", 4.8508702095432d-35, 0.0000000000094d-35, "kg") ,&
  codata_t_constant("helion-electron mass ratio", 5495.88528007d0, 0.00000024d0, " ") ,&
  codata_t_constant("helion g factor", -4.255250615d0, 0.000000050d0, " ") ,&
  codata_t_constant("helion mag. mom", -1.074617532d-26, 0.000000013d-26, "J T^-1") ,&
  codata_t_constant("helion mag. mom. to Bohr magneton ratio", -1.158740958d-3, 0.000000014d-3, " ") ,&
  codata_t_constant("helion mag. mom. to nuclear magneton ratio", -2.127625307d0, 0.000000025d0, " ") ]

type(codata_t_constant), dimension(10), parameter :: codata150 = [&
  codata_t_constant("helion mass", 5.0064127796d-27, 0.0000000015d-27, "kg") ,&
  codata_t_constant("helion mass energy equivalent", 4.4995394125d-10, 0.0000000014d-10, "J") ,&
  codata_t_constant("helion mass energy equivalent in MeV", 2808.39160743d0, 0.00000085d0, "MeV") ,&
  codata_t_constant("helion mass in u", 3.014932247175d0, 0.000000000097d0, "u") ,&
  codata_t_constant("helion molar mass", 3.01493224613d-3, 0.00000000091d-3, "kg mol^-1") ,&
  codata_t_constant("helion-proton mass ratio", 2.99315267167d0, 0.00000000013d0, " ") ,&
  codata_t_constant("helion relative atomic mass", 3.014932247175d0, 0.000000000097d0, " ") ,&
  codata_t_constant("helion shielding shift", 5.996743d-5, 0.000010d-5, " ") ,&
  codata_t_constant("hertz-atomic mass unit relationship", 4.4398216652d-24, 0.0000000013d-24, "u") ,&
  codata_t_constant("hertz-electron volt relationship", 4.135667696d-15, 0.0d0, "eV") ]

type(codata_t_constant), dimension(10), parameter :: codata160 = [&
  codata_t_constant("hertz-hartree relationship", 1.5198298460570d-16, 0.0000000000029d-16, "E_h") ,&
  codata_t_constant("hertz-inverse meter relationship", 3.335640951d-9, 0.0d0, "m^-1") ,&
  codata_t_constant("hertz-joule relationship", 6.62607015d-34, 0.0d0, "J") ,&
  codata_t_constant("hertz-kelvin relationship", 4.799243073d-11, 0.0d0, "K") ,&
  codata_t_constant("hertz-kilogram relationship", 7.372497323d-51, 0.0d0, "kg") ,&
  codata_t_constant("hyperfine transition frequency of Cs-133", 9192631770.0d0, 0.0d0, "Hz") ,&
  codata_t_constant("inverse fine-structure constant", 137.035999084d0, 0.000000021d0, " ") ,&
  codata_t_constant("inverse meter-atomic mass unit relationship", 1.33102505010d-15, 0.00000000040d-15, "u") ,&
  codata_t_constant("inverse meter-electron volt relationship", 1.239841984d-6, 0.0d0, "eV") ,&
  codata_t_constant("inverse meter-hartree relationship", 4.5563352529120d-8, 0.0000000000088d-8, "E_h") ]

type(codata_t_constant), dimension(10), parameter :: codata170 = [&
  codata_t_constant("inverse meter-hertz relationship", 299792458.0d0, 0.0d0, "Hz") ,&
  codata_t_constant("inverse meter-joule relationship", 1.986445857d-25, 0.0d0, "J") ,&
  codata_t_constant("inverse meter-kelvin relationship", 1.438776877d-2, 0.0d0, "K") ,&
  codata_t_constant("inverse meter-kilogram relationship", 2.210219094d-42, 0.0d0, "kg") ,&
  codata_t_constant("inverse of conductance quantum", 12906.40372d0, 0.0d0, "ohm") ,&
  codata_t_constant("Josephson constant", 483597.8484d9, 0.0d0, "Hz V^-1") ,&
  codata_t_constant("joule-atomic mass unit relationship", 6.7005352565d9, 0.0000000020d9, "u") ,&
  codata_t_constant("joule-electron volt relationship", 6.241509074d18, 0.0d0, "eV") ,&
  codata_t_constant("joule-hartree relationship", 2.2937122783963d17, 0.0000000000045d17, "E_h") ,&
  codata_t_constant("joule-hertz relationship", 1.509190179d33, 0.0d0, "Hz") ]

type(codata_t_constant), dimension(10), parameter :: codata180 = [&
  codata_t_constant("joule-inverse meter relationship", 5.034116567d24, 0.0d0, "m^-1") ,&
  codata_t_constant("joule-kelvin relationship", 7.242970516d22, 0.0d0, "K") ,&
  codata_t_constant("joule-kilogram relationship", 1.112650056d-17, 0.0d0, "kg") ,&
  codata_t_constant("kelvin-atomic mass unit relationship", 9.2510873014d-14, 0.0000000028d-14, "u") ,&
  codata_t_constant("kelvin-electron volt relationship", 8.617333262d-5, 0.0d0, "eV") ,&
  codata_t_constant("kelvin-hartree relationship", 3.1668115634556d-6, 0.0000000000061d-6, "E_h") ,&
  codata_t_constant("kelvin-hertz relationship", 2.083661912d10, 0.0d0, "Hz") ,&
  codata_t_constant("kelvin-inverse meter relationship", 69.50348004d0, 0.0d0, "m^-1") ,&
  codata_t_constant("kelvin-joule relationship", 1.380649d-23, 0.0d0, "J") ,&
  codata_t_constant("kelvin-kilogram relationship", 1.536179187d-40, 0.0d0, "kg") ]

type(codata_t_constant), dimension(10), parameter :: codata190 = [&
  codata_t_constant("kilogram-atomic mass unit relationship", 6.0221407621d26, 0.0000000018d26, "u") ,&
  codata_t_constant("kilogram-electron volt relationship", 5.609588603d35, 0.0d0, "eV") ,&
  codata_t_constant("kilogram-hartree relationship", 2.0614857887409d34, 0.0000000000040d34, "E_h") ,&
  codata_t_constant("kilogram-hertz relationship", 1.356392489d50, 0.0d0, "Hz") ,&
  codata_t_constant("kilogram-inverse meter relationship", 4.524438335d41, 0.0d0, "m^-1") ,&
  codata_t_constant("kilogram-joule relationship", 8.987551787d16, 0.0d0, "J") ,&
  codata_t_constant("kilogram-kelvin relationship", 6.509657260d39, 0.0d0, "K") ,&
  codata_t_constant("lattice parameter of silicon", 5.431020511d-10, 0.000000089d-10, "m") ,&
  codata_t_constant("lattice spacing of ideal Si (220", 1.920155716d-10, 0.000000032d-10, "m") ,&
  codata_t_constant("Loschmidt constant (273.15 K, 100 kPa", 2.651645804d25, 0.0d0, "m^-3") ]

type(codata_t_constant), dimension(10), parameter :: codata200 = [&
  codata_t_constant("Loschmidt constant (273.15 K, 101.325 kPa", 2.686780111d25, 0.0d0, "m^-3") ,&
  codata_t_constant("luminous efficacy", 683.0d0, 0.0d0, "lm W^-1") ,&
  codata_t_constant("mag. flux quantum", 2.067833848d-15, 0.0d0, "Wb") ,&
  codata_t_constant("molar gas constant", 8.314462618d0, 0.0d0, "J mol^-1 K^-1") ,&
  codata_t_constant("molar mass constant", 0.99999999965d-3, 0.00000000030d-3, "kg mol^-1") ,&
  codata_t_constant("molar mass of carbon-12", 11.9999999958d-3, 0.0000000036d-3, "kg mol^-1") ,&
  codata_t_constant("molar Planck constant", 3.990312712d-10, 0.0d0, "J Hz^-1 mol^-1") ,&
  codata_t_constant("molar volume of ideal gas (273.15 K, 100 kPa", 22.71095464d-3, 0.0d0, "m^3 mol^-1") ,&
  codata_t_constant("molar volume of ideal gas (273.15 K, 101.325 kPa", 22.41396954d-3, 0.0d0, "m^3 mol^-1") ,&
  codata_t_constant("molar volume of silicon", 1.205883199d-5, 0.000000060d-5, "m^3 mol^-1") ]

type(codata_t_constant), dimension(10), parameter :: codata210 = [&
  codata_t_constant("Molybdenum x unit", 1.00209952d-13, 0.00000053d-13, "m") ,&
  codata_t_constant("muon Compton wavelength", 1.173444110d-14, 0.000000026d-14, "m") ,&
  codata_t_constant("muon-electron mass ratio", 206.7682830d0, 0.0000046d0, " ") ,&
  codata_t_constant("muon g factor", -2.0023318418d0, 0.0000000013d0, " ") ,&
  codata_t_constant("muon mag. mom", -4.49044830d-26, 0.00000010d-26, "J T^-1") ,&
  codata_t_constant("muon mag. mom. anomaly", 1.16592089d-3, 0.00000063d-3, " ") ,&
  codata_t_constant("muon mag. mom. to Bohr magneton ratio", -4.84197047d-3, 0.00000011d-3, " ") ,&
  codata_t_constant("muon mag. mom. to nuclear magneton ratio", -8.89059703d0, 0.00000020d0, " ") ,&
  codata_t_constant("muon mass", 1.883531627d-28, 0.000000042d-28, "kg") ,&
  codata_t_constant("muon mass energy equivalent", 1.692833804d-11, 0.000000038d-11, "J") ]

type(codata_t_constant), dimension(10), parameter :: codata220 = [&
  codata_t_constant("muon mass energy equivalent in MeV", 105.6583755d0, 0.0000023d0, "MeV") ,&
  codata_t_constant("muon mass in u", 0.1134289259d0, 0.0000000025d0, "u") ,&
  codata_t_constant("muon molar mass", 1.134289259d-4, 0.000000025d-4, "kg mol^-1") ,&
  codata_t_constant("muon-neutron mass ratio", 0.1124545170d0, 0.0000000025d0, " ") ,&
  codata_t_constant("muon-proton mag. mom. ratio", -3.183345142d0, 0.000000071d0, " ") ,&
  codata_t_constant("muon-proton mass ratio", 0.1126095264d0, 0.0000000025d0, " ") ,&
  codata_t_constant("muon-tau mass ratio", 5.94635d-2, 0.00040d-2, " ") ,&
  codata_t_constant("natural unit of action", 1.054571817d-34, 0.0d0, "J s") ,&
  codata_t_constant("natural unit of action in eV s", 6.582119569d-16, 0.0d0, "eV s") ,&
  codata_t_constant("natural unit of energy", 8.1871057769d-14, 0.0000000025d-14, "J") ]

type(codata_t_constant), dimension(10), parameter :: codata230 = [&
  codata_t_constant("natural unit of energy in MeV", 0.51099895000d0, 0.00000000015d0, "MeV") ,&
  codata_t_constant("natural unit of length", 3.8615926796d-13, 0.0000000012d-13, "m") ,&
  codata_t_constant("natural unit of mass", 9.1093837015d-31, 0.0000000028d-31, "kg") ,&
  codata_t_constant("natural unit of momentum", 2.73092453075d-22, 0.00000000082d-22, "kg m s^-1") ,&
  codata_t_constant("natural unit of momentum in MeV/c", 0.51099895000d0, 0.00000000015d0, "MeV/c") ,&
  codata_t_constant("natural unit of time", 1.28808866819d-21, 0.00000000039d-21, "s") ,&
  codata_t_constant("natural unit of velocity", 299792458.0d0, 0.0d0, "m s^-1") ,&
  codata_t_constant("neutron Compton wavelength", 1.31959090581d-15, 0.00000000075d-15, "m") ,&
  codata_t_constant("neutron-electron mag. mom. ratio", 1.04066882d-3, 0.00000025d-3, " ") ,&
  codata_t_constant("neutron-electron mass ratio", 1838.68366173d0, 0.00000089d0, " ") ]

type(codata_t_constant), dimension(10), parameter :: codata240 = [&
  codata_t_constant("neutron g factor", -3.82608545d0, 0.00000090d0, " ") ,&
  codata_t_constant("neutron gyromag. ratio", 1.83247171d8, 0.00000043d8, "s^-1 T^-1") ,&
  codata_t_constant("neutron gyromag. ratio in MHz/T", 29.1646931d0, 0.0000069d0, "MHz T^-1") ,&
  codata_t_constant("neutron mag. mom", -9.6623651d-27, 0.0000023d-27, "J T^-1") ,&
  codata_t_constant("neutron mag. mom. to Bohr magneton ratio", -1.04187563d-3, 0.00000025d-3, " ") ,&
  codata_t_constant("neutron mag. mom. to nuclear magneton ratio", -1.91304273d0, 0.00000045d0, " ") ,&
  codata_t_constant("neutron mass", 1.67492749804d-27, 0.00000000095d-27, "kg") ,&
  codata_t_constant("neutron mass energy equivalent", 1.50534976287d-10, 0.00000000086d-10, "J") ,&
  codata_t_constant("neutron mass energy equivalent in MeV", 939.56542052d0, 0.00000054d0, "MeV") ,&
  codata_t_constant("neutron mass in u", 1.00866491595d0, 0.00000000049d0, "u") ]

type(codata_t_constant), dimension(10), parameter :: codata250 = [&
  codata_t_constant("neutron molar mass", 1.00866491560d-3, 0.00000000057d-3, "kg mol^-1") ,&
  codata_t_constant("neutron-muon mass ratio", 8.89248406d0, 0.00000020d0, " ") ,&
  codata_t_constant("neutron-proton mag. mom. ratio", -0.68497934d0, 0.00000016d0, " ") ,&
  codata_t_constant("neutron-proton mass difference", 2.30557435d-30, 0.00000082d-30, "kg") ,&
  codata_t_constant("neutron-proton mass difference energy equivalent", 2.07214689d-13, 0.00000074d-13, "J") ,&
  codata_t_constant("neutron-proton mass difference energy equivalent in MeV", 1.29333236d0, 0.00000046d0, "MeV") ,&
  codata_t_constant("neutron-proton mass difference in u", 1.38844933d-3, 0.00000049d-3, "u") ,&
  codata_t_constant("neutron-proton mass ratio", 1.00137841931d0, 0.00000000049d0, " ") ,&
  codata_t_constant("neutron relative atomic mass", 1.00866491595d0, 0.00000000049d0, " ") ,&
  codata_t_constant("neutron-tau mass ratio", 0.528779d0, 0.000036d0, " ") ]

type(codata_t_constant), dimension(10), parameter :: codata260 = [&
  codata_t_constant("neutron to shielded proton mag. mom. ratio", -0.68499694d0, 0.00000016d0, " ") ,&
  codata_t_constant("Newtonian constant of gravitation", 6.67430d-11, 0.00015d-11, "m^3 kg^-1 s^-2") ,&
  codata_t_constant("Newtonian constant of gravitation over h-bar c", 6.70883d-39, 0.00015d-39, "(GeV/c^2)^-2") ,&
  codata_t_constant("nuclear magneton", 5.0507837461d-27, 0.0000000015d-27, "J T^-1") ,&
  codata_t_constant("nuclear magneton in eV/T", 3.15245125844d-8, 0.00000000096d-8, "eV T^-1") ,&
  codata_t_constant("nuclear magneton in inverse meter per tesla", 2.54262341353d-2, 0.00000000078d-2, "m^-1 T^-1") ,&
  codata_t_constant("nuclear magneton in K/T", 3.6582677756d-4, 0.0000000011d-4, "K T^-1") ,&
  codata_t_constant("nuclear magneton in MHz/T", 7.6225932291d0, 0.0000000023d0, "MHz T^-1") ,&
  codata_t_constant("Planck constant", 6.62607015d-34, 0.0d0, "J Hz^-1") ,&
  codata_t_constant("Planck constant in eV/Hz", 4.135667696d-15, 0.0d0, "eV Hz^-1") ]

type(codata_t_constant), dimension(10), parameter :: codata270 = [&
  codata_t_constant("Planck length", 1.616255d-35, 0.000018d-35, "m") ,&
  codata_t_constant("Planck mass", 2.176434d-8, 0.000024d-8, "kg") ,&
  codata_t_constant("Planck mass energy equivalent in GeV", 1.220890d19, 0.000014d19, "GeV") ,&
  codata_t_constant("Planck temperature", 1.416784d32, 0.000016d32, "K") ,&
  codata_t_constant("Planck time", 5.391247d-44, 0.000060d-44, "s") ,&
  codata_t_constant("proton charge to mass quotient", 9.5788331560d7, 0.0000000029d7, "C kg^-1") ,&
  codata_t_constant("proton Compton wavelength", 1.32140985539d-15, 0.00000000040d-15, "m") ,&
  codata_t_constant("proton-electron mass ratio", 1836.15267343d0, 0.00000011d0, " ") ,&
  codata_t_constant("proton g factor", 5.5856946893d0, 0.0000000016d0, " ") ,&
  codata_t_constant("proton gyromag. ratio", 2.6752218744d8, 0.0000000011d8, "s^-1 T^-1") ]

type(codata_t_constant), dimension(10), parameter :: codata280 = [&
  codata_t_constant("proton gyromag. ratio in MHz/T", 42.577478518d0, 0.000000018d0, "MHz T^-1") ,&
  codata_t_constant("proton mag. mom", 1.41060679736d-26, 0.00000000060d-26, "J T^-1") ,&
  codata_t_constant("proton mag. mom. to Bohr magneton ratio", 1.52103220230d-3, 0.00000000046d-3, " ") ,&
  codata_t_constant("proton mag. mom. to nuclear magneton ratio", 2.79284734463d0, 0.00000000082d0, " ") ,&
  codata_t_constant("proton mag. shielding correction", 2.5689d-5, 0.0011d-5, " ") ,&
  codata_t_constant("proton mass", 1.67262192369d-27, 0.00000000051d-27, "kg") ,&
  codata_t_constant("proton mass energy equivalent", 1.50327761598d-10, 0.00000000046d-10, "J") ,&
  codata_t_constant("proton mass energy equivalent in MeV", 938.27208816d0, 0.00000029d0, "MeV") ,&
  codata_t_constant("proton mass in u", 1.007276466621d0, 0.000000000053d0, "u") ,&
  codata_t_constant("proton molar mass", 1.00727646627d-3, 0.00000000031d-3, "kg mol^-1") ]

type(codata_t_constant), dimension(10), parameter :: codata290 = [&
  codata_t_constant("proton-muon mass ratio", 8.88024337d0, 0.00000020d0, " ") ,&
  codata_t_constant("proton-neutron mag. mom. ratio", -1.45989805d0, 0.00000034d0, " ") ,&
  codata_t_constant("proton-neutron mass ratio", 0.99862347812d0, 0.00000000049d0, " ") ,&
  codata_t_constant("proton relative atomic mass", 1.007276466621d0, 0.000000000053d0, " ") ,&
  codata_t_constant("proton rms charge radius", 8.414d-16, 0.019d-16, "m") ,&
  codata_t_constant("proton-tau mass ratio", 0.528051d0, 0.000036d0, " ") ,&
  codata_t_constant("quantum of circulation", 3.6369475516d-4, 0.0000000011d-4, "m^2 s^-1") ,&
  codata_t_constant("quantum of circulation times 2", 7.2738951032d-4, 0.0000000022d-4, "m^2 s^-1") ,&
  codata_t_constant("reduced Compton wavelength", 3.8615926796d-13, 0.0000000012d-13, "m") ,&
  codata_t_constant("reduced muon Compton wavelength", 1.867594306d-15, 0.000000042d-15, "m") ]

type(codata_t_constant), dimension(10), parameter :: codata300 = [&
  codata_t_constant("reduced neutron Compton wavelength", 2.1001941552d-16, 0.0000000012d-16, "m") ,&
  codata_t_constant("reduced Planck constant", 1.054571817d-34, 0.0d0, "J s") ,&
  codata_t_constant("reduced Planck constant in eV s", 6.582119569d-16, 0.0d0, "eV s") ,&
  codata_t_constant("reduced Planck constant times c in MeV fm", 197.3269804d0, 0.0d0, "MeV fm") ,&
  codata_t_constant("reduced proton Compton wavelength", 2.10308910336d-16, 0.00000000064d-16, "m") ,&
  codata_t_constant("reduced tau Compton wavelength", 1.110538d-16, 0.000075d-16, "m") ,&
  codata_t_constant("Rydberg constant", 10973731.568160d0, 0.000021d0, "m^-1") ,&
  codata_t_constant("Rydberg constant times c in Hz", 3.2898419602508d15, 0.0000000000064d15, "Hz") ,&
  codata_t_constant("Rydberg constant times hc in eV", 13.605693122994d0, 0.000000000026d0, "eV") ,&
  codata_t_constant("Rydberg constant times hc in J", 2.1798723611035d-18, 0.0000000000042d-18, "J") ]

type(codata_t_constant), dimension(10), parameter :: codata310 = [&
  codata_t_constant("Sackur-Tetrode constant (1 K, 100 kPa", -1.15170753706d0, 0.00000000045d0, " ") ,&
  codata_t_constant("Sackur-Tetrode constant (1 K, 101.325 kPa", -1.16487052358d0, 0.00000000045d0, " ") ,&
  codata_t_constant("second radiation constant", 1.438776877d-2, 0.0d0, "m K") ,&
  codata_t_constant("shielded helion gyromag. ratio", 2.037894569d8, 0.000000024d8, "s^-1 T^-1") ,&
  codata_t_constant("shielded helion gyromag. ratio in MHz/T", 32.43409942d0, 0.00000038d0, "MHz T^-1") ,&
  codata_t_constant("shielded helion mag. mom", -1.074553090d-26, 0.000000013d-26, "J T^-1") ,&
  codata_t_constant("shielded helion mag. mom. to Bohr magneton ratio", -1.158671471d-3, 0.000000014d-3, " ") ,&
  codata_t_constant("shielded helion mag. mom. to nuclear magneton ratio", -2.127497719d0, 0.000000025d0, " ") ,&
  codata_t_constant("shielded helion to proton mag. mom. ratio", -0.7617665618d0, 0.0000000089d0, " ") ,&
  codata_t_constant("shielded helion to shielded proton mag. mom. ratio", -0.7617861313d0, 0.0000000033d0, " ") ]

type(codata_t_constant), dimension(10), parameter :: codata320 = [&
  codata_t_constant("shielded proton gyromag. ratio", 2.675153151d8, 0.000000029d8, "s^-1 T^-1") ,&
  codata_t_constant("shielded proton gyromag. ratio in MHz/T", 42.57638474d0, 0.00000046d0, "MHz T^-1") ,&
  codata_t_constant("shielded proton mag. mom", 1.410570560d-26, 0.000000015d-26, "J T^-1") ,&
  codata_t_constant("shielded proton mag. mom. to Bohr magneton ratio", 1.520993128d-3, 0.000000017d-3, " ") ,&
  codata_t_constant("shielded proton mag. mom. to nuclear magneton ratio", 2.792775599d0, 0.000000030d0, " ") ,&
  codata_t_constant("shielding difference of d and p in HD", 2.0200d-8, 0.0020d-8, " ") ,&
  codata_t_constant("shielding difference of t and p in HT", 2.4140d-8, 0.0020d-8, " ") ,&
  codata_t_constant("speed of light in vacuum", 299792458.0d0, 0.0d0, "m s^-1") ,&
  codata_t_constant("standard acceleration of gravity", 9.80665d0, 0.0d0, "m s^-2") ,&
  codata_t_constant("standard atmosphere", 101325.0d0, 0.0d0, "Pa") ]

type(codata_t_constant), dimension(10), parameter :: codata330 = [&
  codata_t_constant("standard-state pressure", 100000.0d0, 0.0d0, "Pa") ,&
  codata_t_constant("Stefan-Boltzmann constant", 5.670374419d-8, 0.0d0, "W m^-2 K^-4") ,&
  codata_t_constant("tau Compton wavelength", 6.97771d-16, 0.00047d-16, "m") ,&
  codata_t_constant("tau-electron mass ratio", 3477.23d0, 0.23d0, " ") ,&
  codata_t_constant("tau energy equivalent", 1776.86d0, 0.12d0, "MeV") ,&
  codata_t_constant("tau mass", 3.16754d-27, 0.00021d-27, "kg") ,&
  codata_t_constant("tau mass energy equivalent", 2.84684d-10, 0.00019d-10, "J") ,&
  codata_t_constant("tau mass in u", 1.90754d0, 0.00013d0, "u") ,&
  codata_t_constant("tau molar mass", 1.90754d-3, 0.00013d-3, "kg mol^-1") ,&
  codata_t_constant("tau-muon mass ratio", 16.8170d0, 0.0011d0, " ") ]

type(codata_t_constant), dimension(10), parameter :: codata340 = [&
  codata_t_constant("tau-neutron mass ratio", 1.89115d0, 0.00013d0, " ") ,&
  codata_t_constant("tau-proton mass ratio", 1.89376d0, 0.00013d0, " ") ,&
  codata_t_constant("Thomson cross section", 6.6524587321d-29, 0.0000000060d-29, "m^2") ,&
  codata_t_constant("triton-electron mass ratio", 5496.92153573d0, 0.00000027d0, " ") ,&
  codata_t_constant("triton g factor", 5.957924931d0, 0.000000012d0, " ") ,&
  codata_t_constant("triton mag. mom", 1.5046095202d-26, 0.0000000030d-26, "J T^-1") ,&
  codata_t_constant("triton mag. mom. to Bohr magneton ratio", 1.6223936651d-3, 0.0000000032d-3, " ") ,&
  codata_t_constant("triton mag. mom. to nuclear magneton ratio", 2.9789624656d0, 0.0000000059d0, " ") ,&
  codata_t_constant("triton mass", 5.0073567446d-27, 0.0000000015d-27, "kg") ,&
  codata_t_constant("triton mass energy equivalent", 4.5003878060d-10, 0.0000000014d-10, "J") ]

type(codata_t_constant), dimension(10), parameter :: codata350 = [&
  codata_t_constant("triton mass energy equivalent in MeV", 2808.92113298d0, 0.00000085d0, "MeV") ,&
  codata_t_constant("triton mass in u", 3.01550071621d0, 0.00000000012d0, "u") ,&
  codata_t_constant("triton molar mass", 3.01550071517d-3, 0.00000000092d-3, "kg mol^-1") ,&
  codata_t_constant("triton-proton mass ratio", 2.99371703414d0, 0.00000000015d0, " ") ,&
  codata_t_constant("triton relative atomic mass", 3.01550071621d0, 0.00000000012d0, " ") ,&
  codata_t_constant("triton to proton mag. mom. ratio", 1.0666399191d0, 0.0000000021d0, " ") ,&
  codata_t_constant("unified atomic mass unit", 1.66053906660d-27, 0.00000000050d-27, "kg") ,&
  codata_t_constant("vacuum electric permittivity", 8.8541878128d-12, 0.0000000013d-12, "F m^-1") ,&
  codata_t_constant("vacuum mag. permeability", 1.25663706212d-6, 0.00000000019d-6, "N A^-2") ,&
  codata_t_constant("von Klitzing constant", 25812.80745d0, 0.0d0, "ohm") ]

type(codata_t_constant), dimension(4), parameter :: codata354 = [&
  codata_t_constant("weak mixing angle", 0.22290d0, 0.00030d0, " ") ,&
  codata_t_constant("Wien frequency displacement law constant", 5.878925757d10, 0.0d0, "Hz K^-1") ,&
  codata_t_constant("Wien wavelength displacement law constant", 2.897771955d-3, 0.0d0, "m K") ,&
  codata_t_constant("W to Z mass ratio", 0.88153d0, 0.00017d0, " ") ]

type(codata_t_constant), dimension(354), public :: codata_constants = [&
codata10 ,&
codata20 ,&
codata30 ,&
codata40 ,&
codata50 ,&
codata60 ,&
codata70 ,&
codata80 ,&
codata90 ,&
codata100 ,&
codata110 ,&
codata120 ,&
codata130 ,&
codata140 ,&
codata150 ,&
codata160 ,&
codata170 ,&
codata180 ,&
codata190 ,&
codata200 ,&
codata210 ,&
codata220 ,&
codata230 ,&
codata240 ,&
codata250 ,&
codata260 ,&
codata270 ,&
codata280 ,&
codata290 ,&
codata300 ,&
codata310 ,&
codata320 ,&
codata330 ,&
codata340 ,&
codata350 ,&
codata354 ]

end module codata_last
